/* A LA ORDEN — LOTE 1 PERMANENCIA · 58 preguntas CURADAS a mano (22-sep-2026)
   Huecos reforzados: Situaciones · Carrera militar · Tropa y marinería ·
   Seguridad Nacional y ESN 2021 · Doctrina · UE · OTAN · ONU · OSCE ·
   Misiones · Físicas · Convocatoria · FAS.
   Explicaciones que enseñan el PORQUÉ (nada de ecos). */
window.QUESTIONS9 = [
/* ===== SITUACIONES · L 39/2007 (4 → 9) · B2 ===== */
{c:"perm",b:"B2",t:"Situaciones",d:"F",id:"pe001",q:"¿Cuántas situaciones administrativas tiene el militar de carrera?",o:["Tres: servicio activo, reserva y retiro","Dos: activo y paro","Cinco","Solo una"],a:0,x:"La Ley 39/2007 fija TRES situaciones: servicio activo (ejerciendo), reserva (hasta la edad legal, con pensión de reserva) y retiro (cese definitivo). Es el mapa vital de toda la carrera y por eso cae en todos los exámenes.",r:"Ley 39/2007"},
{c:"perm",b:"B2",t:"Situaciones",d:"M",id:"pe002",q:"Dentro del SERVICIO ACTIVO, un militar puede estar:",o:["En destino o disponible","De vacaciones perpetuas","En paro y retirado a la vez","Solo en su casa"],a:0,x:"Dentro del activo se distingue entre estar EN DESTINO (con puesto asignado) y DISPONIBLE (a la espera de destino o en la situación de disponibles). El mando de personal gestiona esos estados a efectos de retribuciones y servicios.",r:"Ley 39/2007"},
{c:"perm",b:"B2",t:"Situaciones",d:"M",id:"pe003",q:"¿Qué situación administra la RESERVA DE ESPECIAL DISPONIBILIDAD (RED)?",o:["La de los militares de tropa y marinería con compromiso temporal que FINALIZA","La de los generales","La de los reservistas voluntarios","Ninguna, no existe"],a:0,x:"La RED (L 39/2007) es la situación «puente» del militar temporal al terminar su compromiso: conserva vínculo y derechos básicos mientras decide su futuro. Es concepto CLAVE del examen de permanencia: el temporal no «sale a la calle» sin más, pasa a la RED.",r:"Ley 39/2007 art. 99"},
{c:"perm",b:"B2",t:"Situaciones",d:"M",id:"pe004",q:"Para el militar de tropa que accede a la condición de carrera (permanencia), esa condición se adquiere:",o:["El 31 de diciembre del año de la convocatoria","El día que firma el contrato","Cumplidos los 40 años","Cuando lo decide el coronel"],a:0,x:"Patrón oficial de las convocatorias de permanencia: la condición de militar de carrera se adquiere el 31 de DICIEMBRE del año de la convocatoria (para la de 2026, el 31-dic-2026). Entre la resolución y esa fecha hay periodo de documentación y compromiso.",r:"Bases de la convocatoria de permanencia"},
{c:"perm",b:"B2",t:"Situaciones",d:"M",id:"pe005",q:"El paso a la situación de RESERVA se produce:",o:["Al alcanzar la edad legal que fija la ley para cada empleo y escala","Cuando el militar se enfada","Por una sanción leve","Cada verano"],a:0,x:"La reserva no es una sanción ni una opción automática: llega al cumplir la EDAD legal que la Ley 39/2007 fija según empleo y escala. En reserva se perciben las correspondientes habiles pasivas y se conservan derechos de representación, hasta el retiro.",r:"Ley 39/2007 arts. 90-91"},

/* ===== CARRERA MILITAR · L 39/2007 (4 → 12) · B2 ===== */
{c:"perm",b:"B2",t:"Carrera militar",d:"F",id:"pe006",q:"¿Qué regula la Ley 39/2007, de 19 de noviembre?",o:["La Carrera Militar","El tráfico rodado","La pesca marítima","Los presupuestos generales"],a:0,x:"La Ley 39/2007 de la Carrera Militar es la norma marco de la profesión: acceso, formación, empleos, situaciones administrativas, derechos y deberes básicos. Todo examen de permanencia la rocía entero.",r:"Ley 39/2007"},
{c:"perm",b:"B2",t:"Carrera militar",d:"M",id:"pe007",q:"¿Cuánto dura el compromiso de larga duración?",o:["3 años","6 meses","1 año","10 años"],a:0,x:"El compromiso de larga duración son 3 AÑOS (art. 63 L 39/2007), prorrogables. Es el vínculo propio de la condición de militar de tropa/carrera y su incumplimiento tiene consecuencias disciplinarias y de condición.",r:"Ley 39/2007 art. 63"},
{c:"perm",b:"B2",t:"Carrera militar",d:"F",id:"pe008",q:"Orden ASCENDENTE de los empleos de tropa y marinería:",o:["Soldado, cabo, cabo primero","Cabo, soldado, cabo primero","Cabo primero, cabo, soldado","Soldado, cabo primero, cabo"],a:0,x:"De menos a más: soldado → cabo → cabo primero. La cadena de mando en una escuadra se apoya en esa escala: el cabo manda la escuadra y el cabo 1º es el mando intermedio que guía a los cabos.",r:"Ley 39/2007 (empleos)"},
{c:"perm",b:"B2",t:"Carrera militar",d:"M",id:"pe009",q:"Según la normativa reciente de ascensos, la adquisición del empleo de Cabo 1º está supeditada a:",o:["La obtención del destino definitivo en la unidad correspondiente","Sortear entre los amigos","Tener 20 años de servicio sí o sí","Comprar el galón"],a:0,x:"Las convocatorias recientes (p. ej. Res. 551/01505/26, BOD nº 23) fijan que el ascenso está SUPEDITADO A LA OBTENCIÓN DE DESTINO: aprobar el examen no basta, hay que tener destino en unidad que lo habilite. Regla nueva que cae seguro.",r:"BOD nº 83-26 · Res. 551/01505/26"},
{c:"perm",b:"B2",t:"Carrera militar",d:"M",id:"pe010",q:"Las retribuciones BÁSICAS del militar son:",o:["El sueldo y las pagas extraordinarias","El coche oficial","Las dietas de maniobra","El premio de navidad del economato"],a:0,x:"Básicas (igual para todos del mismo empleo, sin ruedo): SUELDO + DOS PAGAS EXTRAORDINARIAS (junio y diciembre). Todo lo demás son complementos (destino, especificidad, antigüedad…) que varían por puesto. Distinción básica/complementaria = pregunta clásica.",r:"Ley 39/2007 art. 109"},
{c:"perm",b:"B2",t:"Carrera militar",d:"D",id:"pe011",q:"El baremo de DESTINOS que puntúa para el concurso de permanencia se rige fundamentalmente por:",o:["La OM 19/2009 (modificada por la OM 12/2019)","El reglamento de tránsito","La ley electoral","La norma UNE"],a:0,x:"La Orden 19/2009 (modificada por la OM 12/2019) regula los criterios de valoración de destinos (permanencia en unidades, zona, operatividad) para los concursos de TM. El requisito típico: 4 años en determinados destinos. Memoriza: OM 19/2009 = destinos.",r:"OM 19/2009 · OM 12/2019"},
{c:"perm",b:"B2",t:"Carrera militar",d:"M",id:"pe012",q:"La aptitud psicofísica del militar:",o:["Se evalúa con pruebas físicas reglamentarias y es REQUISITO para adquirir y conservar la condición","Solo importa en la gimnasia del jueves","No afecta nunca","Se mide por el color de los ojos"],a:0,x:"La aptitud (médica y física) es requisito permanente: se comprueba al acceder y se mantiene durante la carrera con las pruebas físicas reglamentarias. Un aptitud deficiente puede condicionar ascensos y permanencia — por eso el plan de preparación física importa.",r:"Ley 39/2007 · bases de convocatoria"},

/* ===== TROPA Y MARINERÍA · L 8/2006 (8 → 12) · B2 ===== */
{c:"perm",b:"B2",t:"Tropa y marinería",d:"M",id:"pe013",q:"La Ley 8/2006, de Tropa y Marinería, regula:",o:["El compromiso, las prórrogas y los derechos esenciales del militar de tropa","El servicio de limpieza del acuartelamiento","Los precios del bar","El tráfico del Puerto"],a:0,x:"La L 8/2006 es la ley básica de la tropa: compromiso inicial, prórrogas, derechos, y el marco para acceder a la condición de carrera (permanencia). Su nombre completo: Ley de Tropa y Marinería de las Fuerzas Armadas.",r:"Ley 8/2006"},
{c:"perm",b:"B2",t:"Tropa y marinería",d:"M",id:"pe014",q:"Las prórrogas del compromiso de tropa son de:",o:["2 o 3 años","1 mes","10 años","24 horas"],a:0,x:"Tras el compromiso inicial, las prórrogas son de 2 o 3 años a elección del militar (art. de la L 8/2006). Ese engranaje de compromisos es el camino que lleva a poder presentarse a la permanencia.",r:"Ley 8/2006"},
{c:"perm",b:"B2",t:"Tropa y marinería",d:"M",id:"pe015",q:"La condición de militar de tropa y marinería se adquiere:",o:["Con la formalización del compromiso ante el mando","Al cobrar la primera nómina","Con una selfie en el cuartel","Al comprar el uniforme"],a:0,x:"La condición nace con la FORMALIZACIÓN DEL COMPROMISO (acto formal ante el mando, con los deberes y derechos que conlleva). No es el examen ni el contrato mercantil: es el compromiso regulado en la L 8/2006.",r:"Ley 8/2006"},
{c:"perm",b:"B2",t:"Tropa y marinería",d:"M",id:"pe016",q:"Un cometido esencial del militar de tropa y marinería es:",o:["Participar en operaciones militares y garantizar la seguridad y defensa de España","Elegir al Gobierno","Dirigir la política exterior","Legislar en el Congreso"],a:0,x:"La tropa es la base de la fuerza: participa en operaciones, sirve en las unidades y ejecuta los servicios esenciales de defensa. Por eso la permanencia exige compromiso de larga duración: la operación necesita estabilidad, no giros de 6 meses.",r:"Ley 8/2006 · L 39/2007"},

/* ===== SEGURIDAD NACIONAL · L 36/2015 (4 → 9) · B3 ===== */
{c:"perm",b:"B3",t:"Seguridad Nacional",d:"F",id:"pe017",q:"¿Qué ley regula el Sistema de Seguridad Nacional?",o:["La Ley 36/2015, de 28 de septiembre","La Ley 39/2007","El código de circulación","La LO 8/2014"],a:0,x:"La Ley 36/2015 es la norma básica del Sistema de Seguridad Nacional: define SN, órganos (Presidente del Gobierno, CNS), principios y ámbitos de acción. Nació de la experiencia contra el terrorismo y las crisis, para coordinar a todo el Estado.",r:"Ley 36/2015"},
{c:"perm",b:"B3",t:"Seguridad Nacional",d:"M",id:"pe018",q:"Según la L 36/2015, la Seguridad Nacional es la acción del Estado para:",o:["Proteger la libertad y el bienestar de los ciudadanos, la defensa de España y los principios constitucionales","Proteger solo a los políticos","Controlar el fútbol","Vigilar el tráfico"],a:0,x:"La definición legal: proteger la libertad y el bienestar de los ciudadanos, la defensa de España y los principios y valores constitucionales, y garantizar la seguridad y el bienestar de la población. Apunta a la definición LITERAL: cae tal cual.",r:"Ley 36/2015 art. 2"},
{c:"perm",b:"B3",t:"Seguridad Nacional",d:"M",id:"pe019",q:"¿Quién DIRIGE el Sistema de Seguridad Nacional y preside el Consejo de Seguridad Nacional (CNS)?",o:["El Presidente del Gobierno","El Rey","El alcalde","El Defensor del Pueblo"],a:0,x:"El Presidente del Gobierno dirige la SN y preside el CNS (integrado por vicepresidentes, ministros y altos cargos). Es el órgano superior de coordinación del sistema; no es un mando militar: es dirección política del más alto nivel.",r:"Ley 36/2015"},
{c:"perm",b:"B3",t:"Seguridad Nacional",d:"M",id:"pe020",q:"¿Qué órgano APOYA al CNS en la gestión de crisis?",o:["El Comité de Situación","El Consejo de Estado","La real academia","El comité de empresa"],a:0,x:"El Comité de Situación es el órgano de trabajo del CNS para gestionar crisis: reúne a los centros de mando y seguimiento (como el CECODAC) y mantiene el pulso de la crisis hora a hora. Ante una crisis grave, es la «sala de máquinas».",r:"Ley 36/2015"},

/* ===== ESN · ESTRATEGIA DE SEGURIDAD NACIONAL 2021 (4 → 9) · B3 ===== */
{c:"perm",b:"B3",t:"ESN",d:"F",id:"pe021",q:"¿Qué Estrategia de Seguridad Nacional está VIGENTE?",o:["La ESN 2021","La ESN de 1978","La ESN de 1856","No hay ninguna"],a:0,x:"La ESN vigente es la de 2021, aprobada por el Congreso de los Diputados a propuesta del Presidente del Gobierno (como exige la L 36/2015). Analiza el contexto geopolítico y fija intereses, ámbitos y líneas de acción del país.",r:"ESN 2021 · Ley 36/2015"},
{c:"perm",b:"B3",t:"ESN",d:"M",id:"pe022",q:"Según la ESN 2021, el contexto geopolítico se caracteriza por el deterioro de las relaciones internacionales en sus facetas:",o:["Comercial, tecnológica, diplomática o militar","Solo gastronómica","Cultural y deportiva","Turística"],a:0,x:"Capítulo 1 de la ESN 2021: «las dinámicas de confrontación y competencia han prevalecido sobre las de negociación y acuerdo… en todas sus facetas: comercial, tecnológica, diplomática o militar». La pregunta de tu amigo en el examen oficial — aprendida por ejemplo.",r:"ESN 2021, cap. 1"},
{c:"perm",b:"B3",t:"ESN",d:"M",id:"pe023",q:"Entre las AMENAZAS Y RIESGOS que destaca la ESN 2021 están:",o:["El terrorismo yihadista, los ciberataques, la guerra híbrida y la desinformación","El mal tiempo el fin de semana","La subida del pan","El descuido del uniforme"],a:0,x:"La ESN 2021 enumera terrorismo y violencia yihadista, ciberataques, guerra híbrida, desinformación, inestabilidad regional, cambio climático y pandemias, entre otros. Nota clave: hoy la amenaza se juega también en el ciberespacio y en la mente de la gente.",r:"ESN 2021"},
{c:"perm",b:"B3",t:"ESN",d:"M",id:"pe024",q:"Los INTERESES de seguridad nacional según la ESN incluyen:",o:["La soberanía e independencia de España, su integridad territorial y el orden constitucional","Los intereses del club de fútbol","Los intereses bancarios del vecino","Ninguno"],a:0,x:"Intereses de la SN (ESN 2021): soberanía e independencia, integridad territorial, orden constitucional, seguridad de la población, bienestar económico y defensa de España. Son el «qué» que protege el Estado; el Sistema y sus órganos son el «cómo».",r:"ESN 2021"},
{c:"perm",b:"B3",t:"ESN",d:"M",id:"pe025",q:"Los VECTORES DE TRANSFORMACIÓN del contexto internacional según la ESN incluyen:",o:["La globalización, la digitalización, el cambio climático y los cambios demográficos","La moda del momento","El precio del café","La luna llena"],a:0,x:"Los vectores son las grandes fuerzas que cambian el mundo: globalización, revolución tecnológica y digitalización, cambio climático, demografía, auge de populismos… Entenderlos permite anticipar amenazas en lugar de perseguirlas.",r:"ESN 2021"},

/* ===== DOCTRINA (3 → 7) · B3 ===== */
{c:"perm",b:"B3",t:"Doctrina",d:"M",id:"pe026",q:"La DOCTRINA militar es:",o:["El conjunto de principios rectores que guían el empleo de las fuerzas para lograr los objetivos","Una lista de castigos","El manual del economato","Un libro de moda"],a:0,x:"Doctrina = principios rectores (no reglas rígidas) que orientan cómo se organizan, preparan y emplean las fuerzas. Da un lenguaje común y coherencia al ejército. Se organiza en niveles: estratégico, operativo y táctico.",r:"Doctrina militar · MADOC"},
{c:"perm",b:"B3",t:"Doctrina",d:"M",id:"pe027",q:"Los niveles de la doctrina militar son:",o:["Estratégico, operativo y táctico","Pequeño, mediano y grande","Bajo, medio y alto","Ninguno"],a:0,x:"Estratégico (qué guerra y para qué), operativo (cómo enlazar los medios en campañas) y táctico (cómo combate la unidad en el terreno). El cabo/soldado vive el táctico, pero saber el mapa completo lo distingue al que estudia de verdad.",r:"Doctrina militar"},
{c:"perm",b:"B3",t:"Doctrina",d:"F",id:"pe028",q:"En el Ejército de Tierra, el organismo encargado del adiestramiento y la doctrina es:",o:["El MADOC (Mando de Adiestramiento y Doctrina)","El MAM","El Ministerio de Hacienda","La Ertzaintza"],a:0,x:"MADOC = Mando de Adiestramiento y Doctrina (CG en Granada): prepara a las unidades y desarrolla la doctrina del ET. De su sigla sale el famoso «temario MADOC» que estudian los aspirantes a cabo.",r:"Organización del ET"},
{c:"perm",b:"B3",t:"Doctrina",d:"M",id:"pe029",q:"Los STANAG de la OTAN son:",o:["Acuerdos de NORMALIZACIÓN (standarization) para interoperar entre aliados","Contratos de compra de armas","Tratados de paz","Un equipo de fútbol"],a:0,x:"STANAG = STANdardization Agreement: acuerdos que homologan procedimientos, calibres, documentos y equipos para que los ejércitos aliados INTEROPEREN (se entiendan y funcionen juntos). Ejemplo práctico: formatos de órdenes y de informes comunes.",r:"OTAN · doctrina"},

/* ===== UNIÓN EUROPEA (4 → 9) · B3 ===== */
{c:"perm",b:"B3",t:"UE",d:"M",id:"pe030",q:"Los Tratados vigentes de la Unión Europea son los de:",o:["Lisboa (2007, en vigor desde 2009): TUE y TFUE","Maastricht de 1992 sin reformar","Roma de 1957 sin reformar","No hay tratados"],a:0,x:"El Tratado de Lisboa reordenó todo: TUE (Tratado de la Unión Europea) y TFUE (Funcionamiento), en vigor desde diciembre de 2009. Cualquier pregunta institucional de la UE se resuelve mirando a Lisboa.",r:"UE · Tratado de Lisboa"},
{c:"perm",b:"B3",t:"UE",d:"M",id:"pe031",q:"La Política Común de Seguridad y Defensa (PCSD/PSOP) de la UE permite:",o:["Lanzar misiones civiles y militares de gestión de crisis fuera de la UE","Declarar la guerra a China","Sustituir a la OTAN","Prohibir el turismo"],a:0,x:"La PCSD es el brazo operativo de la UE en seguridad: misiones CIVILES (policía, asesoría) y MILITARES (instrucción, estabilización) fuera de la Unión. España participa habitualmente: es proyección de la UE y experiencia para nuestros militares.",r:"UE · PSOP"},
{c:"perm",b:"B3",t:"UE",d:"D",id:"pe032",q:"La PESCO (Cooperación Estructurada Permanente), lanzada en 2017, sirve para:",o:["Que los Estados miembros cooperen en defensa (proyectos, capacidades, despliegues) de forma vinculante","Organizar el festival de Eurovisión","Repartir la PAC","Nada"],a:0,x:"PESCO: marco de cooperación defensiva VINCULANTE entre Estados miembros (2017): proyectos conjuntos de capacidades, inversión y despliegue. Es el mayor salto de integración defensiva europea desde la CECA — y una sigla que ya ha caído en exámenes.",r:"UE · PESCO"},
{c:"perm",b:"B3",t:"UE",d:"M",id:"pe033",q:"La «Brújula Estratégica» de la UE (2022) es:",o:["El plan de la UE para su seguridad y defensa a 2030","Un instrumento de orientación en el mar","Una ley de tráfico","El himno europeo"],a:0,x:"Aprobada en marzo de 2022, la Brújula Estratégica fija objetivos de la UE en seguridad y defensa para esta década (capacidades, misiones, inversión, asociaciones). Su nombre es metafórico: marca el rumbo — como una brújula.",r:"UE · Brújula Estratégica 2022"},
{c:"perm",b:"B3",t:"UE",d:"M",id:"pe034",q:"¿Qué institución de la UE PROPONE la legislación y vigila su cumplimiento?",o:["La Comisión Europea","El Comité de las Regiones","El Defensor del Pueblo europeo","La alcaldía"],a:0,x:"La Comisión Europea tiene el «monopolio de iniciativa legislativa» y es la guardiana de los Tratados. El Consejo define orientaciones, el Parlamento aprueba y controla. Saber quién propone, quién aprueba y quién decide evita trampas de examen.",r:"UE · instituciones"},

/* ===== OTAN (7 → 11) · B3 ===== */
{c:"perm",b:"B3",t:"OTAN",d:"M",id:"pe035",q:"España se adhirió a la OTAN en 1982 y su PERMANENCIA se ratificó en referéndum en:",o:["1986","1955","1939","2001"],a:0,x:"Cronología oficial: adhesión el 30-may-1982; el 12-mar-1986 el referéndum ratificó la permanencia en la Alianza con tres condiciones del Gobierno (no integración en su estructura militar — luego superada —, no instalación de armas nucleares y reducción progresiva de las bases de EE. UU.).",r:"OTAN · España"},
{c:"perm",b:"B3",t:"OTAN",d:"M",id:"pe036",q:"El ARTÍCULO 5 del Tratado de Washington establece:",o:["Que un ataque armado contra un aliado se considera un ataque contra todos (defensa colectiva)","Que se juega al fútbol cada primavera","Que se comparte el salario","Que cada país se defiende solo"],a:0,x:"El art. 5 es el corazón de la Alianza: defensa COLECTIVA. Se ha invocado una sola vez: tras los atentados del 11-S de 2001, en favor de EE. UU. Es la garantía que disuade y el motivo político de la Alianza.",r:"Tratado de Washington 1949"},
{c:"perm",b:"B3",t:"OTAN",d:"M",id:"pe037",q:"Los países FUNDADORES de la OTAN (1949) fueron:",o:["Doce","Dos","Cincuenta","Ciento noventa y tres"],a:0,x:"Doce fundadores (Bélgica, Canadá, Dinamarca, EE. UU., Francia, Islandia, Italia, Luxemburgo, Noruega, Países Bajos, Portugal y Reino Unido). Hoy la Alianza se ha ampliado hasta más de 30 miembros. España entró en 1982.",r:"Tratado de Washington 1949"},
{c:"perm",b:"B3",t:"OTAN",d:"M",id:"pe038",q:"La base naval española de ROTA acoge buques estadounidenses de defensa antimisiles como parte de:",o:["El escudo antimisiles de la OTAN","El mercado central","La flota de pesca","Un reality show naval"],a:0,x:"En Rota (Cádiz) están desplegados destructores con sistema AEGIS que integran el escudo antimisiles de la OTAN en Europa (defensa frente a misiles balísticos). España aporta infraestructura y participa: ejemplo tangible de la contribución aliada desde nuestro país.",r:"OTAN · defensa antimisiles"},

/* ===== ONU (6 → 9) · B3 ===== */
{c:"perm",b:"B3",t:"ONU",d:"M",id:"pe039",q:"España se convirtió en miembro de la ONU en:",o:["1955","1945","1920","2005"],a:0,x:"La ONU nació en 1945 (Carta de San Francisco), pero España no entró hasta el 14-dic-1955, ya en el contexto de la Guerra Fría (admisión masiva de países). Fechas de entrada de España a organismos: ONU 1955, OTAN 1982, CEE 1986 — trío que conviene tener encadenado.",r:"ONU"},
{c:"perm",b:"B3",t:"ONU",d:"M",id:"pe040",q:"¿Qué órgano de la ONU tiene 5 miembros PERMANENTES con derecho de veto?",o:["El Consejo de Seguridad","La Asamblea General","La FAO","La UNESCO"],a:0,x:"Consejo de Seguridad: 15 miembros — 5 permanentes con veto (EE. UU., Reino Unido, Francia, Rusia y China, los vencedores de la II Guerra Mundial) y 10 no permanentes elegidos por 2 años. Sus resoluciones son VINCULANTES; por eso sus decisiones pesan tanto.",r:"Carta de la ONU"},
{c:"perm",b:"B3",t:"ONU",d:"M",id:"pe041",q:"Las misiones de PAZ de la ONU («cascos azules») se despliegan:",o:["Con mandato del Consejo de Seguridad (o la Asamblea) y consentimiento de las partes","Por decisión de un solo país","Sin permiso de nadie","Solo en América del Sur"],a:0,x:"Las misiones de paz nacen con MANDATO del Consejo de Seguridad (o la AG en casos excepcionales) y funcionan sobre el consentimiento de las partes en conflicto, imparcialidad y no uso de la fuerza salvo legítima defensa. España las apoya desde hace décadas (p. ej. FINUL).",r:"ONU · operaciones de paz"},

/* ===== OSCE (3 → 7) · B3 ===== */
{c:"perm",b:"B3",t:"OSCE",d:"M",id:"pe042",q:"El origen de la OSCE está en:",o:["La Conferencia sobre Seguridad y Cooperación en Europa (Helsinki, 1975)","La Conferencia de Potsdam","El Congreso de Viena de 1815","Una reunión de vecinos"],a:0,x:"Acta Final de Helsinki (1975): 35 países (incluidos EE. UU. y URSS) acuerdan «canasta» de seguridad, cooperación y derechos humanos. Del proceso CSCE nace la OSCE organizada (Carta de París 1990; institucionalizada en Budapest 1994).",r:"OSCE · Helsinki 1975"},
{c:"perm",b:"B3",t:"OSCE",d:"F",id:"pe043",q:"La SEDE de la OSCE está en:",o:["Viena (Austria)","Roma","Tokio","Cádiz"],a:0,x:"Sede institucional: Viena (como la OPEP y otras). La OSCE es la mayor organización regional de seguridad del mundo: 57 estados participantes desde Vancouver a Vladivostok. España es participante desde el origen (Helsinki 1975).",r:"OSCE"},
{c:"perm",b:"B3",t:"OSCE",d:"M",id:"pe044",q:"¿Cuántos estados PARTICIPAN en la OSCE?",o:["57","10","120","200"],a:0,x:"57 estados participantes: la mayor organización de seguridad REGIONAL del planeta. Sus herramientas: prevención de conflictos, observación electoral (España participa con observadores), misiones de campo y control de armamentos (Vienna Document).",r:"OSCE"},

/* ===== MISIONES (2 → 8) · B3 ===== */
{c:"perm",b:"B3",t:"Misiones",d:"M",id:"pe045",q:"La contribución española a la FINUL (Líbano) se denomina:",o:["Operación Libre Hidalgo","Operación Marfil","Operación Atalanta","Operación Balmis"],a:0,x:"En el marco de la FINUL (fuerza de paz de la ONU en el Líbano desde 1978), España despliega la Brigada «Libre Hidalgo» con base «Miguel de Cervantes» (Marjayoun). Es la misión española de larga duración más emblemática: pregunta casi garantizada.",r:"FINUL · Operación Libre Hidalgo"},
{c:"perm",b:"B3",t:"Misiones",d:"M",id:"pe046",q:"La operación ATALANTA de la UE actúa contra:",o:["La piratería en el Cuerno de África (océano Índico)","El contrabando de chucherías","La pesca deportiva","El tráfico aéreo"],a:0,x:"Atalanta (desde 2008): operación naval de la UE contra la piratería frente a Somalia y el Cuerno de África, protegiendo el tráfico marítimo y al PMA. Ha sido la gran misión naval europea y España aporta buques y aeronaves habitualmente.",r:"UE · Operación Atalanta"},
{c:"perm",b:"B3",t:"Misiones",d:"M",id:"pe047",q:"Las misiones tipo EUTM de la UE son:",o:["Misiones de INSTRUCCIÓN militar a fuerzas de terceros países","Conciertos musicales","Misiones de rescatе de turistas","Cursos de cocina"],a:0,x:"EUTM (European Union Training Mission): misiones de formación/instrucción de la UE a ejércitos nacionales (p. ej. EUTM Malí, EUTM Mozambique). España participa en varias: enseñar a luchar bien es también defensa colectiva — y experiencia de mando para cabos y sargentos.",r:"UE · EUTM"},
{c:"perm",b:"B3",t:"Misiones",d:"M",id:"pe048",q:"El mando militar de las operaciones de las FAS lo ejerce:",o:["El MOPS (Mando de Operaciones), dependiente del JEMAD","El alcalde de Madrid","El capitán del puerto","La UEFA"],a:0,x:"El MOPS (Mando de Operaciones, en Madrid) planifica y conduce las operaciones nacionales, bajo el JEMAD y el Ministro de Defensa. Para misiones concretas se designan componentes (terrestre, marítimo, aéreo). Saber QUIÉN manda qué es la base del examen.",r:"Estructura de mando operativa"},
{c:"perm",b:"B3",t:"Misiones",d:"M",id:"pe049",q:"La base española de la misión en el Líbano se llama:",o:["«Miguel de Cervantes»","«El Cid»","«Francisco Franco»","«Base Sur»"],a:0,x:"Base «Miguel de Cervantes», en Marjayoun (sur del Líbano): sede de la Brigada Libre Hidalgo dentro de la FINUL. Detalles como el nombre de la base son las preguntas «fáciles» que se puntúan: memorízalos con imagen (Cervantes escribiendo en el Líbano).",r:"FINUL · Libre Hidalgo"},
{c:"perm",b:"B3",t:"Misiones",d:"M",id:"pe050",q:"Una misión de la UE se diferencia de una de la ONU en que:",o:["Las de la UE suelen ser de la UE (instrucción, civil) y las de la ONU de paz con mandato universal; cada organización tiene su marco legal","No se diferencian","Las de la UE son de guerra","Las de la ONU son vacaciones pagadas"],a:0,x:"Marco legal y carácter: ONU = operaciones de paz con mandato del Consejo de Seguridad e imparcialidad; UE = misiones dentro de la PCSD (civiles o militares) en el marco de la PESC. España puede participar en ambas (o incluso en las OTAN): cada una con su mandato y reglas.",r:"ONU · UE · doctrina"},

/* ===== FÍSICAS (2 → 5) · B3 ===== */
{c:"perm",b:"B3",t:"Físicas",d:"M",id:"pe051",q:"La aptitud física en los procesos de la tropa:",o:["Se evalúa con pruebas reglamentarias (velocidad/agilidad, fuerza, resistencia) y es REQUISITO","Se ignora","Se adivina","Depende del color del calzado"],a:0,x:"Las bases fijan pruebas generales (circuito de velocidad y agilidad, fuerza tren superior tipo flexiones, resistencia tipo carrera) con marcas mínimas según sexo y edad, según el plan de preparación física de las FAS. Prepararlas con meses de margen: la nota que se autocontrola.",r:"Bases de convocatoria · plan de IPP"},
{c:"perm",b:"B3",t:"Físicas",d:"M",id:"pe052",q:"¿Cuándo conviene preparar las pruebas físicas?",o:["Con meses de antelación, de forma progresiva","La noche antes","Nunca","Solo mirando vídeos"],a:0,x:"La preparación física progresiva (8-12 semanas) mejora marcas y evita lesiones; la improvisación del día anterior lo único que consigue es un esguince y un suspenso. Regla de caballo: constancia antes que heroísmo.",r:"Plan de preparación física"},
{c:"perm",b:"B3",t:"Físicas",d:"M",id:"pe053",q:"Un positivo en detección de sustancias en los procesos de acceso:",o:["Impide la admisión y causa exclusión del proceso","Da puntos extra","Solo avisa a la familia","No tiene consecuencias"],a:0,x:"El control de detección de drogas es requisito: un positivo EXCLUYE del proceso (y la negativa a hacerse el control también). Las bases lo recogen expresamente; la conducta y la salud son parte del perfil militar.",r:"Bases de convocatoria"},

/* ===== CONVOCATORIA (2 → 5) · B3 ===== */
{c:"perm",b:"B3",t:"Convocatoria",d:"M",id:"pe054",q:"¿Dónde se PUBLICA la convocatoria de ascenso/permanencia y sus bases?",o:["En el Boletín Oficial del Ministerio de Defensa (BOD) y en el BOE","En un cartel del bar","Por rumores en el taller","Por carta al azar"],a:0,x:"La convocatoria y sus bases se publican en el BOD (Boletín Oficial del Ministerio de Defensa) y, si procede, en el BOE. Las instancias se presentan por VÍA ELECTRÓNICA en el registro del Ministerio. Vigilar el BOD es parte del oficio de candidato.",r:"BOD · normativa de convocatorias"},
{c:"perm",b:"B3",t:"Convocatoria",d:"M",id:"pe055",q:"¿Cómo se presenta la instancia de las convocatorias de tropa?",o:["Por registro electrónico (sede electrónica del Ministerio de Defensa)","A mano en una papelera","Por mensajería sin identificar","Por teléfono a las 3 de la madrugada"],a:0,x:"Todas las instancias se tramitan por SEDE ELECTRÓNICA (certificado digital o Cl@ve). Errores típicos: dejarlo para el último día (la web se satura) y no guardar el justificante. El justificante de presentación es tu seguro de vida administrativo.",r:"Sede electrónica · bases"},
{c:"perm",b:"B3",t:"Convocatoria",d:"M",id:"pe056",q:"El DOCUMENTO de identidad válido para presentarse a una convocatoria es:",o:["El DNI o TIP en vigor","Una nota del sargento","La foto del móvil","El abono de transporte"],a:0,x:"DNI o TIP (Tarjeta de Identidad Personal militar) EN VIGOR. Si caduca antes del examen, pedir cita para renovarlo YA: miles de candidaturas tropiezan cada año por una fecha de caducidad pasada.",r:"Bases de convocatoria"},

/* ===== FAS (5 → 8) · B1 ===== */
{c:"perm",b:"B1",t:"FAS",d:"M",id:"pe057",q:"¿Quién ejerce el MANDO OPERATIVO de las Fuerzas Armadas (bajo el Ministro de Defensa)?",o:["El JEMAD (Jefe de Estado Mayor de la Defensa)","El Rey","El capitán general","El jefe de la plaza"],a:0,x:"Tras la reorganización (RD 1099/2019 y reforma de las RROO por RD 173/2021), los mandos operativos dependen del JEMAD, bajo la autoridad del Ministro de Defensa. Los Jefes de Estado Mayor (JEME, AJEMA, JEA) preparan sus ejércitos: separación entre «preparar» y «emplear».",r:"RD 1099/2019 · RD 173/2021"},
{c:"perm",b:"B1",t:"FAS",d:"M",id:"pe058",q:"La UNIDAD MILITAR DE EMERGENCIAS (UME) se dedica a:",o:["Actuar en emergencias por riesgos naturales y tecnológicos (incendios, inundaciones, terremotos, nieve)","Custodiar museos","Organizar la cabalgata de Reyes","Controlar el tráfico aéreo civil"],a:0,x:"La UME (creada en 2006, dependiente del Ministerio de Defensa) es la fuerza de las FAS para emergencias: incendios forestales, inundaciones, nevadas, terremotos, riesgos tecnológicos. Sus batallones (BIEM) repartidos por el territorio responden a las catástrofes que la sociedad no puede afrontar sola.",r:"UME · creación 2006"}
];
