/* A LA ORDEN — LOTE 2 CABO 1º · 45 preguntas CURADAS a mano (22-sep-2026)
   Huecos reforzados: Geografía · Historia · Inglés · Primeros auxilios · NBQ.
   Explicaciones que enseñan el PORQUÉ (nada de ecos). */
window.QUESTIONS11 = [
/* ===== GEOGRAFÍA (0 → 12) · B1 ===== */
{c:"cabo1",b:"B1",t:"Geografía",d:"M",id:"c1q001",q:"Las VERTIENTES hidrográficas de la España peninsular son:",o:["Tres: cantábrica, atlántica y mediterránea","Una sola","Cinco","Cuatro"],a:0,x:"Tres vertientes: los ríos cantábricos son cortos, rápidos y caudalosos (nacimiento y desembocadura juntas); los atlánticos son los GRANDES (Duero, Tajo, Guadiana, Guadalquivir); los mediterráneos incluyen al Ebro, el más caudaloso pese a ser de vertiente mediterránea. Clasificar ríos por vertiente es pregunta segura.",r:"Geografía de España"},
{c:"cabo1",b:"B1",t:"Geografía",d:"M",id:"c1q002",q:"El río más CAUDALOSO de España es:",o:["El Ebro","El Guadalquivir","El Manzanares","El Segura"],a:0,x:"El Ebro es el más caudaloso (vierte su agua en el Mediterráneo). Para no confundir superlativos: el Tajo es el más LARGO peninsular, el Duero tiene la CUENCA más extensa y el Miño es el más importante de Galicia. Cada río su superlativo: apúntalos juntos.",r:"Geografía de España"},
{c:"cabo1",b:"B1",t:"Geografía",d:"F",id:"c1q003",q:"La cordillera que hace de frontera natural entre España y Francia es:",o:["Los Pirineos","Sierra Morena","Los Andes","Sistema Central"],a:0,x:"Los Pirineos: unos 430 km de la cornisa cantábrica al Mediterráneo, con el Aneto (3.404 m) como techo. Frontera natural histórica que además limita 5 provincias españolas: Girona, Lleida, Huesca, Navarra y Gipuzkoa.",r:"Geografía de España"},
{c:"cabo1",b:"B1",t:"Geografía",d:"D",id:"c1q004",q:"El «techo» de la España PENINSULAR es:",o:["El Mulhacén (3.479 m, Sierra Nevada)","El Teide","El Aneto","La Peña Vieja"],a:0,x:"Trampa clásica: el TEIDE (3.715 m) es la máxima altitud de ESPAÑA, pero está en Tenerife (isla, no península). El techo de la PENÍNSULA es el Mulhacén, en Sierra Nevada (Sistemas Béticos, Granada); el del Pirineo, el Aneto. «España» y «península» no son lo mismo en geografía.",r:"Geografía de España"},
{c:"cabo1",b:"B1",t:"Geografía",d:"M",id:"c1q005",q:"La frontera terrestre MÁS LARGA de España (y de la UE) es la de:",o:["Portugal (unos 1.214 km)","Francia","Andorra","Marruecos"],a:0,x:"España–Portugal: ~1.214 km de frontera, la más larga de la Unión Europea (la «raya»). Después Francia (~623 km), Andorra (~63 km) y Gibraltar (~1,2 km). Con Marruecos solo hay frontera terrestre en Ceuta y Melilla. Dato de interés militar: perimetros vigilados y cooperación fronteriza.",r:"Geografía de España"},
{c:"cabo1",b:"B1",t:"Geografía",d:"F",id:"c1q006",q:"Los dos archipiélagos españoles y sus mares:",o:["Baleares en el Mediterráneo y Canarias en el Atlántico","Ambos en el Atlántico","Ambos en el Mediterráneo","Baleares en el Cantábrico"],a:0,x:"Baleares (Mallorca, Menorca, Ibiza, Formentera y Cabrera) frente al Mediterráneo; Canarias (8 islas) en el Atlántico, frente a África. Su valor estratégico militar explica bases, vigilancia marítima y aeródromos: Baleares domina el Mediterráneo occidental y Canarias el Atlántico oriental y la ruta africana.",r:"Geografía de España"},
{c:"cabo1",b:"B1",t:"Geografía",d:"M",id:"c1q007",q:"¿Cuántas islas forman CANARIAS (contando La Graciosa)?",o:["Ocho","Tres","Doce","Una"],a:0,x:"Ocho islas: Tenerife, Gran Canaria, Lanzarote, Fuerteventura, La Palma, La Gomera, El Hierro y La Graciosa (reconocida como isla en 2018). Dos provincias: Las Palmas y Santa Cruz de Tenerife. El Teide (Tenerife) es la máxima altitud de todo España: 3.715 m.",r:"Geografía de España"},
{c:"cabo1",b:"B1",t:"Geografía",d:"F",id:"c1q008",q:"España se organiza en:",o:["17 comunidades autónomas y 2 ciudades autónomas (Ceuta y Melilla)","10 regiones","25 provincias imperiales","4 reinos"],a:0,x:"17 CCAA + Ceuta y Melilla como ciudades autónomas (art. 2 y 137 de la CE). Hay comunidades uniprovinciales (Madrid, Murcia, Asturias, Cantabria, La Rioja, Navarra). Para el examen: saber capitales de comunidad y provincias que limitan con frontera exterior.",r:"CE · organización territorial"},
{c:"cabo1",b:"B1",t:"Geografía",d:"D",id:"c1q009",q:"El punto MÁS MERIDIONAL de la España peninsular es:",o:["Punta de Tarifa (Cádiz)","Cabo de Creus","Estaca de Bares","Cabo Touriñán"],a:0,x:"Los cuatro extremos peninsulares: NORTE Estaca de Bares (entre Lugo y La Coruña), SUR Punta de Tarifa (Cádiz, mirando a Marruecos), ESTE Cap de Creus (Girona), OESTE Cabo Touriñán (La Coruña). Tarifa es además el punto más próximo a África: el Estrecho mide unos 14 km.",r:"Geografía de España"},
{c:"cabo1",b:"B1",t:"Geografía",d:"M",id:"c1q010",q:"El Estrecho de Gibraltar separa España de Marruecos por unos:",o:["14 kilómetros","500 kilómetros","100 millas náuticas","2 metros"],a:0,x:"Unos 14 km en su parte más estrecha (punta Tarifa–punta Cires). Es la llave entre el Atlántico y el Mediterráneo: por eso su vigilancia (misión VIGMIRO) es históricamente vital para España, y por eso las plazas de soberanía y bases del entorno pesan tanto estratégicamente.",r:"Geografía estratégica"},
{c:"cabo1",b:"B1",t:"Geografía",d:"D",id:"c1q011",q:"¿Cuántas provincias españolas limitan con FRANCIA?",o:["Cinco: Girona, Lleida, Huesca, Navarra y Gipuzkoa","Ninguna","Toda la cornisa","Veinte"],a:0,x:"Recorriendo los Pirineos de este a oeste: Girona, Lleida, Huesca, Navarra y Gipuzkoa. (Andorra se interpone entre Francia y Lleida en un tramo). Provincias fronterizas = preguntas de geografía militar clásica: es la única frontera terrestre con un país europeo grande.",r:"Geografía de España"},
{c:"cabo1",b:"B1",t:"Geografía",d:"M",id:"c1q012",q:"Los sistemas que DIVIDEN la Meseta en submeseta norte y sur son:",o:["El Sistema Central y los Montes de Toledo","Los Alpes","La Cordillera Costero-Catalana","Ninguno"],a:0,x:"La Meseta se parte en dos: la Submeseta NORTE (cuenca del Duero) y la SUR (cuencas del Tajo y Guadiana), separadas por el Sistema Central (Gredos, Guadarrama…) y junto a los Montes de Toledo. La cierran la Cordillera Cantábrica (norte) y Sierra Morena (sur). Entender el «castillo» de la Meseta ordena toda la geografía física.",r:"Geografía de España"},

/* ===== HISTORIA (0 → 12) · B1 ===== */
{c:"cabo1",b:"B1",t:"Historia",d:"M",id:"c1q013",q:"Los famosos TERCIOS españoles (siglos XVI-XVII) fueron creados en tiempos de:",o:["Carlos I (a partir de 1534)","Felipe VI","Franco","Los Reyes Católicos directamente"],a:0,x:"Carlos I estructuró los tercios (Nápoles, Sicilia y Lombardía, 1534), la infantería más temida de Europa durante un siglo y medio — «los invencibles» hasta su derrota en ROCROI (1643) frente al Gran Condé. Precedente directo: las coronelías de Gonzalo Fernández de Córdoba, «el Gran Capitán», en las guerras de Italia de los Reyes Católicos.",r:"Historia militar de España"},
{c:"cabo1",b:"B1",t:"Historia",d:"M",id:"c1q014",q:"«El Gran Capitán», precursor de los tercios, fue:",o:["Gonzalo Fernández de Córdoba","El Cid","Napoleón","Un cabo de semana"],a:0,x:"Gonzalo Fernández de Córdoba (1453-1515): en las guerras de Italia reformó el ejército de los Reyes Católicos (coronelías de piqueros, escudados y ballesteros) y sentó las bases de la infantería española que luego serían los tercios. Apodo ganado en Granada y Nápoles. Los orígenes del ejército permanente español empiezan aquí.",r:"Historia militar de España"},
{c:"cabo1",b:"B1",t:"Historia",d:"F",id:"c1q015",q:"El levantamiento del 2 de MAYO de 1808 dio comienzo a:",o:["La Guerra de Independencia (1808-1814)","La Guerra Civil","El Camino de Santiago","Las Cortes de Cádiz"],a:0,x:"El levantamiento de Madrid contra las tropas napoleónicas (Daoíz y Velarde en el Parque de Artillería de Monteleón) encendió la Guerra de Independencia: seis años de guerrillas y batallas que acabaron con la ocupación francesa. Goya lo inmortalizó; las Cortes de Cádiz y la Constitución de 1812 surgieron en plena guerra.",r:"Historia de España"},
{c:"cabo1",b:"B1",t:"Historia",d:"M",id:"c1q016",q:"La batalla de BAILÉN (julio de 1808) fue:",o:["La primera derrota en campo abierto de un ejército napoleónico","Una batalla de la I Guerra Mundial","Un empate sin importancia","Un concierto"],a:0,x:"El general Castaños rindió al ejército de Dupont: primera derrota TERRESTRE en campo abierto de Napoleón. Rompió el mito de invencibilidad francesa y animó a Europa a levantarse. En el examen aparece como «primer desengaño napoleónico»: fecha 1808 y protagonistas Castaños vs Dupont.",r:"Historia militar de España"},
{c:"cabo1",b:"B1",t:"Historia",d:"M",id:"c1q017",q:"El «Desastre» del 98 supuso la pérdida de:",o:["Cuba, Puerto Rico y Filipinas frente a EE. UU.","Andalucía","Las Islas Feroe","Nada"],a:0,x:"1898: España pierde sus últimas grandes colonias (Cuba, Puerto Rico, Filipinas y Guam) frente a Estados Unidos. Golpe moral e imperial que genera el «regeneracionismo» y la Generación del 98, y obliga a reorganizar el ejército. En las trincheras de Manila y Santiago de Cuba acabó un imperio de cuatro siglos.",r:"Historia de España"},
{c:"cabo1",b:"B1",t:"Historia",d:"M",id:"c1q018",q:"Las GUERRAS CARLISTAS del siglo XIX enfrentaron a:",o:["Los partidarios de Carlos María Isidro con los de Isabel II (cuestión dinástica y foral)","España y Japón","Dos clubes de fútbol","Nadie"],a:0,x:"Tres guerras carlistas (1833-40, 1846-49, 1872-76): la sucesión de Fernando VII (Isabel II vs su hermano Carlos María Isidro) más el choque entre foralismo y liberalismo, con fuerte implantación en el norte (País Vasco, Navarra, Aragón, Cataluña). Moldearon el mapa político-militar del siglo XIX español.",r:"Historia de España"},
{c:"cabo1",b:"B1",t:"Historia",d:"M",id:"c1q019",q:"La DIVISIÓN AZUL (1941-1943) fue:",o:["Una división de voluntarios españoles que combatió en el frente de la URSS en la II Guerra Mundial","Un equipo de natación","Un regimiento de la OTAN","Una marca de uniformes"],a:0,x:"Oficialmente 250.ª División de la Wehrmacht: unos 45.000 voluntarios españoles combatieron en el frente ruso (destacando en el bloqueo de Leningrado) entre 1941 y 1943. Capítulo complejo y triste de nuestra historia militar reciente, pero que en el examen aparece tal cual: voluntarios, URSS, II Guerra Mundial.",r:"Historia militar de España"},
{c:"cabo1",b:"B1",t:"Historia",d:"D",id:"c1q020",q:"La PASCUA MILITAR (6 de enero) la instituyó:",o:["Carlos III en 1782, tras la recuperación de Menorca","Felipe VI en 2015","Napoleón","El alcalde de Madrid"],a:0,x:"Carlos III la creó en 1782 para celebrar la recuperación de MENORCA (arrebatada a los británicos). Cada 6 de enero, en el Palacio Real, se celebra con jura de bandera de nuevos soldados y homenaje a los que dieron su vida. La fecha con su origen: pregunta elegante y recurrente.",r:"Tradición militar"},
{c:"cabo1",b:"B1",t:"Historia",d:"M",id:"c1q021",q:"El SERVICIO MILITAR OBLIGATORIO («la mili») en España finalizó en:",o:["Diciembre de 2001","1939","ayer","1885"],a:0,x:"La profesionalización plena de las FAS culminó con los últimos reemplazos de la mili en diciembre de 2001 (decisión del Gobierno Aznar, en el marco de la Ley 17/1999 del Personal Militar Profesional). Desde entonces, la tropa es 100% profesional: la Ley 8/2006 regula compromisos y prórrogas. Un hito que explica por qué existen los exámenes de permanencia y ascenso.",r:"Ley 17/1999 · Ley 8/2006"},
{c:"cabo1",b:"B1",t:"Historia",d:"M",id:"c1q022",q:"La UNIDAD MILITAR DE EMERGENCIAS (UME) se creó en:",o:["2006 (tras el Prestige y los incendios de Galicia)","1939","1492","el año pasado"],a:0,x:"El RD 416/2006 creó la UME: la lección aprendida del Prestige (2002) y los incendios de Galicia (2006) demostró que España necesitaba una fuerza militar especializada en emergencias (incendios, inundaciones, nevadas, terremotos). Sus batallones BIEM cubren todo el territorio. Éxito absoluto de servicio a la ciudadanía.",r:"UME · RD 416/2006"},
{c:"cabo1",b:"B1",t:"Historia",d:"F",id:"c1q023",q:"La GUERRA CIVIL española (1936-1939) terminó el:",o:["1 de abril de 1939","6 de diciembre de 1978","2 de mayo de 1808","31 de diciembre de 1999"],a:0,x:"Del 17-18 de julio de 1936 al 1 de abril de 1939. A su final siguió una dictadura de casi cuatro décadas, hasta la Transición y la Constitución de 1978, que devolvió las FAS al servicio exclusivo de una democracia parlamentaria (art. 8 CE). Contexto imprescindible para entender la defensa democrática actual.",r:"Historia de España"},
{c:"cabo1",b:"B1",t:"Historia",d:"M",id:"c1q024",q:"La PATRONA de las Fuerzas Armadas españolas es:",o:["La Inmaculada Concepción (festividad: 8 de diciembre)","La Virgen del Rocío","Santa Claus","La Dama de Elche"],a:0,x:"La Inmaculada Concepción es la patrona de las FAS y su festividad militar es el 8 de diciembre. No confundir con el DÍA DE LAS FAS (un sábado de finales de mayo o junio, con desfile móvil por ciudades rotatorias) ni con el patrón del Ejército de Tierra, San Fernando (30 de mayo).",r:"Tradición militar"},

/* ===== INGLÉS (6 → 14) · B2 ===== */
{c:"cabo1",b:"B2",t:"Inglés",d:"F",id:"c1q025",q:"How do you say «CABO» in English?",o:["Corporal","Captain","Cooker","Colonel"],a:0,x:"Cadena de empleos en inglés: Private (soldado), Corporal (cabo), Sergeant (sargento), Lieutenant (teniente), Captain (capitán), Major (comandante), Colonel (coronel), General. Los rangos caen en el inglés de las oposiciones TM casi cada año.",r:"Inglés militar"},
{c:"cabo1",b:"B2",t:"Inglés",d:"M",id:"c1q026",q:"The sergeant says «Fall in!». It means:",o:["¡Formación! (formar filas)","¡Descansen!","¡Vayan al bar!","¡Rompan filas!"],a:0,x:"Vocabulario de formación: «Fall in» = formar; «Attention» = firmes; «At ease» = descansen; «Fall out» / «Dismissed» = rompan filas. Son las órdenes que oirás y darás mil veces: aprenderlas con la imagen de la formación, no de memoria seca.",r:"Inglés militar"},
{c:"cabo1",b:"B2",t:"Inglés",d:"F",id:"c1q027",q:"«Attention!» means:",o:["¡Firmes!","¡Suelto!","¡A correr!","¡Silencio!"],a:0,x:"«Attention» = posición de firmes (talones juntos, cabeza firme). En los exámenes de inglés militar las órdenes básicas se repiten: Attention (firmes), At ease (descansen), March (marchen), Halt (alto). Escúchalas en vídeos de ejércitos anglosajones y se te quedan solas.",r:"Inglés militar"},
{c:"cabo1",b:"B2",t:"Inglés",d:"M",id:"c1q028",q:"«CEASE FIRE» significa:",o:["Alto el fuego","Abre fuego","Cambia de cargador","Toma la colina"],a:0,x:"«Cease fire» = alto el fuego (orden crítica en galería y en combate). Familia de vocabulario de tiro: «fire» (fuego/disparad), «hold fire» (no disparar), «check your fire» (comprueben el fuego). En instrucción de tiro con extranjeros son las órdenes que salvan vidas.",r:"Inglés militar · tiro"},
{c:"cabo1",b:"B2",t:"Inglés",d:"F",id:"c1q029",q:"The four cardinal points in English are:",o:["North, South, East and West","Up, down, left, right","Red, blue, green, yellow","One, two, three, four"],a:0,x:"N = North, S = South, E = East, W = West. Y las combinaciones: Northeast (NE), Southwest (SW)… En operaciones conjuntas con aliados, la terminología de dirección y rumbo (bearing, heading) siempre es en inglés: es el idioma de mando de la OTAN.",r:"Inglés militar · topografía"},
{c:"cabo1",b:"B2",t:"Inglés",d:"D",id:"c1q030",q:"Complete: «The unit ___ deployed three times this year».",o:["has been","are","is being","was be"],a:0,x:"Present perfect PASSIVE: «has been deployed» = «ha sido desplegada» (la unidad recibe la acción). Estructura: has/have + been + participio. Frase típica de informes militares en inglés: el pasivo es el modo favorito de los informes («the mission was completed», «the area was secured»).",r:"Inglés · gramática"},
{c:"cabo1",b:"B2",t:"Inglés",d:"M",id:"c1q031",q:"«Guard duty» means:",o:["Servicio de guardia","Guardería infantil","Guardia urbana","Un baile"],a:0,x:"«Guard duty» = servicio de guardia. Familia: «on duty» (de servicio), «off duty» (fuera de servicio), «guard room» (sala de guardia/corps), «to stand guard» (montar guardia). El vocabulario del día a día en acuartelamiento es el que más se repite en los exámenes.",r:"Inglés militar"},
{c:"cabo1",b:"B2",t:"Inglés",d:"M",id:"c1q032",q:"Who commands a SQUAD in the Spanish Army?",o:["The Corporal","The General","The cook","The Mayor of the town"],a:0,x:"«Squad» = escuadra, mandada por un cabo (Corporal). Para traducir unidades: squad/escuadra, platoon/pelotón, company/compañía, battalion/batallón, brigade/brigada. Pregunta que mezcla inglés + organización: doble valor de estudio.",r:"Inglés militar · organización"},

/* ===== PRIMEROS AUXILIOS (0 → 8) · B1 ===== */
{c:"cabo1",b:"B1",t:"Primeros auxilios",d:"F",id:"c1q033",q:"El orden correcto de actuación en una emergencia (método P.A.S.) es:",o:["Proteger, Avisar, Socorrer","Socorrer, Proteger, Avisar","Avisar, Socorrer, Proteger","Correr y gritar"],a:0,x:"P.A.S.: PROTEGER (a ti primero y al herido del peligro: sin más víctimas), AVISAR (112 con datos claros: qué, dónde, cuántos, cómo) y SOCORRER (solo si sabes cómo). En combate hay un paso CERO: suprimir el fuego y poner a cubierto antes de tocar al herido (Care Under Fire).",r:"Primeros auxilios · TCCC"},
{c:"cabo1",b:"B1",t:"Primeros auxilios",d:"F",id:"c1q034",q:"El teléfono de emergencias en toda España y la UE es:",o:["112","911","600","060"],a:0,x:"El 112 es el número único europeo de emergencias: gratuito y multilingüe. Al llamar comunica: QUÉ pasa, DÓNDE (lo más preciso posible), CUÁNTOS heridos y CÓMO están. En operaciones el sistema militar tiene sus propias redes, pero el 112 es el básico civil.",r:"Primeros auxilios"},
{c:"cabo1",b:"B1",t:"Primeros auxilios",d:"M",id:"c1q035",q:"La RCP básica en un adulto se hace con:",o:["30 compresiones y 2 insuflaciones, a ritmo de 100-120 por minuto","5 compresiones y 15 insuflaciones","Solo insuflaciones","Palmetazos en la espalda"],a:0,x:"Protocolo vigente: 30 compresiones torácicas (centro del pecho, 5-6 cm de profundidad) alternadas con 2 insuflaciones, sin parar casi nunca (relevo cada 2 min si hay más socorristas). Si hay DESFIBRILADOR AUTOMÁTICO (DEA) cerca: encárgalo a alguien YA, salva más vidas que nadie.",r:"RCP básica"},
{c:"cabo1",b:"B1",t:"Primeros auxilios",d:"M",id:"c1q036",q:"La posición lateral de seguridad se aplica a:",o:["Un inconsciente que RESPIRA con normalidad","Un despierto que grita","Un cadáver","Un que corre"],a:0,x:"El inconsciente que respira se pone de lado (boca hacia abajo, pierna flexionada): mantiene la vía aérea libre y evita que se atragante con vómitos. Si NO respira: RCP inmediata. La regla de oro: inconsciente + respira = PLS; inconsciente + no respira = RCP + 112.",r:"Primeros auxilios"},
{c:"cabo1",b:"B1",t:"Primeros auxilios",d:"D",id:"c1q037",q:"Ante una hemorragia masiva de un miembro que no cede con presión directa:",o:["Torniquete lo más ALTO posible del miembro, apuntando la HORA de colocación","Lavar la herida con agua","Esperar al médico sentados","Ponerla a dormir"],a:0,x:"La hemorragia masiva es la primera causa de muerte EVITABLE en combate (~90%). Con presión directa insuficiente: torniquete alto y firme, y ANOTA LA HORA (en el propio torniquete o en la frente del herido) para el hospital. La vieja recomendación de «aflojar cada X minutos» está SUPERADA: aprieta y evacúa.",r:"TCCC · primeros auxilios"},
{c:"cabo1",b:"B1",t:"Primeros auxilios",d:"M",id:"c1q038",q:"Ante una QUEMADURA, lo correcto es:",o:["Enfriar con agua limpia templada 15-20 minutos","Poner hielo directamente","Echar pasta de dientes","Pinchar las ampollas"],a:0,x:"Agua limpia a temperatura ambiente 15-20 min (no helada: el frío extremo daña más el tejido). Quitar anillos y ropa NO adherida; NO pinchar ampollas ni aplicar remedios caseros. Cobertura con apósito limpio y valorar evacuación según extensión. En campaña: el suero fisiológico es tu mejor aliado.",r:"Primeros auxilios"},
{c:"cabo1",b:"B1",t:"Primeros auxilios",d:"M",id:"c1q039",q:"Ante una fractura sospechada, se debe:",o:["Inmovilizar tal como está (sin encajar nada) y evacuar en camilla","Encajar el hueso tirando fuerte","Hacerle caminar para ver si aguantas","Aplicar calor"],a:0,x:"Signos de fractura: dolor intenso, deformidad, incapacidad funcional. NUNCA se encaja nada (puedes cortar arterias y nervios): se inmoviliza la articulación de arriba y la de abajo (férula reglamentaria o improvisada con tablas), se comprueba el pulso distal y se evacúa. En campaña, improvisar con material de equipo es técnica de cabo.",r:"Primeros auxilios"},
{c:"cabo1",b:"B1",t:"Primeros auxilios",d:"D",id:"c1q040",q:"En el protocolo militar TCCC, la primera intervención ante herido en combate suele ser:",o:["Controlar la hemorragia masiva (torniquete) tan pronto como sea seguro","Darle agua","Preguntarle el DNI","Quitarle el casco siempre"],a:0,x:"TCCC (Tactical Combat Casualty Care): fase 1 CARE UNDER FIRE (bajo fuego: suprimir fuego, poner a cubierto, torniquete de acceso si sangra masivamente); fase 2 TACTICAL FIELD CARE (a cubierto: valoración MARCH); fase 3 EVACUACIÓN. La estadística manda: el 90% de las muertes evitables son hemorragias — por eso el torniquete es la reina del botiquín de combate.",r:"TCCC"},

/* ===== NBQ (0 → 5) · B1 ===== */
{c:"cabo1",b:"B1",t:"NBQ",d:"F",id:"c1q041",q:"Las siglas NBQ significan:",o:["Nuclear, Biológico y Químico","Nada Bueno Quizás","Norte, Biblioteca y Química","Nacional, Bienal y Quirúrgica"],a:0,x:"NBQ = armamento de destrucción masiva Nuclear, Biológico y Químico Nuclear, Biológica y Química. En el ámbito aliado se usa CBRN (añadiendo Radiológico). La defensa NBQ agrupa: DETECCIÓN, ALARMA, PROTECCIÓN INDIVIDUAL Y COLECTIVA, y DESCONTAMINACIÓN. El soldado NBQ instruido sobrevive; el que improvisa, no.",r:"Defensa NBQ"},
{c:"cabo1",b:"B1",t:"NBQ",d:"M",id:"c1q042",q:"Ante un ataque NBQ lo PRIMERO es:",o:["Dar la alarma (¡GAS, GAS, GAS!) y ponerse la MÁSCARA en segundos","Sacar el móvil y hacer fotos","Correr a por agua","Quitarse la ropa"],a:0,x:"La alarma inmediata salva a los compañeros (¡GAS GAS GAS! es la señal universal de voz) y la máscara se coloca EN SEGUNDOS (conteniendo la respiración al detectarla). Después: protección de la piel, refugio o salida del área contaminada por la ruta que marque el mando, y descontaminación. Segundos NBQ = vidas.",r:"Defensa NBQ"},
{c:"cabo1",b:"B1",t:"NBQ",d:"M",id:"c1q043",q:"La máscara antigás protege vías respiratorias y ojos mediante:",o:["Un FILTRO (con vida útil limitada)","Una batería de por vida","Magia","Un ventilador de techo"],a:0,x:"El filtro retiene partículas, gases y vapores, pero se SATURA: tiene tiempo de uso limitado y caducidad. Detalles que salvan: la barba impide el ajuste estanque (máscara inútil), y el ajuste se comprueba con la técnica de sellado (obstruir y respirar). El filtro se cambia según el mando NBQ.",r:"Defensa NBQ"},
{c:"cabo1",b:"B1",t:"NBQ",d:"D",id:"c1q044",q:"Un agente NERVIOSO (como el sarín) actúa sobre:",o:["El sistema nervioso (inhibe la enzima que regula los impulsos nerviosos)","El apetito","El corte de pelo","El sistema de sonido del coche"],a:0,x:"Los nerviosos (sarin, VX) inhiben la acetilcolinesterasa: los nervios «se quedan encendidos» y el cuerpo se descontrola (pupilas en punto, convulsiones, asfixia). Existen autoinyectores de antídoto en el equipo individual. Los VESICANTES (mostaza sulfurada) en cambio queman piel y ojos. Distinguir tipos de agente = saber cómo se protege uno.",r:"Defensa NBQ"},
{c:"cabo1",b:"B1",t:"NBQ",d:"M",id:"c1q045",q:"La DESCONTAMINACIÓN NBQ busca:",o:["Eliminar o neutralizar el agente del personal, equipo y terreno para reducir el peligro","Lavar el uniforme los domingos","Pintar los vehículos","Nada"],a:0,x:"La descontaminación elimina/neutraliza el agente: PERSONAL (desvestir, lavado con agua y jabón o disolventes reglamentarios), EQUIPO y TERRENO (marcado y perímetro). Zonas de trabajo: caliente (contaminada), tibia (tránsito) y fría (limpia). Nadie sale de la zona caliente sin descontaminación: así se evita propagar el veneno.",r:"Defensa NBQ"}
];
