/* A LA ORDEN — LOTE 2 PERMANENCIA · 40 preguntas CURADAS a mano (22-sep-2026)
   Refuerzo de los bloques GORDOS del examen de 100 preguntas:
   Constitución · Defensa Nacional (LO 5/2005) · estructura del MINISDEF ·
   mecánica del examen · doctrina · misiones · físicas · convocatoria.
   Explicaciones que enseñan el PORQUÉ (nada de ecos). */
window.QUESTIONS10 = [
/* ===== CONSTITUCIÓN (12 → 22) · B1 ===== */
{c:"perm",b:"B1",t:"Constitución",d:"F",id:"pf001",q:"La Constitución Española fue RATIFICADA por el pueblo en referéndum el:",o:["6 de diciembre de 1978","29 de diciembre de 1978","31 de octubre de 1978","6 de diciembre de 1977"],a:0,x:"Cronología completa: el 31-oct-1978 las Cortes la aprueban, el 27-dic el Rey la sanciona, el 6-dic-1978 el pueblo la RATIFICA en referéndum y el 29-dic se publica en el BOE (entra en vigor). El 6 de diciembre es fiesta nacional por eso. Las trampas del examen juegan con estas cuatro fechas.",r:"Constitución Española 1978"},
{c:"perm",b:"B1",t:"Constitución",d:"F",id:"pf002",q:"Según el art. 1.1 de la CE, los VALORES SUPERIORES del ordenamiento jurídico son:",o:["La libertad, la justicia, la igualdad y el pluralismo político","El orden, la paz y el progreso","La fe, la patria y el honor","El trabajo, la familia y la propiedad"],a:0,x:"Art. 1.1 literal: «España se constituye en un Estado social y democrático de Derecho, que propugna como valores superiores de su ordenamiento jurídico la libertad, la justicia, la igualdad y el pluralismo político». Es el artículo más citado de toda la CE: aprenderlo LITERAL.",r:"CE art. 1.1"},
{c:"perm",b:"B1",t:"Constitución",d:"F",id:"pf003",q:"La forma política del Estado español es:",o:["La Monarquía parlamentaria","La República federal","La monarquía absoluta","El régimen presidencialista"],a:0,x:"Art. 1.3: «La forma política del Estado español es la Monarquía parlamentaria»: el Rey reina pero NO gobierna; el Gobierno responde ante las Cortes. Las alternativas son trampas típicas de examen.",r:"CE art. 1.3"},
{c:"perm",b:"B1",t:"Constitución",d:"F",id:"pf004",q:"La SOBERANÍA nacional reside en:",o:["El pueblo español, del que emanan los poderes del Estado","El Rey","El Presidente del Gobierno","El Ejército"],a:0,x:"Art. 1.2: «La soberanía nacional reside en el pueblo español, del que emanan los poderes del Estado». El pueblo delega en las Cortes (legislativa), el Gobierno (ejecutiva) y los jueces (judicial). Nadie está por encima del pueblo soberano.",r:"CE art. 1.2"},
{c:"perm",b:"B1",t:"Constitución",d:"M",id:"pf005",q:"El art. 2 de la CE se funda en:",o:["La indisoluble unidad de la Nación española y el derecho a la autonomía de las nacionalidades y regiones","La independencia de las provincias","El centralismo puro","La confederación de estados"],a:0,x:"Art. 2: los dos principios que sostienen el Estado: UNIDAD de la Nación española (único sujeto de soberanía) y DERECHO A LA AUTONOMÍA de nacionalidades y regiones (comunidades autónomas con competencias). Equilibrio entre los dos = pregunta de fondo recurrente.",r:"CE art. 2"},
{c:"perm",b:"B1",t:"Constitución",d:"M",id:"pf006",q:"Los DERECHOS FUNDAMENTALES y libertades públicas se recogen en:",o:["El Título I, Capítulo II (arts. 15-29)","El Título VII","El preámbulo","El Título VIII"],a:0,x:"Título I = de los derechos y deberes fundamentales; su Capítulo II (arts. 15 a 29) concentra los derechos fundamentales y libertades públicas: vida (15), ideología (16), libertad (17), igualdad ante la ley (14 en cap. I)... Sus garantías son máximas: recurso de amparo ante el Tribunal Constitucional.",r:"CE Título I"},
{c:"perm",b:"B1",t:"Constitución",d:"M",id:"pf007",q:"Los artículos constitucionales que hablan del deber de DEFENDER España y de la OBJECCIÓN de conciencia son:",o:["El 30.1 y el 30.2","El 8 y el 9","El 1 y el 2","El 104 y el 117"],a:0,x:"Art. 30.1: «Los españoles tienen el derecho y el deber de defender España» — es la base constitucional de la defensa militar. Art. 30.2: la objeción de conciencia (que con el ejército profesional hoy afecta poco en la práctica, pero SIGUE en la Constitución). La pareja 30.1/30.2 cae junta.",r:"CE art. 30"},
{c:"perm",b:"B1",t:"Constitución",d:"M",id:"pf008",q:"Según el art. 104 de la CE, la Guardia Civil:",o:["Tiene naturaleza MILITAR y depende del MIR para sus servicios y de Defensa para las misiones militares","Es un cuerpo civil del Ministerio del Interior puro","Depende de las comunidades autónomas","Es un cuerpo municipal"],a:0,x:"Art. 104: la Guardia Civil es un Instituto armado de naturaleza MILITAR. En tiempo de paz depende del Ministerio del Interior (servicios ordinarios) y del de Defensa para el cumplimiento de sus MISIONES MILITARES. Doble dependencia = la trampa clásica del examen.",r:"CE art. 104 · LO 2/1986"},
{c:"perm",b:"B1",t:"Constitución",d:"M",id:"pf009",q:"Según la CE, la bandera de España y el Himno Nacional son:",o:["Roja, amarilla y roja (art. 4.1) y la Marcha Real (art. 4.3)","Verde y blanca; el Himno de Riego","Azul y blanca; el Ode to Joy","Amarilla solo; el Soniquete"],a:0,x:"Art. 4.1: la bandera está formada por tres franjas ROJA, AMARILLA y ROJA (la amarilla doble de ancho). Art. 4.3: el Himno Nacional es la «Marcha Real». Son símbolos del Estado y respetarlos es deber cívico y militar.",r:"CE art. 4"},
{c:"perm",b:"B1",t:"Constitución",d:"D",id:"pf010",q:"La JURISDICCIÓN MILITAR dentro del Poder Judicial:",o:["Está reconocida por el art. 117.5 y se regula por ley (delitos militares, estados de sitio y emergencias)","No existe en España","Depende de cada comunidad autónoma","Juzga a todos los ciudadanos por igual"],a:0,x:"El art. 117.5 de la CE reconoce la jurisdicción militar en el marco del Poder Judicial y en los casos y formas que la ley prevea. Su ámbito hoy: los delitos militares (CPM, LO 14/2015) y las operaciones de estados excepcionales. La ley que la desarrolla es la LOPJMIL 5/2005 (¡la misma fecha que la de Defensa Nacional!).",r:"CE art. 117.5 · LOPJMIL"},

/* ===== DEFENSA NACIONAL · LO 5/2005 (7 → 15) · B1 ===== */
{c:"perm",b:"B1",t:"Defensa Nacional",d:"F",id:"pf011",q:"La Defensa Nacional se regula principalmente en:",o:["La Ley Orgánica 5/2005, de 17 de noviembre","La Ley 39/2007","La LO 8/2014","La Ley 36/2015"],a:0,x:"La LO 5/2005 es la norma básica de la Defensa Nacional: principios, órganos responsables, organización del sistema y papel de las FAS. Las otras son carreras (39/2007), disciplina (8/2014) y seguridad nacional (36/2015). Cuatro leyes, cuatro temas — no confundirlas.",r:"LO 5/2005"},
{c:"perm",b:"B1",t:"Defensa Nacional",d:"M",id:"pf012",q:"Según el art. 30.1 de la CE, la Defensa es:",o:["Un derecho Y un deber de todos los españoles","Solo una obligación del Gobierno","Solo cosa de militares","Una opción voluntaria sin más"],a:0,x:"«Los españoles tienen el derecho y el deber de defender España»: la defensa es asunto de TODA la sociedad, no solo del personal militar. De este artículo nace toda la legislación de defensa y el propio concepto de Servicio Militar (hoy en reserva, sustituido por el ejército profesional).",r:"CE art. 30.1 · LO 5/2005"},
{c:"perm",b:"B1",t:"Defensa Nacional",d:"F",id:"pf013",q:"Según el art. 8 de la CE, las Fuerzas Armadas tienen como misión:",o:["Garantizar la soberanía e independencia de España, defender su integridad territorial y el ordenamiento constitucional","Controlar el tráfico","Recaudar impuestos","Organizar elecciones"],a:0,x:"Art. 8: la triple misión esencial + la de preservar la paz y el orden en operaciones internacionales (misiones exteriores con autorización previa de las Cortes). Es EL artículo de las FAS en la Constitución: aprenderlo literal.",r:"CE art. 8"},
{c:"perm",b:"B1",t:"Defensa Nacional",d:"M",id:"pf014",q:"¿QUIÉN CONDUCE la política de la Defensa Nacional y fija sus directrices?",o:["El Presidente del Gobierno","El Rey","El JEMAD por sí solo","El alcalde"],a:0,x:"Art. 12 de la LO 5/2005: el Presidente del Gobierno conduce la Defensa Nacional y fija sus directrices; el Ministro de Defensa la desarrolla y ejecuta; el JEMAD es el asesor y mando militar. La cadena de dirección política es: Presidente → Ministro → JEMAD. No confundir con el mando de cada ejército.",r:"LO 5/2005 art. 12"},
{c:"perm",b:"B1",t:"Defensa Nacional",d:"M",id:"pf015",q:"La participación de las FAS en misiones FUERA de España requiere:",o:["Autorización previa de las Cortes Generales","Solo la firma del coronel","Un tuit del ministerio","Nada"],a:0,x:"El art. 8.1 de la CE exige que las misiones fuera del territorio nacional cuenten con AUTORIZACIÓN PREVIA de las Cortes (Congreso). Es un control parlamentario esencial: ninguna brigada sale de España sin debate y voto en el Congreso. Clásico absoluto del examen.",r:"CE art. 8 · LO 5/2005"},
{c:"perm",b:"B1",t:"Defensa Nacional",d:"M",id:"pf016",q:"El Rey es, según la Constitución:",o:["El mando supremo de las FAS (art. 62.h), símbolo de su unidad y permanencia","El que dirige el Ministerio día a día","Un oficial más","El JEMAD"],a:0,x:"Art. 62.h: el Rey es el MANDO SUPREMO de las FAS (función simbólica y representativa, sin mando operativo efectivo). El mando militar real lo ejerce el JEMAD bajo el Ministro y el Presidente, conforme a la ley. La pregunta juega con «supremo» vs «efectivo»: dos conceptos distintos.",r:"CE art. 62.h · LO 5/2005"},
{c:"perm",b:"B1",t:"Defensa Nacional",d:"D",id:"pf017",q:"La reforma de los RROO por el RD 173/2021 trajo, entre otras cosas:",o:["El reconocimiento del cometido de las FAS en EMERGENCIAS y catástrofes, y la actualización de deberes y uso de la fuerza","La supresión de los cabos","Cambiar el uniforme de color","Eliminar la instrucción"],a:0,x:"El RD 173/2021 modernizó las Reales Ordenanzas de 2009: incorpora la experiencia de 25 años de misiones, el cometido de atender emergencias y desastres (UME), el marco actualizado del uso de la fuerza y el papel del militar profesional en la sociedad digital. Los RROO siguen siendo RD 84/2015 en lo básico, con este repaso.",r:"RD 173/2021 · RROO"},
{c:"perm",b:"B1",t:"Defensa Nacional",d:"M",id:"pf018",q:"La RESERVA MILITAR, según la LO 5/2005, puede ser:",o:["Voluntaria (por contrato) u obligatoria (por llamamiento)","Solo para oficiales","Solo en tiempo de guerra","Nunca existe"],a:0,x:"La LO 5/2005 regula la reserva: VOLUNTARIA (los españoles que lo deseen pueden contratar su compromiso) y OBLIGATORIA (llamamiento de quienes ya sirvieron, para cursos de formación o situaciones de emergencia). El objetivo: contar con personal entrenado si el país lo necesita.",r:"LO 5/2005 arts. 60-64"},

/* ===== MINISDEF (6 → 12) · B1 ===== */
{c:"perm",b:"B1",t:"MINISDEF",d:"F",id:"pf019",q:"¿Quién está al frente del Ministerio de Defensa, bajo el Presidente del Gobierno?",o:["El Ministro de Defensa","El JEMAD","El alcalde de Madrid","El Defensor del Pueblo"],a:0,x:"El Ministro de Defensa es el miembro del Gobierno que dirige y ejecuta la política de Defensa (art. 12 LO 5/2005). Bajo su autoridad actúan los subsecretarios, secretarios de Estado y los Jefes de Estado Mayor. El JEMAD es el asesor y mando militar, no el jefe político.",r:"LO 5/2005 · estructura MINISDEF"},
{c:"perm",b:"B1",t:"MINISDEF",d:"M",id:"pf020",q:"La SEDEF (Secretaría de Estado de Defensa) se encarga principalmente de:",o:["Los RECURSOS de defensa: presupuestos, infraestructura, armamento y material (de ella depende la DGAM)","Mandar las tropas en combate","Dirigir la política exterior","Cocinar en el comedor"],a:0,x:"La SEDEF gestiona los medios materiales y económicos: presupuesto, sistemas de información, infraestructura y la Dirección General de Armamento y Material (DGAM), que compra y gestiona el equipamiento militar. Es el «brazo logístico-administrativo» del Ministerio.",r:"Estructura del MINISDEF (RD 994/2017 y siguientes)"},
{c:"perm",b:"B1",t:"MINISDEF",d:"M",id:"pf021",q:"La SEGENDEF (Secretaría General de Defensa) apoya al Ministro especialmente en:",o:["La DIRECCIÓN del PERSONAL y la política de enseñanza","El pintado de muros","La flota pesquera","Nada"],a:0,x:"La SEGENDEF es el «brazo del personal»: apoyo directo al Ministro en la dirección de recursos humanos, enseñanza, protección de datos, acciones sociales. Diferencia clave: SEDEF = medios materiales; SEGENDEF = PERSONAL. Pregunta que separa a quien ha estudiado de quien adivina.",r:"Estructura del MINISDEF"},
{c:"perm",b:"B1",t:"MINISDEF",d:"M",id:"pf022",q:"La SUBSECRETARÍA de Defensa gestiona fundamentalmente:",o:["La organización, los asuntos comunes y el régimen interior del Ministerio","La política de la UE","El calzado reglamentario","Las misiones en el extranjero"],a:0,x:"La Subsecretaría es el «eje común» del Ministerio: organización, presupuestos y asuntos generales, contratación, tecnologías de la información y apoyo a todos los órganos. De su gestión cotidiana depende que el resto del Ministerio funcione.",r:"Estructura del MINISDEF"},
{c:"perm",b:"B1",t:"MINISDEF",d:"M",id:"pf023",q:"La INSPECCIÓN GENERAL DE SANIDAD (IGS) de Defensa se ocupa de:",o:["La SANIDAD militar: hospitales, farmacia, sanidad operativa y salud de los militares","La limpieza de los cuarteles","El veterinario de mascotas","Los taxis militares"],a:0,x:"La IGS gestiona la sanidad militar: hospitales (como el Gómez Ulla), farmacia, salud operativa, prevención y sanidad en operaciones. Cuando un militar baja de una maniobra o una misión, es su cadena sanitaria: desde el puesto de socorro de unidad hasta el hospital militar.",r:"Estructura del MINISDEF"},
{c:"perm",b:"B1",t:"MINISDEF",d:"M",id:"pf024",q:"El ISFAS es:",o:["El Instituto Social de las Fuerzas Armadas: mutualidad que cubre sanidad y prestaciones de militares y familiares","Una base militar en Filipinas","Un tipo de fusil","El sindicato del Ministerio"],a:0,x:"ISFAS = Instituto Social de las Fuerzas Armadas: la «mutua» de los militares. Cubre asistencia sanitaria, prestaciones familiares, incapacidad temporal y otras prestaciones para el personal militar y sus beneficiarios. Saberlo distinguir de la IGS (sanidad operativa) evita trampas.",r:"ISFAS"},

/* ===== EL EXAMEN (5 → 9) · B1 ===== */
{c:"perm",b:"B1",t:"El examen",d:"F",id:"pf025",q:"El examen de permanencia consta de:",o:["100 preguntas en 120 minutos","20 preguntas en 10 minutos","500 preguntas en un día","10 preguntas orales"],a:0,x:"Formato estándar del examen de la condición de militar de carrera (permanencia): 100 preguntas tipo test de 4 opciones, 120 minutos. Muy distinto del de Cabo (50+5 en 70 min): exige resistencia mental y gestión del tiempo — una pregunta cada 72 segundos de media.",r:"Bases de la convocatoria"},
{c:"perm",b:"B1",t:"El examen",d:"M",id:"pf026",q:"La fórmula de corrección del examen de permanencia es:",o:["P = A − E/(n−1), es decir, A − E/3 con 4 opciones","P = A + E","P = E − A","P = al azar"],a:0,x:"Cada acierto suma 1 punto y cada error RESTA 1/(n−1) = 1/3 (con 4 opciones). La idea: con 4 opciones, quien responde al azar acierta 1 de 4 y falla 3; la resta neutraliza la suerte. Blanco no penaliza. Es la fórmula de los 100 puntos máximos.",r:"Bases de la convocatoria"},
{c:"perm",b:"B1",t:"El examen",d:"M",id:"pf027",q:"Las preguntas EN BLANCO en el examen de permanencia:",o:["No penalizan (0 puntos)","Restan 1 punto cada una","Restan más que los fallos","Anulan el examen"],a:0,x:"El blanco no resta: es 0. La estrategia profesional: responde SIEMPRE que descartes al menos una opción (la esperanza matemática mejora el 0); deja blanco si no tienes ni idea y no puedes descartar nada. Gestionar esto puede valer varios puntos de corte.",r:"Bases de la convocatoria"},
{c:"perm",b:"B1",t:"El examen",d:"M",id:"pf028",q:"En un examen con corrección A − E/3, ¿qué conviene hacer con una pregunta que no sabes pero descartas 2 opciones?",o:["Responder: con 2 opciones vivas, la esperanza matemática es positiva (2 de 4)","Dejarla en blanco siempre","Pedir ayuda al compañero","Escribir dos respuestas"],a:0,x:"Cálculo: acierto = +1, fallo = −1/3. Si descartas 2 opciones, aciertas el 50% de las veces: media de +0,33 por pregunta — mejor que el blanco (0). Solo conviene dejar blanco cuando no puedes descartar NADA (media negativa −0,17 si respondes al azar puro).",r:"Estrategia de examen"},

/* ===== FÍSICAS (5 → 7) · B3 ===== */
{c:"perm",b:"B3",t:"Físicas",d:"M",id:"pf029",q:"Las MARCAS mínimas de las pruebas físicas en los procesos de la tropa dependen de:",o:["El sexo y la edad del candidato","La talla del zapato","El color del pelo","El día de la semana"],a:0,x:"El sistema de valoración física de las FAS agrupa a los candidatos por sexo y grupos de edad, y fija marcas mínimas distintas para cada grupo en velocidad/agilidad, fuerza y resistencia. Compara tu marca con la de TU grupo, no con la del mejor de la unidad.",r:"Plan de preparación física FAS"},
{c:"perm",b:"B3",t:"Físicas",d:"M",id:"pf030",q:"Lo IMPRESCINDIBLE antes de cualquier sesión de entrenamiento o prueba física es:",o:["El calentamiento progresivo (movilidad + activación)","Comer mucho","Dormir en la sala de pesas","Tomar 5 cafés"],a:0,x:"El calentamiento (8-10 min de movilidad articular + activación cardiovascular + series suaves) eleva la temperatura muscular y prepara el corazón: previene lesiones y mejora marcas. La lesión del impaciente se llaman «de la primera semana»: llegan al examen cojos.",r:"Preparación física"},

/* ===== CONVOCATORIA (5 → 7) · B3 ===== */
{c:"perm",b:"B3",t:"Convocatoria",d:"M",id:"pf031",q:"Si la INSTANCIA llega FUERA de plazo:",o:["Quedas EXCLUIDO del proceso, sin más trámite","Se acepta con un suplicatorio","Se acepta si llegas el día siguiente","Puedes presentarla al examen directamente"],a:0,x:"Los plazos administrativos son PRECLUSIVOS: cerrada la puerta, cerrada. No hay «se acepta si se retrasa un poco». Por eso el consejo de siempre: presentarla la PRIMERA semana de convocatoria, guardar justificante de la sede electrónica y no confiar en el último día (la web se satura).",r:"Bases de convocatoria"},
{c:"perm",b:"B3",t:"Convocatoria",d:"M",id:"pf032",q:"Las LISTAS de admitidos/excluidos y los resultados del proceso se publican en:",o:["El BOD y la sede electrónica del Ministerio de Defensa","El tablón del bar","La radio local","Un grupo de WhatsApp"],a:0,x:"Toda la tramitación es electrónica: BOD (boletín oficial) para las resoluciones y la sede electrónica de Defensa para consultas y notificaciones. Vigilar las publicaciones ES PARTE DEL PROCESO: hay plazos cortos para subsanar o reclamar y quien no mira, se cae.",r:"BOD · sede electrónica"},

/* ===== DOCTRINA (7 → 9) · B3 ===== */
{c:"perm",b:"B3",t:"Doctrina",d:"M",id:"pf033",q:"La diferencia entre INSTRUCCIÓN y ADIESTRAMIENTO es:",o:["La instrucción prepara al INDIVIDUO; el adiestramiento prepara a la UNIDAD","Son lo mismo","La instrucción es de oficiales y el adiestramiento de cabos","No existe la instrucción"],a:0,x:"Distinción básica de la enseñanza militar: INSTRUCCIÓN = formación del militar individual (tiro, topografía, primeros auxilios); ADIESTRAMIENTO = integración y entrenamiento de la unidad (escuadra, sección, compañía) para cumplir su misión. El cabo 1º participa en ambas: instruye individuos y adiestra su elemento.",r:"Doctrina militar · MADOC"},
{c:"perm",b:"B3",t:"Doctrina",d:"M",id:"pf034",q:"La EVALUACIÓN del adiestramiento sirve para:",o:["Conocer el grado de preparación (aptitud) de la unidad y corregir carencias","Castigar a los soldados","Dar premios al azar","Rellenar el parte"],a:0,x:"Sin evaluación no hay mejora: medir el adiestramiento (ejercicios, calificaciones, pruebas) permite saber si la unidad está APTA para su misión y dónde están las carencias. El ciclo es: planificar → instruir/adiestrar → evaluar → corregir. Nunca se adiestra «por costumbre».",r:"Doctrina de adiestramiento"},

/* ===== MISIONES (8 → 10) · B3 ===== */
{c:"perm",b:"B3",t:"Misiones",d:"M",id:"pf035",q:"La Operación COYOTE es la contribución española a:",o:["El Baltic Air Policing de la OTAN: cazas Eurofighter protegiendo el espacio aéreo báltico desde Lituania","Una película del oeste","La vigilancia del Estrecho","Un festival de música"],a:0,x:"España despliega cazas Eurofighter en Lituania (base Šiauliai) dentro del Baltic Air Policing de la OTAN: proteger el espacio aéreo de Estonia, Letonia y Lituania, aliados sin medios aéreos suficientes. El nombre nacional de la contribución española: Operación Coyote. Ejemplo de disuasión colectiva desde el aire.",r:"OTAN · Baltic Air Policing"},
{c:"perm",b:"B3",t:"Misiones",d:"M",id:"pf036",q:"La misión VIGMIRO consiste en:",o:["La vigilancia y seguridad del Mediterráneo Occidental","Vigilar el Museo del Prado","Controlar el mar Caribe","Nada"],a:0,x:"VIGMIRO (Vigilancia del Mediterráneo Occidental) es la misión permanente de las FAS en aguas del sur de España: aeronaves de patrulla marítima (PATMAR) y medios que vigilan el tráfico marítimo, la seguridad y actúan en apoyo ante emergencias. Misión nacional discreta pero permanente desde 1997.",r:"MOPS · VIGMIRO"},

/* ===== CARRERA MILITAR (11 → 13) · B2 ===== */
{c:"perm",b:"B2",t:"Carrera militar",d:"M",id:"pf037",q:"Según la LO 9/2011, los militares profesionales pueden afiliarse a:",o:["Asociaciones PROFESIONALES de militares (no sindicatos al uso)","Sindicatos civiles generales","Partidos políticos ejerciendo el mando","Nada de nada"],a:0,x:"La LO 9/2011 desarrolla la libertad de ASOCIACIÓN PROFESIONAL: las asociaciones de militares (AMAE, AUME, ATME, USOC-Militar, etc.) defienden intereses profesionales SIN poder llamarse sindicatos ni ejercer huelga. Y los militares en ACTIVO no pueden afiliarse a partidos ni presentarse a cargos políticos sin abandonar el servicio. Distinción que cae cada año.",r:"LO 9/2011"},
{c:"perm",b:"B2",t:"Carrera militar",d:"D",id:"pf038",q:"La Ley 41/2020, de 29 de diciembre, tuvo como efecto principal:",o:["Incorporar el régimen del personal de tropa y marinería como Título VII de la Ley 39/2007, reformando la Ley 8/2006","Prohibir el café en los cuarteles","Crear un cuarto ejército","Nada"],a:0,x:"La Ley 41/2020 reordenó el régimen del personal de TM: su contenido pasó a ser el Título VII de la Ley 39/2007 (acceso, compromisos, promoción de la tropa) y reformó la Ley 8/2006. Resultado práctico: HOY, todo el régimen de tropa se estudia en la L 39/2007 (con la 8/2006 modificada como apoyo). Las bases de permanencia citan esta norma.",r:"Ley 41/2020 · Ley 39/2007 Título VII"},

/* ===== FAS (8 → 10) · B1 ===== */
{c:"perm",b:"B1",t:"FAS",d:"F",id:"pf039",q:"Las Fuerzas Armadas de España están formadas por:",o:["Ejército de Tierra, Armada y Ejército del Aire y del Espacio","Policía Nacional, Guardia Civil y Policía Local","Solo Infantería de Marina","Bomberos y Protección Civil"],a:0,x:"Tres ejércitos: Tierra, Armada y Ejército del Aire (que desde 2021 se denomina oficialmente «Ejército del Aire y del Espacio» por su nueva dimensión espacial). La Guardia Civil y la Policía NO son FAS (la GC es de naturaleza militar, pero es Instituto armado del Interior en tiempo de paz).",r:"LO 5/2005 · estructura FAS"},
{c:"perm",b:"B1",t:"FAS",d:"M",id:"pf040",q:"El JEMAD (Jefe de Estado Mayor de la Defensa) es:",o:["El asesor del Ministro y el MANDO MILITAR de las FAS bajo su autoridad; los JEME/AJEMA/JEA PREPARAN sus ejércitos","El que manda un batallón","El intendente del cuartel","El portero del Ministerio"],a:0,x:"Desde el RD 1099/2019, el JEMAD concentra el mando militar bajo el Ministro: dirige el empleo de las FAS (vía MOPS) y asesora al Gobierno. Los Jefes de Estado Mayor de cada ejército (JEME, AJEMA, JEA) se dedican a PREPARAR sus fuerzas (organización, adiestramiento, dotación). Esquema que hay que tener dormido: EMPLEO = JEMAD; PREPARACIÓN = JEME/AJEMA/JEA.",r:"RD 1099/2019"}
];
