/* MICABO — LOTE OFICIAL 1 · PERMANENCIA · 24 preguntas CURADAS desde la TEORÍA OFICIAL
   del Rincón de Tropa aportada por el usuario (24-sep-2026):
   · Tema 5 OSCE (documento OISD 09003a9980b05468, 30-sep-2019)
   · Bloque Jurídico-Social Tema 3: Derechos y deberes de los miembros de las FAS (LO 9/2011)
   Cada pregunta con fuente de la teoría oficial. Nada de ecos. */
window.QUESTIONS12 = [
/* ===== OSCE — Tema 5 oficial (3 → 13) · B3 ===== */
{c:"perm",b:"B3",t:"OSCE",d:"F",id:"po001",q:"El Acta Final de Helsinki, que dio nacimiento a la CSCE (futura OSCE), se firmó en:",o:["1975","1957","1989","2001"],a:0,x:"Los ministros se reunieron por primera vez el 3 de julio de 1973 en Helsinki (etapa I de la Conferencia) y el Acta Final se firmó en 1975: contiene los principios políticos y los compromisos de cooperación que dieron vida a la CSCE. Nuestro Tema 5 oficial la llama «el nacimiento de la organización».",r:"Teoría oficial · Tema 5 OSCE (OISD)"},
{c:"perm",b:"B3",t:"OSCE",d:"M",id:"po002",q:"Tras el fin de la Guerra Fría, la Cumbre de PARÍS (noviembre de 1990) y su Carta marcaron:",o:["El nuevo rumbo de la CSCE: cooperación tras la confrontación Este-Oeste","La disolución de la OSCE","La entrada de España","La creación de la OTAN"],a:0,x:"Durante los días 19-21 de noviembre de 1990, la Cumbre de París aprobó la Carta de París para una Nueva Europa: el nuevo rumbo de la organización tras la caída del Muro. La firmaron 22 países: los miembros de la Alianza Atlántica y del Pacto de Varsovia.",r:"Teoría oficial · Tema 5 OSCE (OISD)"},
{c:"perm",b:"B3",t:"OSCE",d:"M",id:"po003",q:"En la Cumbre de BUDAPEST (diciembre de 1994) ocurrió:",o:["La CSCE pasó a llamarse OSCE y fijó su sede en Viena","Se firmó el Acta Final","España se adhirió","Se creó la ONU"],a:0,x:"En Budapest (dic-1994) la CSCE dejó de ser una simple conferencia y pasó a llamarse oficialmente OSCE (Organización), fijando su sede en Viena. En aquel momento eran 52 Estados miembros. Cambio de nombre = cambio de naturaleza: de proceso de conferencia a organización permanente.",r:"Teoría oficial · Tema 5 OSCE (OISD)"},
{c:"perm",b:"B3",t:"OSCE",d:"F",id:"po004",q:"¿Cuántos Estados PARTICIPANTES integran hoy la OSCE?",o:["57","22","35","193"],a:0,x:"57 Estados participantes «de distintos puntos del hemisferio norte» (nuestro temario oficial incluye la lista alfabética completa, de Albania a Uzbekistán). Es la mayor organización regional de seguridad del mundo. Truco: 57 = la cifra que se repite en todos los exámenes de OSCE.",r:"Teoría oficial · Tema 5 OSCE (OISD)"},
{c:"perm",b:"B3",t:"OSCE",d:"M",id:"po005",q:"El órgano de CONSULTA POLÍTICA y toma de decisiones de la OSCE es:",o:["El Consejo Permanente","La Asamblea Parlamentaria","El Consejo de Europa","El FSC"],a:0,x:"El Consejo Permanente (que se reúne semanalmente en Viena) es el órgano de consulta política y toma de decisiones. España está integrada en él e interviene en la ejecución de sus resoluciones (misiones de paz, grupos de observadores a zonas en crisis).",r:"Teoría oficial · Tema 5 OSCE (OISD)"},
{c:"perm",b:"B3",t:"OSCE",d:"M",id:"po006",q:"El CONSEJO MINISTERIAL de la OSCE reúne:",o:["Una vez al año a los ministros de Asuntos Exteriores de los países miembros","A los ministros de Defensa cada semana","A los reyes de Europa","A los jefes de Estado cada mes"],a:0,x:"Entre los órganos de la OSCE, el Consejo Ministerial reúne UNA VEZ AL AÑO a los ministros de Asuntos Exteriores. La lista oficial de órganos: Cumbre de Jefes de Estado y Gobierno, Consejo Ministerial, Consejo Permanente, Asamblea Parlamentaria, FSC y ODIHR.",r:"Teoría oficial · Tema 5 OSCE (OISD)"},
{c:"perm",b:"B3",t:"OSCE",d:"M",id:"po007",q:"La ODIHR (Oficina de Instituciones Democráticas y Derechos Humanos) tiene su SEDE en:",o:["Varsovia","Viena","Praga","Copenhague"],a:0,x:"La Oficina de Instituciones Democráticas y Derechos Humanos (ODIHR) tiene su sede en VARSOVIA. Es la rama que organiza la observación electoral y el trabajo en derechos humanos — España participa aportando observadores. No confundir con la sede de la organización (Viena).",r:"Teoría oficial · Tema 5 OSCE (OISD)"},
{c:"perm",b:"B3",t:"OSCE",d:"D",id:"po008",q:"La PRESIDENCIA de la OSCE se ejerce:",o:["Anualmente, por un Estado participante","De por vida por el fundador","Por el Secretario General de la ONU","Por rotación entre ministros de Defensa"],a:0,x:"La Presidencia de la OSCE la ejerce anualmente un Estado participante (que asume la dirección política de la organización durante su año). Junto a ella trabajan el Secretario General y las instituciones (ODIHR, Alto Comisionado, Representante para la libertad de prensa).",r:"Teoría oficial · Tema 5 OSCE (OISD)"},
{c:"perm",b:"B3",t:"OSCE",d:"M",id:"po009",q:"El enfoque INTEGRAL de la seguridad de la OSCE engloba tres dimensiones:",o:["Político-militar, económico-ambiental y humana","Terrestre, marítima y aérea","Norte, sur y este","Legal, económica y deportiva"],a:0,x:"El enfoque integral de la seguridad OSCE tiene tres dimensiones: POLÍTICO-MILITAR, ECONÓMICO-AMBIENTAL y HUMANA (derechos humanos, democracia). Esa visión «de tres dimensiones» es lo que la distingue como foro de diálogo y plataforma de acción conjunta.",r:"Teoría oficial · Tema 5 OSCE (OISD)"},
{c:"perm",b:"B3",t:"OSCE",d:"M",id:"po010",q:"España es miembro de la OSCE (y antes de la CSCE):",o:["Desde sus orígenes (junio de 1973)","Desde 1986","Desde 2001","No es miembro"],a:0,x:"España forma parte de la organización DESDE SUS ORÍGENES (la Conferencia arrancó en junio de 1973) y está integrada en el Consejo Permanente en Viena. También participa en los foros de Viena de Fomento de Medidas de Confianza y Seguridad (FMCS) y control de armamentos (FSC).",r:"Teoría oficial · Tema 5 OSCE (OISD)"},

/* ===== DERECHOS Y DEBERES · LO 9/2011 — Tema 3 oficial (6 → 20) · B2 ===== */
{c:"perm",b:"B2",t:"Derechos y deberes",d:"F",id:"pd001",q:"Además de regular los derechos y deberes, la LO 9/2011 CREÓ:",o:["El Observatorio de la Vida Militar (OVM)","El Guardia Civil","El Consejo de Seguridad Nacional","La UME"],a:0,x:"Art. 1.2 literal: «Asimismo crea el Observatorio de la Vida Militar» — el órgano colegiado que analiza el régimen del personal y las condiciones de vida de los militares y eleva informes (al Congreso, a través del Ministro). El OVM sale en el Tema 7 de tu bloque Jurídico-Social: nace aquí.",r:"LO 9/2011 art. 1 · teoría oficial Tema 3"},
{c:"perm",b:"B2",t:"Derechos y deberes",d:"M",id:"pd002",q:"El ÁMBITO de aplicación de la LO 9/2011 son:",o:["Todos los miembros de las FAS que adquieren la condición militar según la Ley 39/2007","Solo los oficiales","Solo la tropa","Los civiles de Defensa"],a:0,x:"Art. 2: los destinatarios son TODOS los miembros de las FAS que adquieren la condición militar según la Ley 39/2007 (militares de carrera y de tropa y marinería). La ley regula sus derechos fundamentales con las peculiaridades del estatuto militar y las exigencias de la seguridad y defensa.",r:"LO 9/2011 art. 2 · teoría oficial Tema 3"},
{c:"perm",b:"B2",t:"Derechos y deberes",d:"M",id:"pd003",q:"Según el art. 13, el militar y las MANIFESTACIONES:",o:["No puede organizar ni participar activamente en reuniones o manifestaciones de carácter político o sindical","Puede encabezarlas si es en su tiempo libre","Puede hacerlo siempre en uniforme","No tiene ninguna limitación"],a:0,x:"Art. 13.1: puede ejercer el derecho de reunión según la LO 9/1983, pero NO organizar ni participar activamente en reuniones o manifestaciones POLÍTICAS o SINDICALES. Y con uniforme o haciendo uso de su condición: ni organizar, ni participar, NI ASISTIR a manifestaciones políticas, sindicales o reivindicativas en lugares de tránsito público.",r:"LO 9/2011 art. 13 · teoría oficial Tema 3"},
{c:"perm",b:"B2",t:"Derechos y deberes",d:"D",id:"pd004",q:"Una REUNIÓN DENTRO de la unidad (acuartelamiento):",o:["Requiere autorización previa y expresa del jefe, que puede denegarla motivadamente","Está siempre prohibida","La convoca el soldado más antiguo","Es libre sin condiciones"],a:0,x:"Art. 13.2: las reuniones en las unidades deben estar PREVIA Y EXPRESAMENTE AUTORIZADAS por el jefe de unidad, que podrá denegarlas MOTIVADAMENTE ponderando la salvaguarda de la disciplina y las necesidades del servicio. Equilibrio clásico del estatuto: derecho reconocido, ejercicio condicionado al servicio.",r:"LO 9/2011 art. 13.2 · teoría oficial Tema 3"},
{c:"perm",b:"B2",t:"Derechos y deberes",d:"F",id:"pd005",q:"¿Pueden VOTAR los militares profesionales?",o:["Sí, tienen derecho de sufragio activo","No, lo prohíbe la LO 9/2011","Solo en elecciones europeas","Solo por correo"],a:0,x:"Art. 15: el militar tiene DERECHO DE SUFRAGIO (activo): vota como cualquier ciudadano. Lo que la ley limita es otra cosa: la elegibilidad y la participación activa en política (neutralidad política, art. 7). Votar sí — presentarse a alcaldes en activo, no.",r:"LO 9/2011 art. 15 · teoría oficial Tema 3"},
{c:"perm",b:"B2",t:"Derechos y deberes",d:"M",id:"pd006",q:"El DERECHO DE PETICIÓN del militar se ejerce:",o:["Solo individualmente (LO 4/2001)","Por sindicatos","De forma colectiva siempre","Por escrito y a la vez que una queja"],a:0,x:"Art. 16: el derecho de petición se ejerce SÓLO INDIVIDUALMENTE, según la LO 4/2001 reguladora del Derecho de Petición. Las vías COLECTIVAS existen pero por otra puerta: las INICIATIVAS del art. 28. La pareja petición (individual) / iniciativa (puede ser colectiva) es una trampa de examen clásica.",r:"LO 9/2011 art. 16 · teoría oficial Tema 3"},
{c:"perm",b:"B2",t:"Derechos y deberes",d:"M",id:"pd007",q:"Las INICIATIVAS y propuestas que afectan con carácter general a una categoría se presentan:",o:["Ante el oficial, suboficial mayor y cabo mayor designados a tal efecto en la unidad","Directamente en el BOE","Por teléfono al Ministro","En el ayuntamiento"],a:0,x:"Art. 28.2: las iniciativas que afecten con carácter general a los miembros de su categoría se presentan por cada militar EN SU UNIDAD ante el OFICIAL, SUBOFICIAL MAYOR y CABO MAYOR designados a tal efecto, quienes las trasladan al jefe de unidad. Fíjate: el CABO MAYOR es pieza oficial del canal — relevancia del empleo al que aspiras.",r:"LO 9/2011 art. 28.2 · teoría oficial Tema 3"},
{c:"perm",b:"B2",t:"Derechos y deberes",d:"M",id:"pd008",q:"Recibidas las iniciativas, el jefe de unidad:",o:["Atiende y resuelve lo que esté en su ámbito, o lo remite con informe al Mando/Jefatura de Personal del Ejército","Las destruye","Las publica en el tablón","Las manda al Rey"],a:0,x:"Art. 28.2 (continuación): el jefe de unidad resuelve lo suyo o lo remite CON INFORME al Mando o Jefatura de Personal del Ejército correspondiente; este acusa recibo, analiza las propuestas en los órganos que determine y resuelve o envía a la Subsecretaría de Defensa. Y al año se INFORMA del resultado: el circuito está cerrado y garantizado.",r:"LO 9/2011 art. 28.2 · teoría oficial Tema 3"},
{c:"perm",b:"B2",t:"Derechos y deberes",d:"M",id:"pd009",q:"El principio de NEUTRALIDAD POLÍTICA Y SINDICAL del militar:",o:["Le impide ejercer influencia política o sindical desde su condición militar","Le obliga a votar en blanco","Solo aplica a generales","Desaparece en vacaciones"],a:0,x:"Art. 7: neutralidad política y sindical. El militar no puede usar su condición, su uniforme o su unidad para influir política o sindicalmente. Es el principio que also sostiene a las asociaciones profesionales (art. 33.3): respetan la neutralidad y no pueden llamar a la huelga.",r:"LO 9/2011 art. 7 · teoría oficial Tema 3"},
{c:"perm",b:"B2",t:"Derechos y deberes",d:"M",id:"pd010",q:"Las ASOCIACIONES PROFESIONALES de militares tienen como finalidad:",o:["La promoción y defensa de los intereses profesionales, económicos y sociales de sus asociados","Dirigir las operaciones militares","Poner políticas de seguridad y defensa","Sustituir al mando"],a:0,x:"Art. 33.1: su finalidad es la promoción y defensa de los intereses profesionales, económicos y sociales. Pueden hacer actividades sociales (deontología, cultura de seguridad y defensa) pero JAMÁS interferir en decisiones de política de defensa ni en el planeamiento y desarrollo de operaciones (art. 33.2).",r:"LO 9/2011 arts. 33-34 · teoría oficial Tema 3"},
{c:"perm",b:"B2",t:"Derechos y deberes",d:"M",id:"pd011",q:"Para ser válidas, las asociaciones profesionales de militares deben INSCRIBIRSE en:",o:["El Registro de Asociaciones Profesionales de miembros de las FAS del Ministerio de Defensa","El registro municipal","El BOE directamente","Un notario"],a:0,x:"Art. 36.1: la inscripción se hace en el REGISTRO DE ASOCIACIONES PROFESIONALES de miembros de las FAS, habilitado en el Ministerio de Defensa, a solicitud de cualquiera de sus promotores (que depositan los estatutos). Sin inscripción, no quedan en el ámbito de la ley.",r:"LO 9/2011 art. 36 · teoría oficial Tema 3"},
{c:"perm",b:"B2",t:"Derechos y deberes",d:"M",id:"pd012",q:"El DEBER DE RESERVA del militar (art. 21) obliga a:",o:["Guardar secreto sobre los asuntos clasificados y los que así lo exijan por su naturaleza","Contar todo en las redes sociales","Publicar las claves de la unidad","Nada"],a:0,x:"Art. 21: deber de reserva — el militar guarda secreto de la información clasificada y de la que, sin serlo, su divulgación pueda perjudicar los intereses de la Defensa. Deber que PERSISTE aunque finalice el servicio. Enlaza con la LO 9/1968 de Secretos Oficiales y con la protección de datos (RD-LO 3/2018).",r:"LO 9/2011 art. 21 · teoría oficial Tema 3"},
{c:"perm",b:"B2",t:"Derechos y deberes",d:"M",id:"pd013",q:"Si un militar considera vulnerado un derecho, además de las vías internas puede acudir a:",o:["El Defensor del Pueblo (art. 17)","El alcalde de su municipio","Las redes sociales","Nadie"],a:0,x:"Art. 17: el militar puede dirigirse al DEFENSOR DEL PUEBLO en los mismos términos que cualquier ciudadano — es un alto comisionado de las Cortes para la defensa de los derechos del Título I de la Constitución. Junto con las iniciativas/quejas (art. 28) y la asistencia jurídica (art. 29), forma el sistema de garantías del militar.",r:"LO 9/2011 art. 17 · teoría oficial Tema 3"},
{c:"perm",b:"B2",t:"Derechos y deberes",d:"F",id:"pd014",q:"La LO 9/2011, de derechos y deberes de los miembros de las FAS, es de:",o:["5 de agosto de 2011","26 de septiembre de 2014","17 de noviembre de 2007","6 de diciembre de 1978"],a:0,x:"LO 9/2011, de 5 de agosto, de derechos y deberes de los miembros de las Fuerzas Armadas. No confundir: LO 8/2014 (26-sep) es la disciplinaria; Ley 39/2007 (19-nov), la de carrera; LO 5/2005 (17-nov), la de Defensa Nacional. Cuatro fechas, cuatro leyes — el examen las baraja.",r:"LO 9/2011 · teoría oficial Tema 3"}
];
