/* A LA ORDEN — Ronda 3: +12 Cabo 1º y +13 Permanente (desbloquea simulacro completo de 100) */
window.QUESTIONS4 = [
/* ===== CABO 1º ===== */
{c:"cabo1",b:"B1",t:"Régimen disciplinario",d:"M",id:"n229",q:"En general, cuanto más leve es la falta anotada…",o:["Antes se cancela la anotación en la hoja de servicios","Más años tarda en cancelarse","Nunca llega a cancelarse","Depende del destino del militar"],a:0,x:"La LORDFAS fija plazos de cancelación más cortos cuanto más leve es la falta.",r:"LO 8/2014 · cancelación"},
{c:"cabo1",b:"B1",t:"Documentación",d:"F",id:"n230",q:"El parte diario de la unidad sirve para…",o:["Recoger las novedades del día: servicios, altas, bajas y novedades de tropa","Pedir comida al comedor","Anunciar los desfiles del año","Sustituir a la hoja de servicios"],a:0,x:"El parte diario refleja las novedades de la unidad en el día.",r:"Régimen interior"},
{c:"cabo1",b:"B1",t:"Logística",d:"M",id:"n231",q:"Según la clasificación de suministros, la Clase III corresponde a…",o:["Combustibles y lubricantes","Munición","Raciones de combate","Material de fortificación"],a:0,x:"Clase III = POL: petróleos, combustibles y lubricantes.",r:"Clasificación OTAN de suministros"},
{c:"cabo1",b:"B1",t:"Logística",d:"F",id:"n232",q:"La evacuación en combate consiste en…",o:["Trasladar las bajas (heridos y fallecidos) hacia la retaguardia","Retirarse del combate con la unidad","Cambiarse de posición de tiro","Reponer munición del puesto"],a:0,x:"Evacuación: mover bajas desde la primera línea hacia asistencia sanitaria.",r:"Doctrina logística"},
{c:"cabo1",b:"B1",t:"Seguridad",d:"M",id:"n233",q:"El principio de «necesidad de saber» implica…",o:["Solo se facilita información clasificada a quien la necesita para su trabajo","Todos deben conocer todos los secretos","La información se publica para no dar pasos en falso","Solo aplica en operaciones de combate"],a:0,x:"Además de la habilitación de seguridad, hace falta necesidad de saber.",r:"Seguridad de la información"},
{c:"cabo1",b:"B1",t:"Tiro",d:"F",id:"n234",q:"El «cero» de un arma es…",o:["El ajuste de alza y punto de mira para acertar a una distancia determinada","El número de serie del arma","El estado sin munición","El primer disparo de la instrucción"],a:0,x:"«Dar cero»: ajustar el alineamiento de miras al punto de impacto.",r:"Instrucción de tiro"},
{c:"cabo1",b:"B1",t:"Topografía",d:"M",id:"n235",q:"En la retícula UTM de un mapa militar, las coordenadas se leen en…",o:["Kilómetros, con cifras subsidiarias en metros","Millas náuticas","Pasos naturales","Grados sexagesimales únicamente"],a:0,x:"Las cuadrículas UTM se numeran en km; los metros dan la precisión.",r:"Manual topográfico"},
{c:"cabo1",b:"B1",t:"Organización",d:"F",id:"n236",q:"La sección suele estar formada por…",o:["Varias escuadras, al mando de un sargento o cabo 1º","Un solo soldado","Tres brigadas","Todo el regimiento"],a:0,x:"Escuadras → sección → compañía, en la escala orgánica elemental.",r:"Organización de unidades"},
{c:"cabo1",b:"B1",t:"Mando y liderazgo",d:"M",id:"n237",q:"La motivación intrínseca es la que…",o:["Nace de la propia persona: orgullo, superación y pertenencia","Depende de los premios económicos","Se impone con castigos","Viene del inspector general"],a:0,x:"Intrínseca = interna; extrínseca = incentivos o presión externa.",r:"Doctrina de liderazgo"},
{c:"cabo1",b:"B2",t:"Inglés",d:"F",id:"n238",q:"En el alfabeto fonético de la OTAN, la letra N corresponde a…",o:["November","Ninja","North","Neutral"],a:0,x:"November es la palabra clave de la N.",r:"Alfabeto fonético OTAN"},
{c:"cabo1",b:"B2",t:"Técnicas de mando",d:"F",id:"n239",q:"Una orden de operaciones debe ser…",o:["Clara, breve y precisa","Larga y detallada hasta el último detalle","Confidencial incluso para quien la ejecuta","Improvisada en el momento"],a:0,x:"Clara, breve y precisa: la tríada clásica de la orden militar.",r:"Doctrina de órdenes"},
{c:"cabo1",b:"B2",t:"Administración",d:"M",id:"n240",q:"El plazo general para interponer recurso de alzada es de…",o:["1 mes","15 días","3 años","6 meses"],a:0,x:"Un mes (o quince días en vía administrativa previa, según el caso), art. 122 de la Ley 39/2015.",r:"Ley 39/2015, art. 122"},
/* ===== PERMANENTE ===== */
{c:"perm",b:"B1",t:"Constitución",d:"F",id:"n360",q:"Según el art. 30 de la Constitución, defender a España es…",o:["Un derecho y un deber de los españoles","Una opción voluntaria sin regulación","Solo un deber de los militares","Una obligación exclusivamente económica"],a:0,x:"«Los españoles tienen el derecho y el deber de defender a España» (art. 30.1).",r:"CE, art. 30.1"},
{c:"perm",b:"B1",t:"Constitución",d:"M",id:"n361",q:"Según el art. 8 CE, la misión de las Fuerzas Armadas es…",o:["Garantizar la soberanía e independencia de España, defender su integridad territorial y el ordenamiento constitucional","Proteger el comercio internacional","Sostener al Gobierno en funciones","Velar por los intereses económicos en el extranjero"],a:0,x:"Es la literalidad del art. 8.1 CE.",r:"CE, art. 8"},
{c:"perm",b:"B1",t:"Defensa Nacional",d:"M",id:"n362",q:"El mando de la Defensa corresponde al Presidente del Gobierno. La Suprema Jefatura de las Fuerzas Armadas corresponde…",o:["Al Rey, conforme a la Constitución (art. 62)","Al Ministro de Defensa","Al JEMAD","Al Presidente del Congreso"],a:0,x:"Clásica pregunta-trampa: mando de la Defensa = Presidente; Suprema Jefatura de las FAS = el Rey.",r:"CE, art. 62 · Ley 39/2015"},
{c:"perm",b:"B1",t:"MINISDEF",d:"M",id:"n363",q:"La Subsecretaría de Defensa actúa como…",o:["Órgano de asistencia permanente al Ministro y gestiona los recursos humanos y económicos comunes","Mando táctico de las divisiones","Órgano de la OTAN en España","Tribunal de recursos del personal"],a:0,x:"La Subsec gestiona personal común, presupuesto y asistencia permanente al Ministro.",r:"RD 1399/2018"},
{c:"perm",b:"B1",t:"FAS",d:"M",id:"n364",q:"El EMAD es…",o:["El órgano de planificación y apoyo conjuntos al servicio del JEMAD","El ejército de tierra en activo","Un centro de reclutamiento","El archivo militar central"],a:0,x:"Estado Mayor de la Defensa: planificación conjunta y apoyo al JEMAD.",r:"Ley 39/2015 · RD 521/2020"},
{c:"perm",b:"B2",t:"Tropa y marinería",d:"M",id:"n365",q:"La relación de servicios de carácter permanente implica…",o:["La continuidad en el servicio hasta la situación de retiro, como militar profesional","Un contrato renovable cada año","Un máximo de 5 años de servicio","La pérdida de derechos laborales"],a:0,x:"La permanencia consolida la condición profesional hasta el retiro.",r:"Ley 39/2007"},
{c:"perm",b:"B2",t:"Situaciones",d:"F",id:"n366",q:"El militar que presta servicio en su destino está en situación administrativa de…",o:["Servicio activo","Reserva","Retiro","Disponibilidad"],a:0,x:"Activo es la situación de quien ocupa su destino en servicio efectivo.",r:"Ley 39/2007"},
{c:"perm",b:"B2",t:"Concurso",d:"F",id:"n367",q:"La corrección del examen y la valoración de méritos corresponde a…",o:["El órgano de selección nombrado en la convocatoria","El mando de la unidad del aspirante","Un sorteo entre los presentados","La empresa de gastos del proceso"],a:0,x:"La convocatoria designa al órgano de selección competente.",r:"Orden DEF/1341/2017"},
{c:"perm",b:"B3",t:"Físicas",d:"M",id:"n368",q:"La aptitud psicofísica (pruebas físicas) en el proceso de permanente es…",o:["Eliminatoria: se califica como apto o no apto","Un porcentaje de la nota del examen","Opcional si hay plazas sobrantes","Solo para unidades de combate"],a:0,x:"Las pruebas físicas son apto/no apto: sin ellas no hay plaza.",r:"Bases de la convocatoria"},
{c:"perm",b:"B3",t:"Convocatoria",d:"F",id:"n369",q:"Las convocatorias de acceso a la condición de permanente se publican en el…",o:["Boletín Oficial de Defensa (BOD)","Boletín Oficial del Estado únicamente","Diario de sesión del Congreso","Boletín de la Unión Europea"],a:0,x:"Las convocatorias de TM se publican en el BOD.",r:"Orden DEF/1341/2017"},
{c:"perm",b:"B3",t:"ONU",d:"F",id:"n370",q:"La sede central de la ONU está en…",o:["Nueva York","Ginebra","Viena","París"],a:0,x:"Sede en Nueva York; Ginebra y Viena son sedes de oficinas.",r:"ONU"},
{c:"perm",b:"B3",t:"OTAN",d:"F",id:"n371",q:"La sede de la OTAN está en…",o:["Bruselas","Washington","París","Ámsterdam"],a:0,x:"El cuartel general de la OTAN está en Bruselas (Bélgica).",r:"OTAN"},
{c:"perm",b:"B3",t:"UE",d:"M",id:"n372",q:"La PCSD es…",o:["La Política Común de Seguridad y Defensa de la UE","Un pacto de defensa con Rusia","El presupuesto europeo de armamento","La policía fronteriza europea"],a:0,x:"La PCSD enmarca la gestión de crisis y cooperación defensiva de la UE.",r:"UE · Tratado de Lisboa"}
];
