/* MICABO · LOTE OFICIAL 4 — CAMPAÑA TEMA A TEMA · CABO, Bloque I, TEMA 2:
   «Del Militar» (RD 96/2009: arts. 14-23, principios básicos; arts. 32 y 38, normas de actuación).
   16 preguntas CURADAS desde el temario oficial del curso (nov-2025), estilo examen real. */
"use strict";
window.QUESTIONS15 = [
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"F",id:"rt017",q:"Según el art. 14, el militar cuyo propio honor y espíritu no le estimulen a obrar siempre bien…",o:["Vale muy poco para el servicio","Debe pasar a la reserva","Será sancionado disciplinariamente","Debe pedir cambio de destino"],a:0,x:"Art. 14, entrada literal: «el militar cuyo propio honor y espíritu no le estimulen a obrar siempre bien, VALE MUY POCO PARA EL SERVICIO». El espíritu militar se mide en el afán de superación diaria, no en el mínimo reglamentario.",r:"RD 96/2009 art. 14 · Temario oficial Cabo nov-2025, Bloque I T2"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"D",id:"rt018",q:"El art. 14 considera pruebas de «gran desidia e ineptitud para la carrera de las armas»…",o:["Llegar tarde aunque sea de minutos, excusarse con males imaginarios y contentarse con hacer lo preciso","Consultar al jefe antes de cada decisión","Pedir permisos dentro del reglamento","Elegir siempre el servicio más cómodo"],a:0,x:"Art. 14 catálogo exacto: llegar tarde a la obligación «aunque sea de minutos», excusarse con males imaginarios de las fatigas propias y «contentarse regularmente con hacer lo preciso de su deber, sin que su propia voluntad adelante cosa alguna». Tres vicios anti-liderazgo que el examen adora.",r:"RD 96/2009 art. 14 · Temario oficial Cabo nov-2025, Bloque I T2"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"F",id:"rt019",q:"«El llegar tarde a su obligación, aunque sea de minutos» es, para las RROO…",o:["Una prueba de desidia e ineptitud","Una falta leve que no importa","Algo que depende del jefe","Admisible si se avisa"],a:0,x:"Art. 14, literal: llegar tarde AUNQUE SEA DE MINUTOS ya es prueba de gran desidia e ineptitud. La puntualidad militar no admite grados: se es puntual o se falla. Pregunta directa de examen.",r:"RD 96/2009 art. 14 · Temario oficial Cabo nov-2025, Bloque I T2"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"M",id:"rt020",q:"El militar cumplirá sus deberes y obligaciones impulsado por…",o:["El sentimiento del honor inspirado en las RROO","El miedo a la sanción","La ambición de ascenso","La presión del mando"],a:0,x:"Art. 16: cumplirá con exactitud sus deberes «impulsado por el SENTIMIENTO DEL HONOR inspirado en estas Reales Ordenanzas». El motor interior del cumplimiento es el honor, no el temor — es la diferencia entre compromiso y sumisión.",r:"RD 96/2009 art. 16 · Temario oficial Cabo nov-2025, Bloque I T2"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"F",id:"rt021",q:"Las virtudes fundamentales a las que nunca ha de faltar el militar (art. 17) son…",o:["Disciplina, valor, prontitud en la obediencia y exactitud en el servicio","Paciencia, caridad, templanza y prudencia","Fuerza, resistencia, velocidad y puntería","Silencio, disciplina, uniformidad y ahorro"],a:0,x:"Art. 17, cuarteto exacto: DISCIPLINA, VALOR, PRONTITUD EN LA OBEDIENCIA y EXACTITUD EN EL SERVICIO, «virtudes a las que nunca ha de faltar». Las cuatro, en orden y sin inventar: la quinta que aparezca en un examen es trampa.",r:"RD 96/2009 art. 17 · Temario oficial Cabo nov-2025, Bloque I T2"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"M",id:"rt022",q:"¿Cuál de estas NO es una virtud fundamental del art. 17?",o:["La prudencia","La disciplina","El valor","La prontitud en la obediencia"],a:0,x:"Art. 17 solo cita cuatro: disciplina, valor, prontitud en la obediencia y exactitud en el servicio. La «prudencia» es virtud de filósofos, no del catálogo de las RROO. Ojo al «NO» del enunciado: trampa de examen de las que más confunden.",r:"RD 96/2009 art. 17 · Temario oficial Cabo nov-2025, Bloque I T2"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"D",id:"rt023",q:"La justicia imperará en las FAS de modo que…",o:["Nadie tenga nada que esperar del favor ni temer de la arbitrariedad","Todos reciban la misma valoración","Nadie sea sancionado jamás","Losascensos se repartan por cuotas"],a:0,x:"Art. 18, fórmula literal de examen: la justicia impere de tal modo que «NADIE TENGA NADA QUE ESPERAR DEL FAVOR NI TEMER DE LA ARBITRARIEDAD». Dos enemigos de la justicia militar: el favoritismo y la arbitrariedad.",r:"RD 96/2009 art. 18 · Temario oficial Cabo nov-2025, Bloque I T2"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"M",id:"rt024",q:"El militar subordinará la honrada ambición profesional a…",o:["La íntima satisfacción del deber cumplido","La opinión de sus compañeros","El informe de su evaluador","Su expediente personal"],a:0,x:"Art. 19: ejercerá la profesión con dedicación y espíritu de sacrificio, «subordinando la HONRADA AMBICIÓN PROFESIONAL a la ÍNTIMA SATISFACCIÓN DEL DEBER CUMPLIDO». Primero el deber cumplido, después la carrera — el orden lo marca la RROO.",r:"RD 96/2009 art. 19 · Temario oficial Cabo nov-2025, Bloque I T2"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"M",id:"rt025",q:"El militar debe tener amor al servicio y «constante deseo de ser empleado en…»",o:["Las ocasiones de mayor riesgo y fatiga","Los servicios más cómodos","El destino más cercano a casa","Los empleos de gabinete"],a:0,x:"Art. 19, final literal: «amor al servicio y CONSTANTE DESEO DE SER EMPLEADO EN LAS OCASIONES DE MAYOR RIESGO Y FATIGA». Se busca el puesto difícil, no el fácil — es el sello del militar profesional en las RROO.",r:"RD 96/2009 art. 19 · Temario oficial Cabo nov-2025, Bloque I T2"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"F",id:"rt026",q:"La disponibilidad del militar para el servicio es…",o:["Permanente","Semestral","Solo en tiempo de campaña","A demanda del alcalde"],a:0,x:"Art. 20: el militar está en DISPOSIBILIDAD PERMANENTE para el servicio, materializada según su destino y las circunstancias, y realizará cualquier tarea con la máxima DILIGENCIA Y PUNTUALIDAD, en operaciones y en el funcionamiento de las unidades.",r:"RD 96/2009 art. 20 · Temario oficial Cabo nov-2025, Bloque I T2"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"F",id:"rt027",q:"Los miembros de las FAS se sentirán herederos y depositarios de…",o:["La tradición militar española","Los archivos históricos de su cuartel","Los uniformes del siglo XIX","Las consignas extranjeras"],a:0,x:"Art. 21, literal: los militares «se sentirán HEREDEROS Y DEPOSITARIOS de la tradición militar española». La tradición no es folklore: es un encargo que se recibe y se transmite.",r:"RD 96/2009 art. 21 · Temario oficial Cabo nov-2025, Bloque I T2"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"M",id:"rt028",q:"El homenaje a los héroes que forjaron la tradición y a los que entregaron su vida por España es…",o:["Un deber de gratitud y un motivo de estímulo para continuar su obra","Una costumbre opcional","Solo del Día de las Fuerzas Armadas","Una actividad de gabinete"],a:0,x:"Art. 21, doble calificación de examen: el homenaje es UN DEBER DE GRATITUD y UN MOTIVO DE ESTÍMULO para la continuación de su obra. Gratitud mirando atrás, estímulo mirando adelante.",r:"RD 96/2009 art. 21 · Temario oficial Cabo nov-2025, Bloque I T2"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"D",id:"rt029",q:"El militar se esforzará en que su unidad mantenga los mayores niveles de…",o:["Preparación, eficacia, eficiencia y cohesión","Uniformidad, silencio, orden y limpieza","Presupuesto, plantilla, material y honores","Disciplina, guardias, formación y tiro"],a:0,x:"Art. 22, cuarteto exacto: «los mayores niveles de PREPARACIÓN, EFICACIA, EFICIENCIA Y COHESIÓN», con objeto de que la unidad MEREZCA SER DESIGNADA PARA LAS MÁS IMPORTANTES Y ARRIESGADAS MISIONES. El premio a la buena unidad: el trabajo difícil.",r:"RD 96/2009 art. 22 · Temario oficial Cabo nov-2025, Bloque I T2"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"M",id:"rt030",q:"El militar conservará y transmitirá de su unidad…",o:["El historial, las tradiciones y los símbolos","Su presupuesto anual","El arma del día","Los turnos de limpieza"],a:0,x:"Art. 23: conservará y transmitirá el HISTORIAL, TRADICIONES Y SÍMBOLOS de su unidad «para perpetuar su recuerdo, contribuir a fomentar el espíritu de unidad y reforzar las virtudes militares de sus componentes». El cabo es pieza clave en esa transmisión.",r:"RD 96/2009 art. 23 · Temario oficial Cabo nov-2025, Bloque I T2"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"F",id:"rt031",q:"En las relaciones con la población civil (art. 32), el militar será…",o:["Cortés y deferente, evitando toda molestia innecesaria","Distante y desconfiado","Invisible y sin trato","Receptivo solo si hay medios"],a:0,x:"Art. 32: fomentará la relación con la población civil, será CORTÉS Y DEFERENTE en su trato, en particular con la más directamente afectada por sus actividades, EVITANDO TODA MOLESTIA INNECESARIA. Pura letra de misiones y BTL/BCN.",r:"RD 96/2009 art. 32 · Temario oficial Cabo nov-2025, Bloque I T2"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"D",id:"rt032",q:"Si un militar tiene una queja sobre asuntos del servicio (art. 38), debe…",o:["Ponerla en conocimiento de sus superiores, de buen modo y por el conducto reglamentario","Publicarla en redes sociales","Presentarla directamente al Ministro","Silenciarla siempre por disciplina"],a:0,x:"Art. 38, doble condición: ponerla en conocimiento de sus SUPERIORES, haciéndolo DE BUEN MODO y POR EL CONDUCTO REGLAMENTARIO — todo «sin perjuicio de ejercitar los derechos o acciones que legalmente le correspondan». Canal primero, tribunales si hace falta.",r:"RD 96/2009 art. 38 · Temario oficial Cabo nov-2025, Bloque I T2"}
];
