/* MICABO · LOTE OFICIAL 3 — CAMPAÑA TEMA A TEMA · CABO, Bloque I, TEMA 1:
   «Disposiciones Generales» (Reales Ordenanzas RD 96/2009, arts. 1-13).
   16 preguntas CURADAS desde el temario oficial del curso (Rincón de Tropa, nov-2025),
   estilo examen real: enunciado corto, 4 opciones verosímiles, la letra del artículo. */
"use strict";
window.QUESTIONS14 = [
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"F",id:"rt001",q:"Las Reales Ordenanzas para las Fuerzas Armadas constituyen…",o:["El código de conducta de los militares","El reglamento de régimen interior","El manual doctrinal del ET","El compendio de tradiciones militares"],a:0,x:"Art. 1: las RROO «constituyen el código de conducta de los militares» y definen los principios éticos y las reglas de comportamiento conforme a la Constitución y al ordenamiento. No son un reglamento de interior (eso es la OM 50/2011 y su RD 1109/2015).",r:"RD 96/2009 art. 1 · Temario oficial Cabo nov-2025, Bloque I T1"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"M",id:"rt002",q:"Las RROO deben servir de guía para el exacto cumplimiento del deber, inspirado en…",o:["El amor a España, y en el honor, disciplina y valor","La obediencia, la puntualidad y el orden","El juramento y la jerarquía","La historia y las tradiciones"],a:0,x:"Art. 1, letra exacta: «fomentar y exigir el exacto cumplimiento del deber, inspirado en el amor a España, y en el honor, disciplina y valor». El trío honor-disciplina-valor es de las preguntas más repetidas del examen.",r:"RD 96/2009 art. 1 · Temario oficial Cabo nov-2025, Bloque I T1"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"M",id:"rt003",q:"¿A QUIÉN NO se aplican las Reales Ordenanzas?",o:["A los militares profesionales en situaciones administrativas con la condición militar suspendida","A los alumnos de la enseñanza militar de formación","A los reservistas incorporados a las FAS","A los aspirantes a reservista incorporados"],a:0,x:"Art. 2.1: se aplican a TODOS los militares profesionales SALVO que estén en situaciones administrativas con la condición militar suspendida. Sí se aplican a alumnos de formación, aspirantes a reservista y reservistas cuando están incorporados. Trampa clásica del examen.",r:"RD 96/2009 art. 2 · Temario oficial Cabo nov-2025, Bloque I T1"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"D",id:"rt004",q:"¿Cómo se aplican las RROO a la GUARDIA CIVIL?",o:["Se les aplican, excepto cuando contradigan su legislación específica","No se les aplican nunca","Se les aplican íntegramente igual que al ET","Solo en misiones internacionales"],a:0,x:"Art. 2.2: por su naturaleza y condición militar, las RROO se aplican a todos los miembros de la Guardia Civil, EXCEPTO cuando contradigan u opongan a lo previsto en su legislación específica. Matiz de examen seguro.",r:"RD 96/2009 art. 2.2 · Temario oficial Cabo nov-2025, Bloque I T1"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"F",id:"rt005",q:"El PRIMER y más fundamental deber del militar es…",o:["La disposición permanente para defender a España, incluso con la entrega de la vida","Obedecer las órdenes del jefe","Guardar el secreto profesional","Cuidar el material asignado"],a:0,x:"Art. 3, letra exacta: «la disposición permanente para defender a España, incluso con la entrega de la vida cuando fuera necesario, constituye el primer y más fundamental deber del militar». La jerarquía de deberes empieza aquí.",r:"RD 96/2009 art. 3 · Temario oficial Cabo nov-2025, Bloque I T1"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"M",id:"rt006",q:"Ese primer deber «ha de tener su diaria expresión» en…",o:["El más exacto cumplimiento de los preceptos de la Constitución, la LO 5/2005, la Ley 39/2007 y las RROO","La instrucción diaria en el patio de armas","El saludo reglamentario","La revista semanal de equipos"],a:0,x:"Art. 3: la expresión DIARIA del primer deber es el exacto cumplimiento de los preceptos contenidos en la Constitución, la LO 5/2005 de Defensa Nacional, la Ley 39/2007 de carrera militar y las propias RROO. Cuatro normas que hay que memorizar juntas.",r:"RD 96/2009 art. 3 · Temario oficial Cabo nov-2025, Bloque I T1"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"F",id:"rt007",q:"Como deber de carácter general, el militar guardará y hará guardar…",o:["La Constitución, como norma fundamental del Estado","El secreto de los despachos","El material de su unidad","Las tradiciones de su arma"],a:0,x:"Art. 4: el militar «guardará y hará guardar la Constitución como norma fundamental del Estado» y cumplirá las obligaciones de las misiones de las FAS, de su condición y de su sujeción a las leyes penales y disciplinarias militares.",r:"RD 96/2009 art. 4 · Temario oficial Cabo nov-2025, Bloque I T1"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"D",id:"rt008",q:"¿Cuál de estos NO es un principio de actuación del militar como servidor público (art. 5)?",o:["Rentabilidad económica","Imparcialidad","Austeridad","Ejemplaridad"],a:0,x:"Art. 5: objetividad, integridad, neutralidad, responsabilidad, imparcialidad, confidencialidad, dedicación al servicio, transparencia, ejemplaridad, austeridad, accesibilidad, eficacia, honradez y promoción del entorno cultural y medioambiental. La «rentabilidad económica» NO está en la lista — el servidor público no es una empresa.",r:"RD 96/2009 art. 5 · Temario oficial Cabo nov-2025, Bloque I T1"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"F",id:"rt009",q:"Todo militar tiene el deber de prestar ante la Bandera…",o:["Juramento o promesa de defender a España","Saludo en forma","Guardia de honor","Juramento de fidelidad al Rey"],a:0,x:"Art. 6: «prestar ante la Bandera juramento o promesa de defender a España». El mismo artículo manda mostrar el máximo respeto a la Bandera, al Escudo de España y al Himno Nacional como símbolos de la Patria transmitidos por la historia.",r:"RD 96/2009 art. 6 · Temario oficial Cabo nov-2025, Bloque I T1"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"F",id:"rt010",q:"Las características del comportamiento del militar (art. 7) son…",o:["Disciplina, jerarquía y unidad","Valor, prudencia y temple","Lealtad, honor y justicia","Mando, obediencia y abnegación"],a:0,x:"Art. 7: el militar ajusta su comportamiento a las características de las FAS de DISCIPLINA, JERARQUÍA y UNIDAD, «indispensables para conseguir la máxima eficacia en su acción». Tres palabras que estructuran los tres artículos siguientes (8, 9 y 10).",r:"RD 96/2009 art. 7 · Temario oficial Cabo nov-2025, Bloque I T1"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"D",id:"rt011",q:"Según el art. 8, la MANIFESTACIÓN INDIVIDUAL de la disciplina es…",o:["El cumplimiento de las órdenes recibidas","El acatamiento a la Constitución","La firma del partes diarios","La revista de alineación"],a:0,x:"Art. 8, distinción de examen: la disciplina «tiene su EXPRESIÓN COLECTIVA en el acatamiento a la Constitución y su MANIFESTACIÓN INDIVIDUAL en el cumplimiento de las órdenes recibidas». Colectiva = Constitución; individual = órdenes. No invertirlas.",r:"RD 96/2009 art. 8 · Temario oficial Cabo nov-2025, Bloque I T1"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"M",id:"rt012",q:"La disciplina, como norma de actuación de las FAS…",o:["Obliga a mandar con responsabilidad y a obedecer lo mandado","Solo obliga a los subordinados","Es potestativa en tiempo de paz","Sustituye a la ley en campaña"],a:0,x:"Art. 8: la disciplina es «factor de cohesión que obliga a MANDAR CON RESPONSABILIDAD y a OBEDECER LO MANDADO», practicada y exigida como norma de actuación. Ojo: obliga a los dos lados — manda y obedece.",r:"RD 96/2009 art. 8 · Temario oficial Cabo nov-2025, Bloque I T1"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"M",id:"rt013",q:"El orden jerárquico militar define la situación relativa entre los miembros de las FAS en cuanto concierne a…",o:["Mando, subordinación y responsabilidad","Sueldo, empleo y destino","Antigüedad, mérito y ascenso","Instrucción, disciplina y moral"],a:0,x:"Art. 9: el orden jerárquico «define la situación relativa entre sus miembros en cuanto concierne a MANDO, SUBORDINACIÓN y RESPONSABILIDAD». Los de cada nivel están investidos de autoridad en razón de su cargo, destino o servicio.",r:"RD 96/2009 art. 9 · Temario oficial Cabo nov-2025, Bloque I T1"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"D",id:"rt014",q:"La AUTORIDAD, según el art. 9, implica el derecho y el deber de…",o:["Tomar decisiones, dar órdenes y hacerlas cumplir, fortalecer la moral, motivar, mantener la disciplina y administrar los medios","Solo dar órdenes y exigir su cumplimiento","Elegir a sus subordinados","Delegar siempre la responsabilidad"],a:0,x:"Art. 9, catálogo completo: la autoridad implica el derecho y el deber de tomar decisiones, dar órdenes y hacerlas cumplir, FORTALECER LA MORAL, MOTIVAR a los subordinados, mantener la disciplina y ADMINISTRAR LOS MEDIOS asignados. Mando = liderazgo + gestión.",r:"RD 96/2009 art. 9 · Temario oficial Cabo nov-2025, Bloque I T1"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"F",id:"rt015",q:"El militar se comportará con LEALTAD y COMPAÑERISMO como expresión de…",o:["La voluntad de asumir solidariamente con los demás el cumplimiento de las misiones","La amistad personal con la unidad","La costumbre del cuartel","El respeto a los jefes extranjeros"],a:0,x:"Art. 10: lealtad y compañerismo expresan la voluntad de asumir SOLIDARIAMENTE con los demás miembros de las FAS el cumplimiento de sus misiones, contribuyendo así a la UNIDAD de las mismas. Es el artículo del «no se abandona a nadie».",r:"RD 96/2009 art. 10 · Temario oficial Cabo nov-2025, Bloque I T1"},
{c:"cabo",b:"C1",t:"Reales Ordenanzas",d:"M",id:"rt016",q:"La dignidad y los derechos inviolables de la persona son, para el militar…",o:["Valores que tiene la obligación de respetar Y el derecho a exigir","Una recomendación orientativa","Solo aplicables en territorio nacional","Asuntos de la jurisdicción civil"],a:0,x:"Art. 11, simetría de examen: la dignidad y los derechos inviolables son valores que el militar tiene OBLIGACIÓN DE RESPETAR y DERECHO A EXIGIR. En ningún caso se estará sometido ni se someterá a otros a menoscabo de la dignidad personal.",r:"RD 96/2009 art. 11 · Temario oficial Cabo nov-2025, Bloque I T1"}
];
