/* MICABO · LOTE OFICIAL 2 — INGLÉS de CABO 1º (fase a distancia)
   16 preguntas CURADAS desde el ME7-029 (temario oficial de inglés, Rincón de Tropa):
   Unit 1 (units & command schelons) y Military Terms (in the barracks). Traducciones
   literales del glosario oficial — nada inventado. */
"use strict";
window.QUESTIONS13 = [
{c:"cabo1",b:"B2",t:"Inglés",d:"F",id:"in001",q:"En la doctrina en inglés, «fire team» equivale a nuestra…",o:["escuadra","sección","compañía","batallón"],a:0,x:"Glosario oficial ME7-029 (Unit 1, Units and Command Schelons): fire team = ESCUADRA, la unidad más pequeña. Encima están section/platoon (sección), company (compañía) y battalion (batallón).",r:"ME7-029 Inglés (oficial CB1) · Unit 1"},
{c:"cabo1",b:"B2",t:"Inglés",d:"F",id:"in002",q:"«Platoon» se traduce por…",o:["sección","escuadra","regimiento","agrupación"],a:0,x:"ME7-029, Unit 1: platoon = SECCIÓN. En el diálogo oficial del temario: «He's commanding the 2nd Rifle Platoon — va a mandar la segunda Sección de Fusiles». No confundir con squad/fire team (escuadra).",r:"ME7-029 Inglés (oficial CB1) · Unit 1"},
{c:"cabo1",b:"B2",t:"Inglés",d:"D",id:"in003",q:"El «battalion group» (o battalion task group) es nuestro…",o:["grupo táctico","subgrupo táctico","cuartel general","regimiento"],a:0,x:"Glosario oficial Unit 1: battalion task group / battalion group = GRUPO TÁCTICO. Su hermano pequeño, el company task force, es el SUBGRUPO TÁCTICO (nivel compañía). Pareja de examen.",r:"ME7-029 Inglés (oficial CB1) · Unit 1"},
{c:"cabo1",b:"B2",t:"Inglés",d:"M",id:"in004",q:"Una «task force» es una…",o:["agrupación táctica","escuadra de fuego","tarea de mantenimiento","brigada de helicópteros"],a:0,x:"ME7-029, Unit 1: task force = AGRUPACIÓN TÁCTICA. Escala completa del glosario: task force (agrupación táctica) > battalion group (grupo táctico) > company task force (subgrupo táctico).",r:"ME7-029 Inglés (oficial CB1) · Unit 1"},
{c:"cabo1",b:"B2",t:"Inglés",d:"M",id:"in005",q:"«Full corporal» es el empleo de…",o:["cabo primero","cabo","sargento","cabo mayor"],a:0,x:"Glosario oficial del ME7-029: full corporal = CABO PRIMERO; corporal a secas = cabo; sergeant = sargento. Tres empleos que te importan de primera mano — ¡este es tu ascenso dicho en inglés!",r:"ME7-029 Inglés (oficial CB1) · Glosario de empleos"},
{c:"cabo1",b:"B2",t:"Inglés",d:"F",id:"in006",q:"«Sergeant» equivale a…",o:["sargento","suboficial mayor","brigada","teniente"],a:0,x:"ME7-029: sergeant = SARGENTO. La escalera de mando en inglés del temario sigue: private (soldado) → corporal (cabo) → full corporal (cabo primero) → sergeant (sargento).",r:"ME7-029 Inglés (oficial CB1) · Glosario de empleos"},
{c:"cabo1",b:"B2",t:"Inglés",d:"F",id:"in007",q:"«Barracks» es…",o:["cuartel","mochila","mesón","patio de armas"],a:0,x:"Military Terms del ME7-029 (In the barracks, en el cuartel): barracks = CUARTEL. Del mismo glosario: main gate = puerta principal, courtyard = patio de armas, mess = mesón o cantina.",r:"ME7-029 Inglés (oficial CB1) · Military Terms"},
{c:"cabo1",b:"B2",t:"Inglés",d:"M",id:"in008",q:"El «courtyard» de un acuartelamiento es…",o:["el patio de armas","el armero","el zustancia","el polígono"],a:0,x:"Glosario oficial: courtyard = PATIO DE ARMAS. La formación se celebra ahí: military parade = formación, march past = desfile, inspection parade = revista, drill parade = ejercicios de orden cerrado.",r:"ME7-029 Inglés (oficial CB1) · Military Terms"},
{c:"cabo1",b:"B2",t:"Inglés",d:"M",id:"in009",q:"Un «armour squadron» es un…",o:["escuadrón acorazado","regimiento de artillería","batallón de zapadores","grupo logístico"],a:0,x:"ME7-029, Military Terms: armour squadron = ESCUADRÓN ACORAZADO (unidad de caballería/blindados). Compañero de glosario: weapon support company = compañía de armas de apoyo; headquarters battery = batería de plana mayor.",r:"ME7-029 Inglés (oficial CB1) · Military Terms"},
{c:"cabo1",b:"B2",t:"Inglés",d:"M",id:"in010",q:"«Drill parade» significa…",o:["ejercicios de orden cerrado","revista de armas","desfile por la ciudad","instrucción de tiro"],a:0,x:"Glosario oficial: drill parade = EJERCICIOS DE ORDEN CERRADO — voces y movimientos de la tropa. Familia completa: military parade (formación), inspection parade (revista), march past (desfile).",r:"ME7-029 Inglés (oficial CB1) · Military Terms"},
{c:"cabo1",b:"B2",t:"Inglés",d:"F",id:"in011",q:"La voz de mando «Fall in!» ordena…",o:["¡A formar!","¡Descanso!","¡A discreción!","¡De pie, guerra!"],a:0,x:"ME7-029: fall in = ¡A FORMAR! Es la voz para concentrar la tropa en formación. Otras voces del temario: stand at ease (a descansar), dismissed (a discreción, se disuelve la formación).",r:"ME7-029 Inglés (oficial CB1) · Voces de mando"},
{c:"cabo1",b:"B2",t:"Inglés",d:"M",id:"in012",q:"«On leave» es estar…",o:["de permiso","de servicio","de guardia","de corrveo"],a:0,x:"Military Terms: on leave = DE PERMISO; su contrario exacto es on duty = DE SERVICIO. Pareja de antónimos que cae en los exámenes de inglés de la fase a distancia.",r:"ME7-029 Inglés (oficial CB1) · Military Terms"},
{c:"cabo1",b:"B2",t:"Inglés",d:"M",id:"in013",q:"Un «military parade» es una…",o:["formación","instrucción","licencia","concentración"],a:0,x:"Glosario oficial: military parade = FORMACIÓN (concentración de la unidad con instrucciones). Del mismo bloque: march past = desfile (la unidad desfila ante la plana mayor), inspection parade = revista.",r:"ME7-029 Inglés (oficial CB1) · Military Terms"},
{c:"cabo1",b:"B2",t:"Inglés",d:"F",id:"in014",q:"La «chain of command» es la…",o:["cadena de mando","cadena de custodia","cuerda de anclaje","línea de suministro"],a:0,x:"Unit 1 del ME7-029: chain of command = CADENA DE MANDO — la línea de mando desde el private hasta el commander (jefe). Aparece en el primer diálogo oficial del temario: «Who's the commander? — Captain Mayoral».",r:"ME7-029 Inglés (oficial CB1) · Unit 1"},
{c:"cabo1",b:"B2",t:"Inglés",d:"F",id:"in015",q:"«Rucksack» es una…",o:["mochila","cantimplora","haima","bolsa de dormir"],a:0,x:"Military Terms del ME7-029: rucksack = MOCHILA. Vecinos de glosario: lorry = camión, sleeping bag = saco de dormir, boot camp = campamento de reclutas.",r:"ME7-029 Inglés (oficial CB1) · Military Terms"},
{c:"cabo1",b:"B2",t:"Inglés",d:"M",id:"in016",q:"El «march past» es el momento en que la unidad…",o:["desfila pasando ante la plana de revista","rompe la formación","entra en cuartel","recibe el parte"],a:0,x:"Glosario oficial: march past = DESFILE (la unidad marcha pasando ante el mando que preside). Se distingue de military parade (formación) e inspection parade (revista): tres fases del acto militar en inglés.",r:"ME7-029 Inglés (oficial CB1) · Military Terms"}
];
