/* A LA ORDEN — LOTE 1 CABO 1º · 56 preguntas CURADAS a mano (21-sep-2026)
   Temas reforzados: Régimen disciplinario (LO 8/2014) · Documentación militar ·
   Mando y liderazgo (K2/MoM) · Tiro · Topografía · Organización del ET.
   Cada explicación (x) enseña el PORQUÉ — nada de ecos de la respuesta. */
window.QUESTIONS8 = [
/* ===== RÉGIMEN DISCIPLINARIO · LO 8/2014 (de 1 → 13) ===== */
{c:"cabo1",b:"B1",t:"Régimen disciplinario",d:"F",id:"c1o001",q:"¿Qué ley orgánica desarrolla el régimen disciplinario de las Fuerzas Armadas?",o:["LO 8/2014, de 26 de septiembre","LO 9/2011, de 5 de agosto","LO 5/2005, de 17 de noviembre","LO 14/2015, de 13 de octubre"],a:0,x:"La LO 8/2014 (LORDMFAS) es la norma básica: define faltas (leves, graves y muy graves), sanciones y procedimiento. Las otras LO son: 9/2011 derechos y deberes, 5/2005 Defensa Nacional y 14/2015 Código Penal Militar.",r:"LO 8/2014"},
{c:"cabo1",b:"B1",t:"Régimen disciplinario",d:"M",id:"c1o002",q:"¿Cuál es el plazo de prescripción de las faltas MUY GRAVES?",o:["6 meses","1 año","2 años","3 años"],a:3,x:"La prescripción crece con la gravedad: leves 6 meses, graves 2 años y muy graves 3 años. Pasado el plazo sin que el culpable haya sido sancionado, la falta prescribe y no puede castigarse. La sanción prescribe en el mismo plazo que la falta.",r:"LO 8/2014"},
{c:"cabo1",b:"B1",t:"Régimen disciplinario",d:"M",id:"c1o003",q:"¿Cuál es el plazo de prescripción de las faltas LEVES?",o:["6 meses","1 año","2 años","3 años"],a:0,x:"Las leves prescriben a los 6 meses (las graves a 2 años y las muy graves a 3). La regla: a mayor gravedad, más tiempo para instruir y sancionar.",r:"LO 8/2014"},
{c:"cabo1",b:"B1",t:"Régimen disciplinario",d:"M",id:"c1o004",q:"¿Qué sanciones puede imponerse a un militar de tropa por faltas LEVES?",o:["Suspensión de funciones","Apercibimiento y arresto de fin de semana (hasta 4)","Pérdida de destino","Pérdida de empleo"],a:1,x:"Para tropa y marinería las sanciones posibles son apercibimiento y arresto de fin de semana (máximo 4). La pérdida de empleo corresponde a conductas muy graves sancionadas con ella; la suspensión y pérdida de destino son sanciones de oficiales en su mayor parte.",r:"LO 8/2014"},
{c:"cabo1",b:"B1",t:"Régimen disciplinario",d:"D",id:"c1o005",q:"Un cabo 1º ve que su subordinado comete una falta LEVE. ¿Qué le corresponde hacer?",o:["Nada: solo el coronel sanciona","Ejercer la potestad disciplinaria dentro de su competencia, imponiendo la sanción que la ley le permite","Denunciarlo ante el Juzgado Togado siempre","Proponer su baja"],a:1,x:"La potestad disciplinaria corresponde al mando en la medida de su competencia: cada nivel sanciona lo que la ley le asigna (el cabo los apercibimientos por leves, por ejemplo). Al Juzgado Togado solo se acude cuando el hecho puede ser DELITO, no por una falta leve.",r:"LO 8/2014"},
{c:"cabo1",b:"B1",t:"Régimen disciplinario",d:"M",id:"c1o006",q:"¿Qué principio impide sancionar dos veces el mismo hecho?",o:["Non bis in idem","Igualdad ante la ley","Jerarquía militar","Economía de medios"],a:0,x:"«Non bis in idem»: nadie puede ser sancionado dos veces por los mismos hechos. Si el hecho puede ser además delito, el militar puede ser sancionado disciplinariamente Y juzgado penalmente, pero no dos sanciones disciplinarias por lo mismo.",r:"LO 8/2014"},
{c:"cabo1",b:"B1",t:"Régimen disciplinario",d:"M",id:"c1o007",q:"¿Qué derechos tiene el sancionado en el procedimiento disciplinario?",o:["Ninguno: el mando sanciona sin más","Audiencia previa, conocer los hechos imputados, proponer pruebas y recurrir","Solo recurrir si es oficial","Solo presentar escrito ante el Rey"],a:1,x:"La LORDMFAS garantiza: audiencia previa (esuchar tu versión antes de sancionar), conocer los hechos, proponer pruebas y RECURRIR (alzada ante el superior). Son garantías propias de un procedimiento sancionador en un Estado de derecho.",r:"LO 8/2014"},
{c:"cabo1",b:"B1",t:"Régimen disciplinario",d:"M",id:"c1o008",q:"¿Qué ocurre con las anotaciones de sanciones en el expediente pasados los plazos sin nueva falta?",o:["Se borran inmediatamente","Se cancelan (pierden efecto a efectos de reincidencia y valoración)","Se duplican","Pasan al BOE"],a:1,x:"Las anotaciones se CANCELAN transcurridos los plazos (mismos que la prescripción) sin nueva anotación: dejan de contar como antecedente ni agravar futuras sanciones. Por eso importa que una sanción antigua no la persiga para siempre.",r:"LO 8/2014"},
{c:"cabo1",b:"B1",t:"Régimen disciplinario",d:"M",id:"c1o009",q:"El arresto de fin de semana se cumple:",o:["En el acuartelamiento, generalmente los sábados y domingos","En prisión","En el domicilio, solo festivos","Trabajando en la semana"],a:0,x:"El arresto de fin de semana se cumple en el acuartelamiento (o lugar que determine el mando), habitualmente sábado y domingo, con tareas y régimen reforzado. No es prisión: es una sanción disciplinaria militar propia de faltas graves y leves según el caso.",r:"LO 8/2014"},
{c:"cabo1",b:"B1",t:"Régimen disciplinario",d:"D",id:"c1o010",q:"¿Cuándo agravan la responsabilidad disciplinaria?",o:["La negligencia voluntaria y la reiteración","El arrepentimiento","Presentar quejas","La antigüedad"],a:0,x:"Agravan la negligencia voluntaria (hacerlo descuidadamente a sabiendas) y la reiteración (repetir faltas). El arrepentimiento y colaborar al contrario pueden ATENUAR; presentar quejas e iniciativas es un DERECHO que jamás puede sancionarse (no represalias).",r:"LO 8/2014"},
{c:"cabo1",b:"B1",t:"Régimen disciplinario",d:"M",id:"c1o011",q:"Si el hecho imputado puede constituir DELITO, ¿qué debe hacer el mando?",o:["Sancionarlo él mismo y punto","Derivarlo al órgano competente (jurisdicción militar) y suspender el plazo mientras tanto","Olvidarlo si es pequeño","Multarlo"],a:1,x:"Cuando el hecho puede ser delito, el procedimiento disciplinario queda a la espera de la jurisdicción militar (CPM): se deriva lo actuado. Además rige non bis in idem: no se sancionará disciplinariamente lo que ya fue objeto de resolución penal firme por los mismos hechos.",r:"LO 8/2014"},
{c:"cabo1",b:"B1",t:"Régimen disciplinario",d:"M",id:"c1o012",q:"¿Qué es la LORDMFAS?",o:["La Ley Orgánica de Régimen Disciplinario de las Fuerzas Armadas","La Ley de Retribuciones del Militar","El Reglamento de Armas","La Ley de Reserva"],a:0,x:"LORDMFAS = LO 8/2014, de Régimen Disciplinario de las Fuerzas Armadas. La sigla sale a cada rato en exámenes: saber que es la norma disciplinaria básica (sustituyó a la LO 85/1998) y que nació para adaptar la disciplina a la nueva condición laboral del militar.",r:"LO 8/2014"},

/* ===== DOCUMENTACIÓN MILITAR (de 3 → 13) ===== */
{c:"cabo1",b:"B1",t:"Documentación",d:"F",id:"c1o013",q:"¿Cuál es el documento de identidad del militar profesional?",o:["El DNI y, como documento de identificación militar, el TIP","La libreta militar","El carné de conducir","El pasaporte"],a:0,x:"El militar conserva su DNI y además dispone del TIP (Tarjeta de Identidad Personal) militar, que lo identifica ante las instituciones militares y acredita su condición. En los exámenes aparece siempre como «DNI o TIP en vigor».",r:"Documentación militar"},
{c:"cabo1",b:"B1",t:"Documentación",d:"M",id:"c1o014",q:"¿Qué es la hoja de servicios?",o:["El parte diario de la unidad","El documento oficial que recoge los destinos, empleos, recompensas y situaciones del militar a lo largo de su carrera","La orden de comisión de servicio","El inventario del equipo"],a:1,x:"La hoja de servicios es la «biografía administrativa» del militar: destinos, empleos, situaciones administrativas, recompensas, cursos y sanciones anotadas. Es clave en concursos (méritos) y debe estar actualizada; errores en ella afectan a concursos de destino y promoción.",r:"Ley 39/2007 · documentación militar"},
{c:"cabo1",b:"B1",t:"Documentación",d:"M",id:"c1o015",q:"El parte diario de una unidad sirve para:",o:["Comunicar al mando las novedades del día (personal, servicios, instrucción, material)","Pedir vacaciones","Pagar nóminas","Dar permiso de salida"],a:0,x:"El parte diario es la documentación de régimen interior que refleja las novedades de la unidad cada día: efectivos, servicios que se cubren, instrucción prevista, material. El cabo 1º, como mando, debe saber redactarlo correctamente: es el «pulso» diario de la unidad.",r:"Régimen interior"},
{c:"cabo1",b:"B1",t:"Documentación",d:"M",id:"c1o016",q:"¿Qué es una orden general?",o:["Una orden para toda la unidad sobre asuntos generales que se publica (cartel o medio oficial)","Una orden verbal en la instrucción","La orden de detención","Un permiso de armas"],a:0,x:"Las órdenes generales son instrucciones publicadas por escrito dirigidas a toda la unidad sobre asuntos generales (horarios, servicios, normas). Se distinguen de las órdenes particulares (dirigidas a un militar concreto). El que firma responde de su contenido.",r:"Régimen interior"},
{c:"cabo1",b:"B1",t:"Documentación",d:"M",id:"c1o017",q:"La correspondencia y documentación militar se clasifica por su grado de seguridad. ¿Qué significa la clasificación «secreto»?",o:["Que solo la pueden conocer las personas expresamente autorizadas por el mando","Que se puede colgar en el tablón","Que vale para el correo ordinario","Que caduca en un mes"],a:0,x:"La documentación clasificada (secreto, reservado, difusión limitada) se administra por la normativa de secretos oficiales: acceso solo para quienes tengan autorización y necesidad de conocerla, con registro, custodia y destrucción controladas. Un error aquí es responsabilidad del mando.",r:"Ley 9/1968 · secretos oficiales"},
{c:"cabo1",b:"B1",t:"Documentación",d:"M",id:"c1o018",q:"¿Quién firma el parte diario de una compañía normalmente?",o:["El cabo de semana, por delegación del mando de la unidad","El soldado más antiguo","Cualquiera","El alférez ayudante siempre"],a:0,x:"El parte diario lo redacta y firma el mando o quien delega (sargento o cabo de semana según unidad) y lo visada el jefe de la unidad. El cabo 1º candidato a sargento debe dominarlo: es documentación de mando diario.",r:"Régimen interior"},
{c:"cabo1",b:"B1",t:"Documentación",d:"D",id:"c1o019",q:"¿Qué diferencia hay entre «orden de servicio» y «comisión de servicio»?",o:["Ninguna, es lo mismo","La orden de servicio asigna funciones habituales; la comisión es un destino temporal fuera de la unidad para una tarea concreta","La comisión solo la firma el Rey","La orden de servicio es de pago"],a:1,x:"La orden de servicio encuadra las funciones ordinarias (servicios de guardia, detall). La comisión de servicio (CS) es un encargo TEMPORAL fuera de lo habitual, con derecho a dietas/transporte si procede. En documentación y nómina se tramitan distinto.",r:"Documentación militar"},
{c:"cabo1",b:"B1",t:"Documentación",d:"M",id:"c1o020",q:"La libreta o ficha de servicios del soldado/cabo sirve para:",o:["Anotar los servicios, faltas y méritos del militar en la unidad","Comprar en el economato","Solicitar destinos en el extranjero","Registrar sus datos bancarios"],a:0,x:"Es la documentación personal de régimen interior donde el mando anota servicios realizados, faltas leves (apercibimientos) y hechos relevantes de conducta. Debe tratarse con justicia: lo que se anota afecta a valoraciones posteriores.",r:"Régimen interior"},
{c:"cabo1",b:"B1",t:"Documentación",d:"D",id:"c1o021",q:"En documentación militar, ¿qué es un «extracto de orden»?",o:["La copia certificada de una orden que afecta a un militar concreto (destino, recompensa, sanción)","Un resumen de prensa","Un tipo de licencia","La lista de la ración"],a:0,x:"El extracto de orden es la copia oficial (certificada) de la parte de una orden general que afecta a un militar: destinos, ascensos, recompensas, situaciones. Es la documentación que acredita oficialmente ese hecho ante terceros (banco, INSS, concursos).",r:"Documentación militar"},
{c:"cabo1",b:"B1",t:"Documentación",d:"M",id:"c1o022",q:"¿Cómo se debe custodiar el TIP cuando no se lleva encima?",o:["En lugar seguro; su pérdida se comunica de inmediato al mando para anulación y renovación","Se regala a la familia","Se deja en la guantera del coche abierta","Se vende"],a:0,x:"El TIP es documentación de identidad militar: se custodia con cuidado y si se pierde o roba se comunica YA (como el DNI) para anularlo y tramitar duplicado. Usar documentación ajena o falseada es falta grave e incluso delito.",r:"Documentación militar"},

/* ===== MANDO Y LIDERAZGO (de 6 → 18) ===== */
{c:"cabo1",b:"B1",t:"Mando y liderazgo",d:"M",id:"c1o023",q:"En el modelo K2 del Ejército de Tierra, liderar es:",o:["Imponer la propia voluntad","Influir en las personas para conseguir la misión, mejorándolas y fortaleciendo la organización","Castigar los errores","Evitar tomar decisiones"],a:1,x:"El K2 define liderazgo como influir intencionadamente en las personas para lograr la misión Y mejorar la organización: no basta con que obedezcan, hay que hacerlos mejores. El cabo 1º es el primer eslabón de ese liderazgo (nivel directo).",r:"Doctrina de liderazgo K2 · MADOC"},
{c:"cabo1",b:"B1",t:"Mando y liderazgo",d:"M",id:"c1o024",q:"¿Cuáles son los niveles de liderazgo del modelo K2?",o:["Directo, organizacional y estratégico","Bajo, medio y alto","Militar y civil","Primero, segundo y tercero"],a:0,x:"Directo (el del cabo sobre su escuadra, cara a cara), organizacional (mandos que lideran a través de subordinados y sistemas) y estratégico (institucional). El cabo 1º vive el directo y se prepara para el organizacional como sargento.",r:"Doctrina de liderazgo K2 · MADOC"},
{c:"cabo1",b:"B1",t:"Mando y liderazgo",d:"M",id:"c1o025",q:"En el K2, los ATRIBUTOS del líder son:",o:["Carácter, intelecto y presencia","Altura, edad y antigüedad","Título, destino y sueldo","Fuerza, velocidad y puntería"],a:0,x:"Atributos = lo que el líder ES: carácter (valores), intelecto (capacidad de análisis y decisión) y presencia (ejemplo, porte, determinación). Las COMPETENCIAS son lo que HACE: liderar, desarrollar la organización y lograr resultados.",r:"Doctrina de liderazgo K2 · MADOC"},
{c:"cabo1",b:"B1",t:"Mando y liderazgo",d:"M",id:"c1o026",q:"¿Qué es el Mando Orientado a la Misión (MoM)?",o:["El superior transmite su intención y confía la ejecución al subordinado, con libertad para el «cómo»","El superior dirige cada paso del subordinado","Que cada uno haga lo que quiera","Mandar solo por escrito"],a:0,x:"MoM: el superior explica el PARA QUÉ (intención) y deja el CÓMO a quien ejecuta, que conoce el terreno mejor. Confianza mutua + iniciativa. Es la doctrina oficial del ET porque en combate la orden detallada queda obsoleta en minutos; la INTENCIÓN sobrevive.",r:"MoM · MADOC"},
{c:"cabo1",b:"B1",t:"Mando y liderazgo",d:"D",id:"c1o027",q:"La estructura clásica de la orden de operaciones tiene 5 párrafos:",o:["Situación, misión, ejecución, servicio/logística y mando-transmisiones","Saludo, introduce, desarrolla, concluye y firma","Primero, segundo, tercero, cuarto y quinto","Objetivo, fuego, apoyo, retaguardia y fin"],a:0,x:"SDOCM: Situación, misión, ejecución, servicio (logística) y mando y transmisiones. El cabo 1º debe saber estructurar una orden de misión de su escuadra con ese esqueleto: brevedad + claridad + intención, estilo MoM.",r:"MoM · doctrina operativa"},
{c:"cabo1",b:"B1",t:"Mando y liderazgo",d:"M",id:"c1o028",q:"El cabo 1º, respecto al cabo, es además:",o:["Un mando intermedio: guía e instruye a los cabos y refuerza la cadena de mando","Un mero administrativo","Un oficial","El porteador del material"],a:0,x:"El cabo 1º es el mando intermedio entre la tropa y el sargento: además de mandar su elemento, asesora e instruye a los cabos, transmite la doctrina y sostiene la disciplina cuando el cabo duda. Es el puente natural hacia el empleo de sargento (acceso por promoción interna).",r:"Ley 39/2007 · funciones del empleo"},
{c:"cabo1",b:"B1",t:"Mando y liderazgo",d:"M",id:"c1o029",q:"Para mantener la MORAL de la unidad, según la doctrina:",o:["El mando da ejemplo, cuida a sus subordinados y exige con justicia","Solo sanciones","Ignorar los problemas","Delegar en nadie"],a:0,x:"La moral se construye con ejemplo personal (lo primero que mira la tropa), cuidado real del subordinado (descanso, equipo, justicia en los servicios) y exigencia JUSTA: ni blandura ni abuso. Es exactamente lo que las RROO piden al que ejerce mando.",r:"RROO · doctrina K2"},
{c:"cabo1",b:"B1",t:"Mando y liderazgo",d:"M",id:"c1o030",q:"En el MoM, ¿qué es la «intención del mando»?",o:["El PARA QUÉ de la misión: el resultado que el superior quiere conseguir","La lista de teléfonos","El horario de comidas","El parte de material"],a:0,x:"La intención (el «para qué») es lo que guía al subordinado cuando la situación cambia y no hay tiempo de pedir nuevas órdenes: si conoce la intención, decide solo en la dirección correcta. Por eso el MoM la exige SIEMPRE en la orden, clara y breve.",r:"MoM · MADOC"},
{c:"cabo1",b:"B1",t:"Mando y liderazgo",d:"D",id:"c1o031",q:"Un subordinado comete un error ante la tropa. Según la doctrina de liderazgo, lo primero es:",o:["Corregirlo con respeto y en privado si es posible, convertirlo en aprendizaje","Burlarse delante de todos","Ignorarlo para no incomodar","Sancionarlo siempre aunque sea irrelevante"],a:0,x:"El líder desarrolla a su gente: la corrección respetuosa (en privado si es posible) forma; la humillación destruye la confianza y la moral. El error necesario aprendido vale más que la sanción sin sentido. La sanción queda para la indisciplina real, vía LORDMFAS.",r:"Doctrina K2 · RROO"},
{c:"cabo1",b:"B1",t:"Mando y liderazgo",d:"M",id:"c1o032",q:"«Que cada subordinado sepa qué se espera de él» responde al principio de:",o:["Claridad en la orden y en la misión","Disciplina de fila","Igualdad absoluta","Silencio administrativo"],a:0,x:"Una orden clara (quién, qué, cuándo, dónde, para qué) es la base de la ejecución y de la iniciativa útil. La confusión del mando se paga con caos en la ejecución: el MoM exige brevedad pero SIN ambigüedad.",r:"MoM · MADOC"},

/* ===== TIRO (de 2 → 12) ===== */
{c:"cabo1",b:"B1",t:"Tiro",d:"F",id:"c1o033",q:"Primera norma de seguridad con armas:",o:["Toda arma se considera CARGADA hasta comprobar lo contrario","Las armas nuevas no necesitan revisión","Con el seguro puesto se puede apuntar a cualquiera","El cargador puesto significa descargada"],a:0,x:"Las cuatro reglas de oro: 1) toda arma está cargada hasta que TÚ la compruebas; 2) nunca dirigir el arma a lo que no se quiera destruir; 3) el dedo fuera del gatillo hasta apuntar legítimamente; 4) al cargar/descargar, control de recámara y proyectil de recámara. Inamovibles en galería y en servicio.",r:"Instrucción de tiro · MADOC"},
{c:"cabo1",b:"B1",t:"Tiro",d:"M",id:"c1o034",q:"El fusil reglamentario del ET, el G36E, dispara cartuchos:",o:["5,56 × 45 mm OTAN","7,62 × 51 mm OTAN","9 × 19 mm Parabellum","12,7 × 99 mm"],a:0,x:"El G36E usa 5,56×45 OTAN con cargador de 30 cartuchos. El 7,62×51 es de la MG-42/MG-3 y del tirador selecto; el 9×19 de la pistola USP. Emparejar arma-cartucho cae siempre en exámenes.",r:"Instrucción de tiro · armamento ET"},
{c:"cabo1",b:"B1",t:"Tiro",d:"M",id:"c1o035",q:"En la MG-42/MG-3, el número de tiradores de la dotación mínima es:",o:["2 (tirador y aprovisionador)","1","5","8"],a:0,x:"La dotación básica son 2: el tirador (conduce el fuego) y el aprovicionador/enlaza (alimenta la cinta, corrige averías, vigila sectores). El arma, calibre 7,62×51, por cinta de eslabones.",r:"Instrucción de tiro · armamento ET"},
{c:"cabo1",b:"B1",t:"Tiro",d:"M",id:"c1o036",q:"En la puntería, la línea de mira debe alinear:",o:["Punto de mira, alza y objetivo","El hombro y el codo","El objetivo y el sol","El cargador y el cañón"],a:0,x:"Puntería correcta = alinear los tres: alza (cerca del ojo), punto de mira (en la boca del cañón) y objetivo. El error más común es mirar el objetivo y descuidar el punto de mira: el tiro se va alto y ancho.",r:"Teoría del tiro"},
{c:"cabo1",b:"B1",t:"Tiro",d:"M",id:"c1o037",q:"El disparo debe ejecutarse:",o:["En la pausa respiratoria, con presión uniforme del gatillo","Reteniendo el aire el máximo posible con fuerza","Dando un tirón seco al gatillo","Al exhalar violentamente"],a:0,x:"Se dispara en la pausa respiratoria natural (tras exhalar, sin forzar) y con presión CONTINUA y recta del gatillo hasta que sorprenda el disparo. Jalonear (tirar brusco) desvía el arma: es el fallo típico del novato.",r:"Teoría del tiro"},
{c:"cabo1",b:"B1",t:"Tiro",d:"M",id:"c1o038",q:"¿Qué es la zona rasada?",o:["La zona que un proyectil no puede dejar sin batir a causa del perfil del terreno","La parte alta de la curva de nivel","La franja de arena del río","El límite del sector de fuego"],a:0,x:"Zona rasada: la que el proyectil NO bate porque el terreno (una loma, un terraplén) lo corta. Es donde se protege el enemigo y también donde nos protegemos nosotros: buscar la desenfilada (protección frente a fuego y observación) es buscar zona rasada propia.",r:"Instrucción de tiro · doctrina"},
{c:"cabo1",b:"B1",t:"Tiro",d:"D",id:"c1o039",q:"El sector PRINCIPAL de fuego de un combatiente es:",o:["El que le asigna el mando como prioritario para él","Todo el horizonte","El que elige cada uno","Solo el frontal de 10 metros"],a:0,x:"Cada combatiente recibe sector principal (al que debe batir con prioridad) y suplementario (alternativo, normalmente hacia otro flanco). Nadie elige su sector: lo asigna el mando para cubrir todo el frente sin huecos.",r:"Instrucción táctica · MADOC"},
{c:"cabo1",b:"B1",t:"Tiro",d:"M",id:"c1o040",q:"Tras el ejercicio de tiro, el mantenimiento de primera escala del arma incluye:",o:["Desmontado de campo, limpieza y ligera lubricación","Dejarla tal cual hasta el próximo año","Sumergirla en agua","Pintarla"],a:0,x:"Primera escala (la del usuario): desmontado de campo, cepillado y limpieza de recámara/ánima con material reglamentario, lubricación LIGERA y revisión de funcionamientos. Tras tiro real o maniobra: limpieza SIEMPRE, aunque llueva o se estrene el día.",r:"Instrucción de tiro"},
{c:"cabo1",b:"B1",t:"Tiro",d:"D",id:"c1o041",q:"La cadencia de tiro práctica del G36E se caracteriza por:",o:["Ráfagas cortas para conservar dominio del arma y munición","Siempre a fondo hasta vaciar","Un solo cartucho al año","Depende del color del arma"],a:0,x:"Aunque la cadencia teórica ronda los 750 dpm, el tiro ÚTIL es a tiro a tiro o ráfagas CORTAS (2-3): dominio, precisión y economía. Vaciar el cargador en automático solo en emergencia inmediata.",r:"Instrucción de tiro · armamento"},
{c:"cabo1",b:"B1",t:"Tiro",d:"M",id:"c1o042",q:"La pistola USP Compact funciona:",o:["En doble acción el primer disparo y simple acción los siguientes","Solo en automático","Con cuerda como un reloj","Solo con el seguro quitado y munición aparte"],a:0,x:"La USP Compact: primer disparo en doble acción (el martillo sube apretando el gatillo, esfuerzo mayor) y los siguientes en simple acción (martillo ya montado, gatillo suave). Por eso el primer disparo exige control extra. Cargador de ~13 cartuchos de 9×19.",r:"Armamento ET"},

/* ===== TOPOGRAFÍA (de 2 → 8) ===== */
{c:"cabo1",b:"B1",t:"Topografía",d:"M",id:"c1o043",q:"El mapa militar básico del ET es el MTN a escala:",o:["1:50.000","1:10.000.000","1:500","1:5.000"],a:0,x:"El Mapa Topográfico Nacional 1:50.000 es la base (1 cm mapa = 500 m terreno). Para detallar se usan 1:25.000. La escala y su equivalencia caen siempre: saber pasar de mapa a terreno y viceversa.",r:"IGN · cartografía militar"},
{c:"cabo1",b:"B1",t:"Topografía",d:"M",id:"c1o044",q:"La península Ibérica ocupa los husos UTM:",o:["29, 30 y 31","1, 2 y 3","60, 61 y 62","44, 45 y 46"],a:0,x:"La península: husos 29 (oeste), 30 (centro, incluye Madrid) y 31 (este); Baleares 31 y Canarias 28. Cada huso mide 6° de longitud. El sistema militar global MGRS se apoya en UTM.",r:"IGN · MGRS"},
{c:"cabo1",b:"B1",t:"Topografía",d:"M",id:"c1o045",q:"¿Qué es la equidistancia entre curvas de nivel?",o:["La diferencia de ALTITUD constante entre dos curvas consecutivas","La distancia entre dos pueblos","El ancho del mapa","La hora solar"],a:0,x:"Curvas de nivel = puntos de igual altitud; la equidistancia es el salto vertical fijo entre curvas consecutivas (p. ej. 20 m en el 1:50.000). Curvas juntas = pendiente fuerte; separadas = terreno suave. Con ellas se «lee» el terreno sin verlo.",r:"Cartografía militar"},
{c:"cabo1",b:"B1",t:"Topografía",d:"M",id:"c1o046",q:"Los TRES nortes del mapa son:",o:["Geográfico (verdadero), magnético y de rejilla","Norte, sur y este","Solar, lunar y estelar","Rojo, azul y verde"],a:0,x:"Verdadero/geográfico (meridiano hacia el polo), magnético (el que marca la aguja) y de rejilla (las líneas verticales UTM del mapa). Sus ángulos entre sí (declinación y convergencia) se corrigen al pasar brújula↔mapa↔terreno.",r:"Topografía militar"},
{c:"cabo1",b:"B1",t:"Topografía",d:"M",id:"c1o047",q:"Para volver sobre tus pasos con brújula usas:",o:["El retroazimut (azimut ± 180°)","El mismo azimut","La brújula al revés, sin calcular","El GPS sin pilas"],a:0,x:"Retroazimut = azimut ± 180° (si pasas por 90°, vuelves por 270°). Regla mental básica de navegación nocturna o con niebla: apunta tu azimut de ida y guarda el retro para el regreso.",r:"Topografía militar"},
{c:"cabo1",b:"B1",t:"Topografía",d:"D",id:"c1o048",q:"El «factor de paso» sirve para:",o:["Calcular la distancia andada contando pasos y multiplicando por la longitud media del paso","Medir la velocidad del viento","Calcular la pendiente del río","Contar los hombres de la sección"],a:0,x:"Cada militar tiene un factor de paso (longitud media de su paso natural). Contando pasos (o dobles pasos) y multiplicando, estimas distancia recorrida sin GPS: imprescindible en navegación nocturna y con visibilidad nula.",r:"Topografía militar"},

/* ===== ORGANIZACIÓN DEL ET (de 2 → 8) ===== */
{c:"cabo1",b:"B1",t:"Organización",d:"M",id:"c1o049",q:"¿Quién manda el Ejército de Tierra?",o:["El JEME (Jefe del Estado Mayor del Ejército de Tierra), bajo el Ministro de Defensa y el JEMAD","El Rey directamente","El capitán de la unidad","El alcalde"],a:0,x:"El JEME es el jefe militar del ET. Encima: Ministro de Defensa (dirección política) y JEMAD (mando operativo de las FAS). El mando se ejerce en cascada: saber QUIÉN es el superior de cada nivel cae en todos los exámenes.",r:"Instrucción 14/2021 · ODEF 559/2024"},
{c:"cabo1",b:"B1",t:"Organización",d:"M",id:"c1o050",q:"Las ARMAS del Ejército de Tierra son:",o:["Infantería, Caballería, Artillería, Ingenieros y Transmisiones","Ejército, Armada y Aire","Guardia Civil y Policía","Solo Infantería"],a:0,x:"Cinco armas: Infantería, Caballería, Artillería, Ingenieros y Transmisiones. Los CUERPOS son generales (Intendencia, Veterinaria), técnicos (ITAM, ITCI) y especiales (Jurídico, Eclesiástico). No confundir armas con cuerpos ni con ejércitos.",r:"Instrucción 14/2021"},
{c:"cabo1",b:"B1",t:"Organización",d:"M",id:"c1o051",q:"La unidad elemental de combate es:",o:["La escuadra","El regimiento","La división","El ejército"],a:0,x:"Escuadra (elemental, la manda un cabo) → sección (básica, un sargento/capitán según arma) → compañía/batería/grupo → regimiento/bandera → brigada → división. El cabo 1º debe recitar esta escalera dormido.",r:"Organización del ET"},
{c:"cabo1",b:"B1",t:"Organización",d:"D",id:"c1o052",q:"El Mando de Fuerzas Terrestres (MFT) es:",o:["El mando orgánico que prepara a las unidades de fuerza para su empleo","Un mando de transmisiones","El mando de la Guardia Real","Una brigada situada en Canarias"],a:0,x:"El ET se estructura en: Cuartel General Terrestre, Mando de Personal (MAPER), Mando de Apoyo a la Maniobra (MAM) y Mando de Fuerzas Terrestres (MFT, Sevilla) — este último prepara y tiene asignadas las unidades de fuerza (brigadas) para el combate.",r:"Instrucción 14/2021 · ODEF 559/2024"},
{c:"cabo1",b:"B1",t:"Organización",d:"M",id:"c1o053",q:"La Brigada «Almogávares» es:",o:["La brigada de infantería ligera paracaidista (VI) de Murcia","Una brigada de la Armada","Una unidad de la Guardia Civil","Un mando aéreo"],a:0,x:"Almogávares VI (Paracaidista) en Murcia; Brunete I en Madrid/Brión; Guzmán el Bueno X en Córdoba; Galicia VII en Pontevedra; Extremadura XI en Badajoz; Canarias XVI; Aragón I en Zaragoza. Los apodos de las brigadas son pregunta clásica.",r:"Organización del ET"},
{c:"cabo1",b:"B1",t:"Organización",d:"M",id:"c1o054",q:"¿Qué es el MAM del Ejército de Tierra?",o:["El Mando de Apoyo a la Maniobra","El Mando Aéreo de Madrid","El Museo del Ejército","El Mando de Artillería de Montaña"],a:0,x:"MAM = Mando de Apoyo a la Maniobra: prepara y da las unidades de apoyo (artillería de campaña, ingenieros, transmisiones, sanidad, logística…) que «apoyan» a las brigadas en combate. No lo confundas con el MFT (fuerzas) ni el MAPER (personal).",r:"Instrucción 14/2021"} 
];
