/* A LA ORDEN — Lote 6 · CABO TIERRA (hechos derivados del test comunitario público de daypo.com
   "test de apoyo ascenso a cabo ET" (2016, 50 preg.) y de ascensoacabo.com. Reescritos y
   actualizados a la normativa vigente: algunos datos del test de 2016 están desfasados
   (verificado: la LODN 5/2005 y las RROO RD 96/2009 que citaba SIGUEN vigentes; lo desfasado se actualizó, p. ej. el régimen de guardias a RD 502/2020) */
window.FACTS_LOTE6 = [
/* ===== RROO: objeto, deberes, disciplina ===== */
["cabo","C1","Reales Ordenanzas","M","RROO art. 1","¿Para qué sirven las Reales Ordenanzas?","Para guiar a todos los militares en el exacto cumplimiento del deber",["Para fijar los sueldos de cada empleo","Para regular solo los desfiles","Para organizar las academias"],"Las RROO sirven de ___ a todos los militares para el exacto cumplimiento del deber.","guía",["trampa","moneda","bandera"]],
["cabo","C1","Reales Ordenanzas","M","RROO art. 3","¿Cuál es el primer deber del militar?","La disposición permanente de defender a España, incluso con su vida",["Pagar puntualmente las cuotas","Asistir a todos los desfiles","Alcanzar el máximo empleo"],"El primer deber del militar es la disposición permanente de defender a España, incluso con su ___.","vida",["sueldo","arma","uniforme"]],
["cabo","C1","Reales Ordenanzas","M","RROO art. 4","¿Qué es la disciplina según las RROO?","Un factor de cohesión: obliga a mandar con responsabilidad y a obedecer lo mandado",["Un sistema de multas","Una cadena de favoritos","Un registro de retrasos"],"La disciplina es factor de ___: obliga a mandar con responsabilidad y a obedecer lo mandado.","cohesión",["presión","colección","ocasión"]],
["cabo","C1","Reales Ordenanzas","M","RROO art. 4","¿Dónde tiene su expresión colectiva la disciplina?","En el acatamiento de las órdenes de los superiores",["En las cartas al editor","En los votos internos","En las encuestas del cuartel"],"La disciplina tiene su expresión colectiva en el acatamiento de las ___ de los superiores.","órdenes",["sugerencias","fiestas","cifras"]],
["cabo","C1","Reales Ordenanzas","M","RROO art. 5","De estas, ¿cuál NO es una virtud fundamental del militar?","El valor",["La disciplina","El honor","La prontitud en la obediencia"],"No es virtud fundamental del militar: las cuatro son disciplina, honor, prontitud en la obediencia y exactitud en el ___","servicio",["descanso","vuelo","armario"]],
["cabo","C1","Reales Ordenanzas","M","RROO art. 61","¿Cómo debe ejercer la autoridad el que manda?","Con firmeza, justicia y equidad",["Con dureza y sin explicaciones","Con favores y amistad","Con multas y castigos diarios"],"El que manda ejerce su autoridad con firmeza, ___ y equidad.","justicia",["jubilación","paciencia infinita","presión"]],
/* ===== Seguridad en las FAS: guardias de seguridad ===== */
["cabo","C1","Seguridad en las FAS","M","Seguridad en las FAS art. 14","¿Qué carácter tienen las guardias de seguridad?","De presencia y duración limitadas, establecidas como servicio de armas",["De duración ilimitada","De voluntariado festivo","De castigo permanente"],"Las guardias de seguridad son de presencia y duración ___, establecidas como servicio de armas.","limitadas",["ilimitadas","aleatoria","opcional"]],
["cabo","C1","Seguridad en las FAS","M","Seguridad en las FAS","¿Cómo prestan servicio los componentes de una guardia de seguridad?","Como centinelas y vigilantes",["Como agentes de la autoridad judiciales","Como policías locales","Como observadores externos"],"Los componentes de la guardia de seguridad prestan su servicio como centinelas y ___.","vigilantes",["jueces","ministros","auditores"]],
["cabo","C1","Seguridad en las FAS","D","Seguridad en las FAS","¿Qué es un destacamento de seguridad?","Una unidad o fracción separada de su unidad superior para establecer una guardia de seguridad",["Una tienda de campaña reforzada","Un coche blindado","Un paquete de munición extra"],"El destacamento de seguridad es una unidad o fracción ___ de su unidad superior para establecer una guardia.","separada",["gemela","inventada","enterrada"]],
["cabo","C1","Seguridad en las FAS","M","Seguridad en las FAS art. 83","¿Cuáles son los cometidos de la guardia de seguridad?","Vigilancia y protección, y control de accesos e identificación de personas, vehículos y materiales",["Solo abrir y cerrar el portón","Contar los gatos del cuartel","Repartir la correspondencia personal"],"La guardia de seguridad realiza la vigilancia y protección y el control de ___ e identificación.","accesos",["nombres","sueldos","menús"]],
/* ===== Régimen Interior ===== */
["cabo","C1","Régimen Interior","M","Régimen interior art. 32","¿Qué es el libro de normas de régimen interior?","El libro de cada instalación que rige su vida y funcionamiento interno",["Un diario secreto del mando","Un catálogo de menús","Un registro de multas de tráfico"],"Cada instalación dispone de un libro de normas de régimen interior que rige su ___ y funcionamiento interno.","vida",["pintura","antigüedad","factura"]],
/* ===== Carrera militar: funciones y empleos ===== */
["cabo","C1","Carrera militar","M","Ley 39/2007 art. 19","¿Qué funciones puede ejercer el militar profesional?","Operativas, técnicas, logísticas y administrativas",["Solo operativas en el extranjero","Solo administrativas en retaguardia","Solo docentes en academias"],"El militar profesional ejerce funciones operativas, técnicas, ___ y administrativas.","logísticas",["mágicas","civiles","arbitrarias"]],
["cabo","C1","Carrera militar","F","Equivalencias de empleos","¿A qué empleo de la Armada equivale un teniente general?","Almirante general",["Capitán de navío","Almirante","Contraalmirante"],"Un teniente general del ET equivale en la Armada al almirante ___.","general",["jefe","mayor"," supremo"]],
["cabo","C1","Carrera militar","F","Equivalencias de empleos","¿A qué empleo del ET equivale un capitán de navío?","Coronel",["Teniente coronel","Comandante","General de brigada"],"Un capitán de navío equivale en el Ejército de Tierra al empleo de ___.","coronel",["comandante","capitán","teniente"]],
["cabo","C1","Carrera militar","F","Equivalencias de empleos","¿A qué empleo de la Armada equivale un comandante?","Capitán de fragata",["Capitán de corbeta","Teniente de navío","Alférez de navío"],"Un comandante del ET equivale en la Armada al capitán de ___.","fragata",["corbeta","navío","yate"]],
/* ===== Armamento (del test comunitario) ===== */
["cabo","C2","Armamento","M","Dotación del ET","¿Cómo es la espoleta de la granada de mano del ET?","Mecano-eléctrica",["Solamente mecánica","Pura mente psíquica","Hidráulica de vapor"],"La espoleta de la granada de mano es mecano-___.","eléctrica",["mecánica pura","manual","solar"]],
["cabo","C2","Armamento","M","Manual C-90","¿Qué características tiene el visor del lanzagranadas C-90?","Dos aumentos y un ángulo de visión de 13 grados",["Diez aumentos y 90 grados","Sin aumentos","Visión nocturna integrada siempre"],"El visor del C-90 tiene dos aumentos y un ángulo de visión de ___ grados.","13",["90","45","180"]],
/* ===== Primeros auxilios ===== */
["cabo","C2","Primeros auxilios","M","Hemorragias","¿Cómo se reconoce una hemorragia arterial?","Sangre rojo intenso, a gran presión y a sacudidas sincrónicas con el pulso",["Sangre rojo oscuro que mana despacio","Sangre azul en pequeñas gotas","No sale sangre nunca"],"En la hemorragia arterial la sangre es rojo intenso y sale a gran presión a sacudidas ___ con el pulso.","sincrónicas",["musicales","invisibles","anuales"]],
/* ===== Actualidad (ascensoacabo) ===== */
["cabo","C1","El examen","M","Nota de corte I/24 (ascensoacabo)","¿Cuál fue la nota de corte del examen I/24 de ascenso a Cabo?","4,390 puntos",["5,000 puntos","3,335 puntos","6,500 puntos"],"La nota de corte del I/24 fue de ___ puntos (la del I/25 fue 4,335).","4,390",["4,335","3,900","5,390"]]
];
