/* A LA ORDEN — Lote 5 · CABO TIERRA (hechos detectados en cuadernillos oficiales públicos I/24,
   reescritos a nuestro estilo para el flujo de estudio) */
window.FACTS_LOTE5 = [
["cabo","C2","Tiro","M","Balística exterior","¿Cómo se llama la línea que es la prolongación del eje del tubo del arma dispuesta para el disparo?","La línea de tiro",["La línea de mira","La línea de situación","La línea de proyección"],"La prolongación del eje del tubo dispuesta para el disparo se llama línea de ___.","tiro",["mira","situación","vista"]],
["cabo","C2","Topografía","F","Cartografía militar","¿Qué escala tiene el mapa militar empleado en operaciones?","1:50.000",["1:5.000","1:10.000","1:25.000"],"El mapa militar empleado en operaciones tiene escala ___.","1:50.000",["1:5.000","1:10.000","1:25.000"]],
["cabo","C1","Código Penal Militar","D","CPM art. 4","¿Quiénes se asimilan a centinela a efectos del Código Penal Militar?","Los operadores de redes militares de transmisiones, comunicaciones o informáticas durante sus cometidos",["Cualquier civil en acuartelamientos","Solo los vigilantes nocturnos","Los miembros de bandas de música en actos"],"A efectos del CPM son centinelas los operadores de redes militares de transmisiones, comunicaciones o ___.","informáticas",["telefónicas civiles","sociales","militares de cocinas"]],
["cabo","C1","Régimen Interior","M","Régimen interior","¿Cómo se denomina el conjunto de infraestructuras y locales al servicio de uno o varios centros u organismos?","El establecimiento",["El acantonamiento","La factoría","El bastión"],"El conjunto de infraestructuras y locales al servicio de uno o varios centros u organismos es el ___.","establecimiento",["organismo","barrio","poblado"]],
["cabo","C1","Seguridad en las FAS","M","Policía militar","¿Qué consideración tienen los militares que prestan servicio como policía militar?","Agentes de la autoridad",["Meros ciudadanos uniformados","Autoridades judiciales","Observadores neutrales"],"Los militares que prestan servicio como policía militar tienen la consideración de ___ de la autoridad.","agentes",["delegados","figuras","símbolos"]]
];
