/* A LA ORDEN — Lote 2 de hechos · CABO TIERRA (mapa de temario según convocatoria oficial:
   Régimen Interior OM 50/2011, Seguridad en las FAS, Tiro, L 8/2006, requisitos I/25) */
window.FACTS_CABO2 = [
/* ===== Régimen Interior (OM 50/2011) ===== */
["cabo","C1","Régimen Interior","M","OM 50/2011","¿Qué norma regula el régimen interior de las unidades del Ejército de Tierra?","La OM 50/2011, de 9 de febrero",["La OM 19/2009, de 5 de febrero","La OM 12/2019, de 14 de febrero","El RD 847/2015, de 2 de octubre"],"El régimen interior de las unidades del ET se regula en la OM ___.","50/2011, de 9 de febrero",["19/2009, de 5 de febrero","12/2019, de 14 de febrero","36/2014, de 28 de abril"]],
["cabo","C1","Régimen Interior","F","OM 50/2011","¿Cómo se llama la comunicación escrita de las novedades diarias de la unidad?","El parte diario",["El parte de guardia mensual","El libro de órdenes","El acta de revista"],"La comunicación escrita de las novedades diarias de la unidad es el parte ___.","diario",["mensual","semanal","extraordinario"]],
["cabo","C1","Régimen Interior","F","OM 50/2011","¿Dónde se registran los servicios de guardia y sus novedades?","En el libro de guardia",["En el libro de visitas","En la hoja de servicios","En el parte meteorológico"],"Los servicios de guardia y sus novedades se registran en el libro de ___.","guardia",["órdenes","visitas","armas"]],
["cabo","C1","Régimen Interior","M","OM 50/2011","¿Qué servicio vela por la seguridad interna del acuartelamiento y el control de accesos?","La guardia",["La escolta","La intendencia","La plana mayor"],"El servicio que vela por la seguridad interna del acuartelamiento y controla los accesos es la ___.","guardia",["escolta","patrulla","sección"]],
["cabo","C1","Régimen Interior","F","RROO","¿Cómo es el saludo militar entre militares?","Mutuo y obligatorio",["Opcional","Exclusivo de suboficiales y oficiales","Solo en actos solemnes"],"El saludo militar es ___ y obligatorio entre militares.","mutuo",["facultativo","exclusivo","eventual"]],
["cabo","C1","Régimen Interior","F","OM 50/2011","¿Qué viste el militar en acto de servicio?","El uniforme reglamentario",["Traje civil discreto","El uniforme de gala únicamente","Ropa deportiva de unidad"],"En acto de servicio el militar viste el ___ reglamentario.","uniforme",["traje","chaleco","equipo"]],
["cabo","C1","Régimen Interior","M","Ley 39/2007 art. 55","¿Puede el militar de tropa residir fuera del acuartelamiento?","Sí; la ley actual no exige autorización para la residencia",["No, nunca","Solo con permiso del Rey","Solo los cabos primeros"],"La ley actual ___ exige autorización para residir fuera del acuartelamiento.","no",["siempre","solo en guerra","únicamente"]],
["cabo","C1","Régimen Interior","F","Seguridad y LORDFAS","¿Cómo está el consumo de alcohol en acto de servicio?","Prohibido",["Permitido en comidas oficiales","Regulado por cada comandante","Permitido fuera del recinto"],"El consumo de alcohol en acto de servicio está ___.","prohibido",["permitido","regulado","tolerado"]],
["cabo","C1","Régimen Interior","M","OM 50/2011","¿Qué recogen las órdenes permanentes de la unidad?","Las normas fijas de funcionamiento y servicios",["Los sueldos del mes","Las vacaciones del mando","El menú del comedor"],"Las órdenes ___ recogen las normas fijas de funcionamiento de la unidad.","permanentes",["temporales","verbales","honoríficas"]],
["cabo","C1","Régimen Interior","F","OM 50/2011","¿Dónde se custodia el armamento colectivo de la unidad?","En el armero",["En el comedor","En el aula de formación","En el vehículo reglamentario"],"El armamento colectivo de la unidad se custodia en el ___.","armero",["despacho","almacén de víveres","trastero"]],
["cabo","C1","Régimen Interior","M","OM 50/2011","¿Quién establece el régimen de entradas y salidas del acuartelamiento?","El mando de la unidad, conforme al régimen interior",["El Ministerio del Interior","Cada soldado libremente","El ayuntamiento"],"El régimen de entradas y salidas lo establece el mando conforme al régimen ___.","interior",["laboral","penitenciario","comunitario"]],
["cabo","C1","Régimen Interior","F","RROO","¿En qué se basa el trato entre militares?","En el respeto, la cortesía y la dignidad",["En la familiaridad","En la indiferencia","En la antigüedad exclusivamente"],"El trato entre militares se basa en el respeto, la ___ y la dignidad.","cortesía",["competencia","prisa","distancia"]],
/* ===== Seguridad en las FAS ===== */
["cabo","C1","Seguridad en las FAS","F","Doctrina de seguridad","¿Cuál es el objetivo principal de la seguridad en las FAS?","Prevenir los accidentes e incidentes en el servicio",["Aumentar el ritmo de instrucción","Sancionar los errores","Reducir el gasto en material"],"La seguridad en las FAS busca prevenir los ___ e incidentes en el servicio.","accidentes",["ascensos","traslados","desfiles"]],
["cabo","C1","Seguridad en las FAS","M","Doctrina de seguridad","¿De quién es la responsabilidad en materia de seguridad?","De todos: el mando la lidera y cada militar la aplica",["Solo del oficial de seguridad","Del fabricante del material","De la inspección sanitaria"],"En seguridad, el mando la lidera y cada militar la ___.","aplica",["vende","dibuja","prohíbe"]],
["cabo","C1","Seguridad en las FAS","M","Doctrina de seguridad","¿Qué se realiza antes de un acto de servicio con riesgos?","Una charla de seguridad sobre los riesgos y su prevención",["Una encuesta de opinión","Una auditoría contable","Un desfile de revista"],"Antes de un acto de servicio con riesgos se realiza una ___ de seguridad.","charla",["encuesta","condena","cita"]],
["cabo","C1","Seguridad en las FAS","F","Doctrina de seguridad","¿Cuándo debe usarse el equipo de protección individual (EPI)?","Cuando se ordene y sea necesario para el servicio",["Cuando lo decida cada uno","Nunca en instrucción","Solo en el extranjero"],"El EPI debe usarse cuando se ___ y sea necesario para el servicio.","ordene",["deseche","olvide","venda"]],
["cabo","C1","Seguridad en las FAS","M","Doctrina de seguridad","¿Qué conviene hacer con los casi-accidentes observados?","Comunicarlos para evitar accidentes futuros",["Ocultarlos","Publicarlos en redes","Olvidarlos"],"Los casi-accidentes deben ___ para evitar accidentes futuros.","comunicarse",["ocultarse","premiarse","explotar"]],
/* ===== El examen · requisitos y nota de corte I/25 ===== */
["cabo","C1","El examen","M","Análisis nota de corte I/25 (carreraet.es)","¿Cuál fue la nota de corte general en el examen I/25 de ascenso a Cabo?","4,335 puntos",["5,000 puntos","3,500 puntos","4,950 puntos"],"La nota de corte general del I/25 fue de ___ puntos.","4,335",["4,000","3,335","5,335"]],
["cabo","C1","El examen","M","Convocatoria I/25","¿Qué evaluación física debe tener superada del año anterior el aspirante?","Las pruebas físicas (IPECs) del año anterior",["El examen psicotécnico del año anterior","La analítica de orina del mes anterior","El curso básico de paracaidista"],"Para presentarse debe tener superadas las pruebas físicas (___) del año anterior.","IPECs",["IDEs","OGUEs","SNAPs"]],
["cabo","C1","El examen","M","Convocatoria I/25","¿Entre qué números de escalafón debía estar comprendido el solicitante en la I/25?","Entre el 60014400 y el 67260915, ambos incluidos",["Entre el 10000000 y el 20000000","Entre el 70000000 y el 79000000","Entre el 55000000 y el 56000000"],"En la I/25 el número de escalafón debía estar entre el 60014400 y el ___.","67260915",["67260916","60014400","68000000"]],
["cabo","C1","El examen","M","Convocatoria I/25","¿Cuántos años previos no debe constar positivo en analítica de orina?","Dos años",["Un año","Cinco años","Diez años"],"No debe constar positivo en analítica de orina en los ___ años previos.","dos",["tres","cinco","diez"]],
["cabo","C1","El examen","M","Convocatoria I/25","¿Qué antecedentes impiden participar en el ascenso a Cabo?","Sentencia firme por delito doloso o dos faltas muy graves no canceladas",["Una multa de tráfico","Un retraso en el parte diario","Haber suspendido el examen dos veces"],"Impiden participar la sentencia firme por delito doloso o dos faltas ___ no canceladas.","muy graves",["leves","antiguas","de tráfico"]],
/* ===== Carrera militar · L 8/2006 y RD 836/2015 ===== */
["cabo","C1","Carrera militar","F","Ley 8/2006","¿Qué ley regula la tropa y marinería?","La Ley 8/2006, de 24 de abril",["La Ley 39/2007, de 19 de noviembre","La LO 9/2011, de 27 de julio","La Ley 39/2015, de 18 de noviembre"],"La tropa y marinería se regula en la Ley ___ de 24 de abril.","8/2006",["39/2007","9/2011","40/2015"]],
["cabo","C1","Carrera militar","F","Ley 8/2006","Según la Ley 8/2006, el personal de tropa y marinería se clasifica en…","Soldados, cabos y cabos primeros",["Sargentos y cabos","Alféreces y tenientes","Especialistas y ayudantes"],"El personal de TM se clasifica en soldados, ___ y cabos primeros.","cabos",["brigadas","sargentos","guías"]],
["cabo","C1","Carrera militar","M","RD 836/2015","¿Cuántas convocatorias por empleo puede presentarse un militar como máximo?","Cuatro, conforme al RD 836/2015",["Dos","Seis","Ilimitadas"],"Un militar puede presentarse hasta ___ convocatorias por empleo.","cuatro",["dos","seis","diez"]],
["cabo","C1","Carrera militar","M","RD 836/2015","¿Consumir convocatoria la renuncia expresada antes de los resultados de la fase de concurso?","No, no consume convocatoria",["Sí, la consume siempre","La consume solo en verano","Depende del mando"],"La renuncia antes de los resultados del concurso ___ convocatoria.","no consume",["consume","duplica","suspende"]],
/* ===== Código Penal Militar · reforma correcta ===== */
["cabo","C1","Código Penal Militar","M","LO 14/2015","¿Qué ley orgánica reformó el Código Penal Militar en 2015?","La Ley Orgánica 14/2015, de 14 de octubre",["La LO 8/2014, de 4 de diciembre","La LO 9/2011, de 27 de julio","La LO 5/2005, de 17 de noviembre"],"El Código Penal Militar fue reformado por la LO ___.","14/2015, de 14 de octubre",["8/2014, de 4 de diciembre","9/2011, de 27 de julio","13/2015, de 5 de octubre"]],
/* ===== Armamento · ampliación ===== */
["cabo","C2","Armamento","F","Examen I/24 · MG-4 ET","¿Qué calibre emplea la ametralladora ligera MG-4?","5,56 × 45 mm",["7,62 × 51 mm","9 × 19 mm","12,7 × 99 mm"],"La ametralladora ligera MG-4 emplea munición 5,56 × ___ mm.","45",["51","99","33"]],
["cabo","C2","Armamento","M","Dotación del ET","¿Qué calibre emplea la ametralladora pesada Browning M2?","12,7 × 99 mm",["7,62 × 51 mm","5,56 × 45 mm","40 mm"],"La Browning M2 es una ametralladora pesada de ___ mm.","12,7",["7,62","5,56","20"]],
["cabo","C2","Armamento","M","Sistemas del ET","El sistema EIMOS del Ejército de Tierra es un mortero integrado de…","60 mm",["81 mm","120 mm","90 mm"],"El EIMOS es un mortero integrado de ___ mm.","60",["81","120","82"]],
["cabo","C2","Armamento","M","Sistemas del ET","¿Qué tipo de sistema es el Spike?","Un sistema antitanque guiado",["Un radar meteorológico","Un dron de vigilancia","Un cañón antiaéreo"],"El Spike es un sistema ___ guiado.","antitanque",["antiaéreo","naval","de comunicaciones"]],
["cabo","C2","Armamento","M","Dotación del ET","¿Qué calibre tiene el lanzagranadas automático SB LAG-40?","40 mm",["30 mm","60 mm","90 mm"],"El lanzagranadas automático SB LAG-40 es de ___ mm.","40",["30","60","45"]],
["cabo","C2","Armamento","M","Manual G36E","¿Cómo funciona el fusil G36?","Por toma de gases",["Por retroceso de cañón","Por muelle permanente","Por fuerza manual"],"El fusil G36 funciona por toma de ___.","gases",["muelles","aire comprimido","electricidad"]],
["cabo","C2","Armamento","F","Munición","¿Para qué sirve la munición trazadora?","Para seguir visualmente la trayectoria del proyectil",["Para silenciar el disparo","Para duplicar el alcance","Para limpiar el cañón"],"La munición ___ permite seguir visualmente la trayectoria.","trazadora",["inerte","de fogueo","perforante"]],
/* ===== Tiro (teoría del tiro) ===== */
["cabo","C2","Tiro","F","Teoría del tiro","¿Cómo se llama la línea que une el ojo, el alza, el punto de mira y el objetivo?","La línea de mira",["La línea de fuego","La línea de retaguardia","La línea de flotación"],"La línea que une ojo, alza, punto de mira y objetivo es la línea de ___.","mira",["fuego","tiro","flujo"]],
["cabo","C2","Tiro","F","Teoría del tiro","¿En qué unidad se expresa la cadencia de tiro?","Disparos por minuto",["Disparos por segundo","Disparos por hora","Disparos por cargador"],"La cadencia de tiro se expresa en disparos por ___.","minuto",["segundo","hora","mes"]],
["cabo","C2","Tiro","M","Teoría del tiro","Las posiciones básicas de tiro con fusil son de pie, de ___ y tendido","rodillas",["espaldas","puntillas","lado"],"Las posiciones básicas de tiro son de pie, de ___ y tendido.","rodillas",["espaldas","costado","pie"]],
["cabo","C2","Tiro","M","Manual G36E","¿Qué permite el selector de tiro del fusil?","Elegir entre disparo individual y automático",["Cambiar el calibre","Plegar el arma","Encender el puntero láser"],"El selector de tiro permite el disparo individual y el ___.","automático",["doble","nulo","remoto"]],
["cabo","C2","Tiro","M","Seguridad del tiro","Antes de abrir fuego se confirma el objetivo y que…","No hay personal amigo o civil en la zona",["El arma esté sucia","Haya viento a favor","Se haya tocado el toque"],"Antes de abrir fuego se confirma que no hay personal ___ en la zona.","amigo o civil",["de retaguardia","de guardia","del comedor"]],
/* ===== Topografía · ampliación ===== */
["cabo","C2","Topografía","M","Manual topográfico","¿Cómo se llama la distancia vertical entre dos curvas de nivel consecutivas?","La equidistancia",["El acimut","El desnivel","La escala"],"La distancia vertical entre dos curvas de nivel consecutivas es la ___.","equidistancia",["proyección","cotación","latitud"]],
["cabo","C2","Topografía","M","Manual topográfico","Cada ___ curvas de nivel, una se dibuja más gruesa y se llama curva madre","5",["2","10","20"],"Cada ___ curvas se dibuja una curva madre más gruesa.","5",["2","10","25"]],
["cabo","C2","Topografía","F","Manual topográfico","¿Cómo se llama la diferencia de altitud entre dos puntos?","El desnivel",["La equidistancia","El acimut","La coordenada"],"La diferencia de altitud entre dos puntos se llama ___.","desnivel",["desvío","déficit","deriva"]],
["cabo","C2","Topografía","F","Manual topográfico","¿Qué norte señala la aguja imantada de la brújula?","El norte magnético",["El norte geográfico","El norte de la cuadrícula","El norte verdadero"],"La aguja imantada señala el norte ___.","magnético",["geográfico","político","de la cuadrícula"]],
["cabo","C2","Topografía","M","Manual topográfico","¿Qué significa orientar el mapa?","Hacer coincidir el norte del mapa con el norte real del terreno",["Ponerlo al sol","Doblarlo por la mitad","Dibujar nuevas curvas"],"Orientar el mapa es hacer coincidir el norte del mapa con el ___ real.","norte",["sur","centro","borde"]],
/* ===== Transmisiones · ampliación ===== */
["cabo","C2","Transmisiones","M","Procedimiento radiofónico","¿Para qué se impone el silencio radio?","Para evitar que el enemigo escuche o localice las emisiones",["Para ahorrar baterías","Para ordenar la conversación","Para celebrar efemérides"],"El silencio radio evita que el enemigo escuche o ___ las emisiones.","localice",["financie","traduzca","grabe en CD"]],
["cabo","C2","Transmisiones","M","Seguridad de la información","¿Qué busca el control de emisiones?","Limitar las transmisiones que pueden revelar la posición",["Aumentar el alcance del emisor","Cambiar de frecuencia cada hora","Prohibir todas las radios"],"El control de emisiones limita las transmisiones que pueden ___ la posición.","revelar",["vender","ampliar","decorar"]],
["cabo","C2","Transmisiones","F","Procedimiento radiofónico","¿Cómo se identifica una unidad en la red de transmisiones?","Mediante su indicativo",["Mediante su matrícula","Con su escudo","Con el sello del cuartel"],"Cada unidad se identifica en la red mediante su ___.","indicativo",["número de teléfono","dirección","alias civil"]],
["cabo","C2","Transmisiones","M","Procedimiento radiofónico","¿Qué debe hacerse antes de transmitir?","Escuchar para no interferir",["Gritar el nombre","Cantar el código","Apagar el equipo"],"Antes de transmitir se debe ___ para no interferir.","escuchar",["apagar","desmontar","sumar"]],
/* ===== Instrucción del combatiente · ampliación ===== */
["cabo","C2","Instrucción del combatiente","M","Doctrina táctica","La táctica que combina el avance de una unidad con el fuego de protección de otra es fuego y…","movimiento",["retirada","silencio","relevo"],"La táctica que combina avance y fuego de protección se llama fuego y ___.","movimiento",["olvido","juego","paso"]],
["cabo","C2","Instrucción del combatiente","F","Instrucción del combatiente","Para marchar por caminos se emplea la formación en ___; para combatir, la desplegada","columna",["círculo","rombo invertido","fila india permanente"],"Para marchar por caminos se emplea la formación en ___.","columna",["cuadro","abanico","línea suelta"]],
["cabo","C2","Instrucción del combatiente","M","Instrucción del combatiente","La misión de reconocimiento del terreno fuera de la base la realiza una…","patrulla",["compañía de carros","banda de guerra","sección sanitaria"],"El reconocimiento fuera de la base lo realiza una ___.","patrulla",["brigada","división","bandera"]],
["cabo","C2","Instrucción del combatiente","M","Doctrina de órdenes","¿Qué orden se prepara por adelantado para posibles contingencias?","La orden preventiva",["La orden de pago","La ordenanza municipal","La orden del día festivo"],"La orden ___ se prepara por adelantado para posibles contingencias.","preventiva",["definitiva","provisional oral","secuestrada"]],
["cabo","C2","Instrucción del combatiente","M","Instrucción del combatiente","¿Por qué se mantienen distancias entre combatientes en el avance?","Para que un solo impacto no afecte a varios",["Para ocupar más terreno","Para ver mejor el mapa","Por comodidad al marchar"],"Las distancias evitan que un solo impacto afecte a ___.","varios",["nadie","el mando","la retaguardia"]],
/* ===== Primeros auxilios · ampliación ===== */
["cabo","C2","Primeros auxilios","M","Protocolo de obstrucción","¿Cómo se llama la maniobra para desobstruir la vía aérea de un adulto consciente?","La maniobra de Heimlich",["Maniobra de Kendall","Posición de Fowler","Maniobra de Lelling"],"La maniobra para desobstruir la vía aérea del adulto consciente es la de ___.","Heimlich",["Kendall","Fowler","Trendelemburg"]],
["cabo","C2","Primeros auxilios","M","Protocolo de quemaduras","¿Qué es lo primero ante una quemadura?","Enfriar con agua abundante",["Poner hielo directamente","Reventar las ampollas","Cubrir con cremas grasas"],"Ante una quemadura, lo primero es ___ con agua abundante.","enfriar",["calentar","vendar apretado","untar"]],
["cabo","C2","Primeros auxilios","M","Protocolo de traumatismos","Ante una fractura abierta se debe…","Inmovilizar sin reducir la fractura",["Colocar el hueso en su sitio a la fuerza","Hacer andar al herido","Aplicar calor local"],"Ante una fractura abierta se debe ___ sin reducir la fractura.","inmovilizar",["masajear","estirar","hidratar"]],
["cabo","C2","Primeros auxilios","F","Sistema de emergencias","¿Cuál es el teléfono único de emergencias en España?","112",["061","091","911"],"El teléfono único de emergencias en España es el ___.","112",["062","091","912"]]
];
