/* A LA ORDEN — Lote 3 · CABO TIERRA (densificación de temario público: mismo fondo que
   trabajan FFIM/ANARO/ascensoacabo, redacción propia. Añade Orden Cerrado y Escuadra y equipo) */
window.FACTS_CABO3 = [
/* ===== Derechos, carrera y organización (segundos ángulos) ===== */
["cabo","C1","Derechos y deberes","F","L 39/2007 art. 39","¿Qué prestan los militares ante la bandera?","Juramento o promesa de servir con lealtad",["Un voto de confianza","Una declaración patrimonial","Nada; solo firman el contrato"],"Ante la bandera, el militar presta ___ o promesa de servir con lealtad.","juramento",["una declaración","un homenaje","un acuerdo"]],
["cabo","C1","Organización del ET","M","Orgánica del ET","¿Quién manda el Ejército de Tierra?","El Jefe de Estado Mayor del Ejército de Tierra (JEME)",["El MOPS","El JEMAD directamente","El Ministro del Interior"],"El Ejército de Tierra lo manda el Jefe de Estado Mayor del Ejército de Tierra, el ___.","JEME",["JEMAD","MOPS","MAPER"]],
["cabo","C1","Organización del ET","M","Orgánica del ET","¿Qué significa MADOC?","El Mando de Adiestramiento y Doctrina",["El Mando de Armamento y Dotaciones","El Mando de Artillería de Costa","El Mando de Asuntos Diplomáticos"],"MADOC significa Mando de ___ y Doctrina.","Adiestramiento",["Armamento","Artillería","Administración"]],
["cabo","C1","Organización del ET","M","Orgánica del ET","¿Qué significa MAPER?","El Mando de Personal",["El Mando de Prevención","El Mando de Apoyo en Retaguardia","El Mando de Paracaidistas"],"MAPER significa Mando de ___.","Personal",["Protección","Provisión","Patrullas"]],
["cabo","C1","Organización del ET","F","Organización del ET","¿Qué significa CEFOT?","Centro de Formación de Tropa",["Centro de Fuego Operativo y Táctico","Cuerpo Especial de Operaciones Tácticas","Centro de Enlace de Fuerzas Territoriales"],"El CEFOT es el Centro de ___ de Tropa.","Formación",["Fuego","Mando","Reclutamiento"]],
["cabo","C1","Carrera militar","M","Ley 8/2006","¿Dónde se inscriben los datos administrativos de los militares de tropa y marinería?","En el Fichero Universal de Tropa (FUT)",["En el censo municipal","En el registro de la propiedad","En el DNI electrónico"],"Los datos administrativos de la TM se inscriben en el Fichero Universal de ___ (FUT).","Tropa",["Trabajo","Titulaciones","Tribunales"]],
["cabo","C1","Régimen Disciplinario","M","LO 8/2014","¿Puede recurrirse una sanción disciplinaria?","Sí, ante la autoridad que la impuso o el superior jerárquico",["No; las sanciones son firmes siempre","Solo ante los tribunales civiles","Solo mediante perdón escrito"],"Las sanciones disciplinarias pueden ___ ante la autoridad que las impuso o el superior.","recurrirse",["duplicarse","publicarse","venderse"]],
["cabo","C1","Régimen Interior","M","OM 50/2011","¿Qué es la «novedad» de un militar en el parte diario?","Todo hecho que altera su situación habitual (ausencia, baja, servicio…)",["Su sueldo del mes","Su edad","Su destino de vacaciones"],"La novedad es todo hecho que altera la situación ___ del militar.","habitual",["económica","sentimental","civil"]],
["cabo","C1","Carrera militar","M","L 39/2007","¿Qué son los «tiempos de servicio»?","Los períodos computables en la relación de servicios profesional",["Los turnos de cocina","Los relojes reglamentarios","Los permisos arbitrarios"],"Los tiempos de servicio son los períodos ___ en la relación de servicios profesional.","computables",["perdidos","de ocio","hipotéticos"]],
/* ===== Orden Cerrado (temario oficial, capítulo 4) ===== */
["cabo","C2","Orden Cerrado","F","Orden cerrado","¿En qué dos partes se divide la voz de mando?","Preventiva y ejecutiva",["Larga y corta","Alta y baja","Única y repetida"],"La voz de mando se divide en parte ___ y ejecutiva.","preventiva",["cortés","oral","lenta"]],
["cabo","C2","Orden Cerrado","F","Orden cerrado","¿Cuál es la posición fundamental del militar?","El firme",["El descansado","El saludo","La formación"],"La posición fundamental del militar en orden cerrado es el ___.","firme",["descansado","estirado","cuadrado"]],
["cabo","C2","Orden Cerrado","M","Orden cerrado","¿Qué busca la instrucción de orden cerrado?","La disciplina, la cohesión y la respuesta automática al mando",["La mimética de combate","El tiro de precisión","La conducción todoterreno"],"El orden cerrado busca la disciplina, la cohesión y la respuesta ___ al mando.","automática",["tardía","opcional","escrita"]],
["cabo","C2","Orden Cerrado","M","Orden cerrado","¿Qué significa la voz «cubrirse»?","Alinear la fila tomando como referencia al compañero",["Protegerse del fuego","Ponerse el casco","Buscar abrigo"],"La voz «cubrirse» significa alinear la fila tomando como ___ al compañero.","referencia",["escudo","ejemplo","atajo"]],
["cabo","C2","Orden Cerrado","M","Orden cerrado","La voz «a discreción» permite…","Relajar la posición sin abandonar el puesto ni hablar",["Marchar libremente","Cantar himnos","Salir del formation"],"«A discreción» permite relajar la posición sin abandonar el puesto ni ___.","hablar",["respirar","parpadear","sostener el arma"]],
/* ===== Escuadra y equipo (temario oficial, capítulo 4) ===== */
["cabo","C2","Escuadra y equipo","F","Organización de unidades","¿Quién manda normalmente una escuadra?","Un cabo",["Un teniente","Un sargento primero","Un soldado"],"Normalmente una escuadra la manda un ___.","cabo",["alférez","brigada","coronel"]],
["cabo","C2","Escuadra y equipo","F","Organización de unidades","¿Qué es un equipo dentro de la escuadra?","La subunidad elemental en que se divide la escuadra",["Un aparato de radio","Un conjunto de mochilas","Una patrulla externa"],"El equipo es la ___ elemental en que se divide la escuadra.","subunidad",["arma","ración","sección"]],
["cabo","C2","Escuadra y equipo","M","Organización de unidades","¿Quién manda normalmente un equipo?","El cabo 1º o el militar de mayor graduación designado",["El general de la brigada","El cocinero de guardia","Se elige a sorteo cada semana"],"Un equipo lo manda normalmente el cabo 1º o el militar de ___ designado.","mayor graduación",["menor antigüedad","mejor puntería","mayor edad"]],
/* ===== Armamento, tiro, topografía, transmisiones (más ángulos) ===== */
["cabo","C2","Armamento","F","Manual G36E","¿Cuántos cartuchos tiene el cargador estándar del G36?","30",["20","25","40"],"El cargador estándar del G36 tiene ___ cartuchos.","30",["15","20","50"]],
["cabo","C2","Armamento","M","Munición","¿Para qué sirve la munición perforante?","Para atravesar protecciones o blindajes ligeros",["Para iluminar la noche","Para señalar posiciones amigas","Para limpiar el ánima"],"La munición perforante sirve para ___ protecciones o blindajes ligeros.","atravesar",["decorar","silenciar","alquilar"]],
["cabo","C2","Armamento","M","Munición","¿Qué granada se emplea contra personal en el descubierto?","La granada de fragmentación",["La granada fumígena","La granada luminosa","La granada de ejercicio"],"La granada de ___ se emplea contra personal en el descubierto.","fragmentación",["humo","luz","señal"]],
["cabo","C2","Tiro","M","Teoría del tiro","¿Qué se corrige con la dirección de viento en el tiro?","El desplazamiento lateral del proyectil",["El retroceso del arma","El brillo de la mira","La cadencia de disparo"],"La dirección de viento se corrige para contrarrestar el ___ lateral del proyectil.","desplazamiento",["peso","brillo","ruido"]],
["cabo","C2","Topografía","F","Manual topográfico","¿Cómo se expresa la escala numérica de un mapa?","Como fracción, por ejemplo 1/50.000",["Con colores","Con porcentajes","En decibelios"],"La escala numérica se expresa como ___, por ejemplo 1/50.000.","fracción",["porcentaje","grados","notas"]],
["cabo","C2","Topografía","M","Manual topográfico","¿Qué tres datos componen una coordenada UTM?","Zona, Este y Norte",["Altura, peso y edad","Día, mes y año","Calle, número y piso"],"Una coordenada UTM se compone de zona, ___ y Norte.","Este",["Oeste","Sur","Centro"]],
["cabo","C2","Transmisiones","M","Procedimiento radiofónico","¿Cómo se confirma la recepción de un mensaje radio?","Con el acuse de recibo",["Apagando la radio","Repetiendo 3 veces el nombre","Cambiando de frecuencia"],"La recepción de un mensaje se confirma con el ___ de recibo.","acuse",["sello","descuento","cambio"]],
/* ===== Instrucción del combatiente y auxilios (más ángulos) ===== */
["cabo","C2","Instrucción del combatiente","M","Instrucción del combatiente","¿Para qué sirve la formación desplegada?","Para combatir o avanzar bajo fuego",["Para desfiles","Para comer en campaña","Para el transporte aéreo"],"La formación ___ sirve para combatir o avanzar bajo fuego.","desplegada",["en columna","de gala","en cuadro"]],
["cabo","C2","Instrucción del combatiente","F","RROO","¿Qué es el espíritu militar?","El conjunto de valores y sentimientos que unen a los militares",["Un desfile anual","Una insignia bordada","Un premio económico"],"El espíritu militar es el conjunto de ___ y sentimientos que unen a los militares.","valores",["sueldos","uniformes","canciones"]],
["cabo","C2","Primeros auxilios","M","Protocolo de evacuación","¿Qué NO debe hacerse con un herido grave mientras llega la evacuación?","Moverlo innecesariamente",["Abrigarlo","Vigilar su respiración","Anotar la hora"],"Con un herido grave no se debe ___ innecesariamente.","moverlo",["vigilarlo","abrigarlo","tranquilizarlo"]]
];
