/* A LA ORDEN — Lote 8 · CABO 1º II (~68 hechos) · rascado 20-sep-2026
   Fuentes: bases oficiales del concurso-oposición I/24 (BOD), página del CEFOT-1
   (ejercito.defensa.gob.es), Guía Docente del Curso de Actualización (CEFOT-1),
   foros (clasespasivas) y normativa vigente (RROO RD 96/2009, LO 8/2014, L 39/2007).
   Reescritos con redacción propia; verificados contra normativa antes de entrar. */
window.FACTS_CABO1B = [
/* ===== El examen (bases I/24 + CEFOT-1) ===== */
["cabo1","B1","El examen","M","Bases I/24","¿Cuántas preguntas tiene el examen de oposición para ascenso a Cabo 1º?","50 preguntas con cuatro alternativas",["40 preguntas con cinco alternativas","60 preguntas con tres alternativas","100 preguntas con cuatro alternativas"],"El examen de Cabo 1º tiene ___ preguntas con cuatro alternativas.","50",["40","60","100"]],
["cabo1","B1","El examen","M","Bases I/24","¿Cómo se reparten las preguntas del examen de Cabo 1º?","35 de Formación Militar y 15 de Formación Sociocultural",["25 y 25","40 y 10","30 y 20"],"Del examen de Cabo 1º, ___ preguntas son de Formación Militar.","35",["25","40","15"]],
["cabo1","B1","El examen","M","CEFOT-1 (I/25)","¿Qué materias se añaden a Formación Militar y Sociocultural en el examen?","Geografía e Historia de España y lengua inglesa básica",["Física y química","Latín y griego","Derecho y economía"],"Al temario del examen se añaden Geografía e Historia de España y lengua ___.","inglesa",["francesa","alemana","italiana"]],
["cabo1","B1","El examen","M","CEFOT-1","¿Cómo se ordena a los opositores de Cabo 1º?","Con la nota de concurso y la de la oposición al 50% cada una",["Solo con la nota del examen","70% concurso y 30% oposición","Por antigüedad en el empleo"],"El ordenamiento final combina nota de concurso y de oposición al ___ cada una.","50%",["30%","70%","100%"]],
["cabo1","B1","El examen","M","Bases I/24","¿Cómo se calcula la nota de corte del examen de Cabo 1º?","La menor entre 5 puntos y la media menos una desviación típica",["Siempre 5 puntos","La media más una desviación típica","El mejor nota del examen"],"La nota de corte será la menor entre 5 y la media menos una desviación ___.","típica",["cuadrática","media","proporcional"]],
["cabo1","B1","El examen","F","CEFOT-1","¿Cuándo se publica en el BOD la convocatoria de Cabo 1º?","En el primer trimestre de cada año",["En julio","En diciembre","Cada dos años"],"La convocatoria de ascenso a Cabo 1º se publica en el ___ trimestre.","primer",["segundo","tercero","cuarto"]],
["cabo1","B1","El examen","M","CEFOT-1","¿De qué dos partes consta el curso de actualización de Cabo 1º?","Una a distancia (CVCDEF) y otra presencial en la Academia de la Especialidad",["Solo un examen final","Dos exámenes escritos","Prácticas en unidad y un examen oral"],"El curso de actualización tiene una parte a distancia y otra ___ en la Academia.","presencial",["opcional","nocturna","voluntaria"]],
["cabo1","B1","El examen","M","CEFOT-1","¿Por dónde se realiza la fase a distancia del curso de actualización?","Mediante el campus virtual CVCDEF",["Por correo postal","En el Rincón de Tropa","Por videoconferencia suelta"],"La fase a distancia del curso se realiza a través del CVC___.","DEF",["EMAD","ET","FAS"]],
["cabo1","B1","El examen","M","Bases I/24","¿Dónde se publican las preguntas y la plantilla de corrección del examen?","En el Rincón de Tropa, preferentemente el mismo día de la prueba",["En el BOE","Por correo certificado","Solo en la academia"],"Las preguntas y plantilla se publican en el Rincón de ___.","Tropa",["Comandancia","Capitanía","Defensa"]],
["cabo1","B1","El examen","M","Bases I/24","¿Puede el opositor llevarse el cuadernillo del examen?","No, y tampoco se le entrega copia",["Sí, al terminar","Solo la mitad","Sí, si paga una tasa"],"Al terminar el examen, el opositor ___ puede llevarse el cuadernillo.","no",["sí","parcialmente","a veces"]],
["cabo1","B1","El examen","M","Bases I/24","¿Qué exigencia física se pide para presentarse a Cabo 1º?","Superar el Test General de la Condición Física con APTO posterior al 1 de enero del año",["Un maratón certificado","La prueba de natación de la Armada","Cualificar en paracaidismo"],"El TGCF con calificación APTO debe estar realizado después del 1 de ___ del año.","enero",["marzo","julio","octubre"]],
["cabo1","B1","El examen","M","OM 12/2019 (bases I/24)","¿Qué tiempo mínimo en el empleo de Cabo se exige?","Tres años de permanencia en el empleo",["Uno","Seis","Diez"],"Se exige un mínimo de ___ años de permanencia en el empleo de Cabo.","3",["1","6","10"]],
["cabo1","B1","El examen","F","Bases I/24","Entre qué números de escalafón podía estar el aspirante en la I/24","Entre el 30003500 y el 31952000, ambos incluidos",["Entre el 1 y el 1000","Entre el 60000000 y el 70000000","Sin límite de escalafón"],"El escalafón del aspirante debía estar entre el 30003500 y el ___.","31952000",["30000000","32000000","31141000"]],
["cabo1","B1","El examen","M","OM 55/2010 (bases I/24)","¿Qué calificación negativa en los IPEC puede excluir del proceso?","Calificación «E» en dos informes sucesivos o tres alternos de los últimos cinco años",["Cualquier «B»","Un informe antiguo de hace diez años","Nunca influyen los IPEC"],"La calificación «E» en dos informes sucesivos o tres ___ puede excluir.","alternos",["aleatorios","parciales","extras"]],
["cabo1","B1","El examen","M","Bases I/24","¿En qué situaciones administrativas se puede estar para presentarse?","Servicio activo, servicios especiales o excedencia voluntaria",["Solo en reserva","Solo en retiro","Cualquier situación, incluso suspendido"],"Se puede presentar el personal en activo, servicios especiales o excedencia ___.","voluntaria",["forzosa","penal","temporal"]],
["cabo1","B1","El examen","F","CEFOT-1","¿Qué departamento del CEFOT-1 organiza el examen?","El Departamento de Ciencia y Técnica Militar",["El de Recursos Humanos","El de Intervención","El de Logística"],"El examen lo organiza el Departamento de Ciencia y Técnica ___ del CEFOT-1.","Militar",["Económica","Jurídica","Deportiva"]],
/* ===== Curso de actualización (guía docente) ===== */
["cabo1","B1","El examen","M","Guía docente del curso","¿Cómo se calcula la nota final de un módulo del curso (FC)?","FC = (NFD + 9·NEX) / 10, con mínimo 5 para ser apto",["FC = (NFD + NEX) / 2","FC = NFD · NEX","FC = NEX − NFD"],"La nota del módulo es FC = (NFD + 9·NEX) / ___ y se exige un 5 mínimo.","10",["2","5","9"]],
["cabo1","B1","El examen","M","Guía docente del curso","¿Qué es la NFD de la fórmula del módulo?","La nota de la fase a distancia: la media de las heteroevaluaciones",["La nota del examen físico","La nota más alta obtenida","Una nota de conducta"],"La NFD es la media de las ___ de la fase a distancia.","heteroevaluaciones",["autoevaluaciones","cointerpretaciones","prorrogas"]],
["cabo1","B1","Seguridad","M","Guía docente del curso","¿Qué cometidos básicos de la Policía Militar debe conocer el aspirante?","El control de tráfico y el apoyo al movimiento",["Las inspecciones fiscales","La ciberseguridad de redes","La vigilancia aduanera"],"Como cometidos de la Policía Militar: el control de ___ y el apoyo al movimiento.","tráfico",["equipos","armas","documentos"]],
["cabo1","B1","Seguridad","M","Guía docente del curso","¿Cuáles son los grados de clasificación de la información militar?","Secreto, reservado, confidencial y difusión limitada",["Público, privado y compartido","Alto, medio y bajo","Nivel 1, 2 y 3"],"Los grados de clasificación de la información: secreto, reservado, confidencial y difusión ___.","limitada",["total","abierta","libre"]],
["cabo1","B1","Topografía","M","Guía docente del curso","¿Qué navegación debe dominar el alumno del curso?","Navegar entre puntos del terreno con mapas, brújula o GPS, de día y de noche",["Solo con GPS de día","Solo con mapas digitales","Sin orientación nocturna"],"Deberá navegar con mapas, brújula o GPS tanto en arco diurno como ___.","nocturno",["estival","solitario","aéreo"]],
/* ===== Mando y liderazgo ===== */
["cabo1","B1","Mando y liderazgo","M","Formación militar","¿Cuáles son los tres estilos clásicos de mando?","Autocrático, participativo y delegador",["Militar, civil y mixto","Duro, blando y neutro","Central, provincial y local"],"Los estilos de mando: autocrático, ___ y delegador.","participativo",["vacacional","aleatorio","silencioso"]],
["cabo1","B1","Mando y liderazgo","M","Formación militar","¿Quién es el primer mando directo del soldado en la cadena?","El cabo",["El sargento","El capitán","El teniente"],"El primer mando directo del soldado es el ___.","cabo",["brigada","alférez","coronel"]],
["cabo1","B1","Mando y liderazgo","M","Formación militar","¿Qué es el liderazgo militar?","La capacidad de influir en las personas para alcanzar los objetivos",["Dar la máxima voz de mando","Sancionar con rapidez","Imponer turnos de guardia"],"El liderazgo es la capacidad de ___ en las personas para lograr los objetivos.","influir",["incluir","intuir","insistir"]],
["cabo1","B1","Mando y liderazgo","M","RROO","¿Cómo debe ejercer el mando para mantener la moral de la unidad?","Dando ejemplo, cuidando a sus subordinados y exigiendo con justicia",["Ignorando los problemas","Solo con sanciones","Delegando en nadie"],"El mando mantiene la moral dando ___, cuidando a los suyos y exigiendo con justicia.","ejemplo",["miedo","vergüenza","gritos"]],
["cabo1","B1","Mando y liderazgo","M","RROO art. 48","¿Qué límite tiene la obediencia debida?","No obliga a obedecer órdenes constitutivas de delito",["Se suspende en maniobras","Caduca a los dos años","No existe ningún límite"],"Las órdenes constitutivas de ___ no obligan a obedecerlas.","delito",["servicio","guardia","instrucción"]],
["cabo1","B1","Mando y liderazgo","M","Formación militar","¿De qué responde el mando respecto a las órdenes que da?","De su legalidad, oportunidad y ejecución",["Solo de su redacción","De nada si firma otro","Solo de su formato"],"El mando responde de la legalidad, oportunidad y ___ de sus órdenes.","ejecución",["estética","longitud","firma"]],
/* ===== Técnicas de mando ===== */
["cabo1","B2","Técnicas de mando","M","Formación militar","¿Cómo debe ser una orden militar?","Clara, precisa y completa",["Larga y detallada hasta el infinito","Opcional y sugerida","Secreta incluso para quien la ejecuta"],"Una orden militar debe ser clara, ___ y completa.","precisa",["cariñosa","poética","extensa"]],
["cabo1","B2","Técnicas de mando","M","Formación militar","¿Cuáles son los pasos clásicos para instruir una destreza?","Explicar, demostrar, ejecutar y corregir",["Aprobar, promulgar y archivar","Omitir, suplicar y despedir","Contar, cantar y bailar"],"Para instruir: explicar, demostrar, ___ y corregir.","ejecutar",["descansar","olvidar","celebrar"]],
/* ===== Régimen disciplinario ===== */
["cabo1","B1","Régimen disciplinario","M","LO 8/2014","En cuánto tiempo prescriben las faltas muy graves","A los tres años",["A los seis meses","A los diez años","Nunca prescriben"],"Las faltas muy graves prescriben a los ___ años.","3",["6","10","15"]],
["cabo1","B1","Régimen disciplinario","M","LO 8/2014","En cuánto tiempo prescriben las faltas graves y las leves","Graves: dos años; leves: un año",["Graves: un mes; leves: una semana","Ambas a los cinco años","Graves: nunca; leves: diez años"],"Las faltas graves prescriben a los ___ años y las leves a uno.","2",["3","5","10"]],
["cabo1","B1","Régimen disciplinario","M","LO 8/2014","¿Qué clases de arresto prevé la LO 8/2014?","Arresto domiciliario y arresto de actividad",["Arresto electorales y fiscales","Prisión y destierro","Multas fijas y variables"],"La LO 8/2014 prevé el arresto domiciliario y el arresto de ___.","actividad",["verano","fuego","primavera"]],
["cabo1","B1","Régimen disciplinario","M","LO 8/2014","¿Por qué faltas procede la amonestación?","Por las faltas leves",["Por las muy graves","Por ninguna","Solo por delitos"],"La amonestación es la sanción típica de las faltas ___.","leves",["muy graves","graves","terroríficas"]],
/* ===== Documentación / Administración ===== */
["cabo1","B1","Documentación","M","Administración militar","¿Qué refleja la hoja de servicios del militar?","Sus destinos, empleos, situaciones y méritos a lo largo de la carrera",["Sus comidas del comedor","Las películas vistas en el cuartel","Solo su DNI"],"La hoja de servicios refleja destinos, empleos, situaciones y ___ de la carrera.","méritos",["menús","multas","vistas"]],
["cabo1","B1","Documentación","F","Administración militar","¿Qué es el Rincón de Tropa?","El portal del Ejército de Tierra para el personal de tropa",["Una tienda de ultramarinos","Un rincón del comedor","Un videojuego"],"El Rincón de ___ es el portal del ET para el personal de tropa.","Tropa",["Mando","Intendencia","Mañana"]],
["cabo1","B2","Administración","M","L 39/2007","¿Cuántos días naturales de permiso anual retribuido tienen los militares profesionales?","30 días naturales",["15 días","45 días","90 días"],"El permiso anual retribuido son ___ días naturales.","30",["15","45","60"]],
["cabo1","B2","Administración","M","Administración militar","¿Dónde se publican los ascensos y las resoluciones que afectan al personal?","En el Boletín Oficial de Defensa (BOD)",["En el BOE siempre","En la radio del cuartel","En carteles de bar"],"Los ascensos y resoluciones se publican en el Boletín Oficial de ___.","Defensa",["España","Tierra","Comercio"]],
/* ===== Logística ===== */
["cabo1","B1","Logística","F","Clases de abastecimiento","¿Qué comprende la Clase I de abastecimiento?","Víveres y agua",["Munición","Combustible","Medicinas"],"La Clase I de abastecimiento comprende víveres y ___.","agua",["munición","gasolina","vendas"]],
["cabo1","B1","Logística","F","Clases de abastecimiento","¿Qué comprende la Clase III de abastecimiento?","Combustibles y lubricantes",["Víveres","Vestuario","Cartografía"],"La Clase III comprende combustibles y ___.","lubricantes",["libretas","capotes","mapas"]],
["cabo1","B1","Logística","F","Clases de abastecimiento","¿Qué comprende la Clase V de abastecimiento?","Munición",["Víveres","Combustible","Equipo de zapador"],"La Clase V de abastecimiento es la ___","munición",["ropa","gasolina","comida"]],
["cabo1","B1","Logística","F","Clases de abastecimiento","¿Qué comprende la Clase VIII de abastecimiento?","Material sanitario",["Material de ingenieros","Munición de guerra","Agua potable"],"La Clase VIII comprende el material ___","sanitario",["deportivo","fotográfico","musical"]],
["cabo1","B1","Logística","M","Clases de abastecimiento","¿Qué comprende la Clase II de abastecimiento?","Vestuario y equipo individual",["Vehículos nuevos","Víveres enlatados","Vales de combustible"],"La Clase II comprende vestuario y ___ individual.","equipo",["adiestramiento","combustible","munición"]],
/* ===== Seguridad ===== */
["cabo1","B1","Seguridad","M","Normas de seguridad con armas","¿Cuál es la regla de oro al tratar cualquier arma?","Considerarla siempre cargada",["Considerarla siempre descargada","Mirar al cañón por diversión","Pulsar el gatillo para vaciarla"],"Regla de oro: toda arma se considera siempre ___","cargada",["descargada","rota","ajena"]],
["cabo1","B1","Seguridad","M","Normas de seguridad con armas","¿Hacia dónde nunca se dirige el cañón de un arma?","Hacia personas, salvo uso legítimo del arma",["Hacia el objetivo en tiro","Hacia arriba nunca","Hacia el suelo siempre"],"Nunca se dirige el cañón hacia ___ salvo uso legítimo.","personas",["mapas","banderas","vehículos propios"]],
["cabo1","B1","Seguridad","M","Seguridad en las FAS","¿Quién es el responsable de la seguridad de la unidad?","El jefe de la unidad",["El más antiguo de la guardia","El delegado de personal","El intendente"],"El responsable de la seguridad de la unidad es el jefe de la ___","unidad",["guardia","instalación menor","sección rival"]],
["cabo1","B1","Seguridad","M","Contramedidas","¿Qué se hace ante un artefacto explosivo improvisado sospechoso?","No manipularlo, alejarse, avisar y proteger",["Abrirlo para ver su contenido","Cargarlo en el vehículo","Hacerle fotografías de cerca"],"Ante un IED sospechoso: no manipular, ___ y avisar.","alejarse",["examinarlo","desarmarlo","enviarlo"]],
/* ===== Tiro ===== */
["cabo1","B1","Tiro","M","Balística","¿Qué tres fases tiene la balística?","Interior, exterior y de efectos",["Antes, durante y después","Superior, media e inferior","Inicial, media y final"],"Las tres fases de la balística: interior, ___ y de efectos.","exterior",["superior","profunda","planetaria"]],
["cabo1","B1","Tiro","M","Balística","¿Dónde se mide la velocidad inicial del proyectil?","En la boca del cañón",["En el objetivo","A mitad de trayectoria","En la recámara"],"La velocidad inicial se mide en la boca del ___.","cañón",["objetivo","alza","cargador"]],
["cabo1","B1","Tiro","M","Tiro","¿Qué corrige el alza del arma?","La caída del proyectil sobre la distancia",["El retroceso del arma","El ruido del disparo","El peso del cargador"],"El alza compensa la ___ del proyectil con la distancia.","caída",["velocidad","rotación","masa"]],
["cabo1","B1","Tiro","M","Tiro","¿Cómo afecta el viento al disparo?","Desvía el proyectil: hay que apuntar contrarestándolo",["No afecta nunca","Solo en tiros nocturnos","Solo dentro del cañón"],"El viento ___ el proyectil y obliga a corregir el apuntado.","desvía",["acelera siempre","detiene","enfría"]],
["cabo1","B1","Tiro","M","Secuencia del disparo","¿Cuál es la secuencia clásica del disparo?","Respirar, apuntar, retener la respiración y apretar suavemente",["Gritar, cerrar los ojos y tirar fuerte","Apretar dos veces seguidas","Sostener con una mano y soltar"],"Secuencia del disparo: respirar, apuntar, retener y ___ suavemente.","apretar",["gritar","golpear","soltar"]],
/* ===== Topografía ===== */
["cabo1","B1","Topografía","M","Sistema UTM","¿Cómo se miden las coordenadas UTM?","La X hacia el Este y la Y hacia el Norte",["La X al Sur y la Y al Oeste","Ambas al azar","Solo en grados sexagesimales"],"En UTM, la X mide hacia el Este y la ___ hacia el Norte.","Y",["Z","W","V"]],
["cabo1","B1","Topografía","M","Orientación","¿Qué es el acimut de un punto?","El ángulo desde el Norte medido en sentido horario",["La distancia entre dos puntos","La altura sobre el nivel del mar","El ángulo contrario a las agujas"],"El acimut es el ángulo desde el Norte medido en sentido ___","horario",["antihorario","aleatorio","vertical"]],
["cabo1","B1","Topografía","M","Orientación","¿Hacia dónde apunta la aguja de la brújula?","Al Norte magnético",["Al Norte geográfico exacto","Al Sur siempre","A la derecha del mapa"],"La aguja imantada de la brújula apunta al Norte ___","magnético",["geográfico exacto","celestial","de la brújula"]],
["cabo1","B1","Topografía","M","Orientación","¿Qué es la declinación magnética?","La diferencia entre el Norte geográfico y el Norte magnético",["Una falla de la brújula","La inclinación del mapa","El ángulo del sol"],"La declinación magnética es la diferencia entre Norte geográfico y Norte ___.","magnético",["verdadero","local","auxiliar"]],
["cabo1","B1","Topografía","M","GPS","¿Cuántos satélites necesita el GPS para una posición tridimensional?","Cuatro satélites como mínimo",["Uno solo","Dos","Veinticuatro a la vez"],"Para fijar posición 3D, el GPS necesita mínimo ___ satélites.","4",["1","2","12"]],
/* ===== Organización ===== */
["cabo1","B1","Organización","F","CEFOT-1","¿Dónde está el CEFOT nº 1?","En Cáceres",["En Toledo","En Madrid","En Barcelona"],"El Centro de Formación de Tropa nº 1 está en ___","Cáceres",["Toledo","Valladolid","Zaragoza"]],
["cabo1","B1","Organización","M","Curso de actualización","¿Dónde se realiza la fase presencial del curso de actualización?","En la Academia de la Especialidad fundamental de cada uno",["En el propio cuartel","En casa, por Internet","En el Rincón de Tropa"],"La fase presencial se completa en la ___ de la Especialidad correspondiente.","Academia",["Comandancia","Delegación","Oficina"]],
/* ===== Inglés militar ===== */
["cabo1","B2","Inglés","F","Inglés militar","¿Cómo se dice «sargento» en inglés?","Sergeant",["Sheriff","Sailor","Second lieutenant"],"«Sargento» en inglés se escribe ___","Sergeant",["Sheriff","Sergeant-major none","Servant"]],
["cabo1","B2","Inglés","F","Inglés militar","¿Cómo se dice «cabo» (empleo) en inglés?","Corporal",["Capital","Corporation","Colonel"],"«Cabo» en inglés se dice ___","Corporal",["Capital","Colonel","Captain"]],
["cabo1","B2","Inglés","F","Inglés militar","¿Qué significa «platoon»?","Pelotón",["Escuadra","Compañía","Batallón"],"«Platoon» significa ___","pelotón",["escuadra","compañía","brigada"]],
["cabo1","B2","Inglés","F","Inglés militar","¿Qué significa «rifle»?","Fusil",["Revólver","Bayoneta","Granada"],"«Rifle» significa ___","fusil",["pistola","cuchillo","escudo"]],
["cabo1","B2","Inglés","F","Inglés militar","¿Qué significa «ammunition»?","Munición",["Uniforme","Equipo","Ración"],"«Ammunition» significa ___","munición",["mochila","botas","casco"]],
["cabo1","B2","Inglés","M","Inglés militar","¿Qué orden es «cease fire»?","Alto el fuego",["Fuego a discreción","Carguen","Fuego de cobertura"],"«Cease fire» significa ___","alto el fuego",["fuego rápido","apoyen el fuego","recarguen"]],
["cabo1","B2","Inglés","F","Inglés militar","¿Qué significa «wounded»?","Herido",["Perdido","Enfermo","Capturado"],"«Wounded» significa ___","herido",["perdido","sano","ascendido"]],
["cabo1","B2","Inglés","F","Inglés militar","¿Qué significa «target»?","Objetivo",["Táctica","Trinchera","Torreta"],"«Target» significa ___","objetivo",["trinchera","tanque","tender"]]
];
