/* A LA ORDEN — Lote 9 · PERMANENCIA II (~70 hechos) · rascado 20-sep-2026
   Fuentes: convocatoria Permanencia 2026 despiezada por webs expertas
   (permanenciayague.com, davante.es, formacioneureka.com), página oficial del
   CEFOT-1 y normativa vigente (CE, LO 5/2005, L 36/2015, L 39/2007, L 8/2006,
   LO 9/2011). Corrige el ref error anterior: la LODN vigente es la LO 5/2005. */
window.FACTS_PERM2 = [
/* ===== El examen ===== */
["perm","B1","El examen","M","Convocatoria 2026","¿Cuál es la puntuación máxima de la prueba de conocimientos de permanencia?","100 puntos",["50 puntos","200 puntos","10 puntos"],"La prueba de conocimientos se puntúa sobre ___ puntos.","100",["50","200","70"]],
["perm","B1","El examen","M","Convocatoria 2026","¿Cómo está estructurado el temario del examen de permanencia?","21 temas agrupados en 3 bloques",["10 temas en 2 bloques","50 temas sin agrupar","7 temas en 7 bloques"],"El temario son ___ temas agrupados en 3 bloques.","21",["10","15","30"]],
["perm","B1","El examen","M","Convocatoria 2026","¿Qué peso tiene la fase de oposición en la nota final de permanencia?","El 50%",["El 100%","El 30%","Ninguno, solo cuenta el concurso"],"La fase de oposición supone el ___ de la puntuación final.","50%",["30%","70%","100%"]],
["perm","B1","El examen","M","CEFOT-1","¿Cómo se asignan las plazas de permanencia?","Por riguroso orden de la nota final (concurso + oposición)",["Por sorteo entre aptos","Por antigüedad","Por orden alfabético"],"Las plazas se asignan por riguroso ___ de la nota final.","orden",["sorteo","voto","método"]],
/* ===== Convocatoria 2026 ===== */
["perm","B3","Convocatoria","F","Convocatoria 2026","¿Cuál fue el plazo de solicitudes de la permanencia 2026?","Del 18 de junio al 7 de julio de 2026",["Del 1 al 31 de enero","Todo el verano","Del 7 al 18 de junio al revés"],"Las solicitudes de permanencia 2026: del 18 de ___ al 7 de julio.","junio",["enero","marzo","octubre"]],
["perm","B3","Convocatoria","M","Convocatoria 2026","¿Hasta cuándo se pudieron acreditar méritos en la permanencia 2026?","Hasta el 15 de julio de 2026",["Hasta el 31 de diciembre","Un año después","Nunca, se autocertifican"],"Los méritos se acreditan hasta el 15 de ___ de 2026.","julio",["enero","junio","septiembre"]],
["perm","B3","Convocatoria","M","Convocatoria 2026","¿Cómo se pagan las tasas del proceso de permanencia?","Con el modelo 790, pago mediante IPS",["En efectivo en el cuartel","Por bizum al ministerio","Sin ningún pago"],"Las tasas se pagan con el modelo ___ mediante IPS.","790",["690","100","999"]],
["perm","B3","Convocatoria","F","Convocatoria 2026","¿Desde cuándo surte efectos la condición de militar de carrera en la 2026?","Desde el 31 de diciembre de 2026",["Desde el día del examen","Desde el 1 de enero de 2027","Desde la publicación en el BOE"],"La condición de militar de carrera tendrá efectos desde el 31 de ___ de 2026.","diciembre",["enero","junio","marzo"]],
["perm","B3","Convocatoria","F","Convocatoria 2026 (Tierra)","¿Cuántas plazas ofertó la permanencia 2026 para Música del ET?","4 plazas",["40 plazas","Ninguna","100 plazas"],"Para Música del ET se ofertaron ___ plazas en la permanencia 2026.","4",["14","24","40"]],
/* ===== Fase de concurso ===== */
["perm","B2","Concurso","M","Bases permanencia","¿Cuál es el máximo de puntos por méritos profesionales?","40 puntos",["10 puntos","25 puntos","60 puntos"],"Los méritos profesionales se valoran hasta ___ puntos.","40",["20","25","50"]],
["perm","B2","Concurso","M","Bases permanencia","¿Cuál es el máximo de puntos por méritos académicos?","20 puntos",["40 puntos","5 puntos","30 puntos"],"Los méritos académicos se valoran hasta ___ puntos.","20",["10","40","50"]],
["perm","B2","Concurso","M","Bases permanencia","¿Cuál es el máximo de puntos por los informes de calificación?","25 puntos",["15 puntos","40 puntos","5 puntos"],"Los informes personales de calificación puntúan hasta ___ puntos.","25",["15","40","60"]],
["perm","B2","Concurso","M","Bases permanencia","¿Cuál es el máximo de puntos por aptitud psicofísica?","15 puntos",["25 puntos","50 puntos","2 puntos"],"La aptitud psicofísica se valora hasta ___ puntos.","15",["5","25","40"]],
["perm","B2","Concurso","M","Bases permanencia","¿Qué IPEC se tienen en cuenta para la nota de concurso?","La media aritmética de los 5 últimos",["El mejor de todos","Los 15 últimos","Solo el último"],"Se envía la media aritmética de los ___ últimos IPEC.","5",["3","8","10"]],
["perm","B2","Concurso","M","Bases permanencia","¿Qué tiempo mínimo de servicios se exige para la permanencia?","14 años, con los últimos 5 en el mismo Ejército",["2 años sin más","5 años totales","30 años"],"Se exigen ___ años de servicios, los últimos 5 en el mismo Ejército.","14",["4","10","20"]],
["perm","B2","Concurso","M","Bases permanencia","¿Qué titulación mínima se exige para la permanencia?","Técnico de grado medio del sistema educativo o equivalente",["Doctorado","Certificado escolar","Ninguna"],"La titulación mínima es ___ de grado medio o equivalente.","Técnico",["Licenciado","Maestro","Ayudante"]],
["perm","B2","Concurso","M","Bases permanencia","¿En qué situaciones administrativas se puede acceder a permanencia?","Servicio activo o excedencia",["Solo en retiro","Solo en reserva retirada","Suspensión de funciones"],"Se puede solicitar estando en servicio activo o en ___","excedencia",["reserva","prisión","vacaciones"]],
["perm","B2","Concurso","M","Bases permanencia","¿Qué compromiso debe tener suscrito el aspirante a permanencia?","Un compromiso de larga duración con las Fuerzas Armadas",["Un contrato de una campaña","Ninguno","Un préstamo militar"],"El aspirante debe tener suscrito un compromiso de larga ___ con las FAS.","duración",["distancia","guardia","lista"]],
["perm","B2","Concurso","M","Bases permanencia","¿Qué evaluación previa se exige para la permanencia?","Haber sido evaluado favorablemente para adquirir la condición de militar de carrera",["Un examen de inglés","Una entrevista con el rey","Un test psicológico secreto"],"Hay que haber sido evaluado ___ para adquirir la condición de militar de carrera.","favorablemente",["aleatoriamente","negativamente","nunca"]],
["perm","B2","Concurso","M","Bases permanencia","¿Cuántas veces se puede solicitar el acceso a permanencia?","Máximo 3 convocatorias ordinarias y 2 extraordinarias",["Solo 1 vez en la vida","5 ordinarias y 5 extraordinarias","Sin límite"],"Límite de convocatorias: ___ ordinarias y 2 extraordinarias.","3",["1","5","7"]],
["perm","B2","Concurso","M","Bases permanencia","¿Dónde se realiza el reconocimiento médico para la permanencia?","En los hospitales de la red sanitaria militar",["En cualquier farmacia","Por videollamada","Solo en el médico del cuartel"],"El reconocimiento médico se realiza en hospitales de la red sanitaria ___","militar",["privada","provincial","animal"]],
/* ===== Pruebas físicas ===== */
["perm","B3","Físicas","M","Convocatoria 2026","¿Cuáles son las cuatro pruebas físicas de la permanencia 2026?","Potencia tren superior, plancha isométrica, carrera de 2.000 m y circuito de agilidad-velocidad",["Maratón, natación, esgrima y salto","Press banca, pesas y flexiones","Solo una carrera de 10 km"],"Las pruebas 2026: potencia tren superior, plancha isométrica, carrera de ___ m y circuito de agilidad.","2.000",["500","5.000","42.000"]],
["perm","B3","Físicas","M","Convocatoria 2026","¿Qué prueba mide la resistencia de la zona central (core)?","La plancha isométrica",["La carrera de 2.000 m","El circuito de agilidad","El salto vertical"],"La plancha ___ mide la resistencia de la zona central.","isométrica",["invertida","cantada","doble"]],
["perm","B3","Físicas","M","Convocatoria 2026","¿Desde cuándo son válidas las pruebas físicas periódicas para la 2026?","Las realizadas después del 1 de enero de 2025",["Las de toda la vida","Solo las del mismo mes","Las anteriores a 2020"],"Para la convocatoria 2026 valen las pruebas físicas posteriores al 1-1-___","2025",["2020","2023","2026"]],
["perm","B3","Físicas","M","Convocatoria 2026","¿De qué plazo debe ser el certificado médico para las pruebas físicas?","Expedido en los 30 días naturales anteriores",["De los últimos 5 años","Expedido el mismo día del examen","No hace falta certificado"],"El certificado médico debe ser de los ___ días naturales anteriores a las pruebas.","30",["7","90","365"]],
/* ===== Tropa y marinería / carrera ===== */
["perm","B2","Tropa y marinería","M","Guías permanencia (L 39/2007)","¿A qué edad finaliza la relación de servicios de un militar de tropa sin permanencia?","A los 45 años",["A los 30","A los 61","Nunca termina"],"Sin permanencia, la relación de servicios de tropa finaliza a los ___ años.","45",["30","61","65"]],
["perm","B2","Tropa y marinería","M","Guías permanencia","¿Qué condición otorga superar el proceso de permanencia?","La condición de militar de carrera (relación de servicios de carácter permanente)",["El empleo de sargento","Un ascenso a suboficial","La nacionalidad doble"],"La permanencia otorga la condición de ___ de carrera.","militar",["persona","atleta","familia"]],
["perm","B2","Tropa y marinería","M","Guías permanencia","¿La permanencia es un ascenso de escala?","No: consolida el puesto de trabajo sin cambiar de escala",["Sí, se pasa a suboficial","Sí, a oficial","Depende del examen"],"La permanencia no es un ascenso: ___ el puesto de trabajo.","consolida",["elimina","traslada","subasta"]],
["perm","B2","Tropa y marinería","F","Ley 8/2006","¿Qué ley regula la Tropa y Marinería?","La Ley 8/2006, de 24 de abril",["La LO 9/2011","La L 36/2015","El RD 96/2009"],"La Tropa y Marinería se regula en la Ley ___ de 24 de abril.","8/2006",["9/2011","36/2015","39/2007"]],
["perm","B2","Tropa y marinería","M","Ley 8/2006","¿Cuánto dura el compromiso inicial de un militar de tropa?","Dos años",["Seis meses","Cinco años","Toda la vida"],"El compromiso inicial de tropa es de ___ años.","2",["1","5","10"]],
["perm","B2","Situaciones","M","L 39/2007","¿Qué situaciones administrativas puede tener un militar profesional?","Servicio activo, servicios especiales, reserva, retiro, excedencia y suspensión de funciones",["Activo, jubilado y de fiesta","Solo activo o retirado","Especial, temporal y eterno"],"Situaciones: activo, servicios especiales, reserva, retiro, excedencia y ___ de funciones.","suspensión",["promoción","delegación","firmas"]],
["perm","B2","Carrera militar","F","Evaluación","¿Qué significan las siglas IPEC?","Informe Personal de Calificación",["Índice Profesional de Empleos y Cargos","Instituto Penal de las Cortes","Informe Permanente de Expedientes"],"IPEC significa Informe Personal de ___","Calificación",["Clasificación","Carrera","Comandancia"]],
["perm","B2","Derechos y deberes","M","LO 9/2011","¿Cómo se ejerce el derecho de reunión de los militares?","Fuera de las horas de servicio y comunicándolo previamente",["Dentro de las maniobras","Con arma en mano","Sin ninguna norma"],"El derecho de reunión se ejerce fuera de las horas de servicio y con ___ previa.","comunicación",["amenaza","música","censura"]],
["perm","B1","FAS","F","EMAD","¿Quién dirige el Estado Mayor de la Defensa (EMAD)?","El JEMAD",["El Ministro de Defensa en persona","El Rey","El SACEUR"],"El Estado Mayor de la Defensa lo dirige el ___","JEMAD",["JEME","AJEMA","Ministro"]],
["perm","B1","FAS","F","EMAD","¿Qué siglas corresponden al Almirante Jefe de Estado Mayor de la Armada?","AJEMA",["JEMA","AJEMAR","AJME"],"El Almirante Jefe de Estado Mayor de la Armada es el ___","AJEMA",["JEMA","AJEME","AJAM"]],
/* ===== Constitución ===== */
["perm","B1","Constitución","F","CE","¿En qué fecha se aprobó la Constitución en referéndum?","El 6 de diciembre de 1978",["El 31 de octubre de 1978","El 1 de enero de 1979","El 14 de octubre de 1977"],"La Constitución se aprobó en referéndum el 6 de ___ de 1978.","diciembre",["enero","octubre","junio"]],
["perm","B1","Constitución","M","CE art. 8.1","¿Cuál es la misión de las Fuerzas Armadas según el art. 8.1 de la CE?","Garantizar la soberanía e independencia de España, defender su integridad territorial y el ordenamiento constitucional",["Hacer desfiles en las fiestas","Controlar las elecciones","Educar a la población"],"Las FAS garantizan la soberanía e independencia de España y defienden su ___ territorial.","integridad",["economía","histórica","población"]],
["perm","B1","Constitución","M","CE art. 8.2","¿Qué tipo de ley regula las Fuerzas Armadas?","Una ley orgánica",["Un real decreto simple","Una orden ministerial","Un reglamento europeo"],"Las FAS tienen su regulación básica en una ley ___","orgánica",["municipal","deportiva","provisional"]],
["perm","B1","Constitución","M","CE art. 1.1","¿Cuáles son los valores superiores del ordenamiento jurídico?","Libertad, justicia, igualdad y pluralismo político",["Orden, fuerza, mando y silencio","Sueldo, destino, ascenso y permiso","Fe, esperanza y caridad"],"Valores superiores: libertad, justicia, igualdad y pluralismo ___","político",["religioso","cultural","laboral"]],
["perm","B1","Constitución","M","CE art. 1.2","¿Dónde reside la soberanía nacional?","En el pueblo español",["En el Rey","En el ejército","En el Senado"],"La soberanía nacional reside en el pueblo ___","español",["rey","congreso","ayuntamiento"]],
["perm","B1","Constitución","M","CE art. 4","¿Cómo es la bandera de España?","Roja, gualda y roja",["Azul, blanca y azul","Verde, blanca y roja","Amarilla y morada"],"La bandera de España: roja, ___ y roja.","gualda",["dorada y azul","negra","blanca"]],
/* ===== Defensa Nacional ===== */
["perm","B1","Defensa Nacional","M","LO 5/2005","¿Cuál es la Ley Orgánica de la Defensa Nacional vigente?","La LO 5/2005, de 17 de noviembre",["La Ley 39/2015, de 1 de octubre","La LO 9/2011","La Ley 2/2015"],"La Ley Orgánica de la Defensa Nacional vigente es la LO ___ de 17 de noviembre.","5/2005",["39/2015","8/2014","36/2015"]],
["perm","B1","Defensa Nacional","M","LO 5/2005","¿Quién dirige la política de defensa y dispone de las FAS?","El Presidente del Gobierno",["El Rey","El Ministro de Defensa","El Congreso"],"El Presidente del Gobierno dirige la política de ___ y dispone de las FAS.","defensa",["economía","guerra mundial","policía"]],
["perm","B1","Defensa Nacional","M","LO 5/2005","¿Quién desarrolla y ejecuta la política de defensa?","El Ministro de Defensa, dentro de su ámbito",["El JEME","Las Cortes","El Consejo de Estado"],"El Ministro de Defensa desarrolla y ___ la política de defensa.","ejecuta",["prohíbe","interpreta","vende"]],
["perm","B1","Defensa Nacional","M","CE art. 97","¿Qué atribuye la Constitución al Gobierno en materia de defensa?","Dirigir la política interior y exterior, la administración civil y militar y la defensa",["Solo organizar desfiles","Nombrar a los soldados","Votar las leyes en el Senado"],"El Gobierno dirige la administración civil y ___ y la defensa.","militar",["judicial","eclesiástica","deportiva"]],
/* ===== Seguridad Nacional / ESN ===== */
["perm","B3","Seguridad Nacional","M","L 36/2015","¿Qué ley regula la Seguridad Nacional?","La Ley 36/2015, de 28 de septiembre",["La LO 5/2005","La L 39/2007","El Código Penal"],"La Seguridad Nacional se regula en la Ley ___ de 28 de septiembre.","36/2015",["5/2005","39/2007","8/2006"]],
["perm","B3","Seguridad Nacional","M","L 36/2015","¿Quién preside el Consejo de Seguridad Nacional?","El Presidente del Gobierno",["El Ministro de Defensa","El JEMAD","El Rey"],"El Consejo de Seguridad Nacional lo preside el Presidente del ___","Gobierno",["Congreso","Tribunal","Senado"]],
["perm","B3","ESN","M","ESN 2021","¿Cuál es la Estrategia de Seguridad Nacional vigente?","La de 2021 (sustituyó a la de 2017)",["La de 1999","La de 2011","La de 2035 ya aprobada"],"La Estrategia de Seguridad Nacional vigente es la del año ___","2021",["2017","2010","1999"]],
["perm","B3","Seguridad Nacional","M","L 36/2015","¿La seguridad nacional abarca solo amenazas militares?","No: también amenazas y crisis no militares",["Sí, solo militares","Solo terrorismo","Solo ciberataques"],"La seguridad nacional abarca amenazas y crisis militares y ___","no militares",["de verano","ficticias","de mercado"]],
/* ===== OTAN ===== */
["perm","B3","OTAN","F","OTAN","¿Cuándo y dónde se firmó el Tratado de Washington?","El 4 de abril de 1949",["El 6 de diciembre de 1978","El 28 de septiembre de 2015","El 24 de abril de 2006"],"El Tratado fundacional de la OTAN se firmó el 4 de abril de ___","1949",["1955","1982","1919"]],
["perm","B3","OTAN","F","OTAN","¿Dónde está la sede de la OTAN?","En Bruselas (Bélgica)",["En Nueva York","En París","En Viena"],"La sede de la OTAN está en ___","Bruselas",["Washington","Londres","Ginebra"]],
["perm","B3","OTAN","M","Tratado de Washington","¿Qué establece el artículo 5 del Tratado?","La defensa colectiva: un ataque contra uno es un ataque contra todos",["La libre circulación","El comercio de armas","La moneda común"],"El artículo 5: un ataque contra un aliado es un ataque contra ___","todos",["el Consejo","su capital","nadie"]],
["perm","B3","OTAN","M","OTAN","¿Cuándo se ha invocado el artículo 5?","Solo una vez: tras los atentados del 11-S de 2001",["Nunca","En cada maniobra","Tras la Segunda Guerra Mundial"],"El artículo 5 se ha invocado una sola vez: tras el ___","11-S",["Día D","Brexit","coronavirus"]],
["perm","B3","OTAN","M","OTAN","¿Cuántos países forman la OTAN actualmente?","32 (Suecia fue la 32ª, en 2024)",["12 como en 1949","28","50"],"La OTAN tiene ___ países miembros tras el ingreso de Suecia.","32",["28","12","45"]],
["perm","B3","OTAN","M","España-OTAN","¿Cuándo ingresó España en la OTAN y cuándo ratificó su permanencia?","Ingreso en 1982; referéndum de permanencia en 1986",["Ingreso en 1949","Ingreso en 2000","Nunca ingresó"],"España entró en la OTAN en 1982 y ratificó su permanencia en referéndum en ___","1986",["1982","1949","1998"]],
/* ===== UE / ONU / OSCE / Misiones ===== */
["perm","B3","UE","M","UE","¿Qué es la CEDIS (PESCO)?","La cooperación estructurada permanente de la UE en defensa (2017)",["Un ejército europeo único","Un tratado de comercio","La policía europea"],"La CEDIS/PESCO es la cooperación estructurada ___ de la UE.","permanente",["temporal","secreta","deportiva"]],
["perm","B3","UE","M","UE","¿Qué es la Agencia Europea de Defensa?","La agencia de la UE que apoya el desarrollo de capacidades de defensa",["Una academia de paracaidistas","Un banco militar","Un tribunal internacional"],"La Agencia Europea de Defensa apoya el desarrollo de ___ de defensa.","capacidades",["pensiones","universidades","playas"]],
["perm","B3","UE","M","UE","¿Contra qué opera la operación europea Atalanta?","Contra la piratería en el cuerno de África (Somalia)",["Contra el contrabando de jamón","En el Báltico","Contra la nieve"],"Atalanta es la operación de la UE contra la ___ en Somalia.","piratería",["pesca legal","turismo","cacería"]],
["perm","B3","ONU","F","ONU","¿Cuándo se fundó la ONU?","En 1945, con la Carta de San Francisco",["En 1949","En 1919","En 1957"],"La ONU se fundó en 1945 con la Carta de ___","San Francisco",["París","Yalta","Londres"]],
["perm","B3","ONU","F","ONU","¿Dónde está la sede de la ONU?","En Nueva York",["En Ginebra","En Bruselas","En Viena"],"La sede principal de la ONU está en ___","Nueva York",["Ginebra","Madrid","Tokio"]],
["perm","B3","ONU","M","ONU","¿Cómo es el Consejo de Seguridad de la ONU?","15 miembros: 5 permanentes con derecho de veto",["10 miembros sin veto","Todos los países miembros","5 miembros rotos al azar"],"El Consejo de Seguridad: 15 miembros, ___ permanentes con veto.","5",["3","10","15"]],
["perm","B3","OSCE","F","OSCE","¿Dónde tiene su sede la OSCE?","En Viena",["En Moscú","En Estocolmo","En Milán"],"La OSCE tiene su sede en ___","Viena",["Praga","Berlín","Roma"]],
["perm","B3","OSCE","M","OSCE","¿Cuántos estados participan en la OSCE?","57: la mayor organización regional de seguridad",["12","27","190"],"La OSCE agrupa a ___ estados: la mayor organización regional de seguridad.","57",["27","32","100"]],
["perm","B3","Misiones","M","Misiones exteriores","¿En qué misión de la ONU en Líbano participa España desde 2006?","En la FINUL",["En la KFOR","En la MINUSMA","En la EUTM Somalia"],"España participa desde 2006 en la ___ (Líbano).","FINUL",["KFOR","ATALANTA","OSCE"]]
];
