#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Lote Tema 9 · Transmisiones (PR4G + Mando de Transmisiones/JCISAT de la DEF/708/2020) — 50 preguntas, formato: [dif, pregunta, opciones(correcta=0), explicación, ref]
RAW = [
["F","¿Qué equipo dota al Ejército de Tierra de la Red Radio de Combate (RRC) en VHF?",["El radioteléfono táctico PR4G","El equipo AN/PRC-77","El radioenlace troposférico","El equipo HF de onda corta SATCOM"],"El PR4G (Programa Radio de 4ª Generación) es la base de la RRC: comunicaciones protegidas y seguras en fonía y datos para las pequeñas unidades.","Sistema PR4G · ejercito.defensa.gob.es"],
["F","La gama de frecuencia del radioteléfono PR4G es:",["30-88 MHz (VHF)","118-137 MHz (aérea)","225-400 MHz (UHF)","1,5-30 MHz (HF)"],"Gama literal de la ficha oficial del Ejército: 30-88 MHz, banda VHF de la red radio de combate.","Sistema PR4G · ficha oficial ET"],
["F","El número de canales posibles del PR4G es:",["2.320","230","1.050","76"],"Ficha oficial: 2.320 canales posibles (la gama 30-88 MHz con canalización de 25 kHz lo permite). No confundir con la potencia (0,4-4 W) ni el alcance.","Sistema PR4G · ficha oficial ET"],
["F","La potencia de emisión del PR4G (versiones portátil/vehicular básicas) es de:",["0,4 a 4 W","100 a 200 W","25 a 50 W","0,1 a 1 W"],"Ficha oficial: potencia de emisión de 0,4 a 4 W. La versión espaldera (manpack) de la V3 alcanza además los 10 W.","Sistema PR4G · ficha oficial ET · TFG DAC Transmisiones"],
["M","El alcance típico del PR4G (con antenas de varilla o fleje) es:",["8 a 10 km","50 a 80 km","1 a 2 km","100 km"],"Ficha oficial (RAAA 94): alcance de 8 a 10 km con las antenas de varilla de 2,6 m o fleje de 1,5 m; altura máxima de funcionamiento 4.500 m.","Sistema PR4G · ficha oficial ET"],
["M","La velocidad del salto de frecuencia del PR4G es de:",["200 a 300 saltos por segundo","10 a 20 saltos por segundo","1.000 saltos por segundo","5 saltos por segundo"],"Ficha oficial: el equipo salta de frecuencia entre 200 y 300 veces por segundo (claves TRANSEC), dejando inútil el intento de localización enemiga.","Sistema PR4G · ficha oficial ET"],
["F","La transferencia de datos del PR4G llega hasta:",["38.400 bits/s","300 bits/s","1.024 bits/s","2.400 bits/s"],"Ficha oficial: transferencia de datos de 38.400 bits/s (conseguido con la V3; las velocidades 9.600/19.200/38.400 bps).","Sistema PR4G · ficha oficial ET"],
["M","El PR4G es compatible con la transmisión digital DELTA:",["Sí, según el estándar EUROCOM D/1, a 16 kbits/s","No, es totalmente analógico","Solo por cable","Solo en modo satélite"],"Ficha oficial: transmisión digital DELTA (EUROCOM D/1) a 16 kbits/s — interoperabilidad con los estándares de la red radio de combate.","Sistema PR4G · ficha oficial ET"],
["M","Entre las protecciones del PR4G figuran:",["Borrado de emergencia, TEMPEST (AMSG-784) y protección contra el pulso electromagnético (EMP)","Ninguna: es un equipo sin protecciones","Solo una funda impermeable","Blindaje balístico del equipo"],"Ficha oficial: «otros»: borrado de emergencia, TEMPEST AMSG-784 y protección con EMP. Trío de protecciones que cae tal cual.","Sistema PR4G · ficha oficial ET"],
["M","Los MODOS DE TRABAJO del PR4G según la ficha oficial son:",["Analógica (sin protector COMSEC) y digital (con protector COMSEC)","Solo analógica","Únicamente digital IP","Satelital y troposférica"],"Ficha oficial literal: analógica sin protector COMSEC y digital con protector COMSEC. La voz protegida exige el protector.","Sistema PR4G · ficha oficial ET"],
["D","Para transmitir en DIGITAL protegido, el PR4G necesita:",["El protector COMSEC instalado (sin él solo trabaja en analógico)","Cambiar la antena a fleje","Subir la potencia a 10 W","Un segundo operador"],"Ficha oficial literal: modo analógico SIN protector COMSEC / modo digital CON protector COMSEC. Sin protector, ni digital ni voz protegida.","Sistema PR4G · ficha oficial ET · caso"],
["D","En el PR4G, la protección del CIFRADO corre a cargo de las claves:",["COMSEC","TRANSEC","GPS","DELTA"],"COMSEC = cifrado (comunicaciones seguras); TRANSEC = salto de frecuencia (protección frente a la guerra electrónica). Las dos claves del sistema.","Sistema PR4G · TFG DAC Transmisiones · caso"],
["D","En el PR4G, la protección frente a la localización por guerra electrónica (el SALTO de frecuencia) corresponde a las claves:",["TRANSEC","COMSEC","AMSG","EUROCOM"],"Al revés que la anterior: TRANSEC protege el modo de transmisión (salto); COMSEC, el contenido (cifrado). Pareja de conceptos que el examinador cruza.","Sistema PR4G · TFG DAC Transmisiones · caso"],
["M","¿Cuál de estos es un MODO de trabajo del PR4G?",["SFR (salto de frecuencia)","OMEGA","GSM militar","SWAN"],"Modos del PR4G: SFR (salto de frecuencia), BCL (búsqueda de canal libre), MIX (mixto), FD (frecuencia digital) y FFC (frecuencia fija de canal).","Sistema PR4G · TFG DAC Transmisiones"],
["M","El modo BCL del PR4G consiste en:",["La búsqueda de canal libre: recorre los canales de una misma frecuencia hasta encontrar el que no está siendo interferido","El borrado de claves en emergencia","La baliza de emergencia de la radio","El bloqueo de la emisora"],"BCL = Búsqueda de Canal Libre: útil cuando el enemigo interfiere una frecuencia; la radio salta al canal limpio.","Sistema PR4G · TFG DAC Transmisiones"],
["M","Entre los servicios del PR4G figuran:",["Llamada selectiva, llamada prioritaria, alarma, vigilancia de canal y prueba de enlace","Difusión de televisión","Navegación inercial","Traducción automática de idiomas"],"Servicios literales del sistema (fichas y fuentes del programa): selectiva, prioritaria, alarma, vigilancia de canal y prueba de enlace.","Sistema PR4G"],
["D","Una unidad debe enviar simultáneamente voz y datos (posición, mensajes) con radios PR4G V3. El modo adecuado es:",["IP/MUX, que permite la transmisión de voz y datos a la vez","SFR exclusivamente","FFC en analógico","Ninguno: la V3 solo transmite voz"],"IP/SAP es solo datos; IP/MUX permite voz y datos simultáneos. Ojo: estas funcionalidades de la V3 no son compatibles con las versiones anteriores.","Sistema PR4G V3 · TFG DAC Transmisiones · caso"],
["D","El modo IP/SAP del PR4G V3 está pensado para:",["Transmitir exclusivamente DATOS","Transmitir solo voz","Transmitir televisión táctica","Apagar la radio remotamente"],"SAP = solo datos; MUX = voz + datos. Diferencia fina y de examen.","Sistema PR4G V3 · TFG DAC Transmisiones"],
["M","La primera versión del PR4G (V1) que llegó en 1992 incorporó el salto tecnológico de:",["La protección de las comunicaciones con salto de frecuencia y cifrado, y software actualizable","La pantalla táctil en color","La conexión WiFi","El piloto automático"],"La V1 sustituyó a los PRC-77 analógicos (sin datos ni protección) aportando salto de frecuencia, cifrado y datos, con software actualizable.","Sistema PR4G · historia del programa"],
["F","El equipo analógico de la red radio de combate que el PR4G vino a sustituir fue:",["El AN/PRC-77 estadounidense","El SCR-536 alemán","El equipo CLANSMAN inglés","El Radio Sonde francés"],"El PRC-77 era analógico de frecuencia fija, solo voz, sin protección: la referencia histórica del cambio de era.","Sistema PR4G · historia del programa"],
["M","Las radios PR4G están fabricadas (bajo licencia, en España) por:",["Amper, hoy integrada en Thales España","Siemens España","Telefónica Investigación","Indra en exclusiva mundial"],"Acuerdo marco Ministerio de Defensa-Amper (hoy Thales España) con tecnología Thales; primera entrega en 1992 y miles de radios suministradas al ET.","Sistema PR4G · historia del programa"],
["M","La V3 del PR4G (aprobada en 2007, «f@snet») incorporó entre otras novedades:",["Receptor GPS, controlador IP, mayor velocidad (cuatro veces la anterior), vocoder de última generación y la mitad de volumen y peso","Motor diésel","Cañón de 25 mm","Panel solar"],"La V3: GPS integrado (no compatible con versiones anteriores), IP nativo, velocidad multiplicada por 4 y menos volumen/peso.","Sistema PR4G V3"],
["D","La versión espaldera (manpack) del PR4G V3 alcanza una potencia de:",["10 W (además de las posiciones de 0,5 y 5 W)","100 W","40 W","25 W"],"La V3 manpack añade 10 W de potencia a las posiciones heredadas de 0,5 y 5 W: alcance extra en combate.","Sistema PR4G V3 · TFG DAC Transmisiones · caso"],
["M","El receptor GPS integrado en la PR4G V3:",["Permite el establecimiento automático de la posición de la radio, pero no es compatible con las versiones anteriores","Elimina la necesidad de cifrado","Es compatible con las radios V1 y V2","Solo funciona enuartel"],"La posición automática de la radio (con evolución futura a Galileo) — pero exige V3: incompatibilidad con V1/V2 que cae como trampa.","Sistema PR4G V3"],
["M","La estación de transmisiones vehicular Mercurio 2000:",["Se basa en un vehículo con dos radioteléfonos 9210 (V3) incorporados","Es un satélite militar","Es un repetidor fijo de montaña","Es un dron repetidor"],"El Mercurio 2000 es la estación de radio en base a vehículo (dos RT 9210 V3) con la que se opera en la sección de radio de las compañías de transmisiones.","Sistema PR4G · estación Mercurio 2000"],
["M","Los modelos del PR4G para las versiones V1/V2 y para la V3 son, respectivamente:",["RT-9200 y RT-9210","RT-8500 y RT-8600","PRC-77 y PRC-78","RT-100 y RT-200"],"Denominaciones de los equipos: RT-9200 (V1/V2) y RT-9210 (V3). Números que se lian en examen.","Sistema PR4G · modelos"],
["D","El PR4G da servicio de comunicaciones a las pequeñas unidades:",["Hasta nivel BATALLÓN, asegurando la transferencia segura de órdenes e informaciones vía radio","Únicamente al mando del Ejército","Solo al nivel división","Ninguna unidad pequeña lo usa"],"La RRC con PR4G da servicio a las pequeñas unidades hasta nivel batallón, incluso en ambientes hostiles de guerra electrónica.","Sistema PR4G · RRC · caso"],
["F","La Red Radio de Combate (RRC/CRN) se caracteriza por:",["Comunicaciones protegidas y seguras tanto en fonía como en datos","Solo datos sin protección","Solo voz en claro","Comunicaciones civiles de GSM"],"CRN (Combat Radio Net): la red de las pequeñas unidades con protección en voz (COMSEC) y modo de transmisión (TRANSEC).","Sistema PR4G · RRC"],
["M","El PR4G está presente como dotación de comunicaciones en los sistemas de armas del ET, entre ellos:",["Leopardo, Pizarro y Tigre","Ninguno","Únicamente camiones logísticos","Solo el material de zapadores"],"La radio combate en los principales programas: Leopardo, Pizarro, Tigre… y también dota a buques de la Armada.","Sistema PR4G · integración en sistemas"],
["M","Además de la RRC, los equipos PR4G forman parte de los medios de transmisión de:",["La Red de Área Táctica (RBA) y del SIMACET","La red telefónica civil","El sistema de pago de nóminas","El circuito cerrado del acuartelamiento"],"RBA (Red de Área Táctica) y SIMACET (Sistema de Información para Mando y Control del ET) usan PR4G en sus medios.","Sistema PR4G · RBA y SIMACET"],
["M","La actualización del modo de transmisión de la V3 (Geomux/Supermux) permite:",["Aumentar la velocidad del canal IP y transmitir datos por el canal de voz cuando está libre","Cambiar el calibre del equipo","Apagar la red entera","Sustituir al satélite Spainsat"],"Evolución reciente de la V3: reutilizar el canal de voz para datos cuando está libre y subir la velocidad del canal IP, de cara a la mejora del C2NET.","Sistema PR4G V3 · actualización"],
["F","Dentro de la organización del Ejército de Tierra, el Mando de Transmisiones cuelga de:",["El Mando de Apoyo a la Maniobra","La Fuerza Logística Operativa","El Mando de Canarias","La Dirección de Acuartelamiento"],"El Mando de Transmisiones es uno de los cinco mandos del Mando de Apoyo a la Maniobra (con MACA, MAAA, Ming y Brigada Logística).","Orden DEF/708/2020 art. 14.2"],
["M","Según el art. 14.7 de la DEF/708/2020, el Mando de Transmisiones está preparado para:",["Su empleo en refuerzo a las unidades de transmisiones de las unidades que se determinen y para proporcionar apoyo CIS, guerra electrónica y ciberdefensa en el marco de una organización operativa","Dirigir las academias","Reclutar a la tropa","Fabricar equipos de radio"],"Literal del artículo: refuerzo + apoyo CIS, GE y ciberdefensa. Es el «remache» de transmisiones de la Fuerza.","Orden DEF/708/2020 art. 14.7"],
["M","En el Cuartel General del ET, la Jefatura del Ciberespacio y de los Servicios de Asistencia Técnica es responsable de:",["Los sistemas de información y telecomunicaciones, la guerra electrónica, la gestión del espectro electromagnético y la ciberdefensa","El abastecimiento de combustible","La instrucción física","Los galones y uniformes"],"La JCISAT (art. 4): CIS + GE + espectro + ciberdefensa, y principal asesora del JEME a través del SEJEME en el ámbito ciberespacial.","Orden DEF/708/2020 art. 4"],
["M","La Subdirección de Ciberdefensa y Actividades Electromagnéticas pertenece a:",["La Jefatura del Ciberespacio y de los Servicios de Asistencia Técnica (JCISAT)","El Mando de Transmisiones directamente","La Dirección de Personal","El Instituto de Historia y Cultura Militar"],"La JCISAT se articula en Subdirección de Servicios de Asistencia Técnica, de Sistemas de Información y Telecomunicaciones y de Ciberdefensa y Actividades Electromagnéticas.","Orden DEF/708/2020 art. 4.4"],
["M","Quien asesora al JEME en el ámbito ciberespacial (CIS, guerra electrónica, espectro y ciberdefensa) lo hace:",["A través del SEJEME (Segundo Jefe del Estado Mayor)","Directamente al Rey","Por conducto del Delegado de Defensa","Mediante el Consejo Superior"],"Art. 4.2: la JCISAT es principal asesora del JEME a través del SEJEME. Detalle de cadena que gusta al examinador.","Orden DEF/708/2020 art. 4.2"],
["D","A un cabo de transmisiones le ordenan preparar la estación de radio vehicular de su sección. Según la dotación habitual, la estación basada en vehículo con dos RT 9210 (V3) es:",["El Mercurio 2000","El Pizarro","El RG-31","El VAMTAC de mando"],"El Mercurio 2000 incorpora dos radioteléfonos 9210 (V3) y sirve de plataforma de red de la sección de radio.","Sistema PR4G · estación Mercurio 2000 · caso"],
["D","En una net de compañía el enemigo intenta interferir la frecuencia que usan. La radio en modo BCL:",["Recorre los canales de la frecuencia en busca del que no está siendo interferido","Apaga la radio automáticamente","Cambia de operador","Debe cambiarse de banda a HF"],"BCL (Búsqueda de Canal Libre) es la respuesta del sistema ante la interferencia dentro de una misma frecuencia.","Sistema PR4G · caso"],
["D","Antes de un despliegue delicado, el jefe ordena estar listo para destruir las claves si hay riesgo de captura del equipo. La función del PR4G que lo permite:",["El borrado de emergencia","El modo MIX","La prueba de enlace","La vigilancia de canal"],"Borrado de emergencia: borra las claves (COMSEC/TRANSEC) para que el equipo capturado no revele la red. Protección literal de la ficha oficial.","Sistema PR4G · ficha oficial ET · caso"],
["D","Un oficial pregunta qué es lo que la RRC protege frente al enemigo. La respuesta completa correcta:",["El contenido de las comunicaciones (cifrado, COMSEC) y el modo de transmisión (salto de frecuencia, TRANSEC)","Solo la antena","Únicamente el volumen de voz","Nada: la red es pública"],"La doble protección es el corazón del sistema: COMSEC (contenido) + TRANSEC (transmisión). Si el examen la parte en dos, hay que saber cuál es cuál.","Sistema PR4G · caso"],
["M","Las antenas habituales del PR4G en configuración básica son:",["Varilla de 2,6 m y fleje de 1,5 m","Parabólica de 3 m","Mástil de 12 m","Dipolo de 40 m"],"Ficha oficial: varilla de 2,6 m (vehicular/portátil) y fleje de 1,5 m. Con ellas se logra el alcance de 8-10 km.","Sistema PR4G · ficha oficial ET"],
["F","La velocidad del salto de frecuencia del PR4G (200-300 saltos/seg) sirve para:",["Impedir que el enemigo localice y siga la emisión","Ahorrar batería","Aumentar el volumen","Mejorar la estanqueidad"],"El salto rápido (TRANSEC) es la defensa ECCM frente a la interceptación y localización por guerra electrónica.","Sistema PR4G · ficha oficial ET"],
["M","En la V3, la voz se mejora mediante:",["Un codificador digital de voz (vocoder) de última generación","Una sirena analógica","Un tocadiscos","Sintevoz de los 80"],"La V3 incorporó vocoder de última generación: «óptima calidad de voz en cualquier condición de propagación o perturbación electrónica».","Sistema PR4G V3"],
["M","La altura máxima de funcionamiento del PR4G (embarcado en aeronaves) es:",["4.500 m","12.000 m","500 m","20.000 m"],"Ficha oficial: 4.500 m de altura máxima de funcionamiento — relevante en FAMET y helicópteros.","Sistema PR4G · ficha oficial ET"],
["D","Un cabo pregunta en qué banda trabaja la red radio de combate de su sección. La respuesta:",["VHF, 30-88 MHz","UHF militar 225-400 MHz","HF 3-30 MHz","Satélite Ku"],"La RRC es VHF (30-88 MHz); HF y satélite son otras capas de comunicaciones (más lejos, menos ancho de banda táctico).","Sistema PR4G · caso"],
["M","La familia PR4G lleva operativa en el Ejército de Tierra desde:",["1992","1962","2015","1978"],"Las primeras unidades llegaron en 1992 sustituyendo a los PRC-77; desde entonces V1, V2 y V3 (con V1/V2 posteriormente modernizadas).","Sistema PR4G · historia del programa"],
["M","¿Cuál de estos NO es un modo de trabajo del PR4G?",["GPS-NODAL","SFR (salto de frecuencia)","BCL (búsqueda de canal libre)","MIX (mixto)"],"Los modos son SFR, BCL, MIX, FD y FFC. GPS es receptor de posicionamiento en la V3, no un modo de trabajo.","Sistema PR4G · trampa de examen"],
["D","En una brigada preguntan qué órgano del ET proporciona refuerzo de transmisiones y apoyo CIS, guerra electrónica y ciberdefensa en la organización operativa. La respuesta:",["El Mando de Transmisiones","El Mando de Personal","La Dirección de Acuartelamiento","El Instituto de Historia y Cultura Militar"],"Literal del art. 14.7 de la DEF/708/2020: el Mando de Transmisiones refuerza y da el apoyo CIS/GE/ciberdefensa.","Orden DEF/708/2020 art. 14.7 · caso"],
["M","Las velocidades de datos incorporadas por la V3 del PR4G son:",["9.600, 19.200 y 38.400 bits/s","300 y 600 bits/s","1 y 2 Mbit/s","100.000 bits/s fijos"],"La V3 multiplicó por cuatro la velocidad de la generación anterior: 9.600/19.200/38.400 bps con protocolo estándar abierto.","Sistema PR4G V3 · TFG DAC Transmisiones"],
["M","El sector transmisiones se ha convertido para la Fuerza en:",["Su «sistema nervioso»: sin comunicaciones no hay mando ni coordinación","Un elemento prescindible en combate","Una unidad exclusivamente administrativa","Un cuerpo ajeno a las operaciones"],"Síntesis de doctrina: las transmisiones son las primeras en llegar y las últimas en marcharse; sin ellas no hay mando y control.","Doctrina de transmisiones · síntesis"]
]
assert len(RAW) == 50, "RAW tiene %d" % len(RAW)
import io
PATRON = [(p + j) % 4 for j in range(13) for p in range(4)][:50]
filas = []
for i, ((dif, q, ops, x, r), dest) in enumerate(zip(RAW, PATRON), 1):
    correcta = ops[0]; resto = ops[1:]
    nuevas = resto[:dest] + [correcta] + resto[dest:]
    esc = lambda t: t.replace('"', '\\"')
    filas.append('{c:"cabo",b:"C1",t:"Transmisiones",d:"%s",id:"tx%02d",q:"%s",o:[%s],a:%d,x:"%s",r:"%s"}' % (dif, i, esc(q), ",".join('"%s"' % esc(o) for o in nuevas), dest, esc(x), esc(r)))
LOTE9 = (',\n/* ===== LOTE EXAMINADOR — Tema 9: Transmisiones (sistema PR4G + Mando de Transmisiones/JCISAT DEF/708/2020)\n'
'   Elaboración PROPIA (examinador GALÓN), 20-sep-2026, 100% contra fuentes verificadas: fichas OFICIALES del\n'
'   Ejército de Tierra (ejercito.defensa.gob.es: 30-88 MHz, 2.320 canales, 0,4-4 W, 8-10 km, 200-300 saltos/seg,\n'
'   antenas 2,6 m / 1,5 m, 4.500 m, 38.400 bits/s, DELTA EUROCOM D/1 16 kbits/s, borrado de emergencia, TEMPEST\n'
'   AMSG-784, EMP, modos analógica/digital-COMSEC) y TFG de la DAC de Transmisiones + programa (V1 1992 sustituye\n'
'   al AN/PRC-77; Amper/Thales España; V3 f@snet 2007: GPS no compatible con V1/V2, IP/SAP solo datos vs IP/MUX\n'
'   voz+datos, manpack 10 W, vocoder, 9.600/19.200/38.400 bps; modos SFR-BCL-MIX-FD-FFC; COMSEC cifrado vs TRANSEC\n'
'   salto; Mercurio 2000 con dos RT 9210; modelos RT-9200/RT-9210; RRC hasta nivel batallón; RBA y SIMACET;\n'
'   actualización Geomux/Supermux). Organización: Orden DEF/708/2020 arts. 14.2 y 14.7 (Mando de Transmisiones)\n'
'   y art. 4 (JCISAT, Subdirección de Ciberdefensa y Actividades Electromagnéticas). NOTA: el dato "230 canales"\n'
'   que aparece en alguna ficha se omite por ser contradictorio con los 2.320 canales oficiales (regla: no preguntar\n'
'   lo que las fuentes disputan). */\n')
s = io.open('/home/user/galon/js/bank7.js', encoding='utf-8').read().rstrip()
assert s.endswith('];')
s = s[:-2] + LOTE9 + ",\n".join(filas) + "\n];\n"
io.open('/home/user/galon/js/bank7.js', 'w', encoding='utf-8').write(s)
from collections import Counter
print("Lote Tema 9 montado: 50 · reparto correctas:", dict(sorted(Counter(PATRON).items())))
