#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Lote Tema 14 · OTAN y UE — 50 preguntas, formato: [dif, pregunta, opciones(correcta=0), explicación, ref]
# Fuentes verificadas 21-sep-2026: exteriores.gob.es (Rep. Perm. OTAN y España-OTAN: 32 miembros; España 30-5-1982
# 16.º miembro; referéndum permanencia 12-3-1986; integración en la estructura militar 1-1-1999; Cumbre de Madrid
# 2022; Rota y SDAM; SG Mark Rutte) · lamoncloa.gob.es (fundación 4-4-1949, 12 fundadores, oleadas de ampliación,
# Finlandia 2023 y Suecia 7-3-2024, art. 5 invocado una vez tras el 11-S) · paises.net/exteriores (art. 10 puerta
# abierta). UE: datos estables clásicos (CECA 1951, Roma 1957, Maastricht 1992, Lisboa 2007, 27 miembros, Brexit
# 31-1-2020, España 1-1-1986, 9 de mayo Día de Europa, bandera/himno/lema, sedes).
RAW = [
["F","La OTAN se fundó con la firma del Tratado de Washington el:",["4 de abril de 1949","29 de agosto de 1949","4 de abril de 1952","31 de octubre de 1948"],"Tratado de Washington, firmado el 4 de abril de 1949 por doce países de ambos lados del Atlántico.","Exteriores · España y la OTAN"],
["F","Los países FUNDADORES de la OTAN fueron:",["Doce","Dieciséis","Treinta y dos","Siete"],"Doce fundadores en 1949: EE. UU., Canadá, Reino Unido, Francia, Bélgica, Países Bajos, Luxemburgo, Noruega, Dinamarca, Islandia, Italia y Portugal.","La Moncloa · OTAN"],
["F","El corazón de la OTAN, el artículo 5 del Tratado, establece que:",["Un ataque armado contra uno o varios aliados (en Europa o Norteamérica) se considera un ataque contra todos","Cada país defiende solo su territorio","La OTAN ataca primero siempre","El Secretario General decide las guerras"],"Defensa colectiva: «todos para uno y uno para todos». Es el artículo que da sentido a la Alianza.","Exteriores · España y la OTAN"],
["M","El artículo 5 de la OTAN se ha invocado:",["Una sola vez: tras los atentados del 11 de septiembre de 2001","Nunca","En cada misión de combate","Dos veces: en el 11-S y en Ucrania"],"Solo una vez, al día siguiente del 11-S (2001), por el ataque a Estados Unidos. Ucrania no es miembro, por eso no lo activa.","La Moncloa · OTAN"],
["M","El artículo 10 del Tratado de Washington establece la «puerta abierta»: puede ingresar",["Cualquier Estado europeo en condiciones de promover los principios del Tratado y contribuir a la seguridad del Atlántico Norte","Cualquier país del mundo sin condiciones","Solo países con costa atlántica","Solo países de la UE"],"La puerta abierta (art. 10): europeo, que promueva los principios y aporte seguridad a la región.","Exteriores · Miembros y ampliación"],
["M","¿Cuántos miembros tiene hoy la OTAN?",["32","30","28","27"],"Suecia se convirtió en el 32.º miembro el 7 de marzo de 2024 (Finlandia lo fue en abril de 2023).","Exteriores · Miembros y ampliación"],
["M","El miembro número 31 de la OTAN, en abril de 2023, fue:",["Finlandia","Suecia","Ucrania","Austria"],"Finlandia abandonó su neutralidad tras la invasión rusa de Ucrania y entró el 4 de abril de 2023.","Exteriores · Miembros y ampliación"],
["M","El miembro número 32 de la OTAN, el 7 de marzo de 2024, fue:",["Suecia","Finlandia","Irlanda","Suiza"],"Suecia, tras 20 meses de bloqueo (Turquía y Hungría), firmó su adhesión en Washington el 7-3-2024.","Exteriores · Miembros y ampliación"],
["F","España ingresó en la OTAN el:",["30 de mayo de 1982","12 de marzo de 1986","1 de enero de 1986","6 de diciembre de 1978"],"El 30-5-1982 España se convirtió en el miembro número dieciséis de la Alianza (proceso iniciado por Calvo-Sotelo).","Exteriores · España y la OTAN"],
["F","El referéndum en el que los españoles avalaron la PERMANENCIA de España en la OTAN se celebró el:",["12 de marzo de 1986","30 de mayo de 1982","23 de febrero de 1981","6 de diciembre de 1978"],"El 12-3-1986 el «sí» a la permanencia (con las tres condiciones del PSOE: no integración militar, prohibición de armas nucleares y reducción gradual de la presencia de EE. UU.).","La Moncloa · OTAN"],
["M","España se incorporó a la ESTRUCTURA MILITAR INTEGRADA de la OTAN el:",["1 de enero de 1999","30 de mayo de 1982","12 de marzo de 1986","4 de abril de 1949"],"Decidida en la Cumbre de Madrid de 1997, la plena participación española en la estructura militar se hizo efectiva el 1-1-1999.","La Moncloa · OTAN"],
["M","La Cumbre de la OTAN celebrada en Madrid en 2022 fue especial para España porque:",["Coincidió con el 40.º aniversario de nuestro ingreso y adoptó el Plan para la Vecindad Sur","Allí se fundó la OTAN","Se acordó la entrada de Ucrania","España abandonó la Alianza"],"Madrid 2022: 40 años del ingreso español y el punto de partida del Plan de Acción para el Flanco Sur (adoptado en la Cumbre de Washington 2024).","Exteriores · España y la OTAN"],
["M","En la Base Naval de Rota (Cádiz) España alberga:",["Seis destructores AEGIS estadounidenses integrados en la Defensa contra Misiles Balísticos de la OTAN","La flota ballenera aliada","El arsenal nuclear europeo","La academia de la OTAN"],"La contribución española al SDAM de la OTAN: seis destructores AEGIS de EE. UU. en Rota.","Exteriores · España y la OTAN"],
["M","El Secretario General de la OTAN es:",["El neerlandés Mark Rutte","El español Javier Colomina","El estadounidense Joe Biden","El francés Emmanuel Macron"],"Mark Rutte (ex primer ministro neerlandés) dirige la Alianza como Secretario General. (Javier Colomina es el representante del SG para la Vecindad Sur: español, pero no SG.)","Exteriores · España y la OTAN"],
["M","Las decisiones IMPORTANTES de la OTAN se toman por:",["Consenso (unanimidad de todos los aliados)","Mayoría simple","Mayoría de dos tercios","Lo decide Estados Unidos"],"Regla de oro aliada: nada se aprueba sin el acuerdo de todos. Por eso la OTAN es 32 países y un solo «sí» común.","OTAN · principios"],
["F","Las siglas OTAN significan:",["Organización del Tratado del Atlántico Norte","Organización Territorial de las Naciones Aliadas","Oficina Técnica del Atlántico Norte","Organización de Tratados Aliados Norteamericanos"],"En inglés NATO (North Atlantic Treaty Organization): la alianza político-militar del Atlántico Norte.","Exteriores · España y la OTAN"],
["M","La OTAN es:",["Una alianza político-militar DEFENSIVA de países soberanos","Un ejército mundial con tropas propias obligatorias","Una agencia de la ONU","Un tratado comercial"],"Alianza defensiva: garantiza libertad y seguridad de sus miembros con medios políticos y militares; no tiene «ejército propio» permanente: usa capacidades nacionales.","Exteriores · objetivos"],
["M","Grecia y Turquía ingresaron en la OTAN en:",["1952","1949","1965","1982"],"Primera ampliación (1952): Grecia y Turquía, flanco sureste frente al bloque soviético.","La Moncloa · ampliaciones"],
["M","La República Federal de Alemania ingresó en la OTAN en:",["1955","1949","1990","2004"],"Alemania (RFA) entró en 1955; la reunificación (1990) la mantuvo en la Alianza con el territorio entero.","La Moncloa · ampliaciones"],
["M","La gran ampliación «hacia el Este» de 1999 incorporó a:",["República Checa, Hungría y Polonia","Estonia, Letonia y Lituania","Bulgaria y Rumanía","Finlandia y Suecia"],"Endosada en la Cumbre de Madrid de 1997, efectiva en 1999: los tres primeros exintegrantes del Pacto de Varsovia.","Exteriores · Miembros y ampliación"],
["M","La ampliación de 2004 fue la mayor y llevó a la OTAN a:",["Siete países: Bulgaria, Eslovaquia, Eslovenia, Estonia, Letonia, Lituania y Rumanía","Tres países nórdicos","Cuatro países balcánicos","Dos países del Cáucaso"],"2004: los países bálticos (antiguos soviéticos) y centro-este europeo en una sola oleada de siete.","Exteriores · Miembros y ampliación"],
["M","Montenegro y Macedonia del Norte entraron en la OTAN respectivamente en:",["2017 y 2020","1999 y 2004","2023 y 2024","2014 y 2016"],"Los dos últimos balcánicos antes de Finlandia/Suecia: Montenegro (2017) y Macedonia del Norte (2020, tras el acuerdo de nombre con Grecia).","Exteriores · Miembros y ampliación"],
["F","El Día de Europa se celebra el:",["9 de mayo","6 de diciembre","12 de marzo","1 de mayo"],"9 de mayo de 1950: Declaración Schuman, la semilla de la construcción europea. Día de Europa desde 1964.","UE · Día de Europa"],
["F","La bandera europea es:",["Doce estrellas doradas en círculo sobre fondo azul","Cinco estrellas rojas en cruz","Una estrella blanca sobre azul","Trece franjas alternas"],"Las 12 estrellas en círculo simbolizan unidad y armonía (12 = perfección; NO eran los miembros: son doce desde antes).","UE · símbolos"],
["F","El himno europeo es:",["La «Oda a la Alegría» de la Novena Sinfonía de Beethoven","El Himno de la Alegría de Mozart","La Marcha Real","La Marsellesa"],"La Oda a la Alegría (Beethoven, 9.ª sinfonía): himno del Consejo de Europa y de la UE, sin letra oficial.","UE · símbolos"],
["F","El lema de la Unión Europea es:",["«Unida en la diversidad»","«Todos para uno y uno para todos»","«Más fuerte juntos siempre»","«Libertad, igualdad, fraternidad»"],"«Unida en la diversidad» (United in diversity): muchos idiomas, culturas y tradiciones, una unión.","UE · símbolos"],
["M","Actualmente la UE está formada por:",["27 Estados miembros","32 Estados miembros","25 Estados miembros","31 Estados miembros"],"Tras el Brexit (salida del Reino Unido el 31-1-2020), la UE queda en 27. Cuidado: 32 es la OTAN.","UE · composición"],
["M","El único país que ha SALIDO de la Unión Europea es:",["El Reino Unido","Grecia","Noruega","Dinamarca"],"Brexit: el Reino Unido salió oficialmente el 31 de enero de 2020 tras el referéndum de 2016.","UE · Brexit"],
["F","España se incorporó a las Comunidades Europeas el:",["1 de enero de 1986","12 de junio de 1985","30 de mayo de 1982","1 de enero de 2000"],"España (con Portugal) entró el 1-1-1986: la tercera ampliación, junto a Portugal.","UE · España"],
["F","El Tratado de Roma (1957) creó:",["La Comunidad Económica Europea (mercado común)","La OTAN","La ONU","La CECA"],"Roma 1957: la CEE de los «seis» (CECA ya existía desde 1951): mercado común carbón-acero-bienes.","UE · tratados"],
["M","El Tratado de MAASTRICHT (1992) es el que:",["Creó la Unión Europea, la ciudadanía europea y abrió el camino al euro","Creó la CECA","Sacó al Reino Unido de la UE","Fundó la OTAN"],"Maastricht (firmado 1992): de Comunidad a UNIÓN: tres pilares, ciudadanía europea y la moneda única en camino.","UE · tratados"],
["M","El Tratado de Lisboa (2007, en vigor 2009) supuso:",["El marco actual de la UE: figura del Presidente del Consejo Europeo y la iniciativa de ciudadanía","La salida de Francia","La creación de la CECA","La entrada de España"],"Lisboa reformó Maastricht/Roma: Presidente estable del Consejo Europeo, Alta Representante, Carta de Derechos vinculante.","UE · tratados"],
["M","La CECA (1951), primera piedra de Europa, agrupó a:",["Seis países: Francia, Alemania, Italia, Bélgica, Países Bajos y Luxemburgo","Doce países","Veintisiete países","Solo a Francia y Alemania"],"Los «seis» fundadores pusieron carbón y acero (industrias de guerra) bajo una alta autoridad común: Schuman-Monnet.","UE · tratados"],
["F","La ciudadana europEA (derecho a circular, residir, votar en municipales y europeas) se creó con:",["El Tratado de Maastricht","El Tratado de Roma","El Tratado de Lisboa","El Tratado de Washington"],"Maastricht 1992: quien tenga la nacionalidad de un Estado miembro es ciudadano de la Unión.","UE · ciudadanía"],
["M","La sede de la COMISIÓN Europea y del CONSEJO está en:",["Bruselas","Estrasburgo","Luxemburgo","Fráncfort"],"Bruselas concentra Comisión y Consejo (y las reuniones del Consejo Europeo).","UE · sedes"],
["M","El PARLAMENTO Europeo celebra sus sesiones plenarias principalmente en:",["Estrasburgo","Bruselas","París","Ámsterdam"],"Estrasburgo (Francia) es la sede oficial de las sesiones plenarias del Parlamento Europeo.","UE · sedes"],
["M","El Tribunal de Justicia de la Unión Europea (TJUE) tiene su sede en:",["Luxemburgo","Bruselas","La Haya","Viena"],"Luxemburgo: garantiza que el derecho de la UE se interprete y aplique igual en todos los Estados.","UE · sedes"],
["M","El Banco Central Europeo (BCE) está en:",["Fráncfort","Bruselas","Berlín","Zúrich"],"Fráncfort (Alemania): el BCE gobierna el euro y la estabilidad de precios de la eurozona.","UE · sedes"],
["M","¿Todos los países de la UE usan el euro?",["No: el euro es la moneda de la eurozona (varios miembros conservan su moneda)","Sí, los 27 desde 1999","Solo lo usan los fundadores","Ninguno lo usa de verdad"],"El euro es la moneda común de la eurozona; países como Suecia o Polonia mantienen moneda propia (y Dinamarca tiene cláusula de exclusión).","UE · euro"],
["M","El Parlamento Europeo se elige:",["Por sufragio universal directo cada 5 años","Lo nombra la Comisión","Lo designa el Consejo","Por sorteo entre alcaldes"],"Desde 1979 los europarlamentarios se eligen por voto directo de los ciudadanos cada cinco años.","UE · instituciones"],
["M","La iniciativa de las leyes de la UE corresponde a:",["La Comisión Europea","El Parlamento Europeo","El Consejo de la OTAN","El Banco Central"],"La Comisión es «el motor legislativo»: propone; Parlamento y Consejo debaten y aprueban.","UE · instituciones"],
["M","El CONSEJO EUROPEO está formado por:",["Los jefes de Estado o de Gobierno de los Estados miembros más su Presidente y el Presidente de la Comisión","Los ministros de Defensa","Los europarlamentarios","Los jueces del TJUE"],"Es el que marca el rumbo político de la UE: cumbres de jefes de Estado y de Gobierno.","UE · instituciones"],
["F","El ESPACIO SCHENGEN permite:",["La libre circulación sin controles en las fronteras interiores de los países que lo integran","Comprar tabaco más barato","Votar en España a los alemanes","Circular en coche sin carné"],"Schengen (acuerdo de 1985) = viaje sin fronteras interiores. Ojo: incluye países NO de la UE y hay miembros de la UE fuera de Schengen.","UE · Schengen"],
["M","La política común de SEGURIDAD Y DEFENSA (PSDC) es:",["Un marco de la UE para misiones y operaciones civiles y militares acordadas entre los Estados","El ejército de la UE con tropas obligatorias","Una agencia de la OTAN","Una política exclusivamente comercial"],"La PSDC (Lisboa) permite a la UE lanzar misiones (socorro, paz, seguridad) con contribuciones voluntarias de los Estados.","UE · PSDC"],
["M","Relación entre OTAN y UE:",["Son organizaciones distintas: la UE es política-económica (con PSDC) y la OTAN es la alianza defensiva del Atlántico Norte","Son la misma organización con dos nombres","La UE manda en la OTAN","Son rivales que no se hablan"],"Distintas y complementarias: 27 (UE) vs 32 (OTAN); comparten valores y muchos miembros, pero cada una lo suyo.","Comparación"],
["M","¿Cuántos países son miembros A LA VEZ de la OTAN y de la UE?",["23 países","27 países","32 países","19 países"],"De los 27 de la UE, 23 están también en la OTAN (Austria, Irlanda, Malta y Chipre no; y la OTAN añade EE. UU., Canadá, Reino Unido, Noruega, Turquía, Suiza no… el conteo exacto: 23).","Comparación"],
["D","Un cabo pregunta por qué España está en OTAN con «condiciones» de 1986. La explicación correcta:",["El referéndum de 1986 avaló la permanencia con tres condiciones: no integración en la estructura militar (hasta 1999), prohibición de armas nucleares en España y reducción de bases de EE. UU.","España entró a la fuerza tras una guerra","El Rey lo decidió por decreto","La OTAN nos obligó a entrar en 1986"],"1982 entra el Gobierno; 1986 el pueblo avala la permanencia con condiciones; 1999 la plena integración militar. Cronología que gusta al examinador.","La Moncloa · OTAN · caso"],
["D","En 2022 Finlandia y Suecia abandonaron su neutralidad histórica. El detonante fue:",["La invasión rusa de Ucrania (feb. 2022): pidieron entrar juntos en la OTAN en mayo de 2022","Una directiva de la UE","La Cumbre de Madrid de 1949","El Brexit"],"La agresión rusa volcó la opinión pública nórdica: solicitud conjunta en mayo de 2022; Finlandia entró en 2023 y Suecia en 2024.","Exteriores · ampliaciones · caso"],
["D","Rota alberga destructores AEGIS para la Defensa contra Misiles Balísticos. Esto significa que España:",["Contribuye activamente al escudo antimisiles de la OTAN desde su territorio","Está siempre en guerra","No participa en la OTAN","Solo entrenar a marinos estadounidenses"],"La contribución española al SDAM: el escudo antimisiles aliado opera también desde Rota con personal y buques de EE. UU. integrados en el sistema aliado.","Exteriores · España y la OTAN · caso"],
["D","Un compañero confunde UE y OTAN. La aclaración más certera:",["La UE legisla (28 miembros → hoy 27) y la OTAN defiende (32): un país puede estar en ambas, en una o en ninguna","Son dos departamentos del mismo organismo","La OTAN es la rama militar de la UE","La UE nació de la OTAN en 1949"],"Dos organizaciones, dos tratados y dos sedes: Bruselas las acoge a ambas, pero no son lo mismo (ni el mismo número de miembros).","Comparación · caso"]
]
assert len(RAW) == 50, "RAW tiene %d" % len(RAW)
import io
PATRON = [(p + j) % 4 for j in range(13) for p in range(4)][:50]
filas = []
for i, ((dif, q, ops, x, r), dest) in enumerate(zip(RAW, PATRON), 1):
    correcta = ops[0]; resto = ops[1:]
    nuevas = resto[:dest] + [correcta] + resto[dest:]
    esc = lambda t: t.replace('"', '\\"')
    filas.append('{c:"cabo",b:"C1",t:"OTAN y UE",d:"%s",id:"ot%02d",q:"%s",o:[%s],a:%d,x:"%s",r:"%s"}' % (dif, i, esc(q), ",".join('"%s"' % esc(o) for o in nuevas), dest, esc(x), esc(r)))
LOTE14 = (',\n/* ===== LOTE EXAMINADOR — Tema 14: OTAN y UE\n'
'   Elaboración PROPIA (examinador GALÓN), 21-sep-2026, contra fuentes verificadas hoy: exteriores.gob.es\n'
'   (Rep. Perm. OTAN: 32 miembros y oleadas 1952/1955/1982/1999/2004/2009/2017/2020/2023/2024; España-OTAN: 30-5-1982\n'
'   16.º miembro, referéndum permanencia 12-3-1986 con condiciones, integración estructura militar 1-1-1999 tras la\n'
'   Cumbre de Madrid de 1997, Cumbre de Madrid 2022 con 40.º aniversario, Rota con 6 destructores AEGIS del SDAM,\n'
'   SG Mark Rutte, art. 5 invocado una vez tras el 11-S, art. 10 puerta abierta) y lamoncloa.gob.es (12 fundadores\n'
'   4-4-1949). UE: datos estables (CECA 1951 seis países, Roma 1957, Maastricht 1992 ciudadanía+euro, Lisboa 2007,\n'
'   27 miembros tras Brexit 31-1-2020, España 1-1-1986, Día de Europa 9-5, bandera 12 estrellas, Oda a la Alegría,\n' 
'   sedes Bruselas/Estrasburgo/Luxemburgo/Fráncfort, Schengen, PSDC). Conteo 23 países en ambas organizaciones\n'
'   (de 27 UE, excluidos Austria, Irlanda, Malta y Chipre en OTAN). */\n')
s = io.open('/home/user/galon/js/bank7.js', encoding='utf-8').read().rstrip()
assert s.endswith('];')
s = s[:-2] + LOTE14 + ",\n".join(filas) + "\n];\n"
io.open('/home/user/galon/js/bank7.js', 'w', encoding='utf-8').write(s)
from collections import Counter
difs = Counter(r[0] for r in RAW)
print("Lote Tema 14 montado: 50 · reparto correctas:", dict(sorted(Counter(PATRON).items())), "· dificultades:", dict(sorted(difs.items())))
