#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Lote Tema 12 · La Constitución Española de 1978 — 50 preguntas, formato: [dif, pregunta, opciones(correcta=0), explicación, ref]
# Fuentes verificadas 21-sep-2026: CONSTITUCIÓN ESPAÑOLA, texto consolidado (BOE-A-1978-31229; BOE núm. 311, de
# 29-12-1978): Preámbulo + Título Preliminar (arts. 1-9) + 10 Títulos + 169 artículos + 4 DA + 9 DT + 1 DD + 1 DF.
# REFORMAS (¡4!): art. 13.2 (BOE 28-8-1992, Maastricht) · art. 135 (BOE 27-9-2011, estabilidad presupuestaria) ·
# art. 49 (BOE 17-2-2024, personas con discapacidad; BOE-A-2024-3099) · art. 69.3 (BOE 20-5-2026, senador propio
# para Formentera; Senado de elección directa 208→209). TODAS por el art. 167; ninguna por el 168.
# NOTA anti-obsoleto: el texto constitucional literal del art. 8.1 dice "Ejército del Aire" (la denominación
# "y del Espacio" es reglamentaria, de 2022, y NO ha reformado la CE).
RAW = [
["F","La Constitución Española de 1978 fue ratificada en referéndum el:",["6 de diciembre de 1978","23 de febrero de 1981","29 de diciembre de 1978","31 de octubre de 1978"],"El 6-12-1978 los españoles ratificaron la Constitución en referéndum (aprobada por las Cortes el 31-10-1978; sancionada por el Rey el 27-12-1978).","CE · BOE-A-1978-31229"],
["F","La Constitución entró en vigor el:",["29 de diciembre de 1978, con su publicación en el BOE","1 de enero de 1979","6 de diciembre de 1978, el día del referéndum","27 de diciembre de 1978, al firmarla el Rey"],"Sancionada por el Rey el 27-12-1978 y publicada en el BOE núm. 311 el 29-12-1978: entra en vigor ese mismo día (su disposición final lo establece así).","CE · disposición final"],
["F","La Constitución Española tiene:",["169 artículos","135 artículos","200 artículos","157 artículos"],"169 artículos repartidos en un Título Preliminar y diez Títulos, más 15 disposiciones (4 adicionales, 9 transitorias, 1 derogatoria y 1 final).","CE · BOE-A-1978-31229"],
["F","De las disposiciones de la Constitución, las TRANSITORIAS son:",["9","4","1","15"],"Nueve transitorias; junto con 4 adicionales, 1 derogatoria y 1 final suman las 15 disposiciones de la Constitución.","CE · BOE-A-1978-31229"],
["F","La estructura de la Constitución es:",["Un Título Preliminar y diez Títulos numerados","Nueve Títulos numerados sin Título Preliminar","Doce Títulos numerados","Un Título Único con capítulos"],"Título Preliminar (arts. 1-9) + diez Títulos: I Derechos (10-55), II Corona, III Cortes, IV Gobierno, V Gobierno-Cortes, VI Poder Judicial, VII Economía, VIII Territorio, IX TC y X Reforma.","CE · BOE-A-1978-31229"],
["F","Según el art. 1.3 CE, la forma política del Estado español es:",["La Monarquía parlamentaria","La República parlamentaria","La Monarquía absoluta","El Estado federal"],"Literal del artículo 1.3: «La forma política del Estado español es la Monarquía parlamentaria».","CE art. 1.3"],
["F","Los valores superiores del ordenamiento jurídico según el art. 1.1 CE son:",["La libertad, la justicia, la igualdad y el pluralismo político","El orden, la paz, el trabajo y la familia","La fe, la patria, el honor y el deber","La igualdad, la fraternidad y la libertad"],"Literal del art. 1.1: España se constituye en un Estado social y democrático de Derecho que propugna como valores superiores la libertad, la justicia, la igualdad y el pluralismo político.","CE art. 1.1"],
["F","Según el art. 1.2 CE, la soberanía nacional reside en:",["El pueblo español, del que emanan los poderes del Estado","El Rey como Jefe del Estado","Las Cortes Generales","El Gobierno en funciones"],"La soberanía NO está en el Rey ni en las Cortes: reside en el pueblo español, del que emanan los poderes del Estado.","CE art. 1.2"],
["F","El art. 2 CE se fundamenta en:",["La indisoluble unidad de la Nación española y el derecho a la autonomía de las nacionalidades y regiones, con solidaridad entre ellas","La confederación de estados independientes","El centralismo puro sin autonomías","La separación de España en estados soberanos"],"Art. 2: unidad de la Nación, patria común e indivisible + derecho a la autonomía + solidaridad: los tres elementos del artículo, nunca dos solos.","CE art. 2"],
["F","Según el art. 3 CE, el castellano es:",["La lengua española oficial del Estado; todos los españoles tienen el deber de conocerla y el derecho a usarla","La única lengua permitida en España","Una lengua de uso privado sin rango oficial","Una lengua extranjera en las CCAA con lengua propia"],"El castellano es oficial del Estado (deber de conocerlo, derecho a usarlo) y las demás lenguas son también oficiales según los Estatutos.","CE art. 3"],
["F","Según el art. 4 CE, la bandera de España está formada por:",["Tres franjas horizontales: roja, amarilla y roja, la amarilla de doble anchura","Tres franjas verticales: roja, amarilla y roja iguales","Una franja roja con cruz blanca","Cinco franjas alternas rojas y amarillas"],"Literal del art. 4.1: tres franjas HORIZONTALES, roja, amarilla y roja, la amarilla de DOBLE anchura que cada una de las rojas.","CE art. 4"],
["F","Según el art. 30.1 CE, la defensa de España es:",["Un derecho y un deber de los españoles","Solo un deber de los militares profesionales","Una opción voluntaria sin obligación alguna","Una obligación exclusiva de las Fuerzas Armadas"],"Art. 30.1 literal: «Los españoles tienen el derecho y el deber de defender a España». Derecho Y deber, no solo deber.","CE art. 30.1"],
["F","El Congreso de los Diputados se compone de un mínimo de:",["300 diputados","150 diputados","500 diputados","208 diputados"],"Art. 68.1: el Congreso se compone de un mínimo de 300 y un máximo de 400 diputados (el sistema actual: 350). Los 208 eran senadores de elección directa hasta la reforma de 2026.","CE art. 68"],
["F","Según el art. 91 CE, el Rey sanciona las leyes aprobadas por las Cortes en el plazo de:",["15 días","48 horas","30 días","6 meses"],"El Rey sancionará EN QUINCE DÍAS las leyes aprobadas por las Cortes y las promulgará y ordenará su inmediata publicación.","CE art. 91"],
["F","Entre las funciones del Gobierno (art. 97 CE) está:",["Dirigir la política interior y exterior, la Administración civil y militar y la defensa del Estado","Juzgar los delitos graves","Dictar sentencias constitucionales","Controlar a los jueces instruyendo causas"],"Art. 97: el Gobierno dirige la política interior y exterior, la Administración civil y militar y la defensa del Estado; ejerce la función ejecutiva y la potestad reglamentaria.","CE art. 97"],
["F","Según el art. 117.1 CE, la justicia emana de:",["El pueblo y se administra en nombre del Rey por Jueces y Magistrados integrantes del poder judicial","El Rey como Jefe del Estado","El Gobierno por delegación","El Ministerio de la Presidencia de Justicia"],"Art. 117.1 literal: la justicia emana del pueblo y se administra en nombre del Rey por Jueces y Magistrados del poder judicial.","CE art. 117.1"],
["F","El jurado, según el art. 125 CE, está regulado por ley orgánica y:",["Participa en el enjuiciamiento en los delitos que determine la ley","Decide solo en causas civiles de familia","Sustituye al juez en todos los procesos penales","Es una opción a la que solo acceden abogados"],"Art. 125: los ciudadanos pueden actuar mediante institución del jurado, en la forma y respecto de aquellos procesos penales que la ley determina (LO del Jurado, 1995).","CE art. 125"],
["F","Según el art. 137 CE, el Estado se organiza territorialmente en:",["Municipios, provincias y Comunidades Autónomas","Departamentos y regiones","Estados federados y condados","Diputaciones forales exclusivamente"],"Art. 137: el Estado se organiza territorialmente en municipios, en provincias y en las CCAA que se constituyan, todas con autonomía para la gestión de sus respectivos intereses.","CE art. 137"],
["F","Según el art. 123 CE, el Tribunal Supremo es:",["El órgano jurisdiccional superior en todos los órdenes, salvo lo dispuesto en materia de garantías constitucionales (el Tribunal Constitucional)","Un tribunal que juzga solo a los ministros","La última instancia también frente al Tribunal Constitucional","Un tribunal exclusivamente militar"],"Supremo en todos los órdenes salvo las garantías constitucionales: la última palabra sobre la CONSTITUCIÓN es del TC, no del TS.","CE art. 123"],
["M","Según el art. 8.1 CE, la misión de las Fuerzas Armadas es:",["Garantizar la soberanía e independencia de España, defender su integridad territorial y el ordenamiento constitucional","Custodiar las fronteras exteriores de la UE","Garantizar solo el orden público interior","Apoyar a la policía en manifestaciones"],"Art. 8.1 literal: garantizar la soberanía e independencia, defender la integridad territorial y el ordenamiento constitucional. La tríada exacta que cae en test.","CE art. 8.1"],
["M","Según el art. 8.1 CE, las Fuerzas Armadas están constituidas por:",["El Ejército de Tierra, la Armada y el Ejército del Aire","El Ejército de Tierra, la Armada, el Ejército del Aire y la Guardia Civil","Solo el Ejército de Tierra y la Armada","El Ejército de Tierra, la Guardia Civil y la Policía Nacional"],"Literal del texto constitucional: ET, Armada y Ejército del Aire (la GC es fuerza militar con adscripción orgánica variable, pero NO integra el art. 8.1). Nota: la denominación «Ejército del Aire y del Espacio» es reglamentaria (2022); el texto de la CE no ha sido reformado.","CE art. 8.1"],
["M","Los principios del art. 9.3 CE son:",["Legalidad, jerarquía normativa, publicidad de las normas, irretroactividad, seguridad jurídica, responsabilidad e interdicción de la arbitrariedad","Igualdad, libertad, fraternidad y solidaridad","Orden, progreso, disciplina y unidad","Proporcionalidad, fidelidad y gratuidad"],"Siete principios del art. 9.3 (la «bandera de la seguridad jurídica»): los recita uno a uno y el test juega a omitir uno.","CE art. 9.3"],
["M","Según el art. 10.1 CE, el fundamento del orden político y de la paz social es:",["La dignidad de la persona, los derechos inviolables que le son inherentes, el libre desarrollo de la personalidad, el respeto a la ley y a los derechos de los demás","La fuerza de las instituciones del Estado","El bien común definido por el Gobierno","La voluntad de la mayoría sin límites"],"Art. 10.1 literal: la dignidad de la persona es la primera piedra del orden constitucional; interpretación de los derechos conforme a la DUDH.","CE art. 10.1"],
["M","La prohibición de discriminación del art. 14 CE se refiere a:",["Nacimiento, raza, sexo, religión, opinión o cualquier otra condición o circunstancia personal o social","Únicamente a la religión","Solo al sexo en el trabajo","Exclusivamente a los extranjeros"],"Art. 14: los españoles son iguales ante la ley, sin que pueda prevalecer discriminación alguna por esas circunstancias (lista abierta: «cualquier otra»).","CE art. 14"],
["M","La duración máxima de la detención preventiva es, según el art. 17.2 CE:",["72 horas","24 horas","96 horas","30 días"],"El plazo máximo de detención preventiva sin certeza judicial es de 72 horas (en terrorismo existe prórroga judicial expresa: no lo pregunta el test básico).","CE art. 17.2"],
["M","El domicilio es inviolable (art. 18.2 CE) salvo:",["Consentimiento del titular, flagrante delicto o resolución judicial motivada","Orden verbal de cualquier funcionario","Simple sospecha del vecindario","Emergencia económica del Estado"],"Tres excepciones exactas: consentimiento del titular, flagrante delicto o resolución motivada del Juez. Ni una más.","CE art. 18.2"],
["M","El recurso de amparo de las libertades y derechos fundamentales (art. 53.2 CE) se tramita:",["En procedimiento preferente y sumario ante los tribunales ordinarios y, en su caso, ante el Tribunal Constitucional","Solo en el Tribunal Supremo tras tres instancias","En la vía administrativa previa obligatoria","Ante el Defensor del Pueblo como juez de amparo"],"Art. 53.2: tutela preferente y sumaria ante tribunales ordinarios (y amparo ante el TC). El Defensor es comisionado de las Cortes, no juez.","CE art. 53.2"],
["M","El Defensor del Pueblo (art. 54 CE) es:",["Alto comisionado de las Cortes Generales, designado por éstas, para la defensa de los derechos del Título I","Un delegado del Gobierno en cada comunidad","El jefe de la Fiscalía General del Estado","Un juez especial del Tribunal Supremo"],"Art. 54: alto comisionado DE LAS CORTES (no del Gobierno), designado por éstas; supervisa la Administración y puede interponer amparo e inconstitucionalidad.","CE art. 54"],
["M","El título más extenso de la Constitución es:",["El Título I (Derechos y deberes fundamentales), con 46 artículos (10-55)","El Título III (Cortes Generales)","El Título VIII (Organización territorial)","El Título X (Reforma)"],"Título I: arts. 10-55 (46 artículos). Le sigue el Título III (66-96, 31 artículos).","CE · estructura"],
["M","Según el art. 69.1 CE, el Senado es:",["La Cámara de representación territorial","La cámara de control del Rey","Una cámara consultiva sin funciones","La cámara de representación popular"],"Art. 69.1 literal: el Senado es la Cámara de representación territorial. El pueblo la representa el Congreso.","CE art. 69.1"],
["M","Según el art. 81 CE, son leyes orgánicas:",["Las relativas a derechos fundamentales y libertades públicas, los Estatutos de Autonomía, el régimen electoral general y las demás previstas en la Constitución","Todas las leyes que apruebe el Gobierno por decreto","Las leyes de Presupuestos Generales del Estado","Cualquier ley que el Senado apruebe por unanimidad"],"El catálogo del art. 81.1 + el dato: se aprueban por MAYORÍA ABSOLUTA del Congreso en votación final sobre el conjunto del proyecto.","CE art. 81"],
["M","La investidura del Presidente del Gobierno (art. 99 CE) requiere:",["Mayoría absoluta del Congreso; si no se obtiene, la misma propuesta se vota 48 horas después bastando la mayoría simple","Mayoría absoluta del Senado","Nombramiento libre del Rey sin voto del Congreso","Referéndum popular de investidura"],"Art. 99: mayoría absoluta en primera votación; 48 horas después, mayoría SIMPLE con la misma propuesta. (Si fracasa, disolución y nuevas elecciones.)","CE art. 99"],
["M","Según el art. 108 CE, el Gobierno responde de su actuación política ante el Congreso:",["Solidariamente, sin perjuicio de la responsabilidad directa de cada Ministro por su gestión","Cada ministro en solitario sin responsabilidad colectiva","Ante el Senado en materias de defensa","Ante el Rey en todos los casos"],"Art. 108: responsabilidad SOLIDARIA ante el Congreso, sin perjuicio de la directa de cada Ministro. La «marca de la casa» del parlamentarismo.","CE art. 108"],
["M","La cuestión de confianza (art. 112 CE) se entiende otorgada por:",["Mayoría simple","Mayoría absoluta","Unanimidad de la cámara","Dos tercios del Congreso"],"Cuestión de confianza (la pide el Presidente del Gobierno al Congreso): basta la mayoría SIMPLE. Ojo, la moción de censura exige lo contrario.","CE art. 112"],
["M","La moción de censura (art. 113 CE) requiere:",["1/10 de diputados, candidato a Presidente incluido y mayoría absoluta para aprobarla","Firma del Rey y mayoría simple","1/3 de senadores y candidato excluido","Mayoría simple y cualquier diputado como firmante"],"Censura CONSTRUCTIVA: el 10% de diputados propone y DEBE incluir un candidato alternativo; aprueba con mayoría absoluta. Si fracasa, no se puede repetir en el mismo periodo de sesiones.","CE art. 113"],
["M","Los estados de alarma, excepción y sitio (art. 116 CE) se declaran:",["Alarma: Gobierno (máx. 15 días); excepción: Congreso (máx. 30+30); sitio: Congreso por mayoría absoluta, a propuesta exclusiva del Gobierno","Los tres por el Rey de oficio","Los tres por el Gobierno sin límite de plazo","Excepción: solo el Ejército en campaña"],"Art. 116 + LO 4/1981: la alarma la declara el Gobierno (máx. 15 días, prórroga solo con el Congreso); la excepción y el sitio los declara el Congreso a propuesta exclusiva del Gobierno, el sitio por mayoría absoluta y con plazos 30+30 la excepción.","CE art. 116 · LO 4/1981"],
["M","Los tribunales de excepción están:",["Prohibidos por el art. 117.5 CE","Permitidos en tiempo de guerra con acuerdo del Rey","Permitidos para delitos militares","Permitidos si lo aprueba el CGPJ"],"Art. 117.5: «El ejercicio de la potestad jurisdiccional en todo tipo de acciones se reserva exclusivamente a los juzgados y tribunales determinados por las leyes» — nadie más, jamás: la garantía del juez predeterminado.","CE art. 117.5"],
["M","Según el art. 122.3 CE, el CGPJ está integrado por:",["El Presidente del Tribunal Supremo y 20 miembros: 12 jueces y magistrados y 8 abogados y otros juristas","El Presidente del Gobierno y 15 jueces","Solo jueces en activo, sin juristas","El Ministro de Justicia y el Fiscal General"],"Órgano de gobierno del Poder Judicial: Presidente del TS (que lo preside) + 20 vocales nombrados por el Rey (12 de la carrera judicial, 8 juristas).","CE art. 122.3"],
["M","Según el art. 124 CE, la Fiscalía tiene como misión:",["Promover la acción de la justicia en defensa de la legalidad, los derechos del ciudadano y el interés público, y velar por la independencia de los tribunales","Defender exclusivamente al Gobierno en juicio","Juzgar a los delincuentes internacionales","Controlar las sentencias de los jueces"],"Art. 124: el Ministerio Fiscal promueve la acción de la justicia, actúa con unidad de actuaciones y dependencia jerárquica; su Fiscal General lo nombra el Rey a propuesta del Gobierno.","CE art. 124"],
["M","La defensa y las Fuerzas Armadas (art. 149.1.4ª CE) son competencia:",["Exclusiva del Estado","Compartida con las CCAA","De las Diputaciones Provinciales","Delegable en los municipios"],"El art. 149.1 enumera las competencias EXCLUSIVAS del Estado: la 4ª es la defensa y las Fuerzas Armadas. La seguridad pública (29ª) es estatal con posibilidad de policías autonómicas: no confundir.","CE art. 149.1.4ª"],
["M","Las medidas del art. 155 CE (obligar a una CCAA a cumplir sus obligaciones) las aprueba:",["El Senado por mayoría absoluta, previo requerimiento al Presidente autonómico","El Congreso por mayoría simple","El Rey por decreto-ley","El Tribunal Constitucional de oficio"],"Art. 155.1: requerimiento previo al Presidente de la CCAA y, si no es atendido, aprobación por MAYORÍA ABSOLUTA DEL SENADO.","CE art. 155"],
["M","El Tribunal Constitucional se compone de 12 magistrados propuestos:",["4 por el Congreso (3/5), 4 por el Senado (3/5), 2 por el Gobierno y 2 por el CGPJ","8 por el Gobierno y 4 por el Rey","12 por el Poder Judicial entre sus miembros","3 por cada partido con grupo propio"],"Art. 159.1: 4+4 (cámaras por mayoría de 3/5), 2 (Gobierno) y 2 (CGPJ); los nombra el Rey. Composición que cae tal cual.","CE art. 159.1"],
["M","El mandato de los magistrados del TC es:",["De 9 años, renovándose por terceras partes cada 3 años","De 6 años, renovándose por mitades","Vitalicio hasta los 75 años","De 12 años, sin renovación parcial"],"Art. 159.3: nueve años y renovación por tercios cada tres (por eso el TC se renueva por bloques).","CE art. 159.3"],
["D","Según el art. 167 CE, el procedimiento ORDINARIO de reforma exige:",["Mayoría de tres quintos de cada Cámara; si no hay acuerdo, comisión paritaria, y referéndum si lo pide 1/10 de cualquier Cámara","Referéndum obligatorio en todo caso","Mayoría simple del Congreso y firma del Rey","Solo el consenso del Gobierno y del TC"],"El camino de TODAS las reformas habidas: 3/5 de cada Cámara, comisión paritaria si hace falta y REFERÉNDUM solo si lo solicita una décima parte de una cámara.","CE art. 167"],
["D","El procedimiento AGRAVADO del art. 168 CE se reserva a:",["Reforma total o la que afecte al Título Preliminar, a la Sección 1.ª del Capítulo II del Título I y al Título II (la Corona)","Cualquier reforma de derechos","Únicamente al Título VIII (territorio)","Los cambios de la bandera"],"Revisión total o reforma que toque Título Preliminar, derechos fundamentales (arts. 14-29) o la Corona: 2/3 de cada Cámara, disolución inmediata, ratificación por 2/3 y REFERÉNDUM obligatorio.","CE art. 168"],
["D","Según el art. 169 CE, no se podrá iniciar la reforma constitucional:",["En tiempo de guerra o de vigencia de los estados del art. 116","En los meses de agosto y diciembre","Mientras exista Gobierno en funciones","Durante cualquier proceso electoral municipal"],"Art. 169 literal: guerra o vigencia de alarma/excepción/sitio congelan la reforma. La Constitución no se toca con la casa en llamas.","CE art. 169"],
["D","¿Se ha utilizado alguna vez el procedimiento agravado del art. 168 CE?",["No, ninguna de las reformas lo ha necesitado","Sí, en la reforma de 2011","Sí, en la reforma de 2024","Sí, dos veces, ambas sobre la Corona"],"Las cuatro reformas de la Constitución (1992, 2011, 2024 y 2026) se tramitaron TODAS por el art. 167: el 168 sigue virgen.","CE arts. 167-168 · reformas"],
["D","Las reformas sufridas por la Constitución hasta hoy son:",["Cuatro: art. 13.2 (1992), art. 135 (2011), art. 49 (2024) y art. 69.3 (2026)","Dos: arts. 13.2 y 135","Una sola: el art. 135 en 2011","Seis, entre 1981 y 2024"],"1.ª: 13.2, sufragio pasivo municipal de extranjeros de la UE (BOE 28-8-1992, Maastricht). 2.ª: 135, estabilidad presupuestaria (BOE 27-9-2011). 3.ª: 49, personas con discapacidad (BOE 17-2-2024). 4.ª: 69.3, senador propio para Formentera (BOE 20-5-2026).","CE · reformas (BOE)"],
["D","La reforma del art. 49 CE (2024) sustituyó el término:",["«Disminuidos» por «personas con discapacidad», en dos apartados, con políticas de autonomía e inclusión en entornos universalmente accesibles","«Extranjeros» por «ciudadanos europeos»","«Presupuesto» por «presupuesto estable»","«Senadores» por «representantes territoriales»"],"BOE 17-2-2024: nuevas redacciones del 49.1 y 49.2 (derechos en condiciones de libertad e igualdad reales y efectivas; políticas de plena autonomía personal e inclusión social). Terminología digna, en vigor el mismo día.","Reforma art. 49 CE · BOE 17-2-2024"],
["D","La cuarta reforma de la Constitución (2026) consistió en:",["Dar al art. 69.3 un senador propio a la isla de Formentera (el Senado de elección directa pasa de 208 a 209)","Sustituir el nombre del Ejército del Aire en el art. 8","Reformar el art. 155 para limitarlo","Eliminar el requisito de refrendo de los actos del Rey"],"BOE 20-5-2026: la más reciente (y la cuarta) reforma toca la composición del Senado de elección directa: Formentera deja de estar integrada con la de las Pitiusas y gana senador propio (208 → 209).","Reforma art. 69.3 CE · BOE 20-5-2026"]
]
assert len(RAW) == 50, "RAW tiene %d" % len(RAW)
import io
PATRON = [(p + j) % 4 for j in range(13) for p in range(4)][:50]
filas = []
for i, ((dif, q, ops, x, r), dest) in enumerate(zip(RAW, PATRON), 1):
    correcta = ops[0]; resto = ops[1:]
    nuevas = resto[:dest] + [correcta] + resto[dest:]
    esc = lambda t: t.replace('"', '\\"')
    filas.append('{c:"cabo",b:"C1",t:"Constitución",d:"%s",id:"ce%02d",q:"%s",o:[%s],a:%d,x:"%s",r:"%s"}' % (dif, i, esc(q), ",".join('"%s"' % esc(o) for o in nuevas), dest, esc(x), esc(r)))
LOTE12 = (',\n/* ===== LOTE EXAMINADOR — Tema 12: La Constitución Española de 1978\n'
'   Elaboración PROPIA (examinador GALÓN), 21-sep-2026, 100% contra el texto consolidado (BOE-A-1978-31229; BOE núm.\n'
'   311, de 29-12-1978): Preámbulo + Título Preliminar (1-9) + 10 Títulos + 169 artículos + 4 DA + 9 DT + 1 DD + 1 DF.\n'
'   Estructura Título I: arts. 10-55 (el más extenso). Art. 8.1 misión y composición FAS (nota: el texto constitucional\n'
'   dice literalmente "Ejército del Aire"; la denominación "y del Espacio" es reglamentaria de 2022 y NO reformó la CE).\n'
'   Leyes orgánicas (81), decreto-ley (86), sanción real (91), referéndum (92), Gobierno (97), investidura (99),\n'
'   responsabilidad solidaria (108), confianza (112), censura constructiva (113), estados (116 + LO 4/1981), Poder\n'
'   Judicial (117, 122.3, 123, 124, 125), territorio (137, 149.1.4ª, 155), TC (159), reforma (167/168/169).\n'
'   REFORMAS verificadas: 13.2 (BOE 28-8-1992, Maastricht) · 135 (BOE 27-9-2011, estabilidad presupuestaria) ·\n'
'   49 (BOE-A-2024-3099, personas con discapacidad) · 69.3 (BOE 20-5-2026, senador propio para Formentera, 208→209).\n'
'   Todas por el art. 167; el 168 sigue sin usarse. ATENCIÓN: apuntes con "la CE solo se ha reformado dos veces" están\n'
'   OBSOLETOS (desde 2024 hay 3 y desde mayo de 2026 hay 4). */\n')
s = io.open('/home/user/galon/js/bank7.js', encoding='utf-8').read().rstrip()
assert s.endswith('];')
s = s[:-2] + LOTE12 + ",\n".join(filas) + "\n];\n"
io.open('/home/user/galon/js/bank7.js', 'w', encoding='utf-8').write(s)
from collections import Counter
difs = Counter(r[0] for r in RAW)
print("Lote Tema 12 montado: 50 · reparto correctas:", dict(sorted(Counter(PATRON).items())), "· dificultades:", dict(sorted(difs.items())))
