#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Lote Tema 5 · Organización de la Defensa (LODEF LO 5/2005 + Ley 39/2007) — 50 preguntas, formato: [dif, pregunta, opciones(correcta=0), explicación, ref]
RAW = [
["F","Según el artículo 1 de la LO 5/2005, de 17 de noviembre (LODEF), esta ley orgánica:",["Regula la defensa nacional y establece las bases de la organización militar conforme a los principios establecidos en la Constitución","Regula únicamente la organización de los tres Ejércitos","Regula los derechos y deberes de los militares","Regula el régimen disciplinario de las Fuerzas Armadas"],"Objeto de la LODEF: defensa nacional + bases de la organización militar. Se dicta de acuerdo con el art. 8.2 CE y en ejercicio de la competencia del art. 149.1.4ª CE.","LO 5/2005 art. 1"],
["M","La política de defensa tiene por finalidad la protección del conjunto de la sociedad española, de su Constitución, de los valores superiores, principios e instituciones, del Estado social y democrático de derecho, del pleno ejercicio de los derechos y libertades y de la garantía, independencia e integridad territorial de España. Además, tiene por objetivo:",["Contribuir a la preservación de la paz y seguridad internacionales, en el marco de los compromisos contraídos por el Reino de España","La intervención en cualquier conflicto internacional","El control del comercio mundial de armas","Sustituir a la diplomacia española en el exterior"],"Art. 2: protección interna + proyección exterior: contribuir a la preservación de la paz y seguridad internacionales.","LO 5/2005 art. 2"],
["F","Según el artículo 8.1 de la Constitución, las Fuerzas Armadas tienen por misión:",["Garantizar la soberanía e independencia de España, defender su integridad territorial y el ordenamiento constitucional","Garantizar la seguridad ciudadana en todo el territorio nacional","Defender los intereses económicos de España en el exterior","Sostener el orden público exclusivamente"],"CE art. 8.1, literal que la LODEF recoge en su art. 15.1. La seguridad ciudadana es de las Fuerzas y Cuerpos de Seguridad (art. 104 CE).","CE art. 8.1 · LODEF art. 15.1"],
["F","El artículo 8.2 de la Constitución encomienda a una ley orgánica regular:",["Las condiciones y las bases del modo en que, en los casos de grave riesgo, catástrofe o calamidad pública, puedan intervenir las Fuerzas Armadas y, en su caso, la atribución al Gobierno de facultades extraordinarias","El régimen económico de las Fuerzas Armadas","La organización de las Delegaciones de Defensa","El estatuto del personal civil de Defensa"],"CE art. 8.2: base de la intervención de las FAS ante emergencias (y de la propia LODEF). La LODEF lo desarrolla en sus arts. 15.3 y 16.e.","CE art. 8.2"],
["M","En materia de defensa, el artículo 149.1.4ª de la Constitución establece que es una competencia:",["Exclusiva del Estado","Compartida entre el Estado y las comunidades autónomas","Delegable en las diputaciones","Concurrente Estado-comunidades"],"Defensa y FAS: competencia EXCLUSIVA del Estado. Trampa clásica con la compartida.","CE art. 149.1.4ª"],
["F","Según el artículo 3 de la LODEF, corresponden al Rey:",["El mando supremo de las Fuerzas Armadas y las demás funciones que en materia de defensa le confiere la Constitución y el resto del ordenamiento jurídico","El mando operativo de las Fuerzas Armadas","La dirección de la política de defensa","La ejecución de la política militar"],"Art. 3 (La Corona), eco del art. 62.h CE: mando supremo. La dirección de la política de defensa es del Presidente del Gobierno (art. 6).","LODEF art. 3 · CE art. 62.h"],
["M","Según el artículo 97 de la Constitución, el Gobierno:",["Dirige la política interior y exterior, la Administración civil y militar y la defensa del Estado","Ejerce el mando supremo de las Fuerzas Armadas","Ejerce la más alta representación de España en materia de defensa","Aprueba los estados de alarma por sí solo"],"CE art. 97: Administración civil y MILITAR. La más alta representación es del Rey (art. 56) y el mando supremo también (62.h).","CE art. 97"],
["D","El Gobierno quiere enviar un contingente humanitario a un país en conflicto, pero su presidente se niega a pedirlo y no hay resolución de la ONU. Según el art. 19 de la LODEF, una misión en el exterior no directamente relacionada con la defensa requiere, entre otras condiciones:",["Que se realice por petición expresa del Gobierno del Estado en cuyo territorio se desarrolle, o que esté autorizada por Resolución del Consejo de Seguridad de la ONU o acordada por organizaciones internacionales de las que España forme parte (UE, OTAN)","Que se realice siempre por invitación de la OTAN, sin excepción","Que lo apruebe el Rey previamente","Que el Congreso declare el estado de sitio"],"Art. 19.a: petición expresa del anfitrión, CSNU o UE/OTAN; b: fines defensivos, humanitarios, de estabilización o de paz; c: conformidad con la Carta de la ONU.","LODEF art. 19 · caso"],
["D","En las reuniones de defensa se discute quién DETERMINA la política de defensa. Según la LODEF:",["El Gobierno: determinar la política de defensa y asegurar su ejecución, dirigir la Administración militar y acordar la participación de las FAS en misiones fuera del territorio nacional","El Presidente del Gobierno, porque dirige la política de defensa","El Ministro de Defensa, porque ejecuta la política de defensa","El Consejo de Defensa Nacional, porque es el órgano decisor"],"Trampa fina: el Gobierno DETERMINA (art. 5); el Presidente DIRIGE (art. 6); el Ministro DESARROLLA Y EJECUTA (art. 7). Y el CDN es asesor, no decide.","LODEF arts. 5, 6 y 7 · caso"],
["F","Según el artículo 6.1 de la LODEF, corresponde al Presidente del Gobierno:",["La dirección de la política de defensa y la determinación de sus objetivos, la gestión de las situaciones de crisis que afecten a la defensa y la dirección estratégica de las operaciones militares en caso de uso de la fuerza","El desarrollo y la ejecución de la política de defensa","El mando de la estructura operativa de las Fuerzas Armadas","La elaboración y definición de la estrategia militar"],"Art. 6.1 literal. El desarrollo y ejecución es del Ministro (7.1); el mando de la estructura operativa, del JEMAD (12.3.b); la estrategia militar, del JEMAD (12.3.e).","LODEF art. 6.1"],
["M","Según el artículo 6.2 de la LODEF, el Presidente del Gobierno:",["Ejerce su autoridad para ordenar, coordinar y dirigir la actuación de las Fuerzas Armadas así como disponer su empleo","Ejerce el mando disciplinario sobre los generales","Preside las academias militares","Nombra a los jefes de Estado Mayor por sí solo"],"Art. 6.2: ordenar, coordinar y dirigir la actuación de las FAS y disponer su empleo.","LODEF art. 6.2"],
["F","¿Quién formula la Directiva de Defensa Nacional?",["El Presidente del Gobierno","El Ministro de Defensa","El Jefe de Estado Mayor de la Defensa","El Consejo de Defensa Nacional"],"Art. 6.3.a: formular la Directiva de Defensa Nacional, con las líneas generales de la política de defensa y las directrices para su desarrollo.","LODEF art. 6.3.a"],
["M","Según el artículo 6.3.d de la LODEF, las misiones de las Fuerzas Armadas las ordena:",["El Presidente del Gobierno","El Ministro de Defensa","El Jefe de Estado Mayor de la Defensa","El Congreso de los Diputados"],"Art. 6.3.d: ordenar las misiones de las FAS. Trampa con el Ministro: él dirige la actuación BAJO la autoridad del Presidente.","LODEF art. 6.3.d"],
["F","Según el artículo 7.1 de la LODEF, corresponde al Ministro de Defensa:",["El desarrollo y la ejecución de la política de defensa","La dirección de la política de defensa y la determinación de sus objetivos","El mando supremo de las Fuerzas Armadas","La conducción estratégica de las operaciones militares"],"Art. 7.1: desarrollo y ejecución. La DIRECCIÓN es del Presidente (art. 6.1).","LODEF art. 7.1"],
["M","Entre las competencias específicas del Ministro de Defensa (art. 7.2 LODEF) figuran:",["Asistir al Presidente del Gobierno en la dirección estratégica de las operaciones militares, dirigir la actuación de las FAS bajo la autoridad del Presidente y determinar y ejecutar la política militar","Formular la Directiva de Defensa Nacional y ordenar las misiones de las FAS","Ejercer el mando de la estructura operativa de las Fuerzas Armadas","Presidir el Consejo de Defensa Nacional"],"Art. 7.2.a-b-c. La Directiva y las misiones: Presidente; la estructura operativa: JEMAD; el CDN lo preside el Presidente del Gobierno.","LODEF art. 7.2"],
["D","El examen distingue política de DEFENSA de política MILITAR. Según la LODEF, la política militar la determina y ejecuta:",["El Ministro de Defensa (art. 7.2.c)","El Presidente del Gobierno (art. 6)","El Gobierno en pleno (art. 5)","El Jefe de Estado Mayor de la Defensa (art. 12)"],"Política de DEFENSA: la dirige el Presidente y la ejecuta el Ministro. La política MILITAR la determina y ejecuta el Ministro. Favorita de examinador.","LODEF arts. 6 y 7 · caso"],
["M","Según el artículo 4.1 de la LODEF, a las Cortes Generales les corresponde:",["Aprobar las leyes relativas a la defensa y los créditos presupuestarios correspondientes, debatir las líneas generales de la política de defensa y controlar la acción del Gobierno en materia de defensa","Ejercer el mando conjunto de las operaciones","Designar al Jefe de Estado Mayor de la Defensa","Aprobar la estrategia militar"],"Art. 4.1.b-c-d: leyes y créditos, debate de líneas generales y control de la acción del Gobierno.","LODEF art. 4.1"],
["F","La autorización, con carácter PREVIO, para la participación de las FAS en misiones fuera del territorio nacional corresponde a:",["El Congreso de los Diputados","El Senado","El Rey","El Consejo de Defensa Nacional"],"Art. 4.2: al CONGRESO en particular le corresponde autorizar con carácter previo. El CDN no autoriza: asesora.","LODEF art. 4.2"],
["M","Para ordenar operaciones en el exterior que NO estén directamente relacionadas con la defensa de España o del interés nacional, el Gobierno:",["Realizará una consulta previa y recabará la autorización del Congreso de los Diputados","Solo informará al Senado una vez concluida la operación","Necesitará real decreto con acuerdo del Consejo de Estado","Podrá actuar sin trámite alguno"],"Art. 17.1: consulta previa + autorización del Congreso.","LODEF art. 17.1"],
["D","Una evacuación urgente de españoles obliga a actuar de inmediato, sin consulta previa al Congreso. Según el art. 17.3 de la LODEF:",["El Gobierno someterá al Congreso de los Diputados, lo antes posible, la decisión que haya adoptado para la ratificación, en su caso","La operación queda exenta de todo control parlamentario","El Rey ratifica la decisión en su lugar","El Gobierno debe pedir permiso al país anfitrión en su defecto"],"Art. 17.2: trámites de urgencia; 17.3: si la máxima urgencia impide la consulta previa, someter la decisión al Congreso lo antes posible para ratificación.","LODEF art. 17.2-3 · caso"],
["F","Sobre el seguimiento de las operaciones en el exterior, el Gobierno informará al Congreso de los Diputados:",["Periódicamente, en un plazo en ningún caso superior a un año","Una única vez al finalizar la misión","Solo cuando el Congreso se lo pida expresamente","Cada seis meses como máximo en todos los casos"],"Art. 18: seguimiento periódico con plazo máximo de UN AÑO. Lo de cada seis meses es de cuadernillo, no de la ley.","LODEF art. 18"],
["F","El Consejo de Defensa Nacional es:",["El órgano colegiado, coordinador, asesor y consultivo del Presidente del Gobierno en materia de defensa","El órgano decisor superior del Ministerio de Defensa","Un órgano del Congreso para controlar la defensa","El máximo órgano de mando operativo de las FAS"],"Art. 8.1, literal completo: colegiado, coordinador, asesor y consultivo DEL PRESIDENTE. Asesora, no manda.","LODEF art. 8.1"],
["M","El Delegado de Defensa en una comunidad autónoma es nombrado:",["Por el Ministro de Defensa, a propuesta del Subsecretario de Defensa, entre Oficiales Generales y Oficiales en situación de servicio activo o reserva","Por el presidente de la comunidad autónoma","Por el JEMAD","Por sorteo entre coroneles"],"Hay una Delegación de Defensa en cada CA y en Ceuta y Melilla. El Subdelegado lo nombra el Subsecretario, a propuesta de la Secretaría General Técnica.","RD 308/2007 arts. 6-7"],
["M","El Consejo de Defensa Nacional en pleno se compone, entre otros, de:",["El Presidente del Gobierno, los Vicepresidentes, los Ministros de Defensa, Interior, Asuntos Exteriores y Economía y Hacienda, el JEMAD, los JEMEs, el Secretario de Estado Director del CNI y el Director del Gabinete de la Presidencia","Únicamente los ministros con competencias militares","Los ministros y todos los generales de la reserva","Los presidentes de las comunidades autónomas como miembros natos"],"Art. 8.5 literal. Las autoridades de las CCAA se convocan solo cuando se estime oportuno (8.8): no son miembros natos.","LODEF art. 8.5"],
["D","¿Cuál de estos cargos NO es miembro nato del Consejo de Defensa Nacional en pleno?",["El Ministro de Justicia","El Director del Gabinete de la Presidencia del Gobierno","El Secretario de Estado Director del Centro Nacional de Inteligencia","El Jefe de Estado Mayor de la Armada"],"El pleno (8.5) incluye a Defensa, Interior, AAEE y Economía y Hacienda; Justicia no figura. El Director del Gabinete, el Director del CNI y los tres JEMEs sí.","LODEF art. 8.5 · caso"],
["M","El consejo ejecutivo del CDN lo integran:",["El Presidente del Gobierno, los Ministros de Defensa, del Interior y de Asuntos Exteriores, el JEMAD, el Secretario de Estado Director del CNI y el Director del Gabinete de la Presidencia","Todos los ministros del Gobierno y los tres JEMEs","Solo los ministros, sin mando militar","Los mismos que el pleno, más los JEMEs"],"Art. 8.6: más reducido que el pleno y, ojo, SIN los JEMEs de los Ejércitos. Trampa típica.","LODEF art. 8.6"],
["M","Según el artículo 8.2 de la LODEF, el Consejo de Defensa Nacional:",["En pleno informará al Rey, a propuesta del Presidente del Gobierno, y cuando el Rey asista a las reuniones, lo presidirá","Debe aprobar todas sus decisiones con la firma del Rey","Solo puede reunirse en presencia del Rey","El Rey lo preside siempre, asista o no"],"Art. 8.2: informe al Rey a propuesta del Presidente; si el Rey asiste, PRESIDE él. En su ausencia, preside el Presidente del Gobierno.","LODEF art. 8.2"],
["F","El órgano de trabajo permanente del Consejo de Defensa Nacional es:",["La Comisión Interministerial de Defensa, adscrita al Ministerio de Defensa","El Estado Mayor de la Defensa","El Mando de Operaciones","La Subsecretaría de Defensa"],"Art. 8.9: la Comisión Interministerial de Defensa, adscrita al Ministerio de Defensa, como órgano de trabajo permanente.","LODEF art. 8.9"],
["M","El Ministerio de Defensa es:",["El departamento de la Administración General del Estado al que corresponde la preparación, el desarrollo y la ejecución de la política de defensa y la obtención y gestión de los recursos humanos y materiales, y en el que se integran las Fuerzas Armadas","Un organismo autónomo dependiente del Congreso","La unión de los tres Ejércitos con independencia del Gobierno","Un órgano del Consejo de Seguridad Nacional"],"Art. 9: departamento de la AGE; las FAS se integran en el Ministerio para dar vertebración al conjunto.","LODEF art. 9"],
["M","Según el artículo 10.1 de la LODEF, las Fuerzas Armadas:",["Son el elemento esencial de la defensa y constituyen una entidad única que se concibe como un conjunto integrador de las formas de acción específicas de cada uno de sus componentes: el Ejército de Tierra, la Armada y el Ejército del Aire","Son tres ejércitos independientes coordinados por el Congreso","Son un órgano de la Unión Europea","Son el elemento esencial de la seguridad ciudadana"],"Art. 10.1: elemento esencial de la DEFENSA, entidad ÚNICA, conjunto INTEGRADOR. Tres palabras clave de examen.","LODEF art. 10.1"],
["F","Las Fuerzas Armadas se organizan en dos estructuras:",["Una orgánica, para la preparación de la fuerza, y otra operativa, para su empleo en las misiones que se le asignen","Una territorial y otra funcional","Una permanente y otra de reserva","Una central y otra periférica"],"Art. 11.1, literal. La orgánica posibilita la generación de la operativa (art. 11.2).","LODEF art. 11.1"],
["M","Según el artículo 11.3 de la LODEF, la estructura operativa se organizará con arreglo a:",["El principio de unidad de mando y a los criterios necesarios para la consecución de la máxima capacidad operativa","El principio de especialidad por Ejércitos","El principio de proximidad territorial","El principio de mando colegiado"],"Art. 11.3: unidad de mando en la operativa. La orgánica se establece con criterios de funcionalidad y organización homogénea (11.2).","LODEF art. 11.2-3"],
["D","Un recluta pregunta quién PREPARA y quién EMPLEA la Fuerza. Según la LODEF:",["La preparación corresponde a la estructura orgánica de los Ejércitos (JEMEs) y el empleo a la estructura operativa, cuyo mando ejerce el JEMAD","Ambas cosas las hace el JEMAD","La preparación es del Ministerio de Asuntos Exteriores y el empleo del Ministro","Nada de eso lo regula la ley"],"Esencia de la LODEF (art. 11 y Exposición de Motivos): los Ejércitos preparan la Fuerza y la ponen a disposición de la estructura operativa, que la emplea.","LODEF arts. 11, 12 y 13 · caso"],
["F","El Estado Mayor de la Defensa es:",["El órgano auxiliar de mando y apoyo al Jefe de Estado Mayor de la Defensa, con un Cuartel General y un Mando de Operaciones subordinado","Un órgano del Gobierno para las crisis internacionales","El órgano de trabajo del Consejo de Defensa Nacional","El órgano encargado del reclutamiento"],"Art. 12.1: órgano auxiliar de mando y apoyo al JEMAD; y 12.2: con Cuartel General y Mando de Operaciones subordinado.","LODEF art. 12"],
["M","Según el artículo 12.3.b de la LODEF, el JEMAD:",["Ejerce, bajo la dependencia del Ministro de Defensa, el mando de la estructura operativa de las Fuerzas Armadas y la conducción estratégica de las operaciones militares","Ejerce el mando de los tres Ejércitos","Depende directamente del Rey","Preside el Gobierno en materias de defensa"],"Art. 12.3.b: mando de la ESTRUCTURA OPERATIVA (no de los Ejércitos) y conducción estratégica de las operaciones, bajo dependencia del Ministro.","LODEF art. 12.3.b"],
["M","El JEMAD ejerce la función de asesoramiento militar a:",["El Presidente del Gobierno y el Ministro de Defensa, a los que auxiliará en la dirección estratégica de las operaciones militares","Únicamente al Ministro de Defensa","Únicamente al Rey","Las Cortes Generales"],"Art. 12.3.a: asesoramiento al Presidente Y al Ministro. Desconfía del únicamente.","LODEF art. 12.3.a"],
["M","Según el artículo 12.4 de la LODEF, respecto de los Jefes de Estado Mayor de los Ejércitos, el JEMAD:",["Los coordina y les imparte directrices para orientar la preparación de la Fuerza, con el objeto de asegurar la eficacia operativa de las Fuerzas Armadas","Les da órdenes operativas directas en todo caso","Es su subordinado","Preside sus academias"],"Art. 12.4: COORDINA e imparte directrices para la PREPARACIÓN. No manda los Ejércitos: ese mando es de cada JEME bajo la autoridad del Ministro (art. 13.2).","LODEF art. 12.4"],
["D","El JEME de un Ejército es herido en accidente y no puede ejercer. ¿Quién lo sustituye con carácter accidental?",["El Oficial General en servicio activo más antiguo de los que estén subordinados en su estructura orgánica","El JEMAD, que manda directamente el Ejército","El Delegado de Defensa de la comunidad autónoma","El Oficial General más antiguo de los tres Ejércitos"],"Art. 13.2: sustitución de los JEMEs por el Oficial General en activo más antiguo de los subordinados en su estructura orgánica. El JEMAD no manda los Ejércitos.","LODEF art. 13.2 · caso"],
["M","Si el que no puede ejercer es el JEMAD, le sustituye con carácter accidental:",["El Jefe de Estado Mayor del Ejército de Tierra, de la Armada o del Ejército del Aire de más antigüedad","El Secretario de Estado de Defensa","El más antiguo de los Subdelegados de Defensa","El Director del CNI"],"Art. 12.2: entre los tres JEMEs, el de más antigüedad.","LODEF art. 12.2 · caso"],
["F","Cada Ejército (Tierra, Armada y Aire) está compuesto por:",["El Cuartel General, la Fuerza y el Apoyo a la Fuerza","El Cuartel General, la Reserva y el Estado Mayor","La Fuerza, el Apoyo y la Inspección","El Mando, el Cuartel General y la Academia"],"Art. 13.1: Cuartel General (asistencia al JEME), Fuerza (preparación para operaciones) y Apoyo a la Fuerza (gestión, mantenimiento y logística).","LODEF art. 13.1"],
["M","Además de la misión del art. 8.1 CE, el artículo 15.2 de la LODEF dice que las FAS contribuyen:",["Militarmente a la seguridad y defensa de España y de sus aliados, en el marco de las organizaciones internacionales de las que España forma parte, así como al mantenimiento de la paz, la estabilidad y la ayuda humanitaria","Al desarrollo económico de los países vecinos","Al control migratorio europeo de forma exclusiva","A la política comercial española"],"Art. 15.2: contribución militar a la seguridad y defensa de España y aliados + paz, estabilidad y ayuda humanitaria.","LODEF art. 15.2"],
["F","Las FAS pueden llevar a cabo misiones de evacuación de los residentes españoles en el extranjero:",["Cuando circunstancias de inestabilidad en un país pongan en grave riesgo su vida o sus intereses","Cualquier año, con carácter turístico","Solo en países miembros de la OTAN","Cuando lo pida cualquier particular español"],"Art. 15.4: evacuación de residentes ante grave riesgo por inestabilidad. Muy preguntada.","LODEF art. 15.4"],
["M","Entre los tipos de operaciones del artículo 16 de la LODEF figura:",["El apoyo a las Fuerzas y Cuerpos de Seguridad del Estado en la lucha contra el terrorismo y a los servicios de rescate en las tareas de búsqueda y salvamento","La gestión de las academias militares","La administración de justicia militar","La negociación de tratados comerciales"],"Art. 16.c. Otras: vigilancia de espacios marítimos y aéreos (a), mantenimiento de la paz y estabilización (b), respuesta a aeronaves terroristas (d), colaboración con las AAPP en grave riesgo (e) y seguridad de los españoles en el exterior (f).","LODEF art. 16"],
["F","Según el artículo 20 de la LODEF, las reglas esenciales del comportamiento de los militares (disciplina, jerarquía, límites de la obediencia y ejercicio del mando) se establecen:",["Mediante ley, de acuerdo con la Constitución, y el Gobierno las desarrolla mediante Real Decreto en las Reales Ordenanzas para las Fuerzas Armadas","Por cada Ejército en sus reglamentos internos","Por costumbre en cada unidad","Por el Consejo de Defensa Nacional"],"Art. 20: la ley es la LO 8/2014 (Tema 2) y el RD de desarrollo son las RROO (Tema 1). Así enlaza los tres temas el examinador.","LODEF art. 20 · LO 8/2014 · RROO"],
["D","Se declara el estado de sitio. Según el art. 22.2 de la LODEF, el sistema de disponibilidad permanente de recursos:",["Será coordinado por el Consejo de Defensa Nacional","Lo dirige el Ministro de Economía en exclusiva","Se disuelve y se reparte entre las comunidades autónomas","Lo asume la OTAN"],"Art. 22.1: el Gobierno establece los criterios de preparación y disponibilidad de los recursos no militares; 22.2: en conflicto armado y estado de sitio, coordina el CDN.","LODEF art. 22 · caso"],
["D","En conflicto bélico y estado de sitio, ¿quién coordina a la Guardia Civil y de quién depende?",["El Consejo de Defensa Nacional la coordina y depende directamente del Ministro de Defensa","El Ministro del Interior la coordina como siempre","El JEMAD la manda directamente","La coordina la OTAN"],"Art. 25: GC coordinada por el CDN dependiendo del Ministro de DEFENSA. Trampa: el CNP sí depende del Ministro del INTERIOR (art. 27).","LODEF arts. 25 y 27 · caso"],
["F","En tiempo de conflicto bélico y durante la vigencia del estado de sitio, las actuaciones del sistema de cooperación en materia de Protección Civil son coordinadas por:",["El Consejo de Defensa Nacional","El Ministerio de Transportes","El Consejo de Seguridad de la ONU","Las comunidades autónomas"],"Art. 28: el CDN coordina la Protección Civil en conflicto bélico/estado de sitio.","LODEF art. 28"],
["F","¿Qué regula la Ley 39/2007, de 19 de noviembre?",["La carrera militar","El régimen del personal militar profesional","Los derechos y deberes de los militares","La jurisdicción militar"],"Ley 39/2007, de 19 de noviembre, de la CARRERA MILITAR (su compañera es la Ley 40/2007, del régimen del personal militar profesional). No confundir títulos.","Ley 39/2007 (19-nov-2007)"],
["M","Según el artículo 19.1 de la Ley 39/2007 (carrera militar), el militar profesional ejerce funciones:",["Operativas, técnicas, logísticas y administrativas","Únicamente operativas","Exclusivamente de mando","Administrativas solo en tiempo de paz"],"Art. 19.1: funciones operativas, técnicas, logísticas y administrativas, desarrolladas por medio de acciones directivas (que incluyen las de mando), de gestión y ejecutivas.","Ley 39/2007 art. 19.1"],
["M","Según la estructura orgánica básica del Ministerio de Defensa, el Ministerio se estructura en:",["La Secretaría de Estado de Defensa, la Subsecretaría de Defensa, la Secretaría General de Política de Defensa y las Fuerzas Armadas","Únicamente los tres Ejércitos","El Congreso, el Senado y el Ministerio","La Guardia Civil y el CNI como únicos órganos"],"Estructura orgánica básica: SEDEF, Subsecretaría, SEGENPOL y FAS. El CNI está adscrito al Ministerio, con dependencia directa del Ministro.","RD 1287/2010 · organigrama defensa.gob.es"]
]
assert len(RAW) == 50, "RAW tiene %d" % len(RAW)
import io
PATRON = [(p + j) % 4 for j in range(13) for p in range(4)][:50]
filas = []
for i, ((dif, q, ops, x, r), dest) in enumerate(zip(RAW, PATRON), 1):
    correcta = ops[0]; resto = ops[1:]
    nuevas = resto[:dest] + [correcta] + resto[dest:]
    esc = lambda t: t.replace('"', '\\"')
    filas.append('{c:"cabo",b:"C1",t:"Organización de la Defensa",d:"%s",id:"od%02d",q:"%s",o:[%s],a:%d,x:"%s",r:"%s"}' % (dif, i, esc(q), ",".join('"%s"' % esc(o) for o in nuevas), dest, esc(x), esc(r)))
LOTE5 = (',\n/* ===== LOTE EXAMINADOR — Tema 5: Organización de la Defensa (LODEF LO 5/2005, de 17 de noviembre + CE + Ley 39/2007)\n'
'   Elaboración PROPIA (examinador GALÓN), 20-sep-2026, sobre texto oficial verificado: BOE consolidado LO 5/2005\n'
'   con ÚLTIMA ACTUALIZACIÓN 18/11/2005 = SIN MODIFICACIONES desde su entrada en vigor (la anunciada reforma con\n'
'   "situación operativa especial" NO está en vigor: EN TRÁMITE, no preguntar como vigente). Literales verificados:\n'
'   arts. 1-2 (objeto y finalidad), 3 (La Corona), 4 (Cortes y autorización previa del Congreso), 5-7 (Gobierno\n'
'   determina / Presidente dirige / Ministro desarrolla y ejecuta), 8 (CDN: pleno, consejo ejecutivo, Rey, Comisión\n'
'   Interministerial), 9-13 (Ministerio, FAS entidad única, estructuras orgánica y operativa, EMAD/JEMAD, Ejércitos),\n'
'   15-19 (misiones, tipos de operaciones, autorización urgencia y seguimiento 1 año, condiciones), 20-22 (reglas\n'
'   esenciales → LO 8/2014 + RROO, régimen disciplinario, recursos y CDN), 25/27/28 (GC/CNP/Protección Civil),\n'
'   Ley 39/2007 art. 19 (carrera militar: funciones operativas, técnicas, logísticas y administrativas), RD 308/2007\n'
'   (Delegaciones/Subdelegaciones de Defensa) y RD 1287/2010 (estructura básica de Mindef; CNI adscrito). */\n')
s = io.open('/home/user/galon/js/bank7.js', encoding='utf-8').read().rstrip()
assert s.endswith('];')
s = s[:-2] + LOTE5 + ",\n".join(filas) + "\n];\n"
io.open('/home/user/galon/js/bank7.js', 'w', encoding='utf-8').write(s)
from collections import Counter
print("Lote Tema 5 montado: 50 · reparto correctas:", dict(sorted(Counter(PATRON).items())))
