#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Lote Tema 11 · Primeros auxilios — 50 preguntas, formato: [dif, pregunta, opciones(correcta=0), explicación, ref]
# Fuentes verificadas 20-sep-2026: GUÍAS ERC 2025 (Consejo Europeo de Reanimación, publicadas el 23-oct-2025; traducción
# del CERCP): secuencia simplificada «Comprobar – Llamar – RCP», compresiones 100-120/min, profundidad 5-6 cm,
# reexpansión completa, interrupciones <10 s, 30:2 en reanimador entrenado, RCP solo manos válida, DEA en cuanto
# disponible, cambio de reanimador por fatiga, 5 ventilaciones iniciales en niño y ahogamiento · CRUZ ROJA (quemaduras:
# apartar fuente de calor, enfriar con chorro suave de agua fría 10-15 min o más si duele; no hielo; no reventar
# ampollas; epistaxis cabeza adelante; golpe de calor sin alcohol) · 112 número único de emergencia de la UE.
RAW = [
["F","La «P» del protocolo PAS (Proteger) consiste en:",["Alejar el peligro y asegurarte de que ni tú, ni la víctima ni los demás sufran daño antes de actuar","Proteger los bolsillos del herido","Cubrir la herida con la mano","Ponerse el casco"],"Sin seguridad no hay socorro: si te lesionas, habrá DOS víctimas. Proteger siempre es el primer paso.","Cruz Roja · PAS"],
["F","El número único de emergencias válido en toda la Unión Europea es:",["112","066","911","080"],"El 112 es gratuito y funciona en toda la UE (en España coexiste con 061 sanitario y 091/092 policiales).","112 · número único europeo"],
["F","En la RCP del adulto, el reanimador entrenado alterna:",["30 compresiones y 2 ventilaciones","15 compresiones y 15 ventilaciones","50 compresiones y 5 ventilaciones","2 compresiones y 30 ventilaciones"],"Relación 30:2 confirmada por las guías ERC 2025 (si no sabes o no quieres ventilar: RCP solo manos, también válida).","ERC 2025 · SVB"],
["F","El ritmo correcto de las compresiones torácicas es:",["Entre 100 y 120 por minuto","Entre 40 y 60 por minuto","Entre 150 y 200 por minuto","Al azar, lo más rápido posible"],"100-120 compresiones por minuto (el compás de «Stayin' Alive»): menos no perfunde y más no llena el corazón.","ERC 2025 · SVB"],
["F","La profundidad de las compresiones en el adulto es:",["Entre 5 y 6 centímetros","Entre 1 y 2 centímetros","Entre 10 y 12 centímetros","Lo que aguante el paciente"],"Al menos 5 cm y no más de 6: menos no genera flujo y más causa lesiones. Con reexpansión completa del tórax entre compresiones.","ERC 2025 · SVB"],
["F","Las interrupciones de las compresiones durante la RCP deben ser:",["De menos de 10 segundos","De hasta 1 minuto","Las necesarias para descansar","De 30 segundos tras cada ciclo"],"Cada parada de compresiones frena el flujo sanguíneo cerebral: se cambian de reanimador o de ritmo en menos de 10 segundos.","ERC 2025 · SVB"],
["F","El DEA (desfibrilador externo automático) se conecta:",["En cuanto esté disponible, siguiendo sus instrucciones de voz","Solo cuando llegue el médico","Después de 30 minutos de RCP","Solo si la víctima es mayor de 65 años"],"La desfibrilación precoz es el eslabón que más vidas salva: el DEA analiza y descarga solo, guiando al socorrista con mensajes.","ERC 2025 · DEA"],
["F","La posición lateral de seguridad se aplica a una víctima:",["Inconsciente que respira con normalidad","Consciente que camina","Que no respira","Con fractura abierta de pelvis"],"Respira = no se hace RCP, pero hay que protegerle la vía aérea de vómito o lengua: boca arriba, la PLS lo garantiza.","Cruz Roja · PLS"],
["F","Ante una quemadura, después de apartar la fuente de calor, se enfría la zona:",["Con agua fresca en chorro suave, entre 10 y 20 minutos","Con hielo directo 2 minutos","Con mantequilla o pasta de dientes","Soplando sobre la quemadura"],"Cruz Roja: chorro suave de agua fría 10-15 minutos (otros protocolos hasta 20) o más si continúa el dolor. El frío corta el daño en profundidad.","Cruz Roja · quemaduras"],
["F","Con una quemadura con ampollas está PROHIBIDO:",["Reventar las ampollas y aplicar hielo o remedios caseros","Taparla con una gasa limpia","Enfriarla con agua fresca","Apartar la fuente de calor"],"La ampolla es un apósito biológico: reventarla abre la puerta a la infección; el hielo empeora el daño tisular.","Cruz Roja · quemaduras"],
["F","Ante un adulto consciente atragantado (no puede respirar ni hablar), se alterna:",["5 golpes en la espalda con 5 compresiones abdominales","5 vaso de agua con 5 respiraciones","Besarle el esternón con 5 palmadas en la frente","Levantarle las piernas con 5 sacudidas"],"Hasta 5 golpes dorsales (talón de la mano, entre los omóplatos) alternando con hasta 5 compresiones abdominales (Heimlich).","ERC · obstrucción de vía aérea"],
["F","Ante una fractura de extremidad, la primera medida es:",["Inmovilizarla tal como está, sin intentar encajarla","Tirar del miembro para alinearlo","Dar a la víctima un analgésico de botiquín","Masajear la zona para quitar el dolor"],"Encajar una fractura puede cortar arterias y nervios: se inmoviliza en la posición encontrada, cubriendo también la articulación de arriba y de abajo.","Cruz Roja · fracturas"],
["F","Con un cuchillo (u otro objeto) empotrado en una herida:",["No se extrae: se fija con vendajes y se traslada","Se tira de él con decisión","Se gira antes de sacarlo","Se lava con agua y se guarda para el médico"],"El objeto está «tapando» los vasos rotos: extraerlo libera la hemorragia. Se estabiliza y solo lo retira el personal sanitario.","Cruz Roja · heridas"],
["F","Ante una hemorragia externa moderada, la primera medida es:",["Presionar directamente la herida con una gasa o paño limpio","Ponerle una cruz de cinta adhesiva","Hacerle beber agua con azúcar","Elevarle las piernas cinco minutos"],"La presión directa corta la sangría en la mayoría de los casos; sobre ella, gasa y vendaje compresivo.","Cruz Roja · hemorragias"],
["F","Si se aplica un torniquete, SIEMPRE hay que:",["Anotar la hora de colocación (en la frente del herido o en el propio torniquete)","Taparlo con la manga para que no se vea","Aflojarlo cada 5 minutos","Mojarlo para que no se pegue"],"El equipo sanitario necesita saber cuánto lleva apretado: sin hora anotada pueden tomar decisiones equivocadas.","Control de hemorragias · torniquete"],
["F","Ante un herido en estado de shock sin traumatismo que lo impida, se le coloca:",["Tumbado, con las piernas elevadas y abrigado","Sentado en una silla","De pie, apoyado en un árbol","Boca abajo con la cabeza colgando"],"Elevar las piernas devuelve sangre al corazón y al cerebro; abrigar frena la pérdida de calor. Nunca se le dará de comer o beber.","Cruz Roja · shock"],
["F","A un herido grave NO se le debe:",["Dar de beber o comer, aunque pida agua","Taparlo con una manta","Hablarle para tranquilizarle","Avisar al 112"],"Con cirugía potencial a la vista, la ingesta retrasa la anestesia y agrava hemorragias internas: se le humedecen los labios, nada más.","Cruz Roja · conducta ante heridos"],
["F","Durante una convulsión está PROHIBIDO:",["Meterle algo en la boca o sujetarle los brazos con fuerza","Apartar los objetos con los que pueda golpearse","Protegerle la cabeza con ropa doblada","Cronometrar la duración de la crisis"],"El mito de la «lengua tragada» provoca fracturas y ahogamiento: nada entre los dientes. Se protege, se cronometra y, si no despierta respirando normal, PLS.","Cruz Roja · convulsiones"],
["F","Ante una hemorragia nasal (epistaxis), la conducta correcta:",["Sentado, cabeza ligeramente hacia delante, presionando la ala de la nariz 10 minutos","Tumbado con la cabeza colgando hacia atrás","Taponeándose la nariz con algodón seco durante un minuto","Echando agua fría en la frente"],"La cabeza atrás hace tragar sangre (vómito y asfixia): adelante y presión. El mito del «cabeza atrás» está fuera de toda guía.","Cruz Roja · epistaxis"],
["F","Sobre una gasa empapada en sangre se debe:",["Añadir otra gasa encima sin retirar la anterior","Retirarla enjuagarla y volver a ponerla","Sustituirla por un pañuelo de papel","Dejar la herida al aire para que se seque"],"Retirar la gasa arranca el coágulo que se estaba formando: se añaden capas y se aprieta más.","Cruz Roja · hemorragias"],
["M","Al llamar al 112 hay que comunicar:",["Qué ocurre, dónde exactamente, cuántos heridos hay y cómo están, sin colgar hasta que lo indiquen","Solo el nombre del herido","Únicamente la dirección y colgar enseguida","Los datos del seguro médico"],"La localización precisa y «no colgar» son vitales: con el altavoz puesto, el centralista guía al socorrista y localiza al equipo de emergencias.","112 · cómo avisar"],
["M","Los eslabones de la cadena de supervivencia son:",["Reconocimiento precoz y aviso, RCP precoz, desfibrilación precoz y cuidados posteriores","Comer, dormir, entrenar y zarpar","Vacunar, curar, operar y recetar","Llamar, esperar, huir y olvidar"],"Cada eslabón encadena al siguiente: falla uno y la víctima muere. La desfibrilación precoz multiplica la supervivencia.","ERC 2025 · cadena de supervivencia"],
["M","La técnica correcta de las compresiones torácicas es:",["En el centro del pecho, brazos rectos, con el peso del cuerpo y permitiendo la reexpansión completa del tórax","Sobre el esternón alto, con los dedos entrelazados apoyando en las costillas","Con los codos doblados empujando lateralmente","Sobre el lado izquierdo del pecho, sobre el corazón"],"«Centro del pecho» (no a la izquierda), codos en extensión, tallo vertical usando el peso: y sin apoyarse nunca entre compresiones.","ERC 2025 · SVB"],
["M","El reanimador se cambia (o alterna) cada 2 minutos porque:",["La fatiga reduce la profundidad y la calidad de las compresiones sin que uno se dé cuenta","Cada 2 minutos el corazón descansa","El DEA hay que apagarlo cada 2 minutos","La ley lo exige expresamente"],"A los 2 minutos la calidad cae aunque el reanimador crea seguir bien: se aprovecha el análisis del DEA para cambiar.","ERC · calidad de la RCP"],
["M","Si no sabes o no quieres hacer ventilaciones (boca a boca), las guías ERC 2025 establecen que:",["La RCP solo con las manos (compresiones continuas) es una alternativa válida","No puedes hacer nada hasta llegar un médico","Debes esperar a que la víctima respire","Solo vale la RCP con respiración artificial forzada"],"ERC 2025 refuerza la RCP «solo manos» para el reanimador no entrenado o dubitativo: compresiones sin parar a 100-120/min.","ERC 2025 · resumen ejecutivo"],
["M","En un ahogamiento (y en el niño), la RCP comienza con:",["5 ventilaciones iniciales antes de empezar las compresiones","10 compresiones sin ventilar nunca","Aplicar el DEA dentro del agua","Dar la vuelta a la víctima y sacudirla"],"El paro por ahogamiento es hipóxico: primero aire. Por eso 5 ventilaciones de inicio (y en niño la parada suele ser también hipóxica).","ERC · ahogamiento y SVB pediátrico"],
["M","Si la víctima atragantada aún puede toser con eficacia:",["No se le golpea la espalda: se le anima a seguir tosiendo","Se le aplica el Heimlich inmediatamente","Se le cuelga de los pies","Se le da agua para «bajarla»"],"La tos es el mejor mecanismo de expulsión: golpear o comprimir con tos eficaz puede empeorar la obstrucción.","ERC · obstrucción de vía aérea"],
["M","Si el atragantado pierde la consciencia, hay que:",["Tumbarlo en el suelo e iniciar la RCP (compresiones)","Sentarlo y sacudirlo","Echarle agua fría en la cara","Esperar tumbado junto a él diez minutos"],"Las compresiones hacen de «maniobra de Heimlich» interna y generan presión: por eso se arranca la RCP sin dudarlo.","ERC · obstrucción de vía aérea"],
["M","La colocación correcta de un torniquete es:",["Entre 5 y 7 cm por encima de la herida, sin apretarlo sobre una articulación","Directamente sobre la herida sangrante","En el cuello o en la ingle si la herida es ahí","En el miembro sano, por simetría"],"Ni sobre la herida ni sobre rodilla/codo (no aprieta): unos dedos por encima, y se estrecha hasta parar la sangría.","Control de hemorragias · torniquete"],
["M","Una vez apretado el torniquete y detenido el sangrado:",["No se afloja: solo el personal sanitario decidirá retirarlo","Se afloja cada 15 minutos «para irrigar»","Se retira a los 10 minutos en cualquier caso","Se afloja si el herido grita de dolor"],"El mito del «aflojar cada 15 minutos» provoca re-sangrado y consumo de coágulos: moderno es apretar y no tocar hasta el hospital.","Control de hemorragias · torniquete"],
["M","Un miembro amputado (dedo, mano) debe:",["Envolverse en gasa húmeda, meterse en bolsa impermeable y colocarse sobre hielo, sin contacto directo","Metersé en el bolsillo del herido directamente","Enterrarse en la arena del camino","Congelarse pegado al hielo tal cual"],"El frío directo mata el tejido: bolsa sobre hielo, sin tocarlo, acompañando siempre al herido. Cada hora cuenta.","Cruz Roja · amputaciones"],
["M","En una fractura abierta (hueso al aire):",["No se empuja el hueso hacia dentro: se cubre con gasa estéril y se inmoviliza","Se reintroduce el hueso con un palo","Se lava el hueso con alcohol y se aprieta","Se vendaje muy fuerte para «meterlo»"],"Empujar el fragmento siembra la infección dentro: cubrir, inmovilizar y trasladar.","Cruz Roja · fracturas"],
["M","El tratamiento de un esguince (torcedura) reciente es:",["Reposo, hielo/envoltura fría, compresión con vendaje y elevación","Estiramiento fuerte del tobillo y marcha inmediata","Calor directo y masaje profundo con alcohol","Amarrar la extremidad con cuerda apretada"],"El cuarteto clásico (reposo, frío, compresión, elevación) frena la hinchazón; el calor y el masaje la empeoran.","Cruz Roja · esguinces"],
["M","Lo PRIMERO ante cualquier quemadura es:",["Apartar la fuente de calor (tapar sartén, desenchufar, alejar de la llama)","Echarle agua sin más","Buscar un espejo para valorar la extensión","Quitar la ropa pegada a la piel tirando"],"Sin cortar el agente (fuego, corriente, producto) la quemadura sigue avanzando: primero cortar, después enfriar.","Cruz Roja · quemaduras"],
["M","En una quemadura química (ácido, lejía):",["Se retira la ropa impregnada y se lava con agua abundante prolongadamente (más que en la térmica)","Se neutraliza echando otro producto químico encima (ácido sobre lejía)","Se espera a que el producto «seque» solo","Se tapa con plástico hermético y nada más"],"Neutralizar con otro químico provoca reacción térmica: agua a chorro y a manta, quitando antes la ropa contaminada.","Cruz Roja · quemaduras químicas"],
["M","Ante un golpe de calor, la conducta es:",["Sombra, sitio fresco, aflojar la ropa, enfriar (agua, paños húmedos) y agua por boca SOLO si está consciente","Darle alcohol para «refrescarlo»","Envolverlo en una manta para que sude","Exponerlo al sol para que se aclimate"],"El alcohol dilata y deshidrata; la manta, mata. Enfriar el cuerpo y, si pierde consciencia, posición lateral y 112.","Cruz Roja · golpe de calor"],
["M","Las señales típicas de un estado de shock son:",["Palidez, piel fría y sudorosa, pulso rápido y débil, sed y ansiedad","Rubor facial, piel caliente, pulso lento y fuerte","Risa incontrolada y apetito normal","Fiebre alta y erupción cutánea exclusivamente"],"El cuerpo «apaga» piel y vísceras para mantener corazón y cerebro: frío, pálido, taquicárdico y sediento.","Cruz Roja · shock"],
["M","Si un insecto (o polvo) entra en el ojo:",["No frotar: lavar con agua o suero abundante, con el ojo abierto o parpadeando bajo el agua","Frotar fuerte para sacarlo","Sacarlo con la punta de un pañuelo seco","Taparlo con una venda apretada dos días"],"Frotar incrusta el cuerpo extraño y raspa la córnea: se lava a manta y, si persiste el dolor, al médico.","Cruz Roja · cuerpo extraño en ojo"],
["M","Ante hipotermia (frío intenso, temblores, somnolencia):",["Abriga gradualmente el TRONCO con ropa seca y calor moderado; nunca fricción ni calor extremo directo","Frotar las extremidades con nieve","Meter al herido en agua caliente","Darle alcohol para «calentar por dentro»"],"El calor brusco dilata periferia y roba sangre del corazón; la fricción lesiona músculo frío. Seco, gradual y al tronco primero.","Cruz Roja · hipotermia"],
["M","Antes de curar una herida, el socorrista debe:",["Lavarse las manos y usar guantes (del botiquín o improvisados)","Soplar sobre la herida para limpiarla","Lamerse los dedos antes de tocar la gasa","Usar la misma gasa para todas las heridas del grupo"],"Autoprotección primero: guantes (improvisados con bolsa si no hay) contra sangre de desconocidos.","Cruz Roja · curas"],
["M","Para limpiar una herida superficial:",["Se limpia del CENTRO hacia AFUERA con suero o agua limpia, con gasa distinta en cada pasada","Desde afuera hacia el centro, con algodón seco","Se lava con alcohol y luego se espolvorea con azúcar","Se deja sin limpiar: la sangre ya la limpia"],"Del centro afuera (para no llevar suciedad a la herida) y sin algodón (se pega y deja fibras).","Cruz Roja · curas"],
["M","Tras una mordedura de serpiente está PROHIBIDO:",["Hacer cortes, succionar la herida o poner torniquete","Inmovilizar el miembro como una fractura","Mantener la calma y reducir el movimiento","Trasladar con urgencia al hospital (o llamar al 112)"],"Cortar y succionar no salva y necrosa; el torniquete concentra el veneno: inmovilizar, calmar y evacuar.","Cruz Roja · mordeduras"],
["D","Las guías ERC 2025 simplificaron la secuencia inicial del socorrista a:",["«Comprobar – Llamar – RCP»","«Avisar – Rezar – Esperar»","«Proteger – Curar – Transportar»","«Respirar – Contar – Cantar»"],"ERC 2025 (publicadas el 23-10-2025): comprobar respuesta y respiración, llamar al 112 (con altavoz) y comprimir YA. Menos pasos, más supervivencia.","ERC 2025 · secuencia SVB"],
["D","Un compañero sangra a chorro desde una pierna en plena maniobra. La conducta correcta:",["Torniquete INMEDIATO sobre la extremidad: la hemorragia masiva no admite demora","Elevarle la pierna y esperar a valorar con calma","Ponerle una gasa pequeña y seguir marchando","Curar la herida después de descansar cinco minutos"],"Ante hemorragia masiva de extremidad, el torniquete es PRIMERA elección (doctrina de control de hemorragias): cada minuto de sangrado mata.","Control de hemorragias · doctrina táctica · caso"],
["D","Llegas a un garaje en llamas con un herido dentro. Antes de valorarle la consciencia:",["Proteger: apagar o alejar el peligro y sacarlo de la zona (si es seguro), sin entrar sin protección","Comprobarle el pulso radial dentro del garaje","Iniciar la RCP dentro, entre las llamas","Llamar al 112 y quedarse fuera para siempre"],"PAS en acción: Proteger antes de Socorrer. Un socorrista quemado duplica las víctimas; valorar se hace fuera del peligro.","Cruz Roja · PAS · caso"],
["D","Estás reanimando; el DEA analiza y dice «no se aconseja descarga». Inmediatamente:",["Reanudas las compresiones (30:2) sin perder tiempo","Esperas otro análisis antes de tocar al paciente","Compruebas el pulso carotídeo un minuto largo","Apagas el DEA y esperas a la ambulancia sentado"],"Sea cual sea el dictamen del DEA, tras el análisis se comprime sin parar: el aparato reanaliza cada 2 minutos.","ERC 2025 · DEA · caso"],
["D","Un militar cae de un muro, se duele del cuello y nota hormigueo en los brazos. La conducta:",["No moverle el cuello ni el cuerpo (salvo peligro inmediato); inmovilizar el eje cabeza-cuello-tronco y avisar al 112","Sentarle para que «descanse el cuello»","Girarle el cuello a ambos lados para valorar el rango","Levantarle a andar despacio para ver si mejora"],"El hormigueo delata lesión medular en ciernes: un giro mal dado puede agravar la lesión para siempre. Se inmoviliza y se evacúa.","Cruz Roja · lesión cervical · caso"],
["D","Tras un golpe en la cabeza, un compañero está lúcido… y a los 20 minutos queda somnoliento con vómitos. Sospechas:",["Hemorragia interna craneal (intervalo lúcido): 112 inmediato y vigilancia constante de su estado","Un simple mareo por el calor: le das agua y sigues","Que tiene hambre: le das un bocadillo","Que finge para saltarse la guardia: le gritas"],"El «intervalo lúcido» es la firma del sangrado intracraneal: lucidez que se apaga + vómitos = emergencia vital ya.","Cruz Roja · traumatismo craneal · caso"],
["D","Estás SOLO ante un adulto inconsciente que no respira. El orden correcto:",["Llamar primero al 112 (con altavoz) y luego iniciar las compresiones","Comprimir 30 minutos y llamar después","Ir corriendo a buscar a alguien y volver tarde","Ventilarle dos minutos antes de pensar en llamar"],"En el adulto el paro es cardíaco: ayuda primero. (En niño y ahogamiento, paro hipóxico: 1 minuto de RCP ANTES de dejar a la víctima para llamar.)","ERC 2025 · llamar · caso"],
["D","En la cantina un compañero se atraganta, deja de toser y pierde la consciencia. Lo correcto:",["Tumbarlo en el suelo y comenzar la RCP con compresiones","Sostenerlo de pie y seguir dándole palmadas una hora","Colgarlo del tobillo desde la barra","Meterle los dedos a ciegas hasta el fondo de la garganta"],"Consciente: golpes y Heimlich. Inconsciente: al suelo y a comprimir (cada compresión empuja el cuerpo extraño).","ERC · obstrucción · caso"]
]
assert len(RAW) == 50, "RAW tiene %d" % len(RAW)
import io
PATRON = [(p + j) % 4 for j in range(13) for p in range(4)][:50]
filas = []
for i, ((dif, q, ops, x, r), dest) in enumerate(zip(RAW, PATRON), 1):
    correcta = ops[0]; resto = ops[1:]
    nuevas = resto[:dest] + [correcta] + resto[dest:]
    esc = lambda t: t.replace('"', '\\"')
    filas.append('{c:"cabo",b:"C2",t:"Primeros auxilios",d:"%s",id:"pa%02d",q:"%s",o:[%s],a:%d,x:"%s",r:"%s"}' % (dif, i, esc(q), ",".join('"%s"' % esc(o) for o in nuevas), dest, esc(x), esc(r)))
LOTE11 = (',\n/* ===== LOTE EXAMINADOR — Tema 11: Primeros auxilios\n'
'   Elaboración PROPIA (examinador GALÓN), 20-sep-2026, 100% contra fuentes verificadas hoy: GUÍAS ERC 2025 (Consejo\n'
'   Europeo de Reanimación, publicadas 23-oct-2025, traducción CERCP: secuencia simplificada «Comprobar-Llamar-RCP»;\n'
'   100-120/min; 5-6 cm; reexpansión completa; interrupciones <10 s; 30:2 entrenado; RCP solo manos válida; DEA en\n'
'   cuanto disponible y compresiones tras cada análisis; cambio de reanimador por fatiga; 5 ventilaciones iniciales\n'
'   en niño y ahogamiento; adulto: llamar primero, niño/ahogamiento: 1 min de RCP antes) · CRUZ ROJA (PAS; quemaduras\n'
'   apartar fuente + agua 10-15 min o más; no hielo ni reventar ampollas; químicas: ropa impregnada + agua a manta;\n'
'   epistaxis cabeza adelante; convulsión: nada en la boca + PLS si no despierta; epistaxis; shock; hipotermia\n'
'   gradual al tronco; heridas: gasas se AÑADEN sin retirar; objeto empotrado no se extrae; amputación: bolsa sobre\n'
'   hielo sin contacto) · control de hemorragias (torniquete 5-7 cm sobre la herida sin articulación, anotar hora,\n'
'   NO aflojar periódicamente: mito fuera; masiva de extremidad = torniquete inmediato, doctrina táctica).\n'
'   NOTA: se omiten cifras de reanimación pediatrica por bandas de edad (fuentes las detallan distinto) y cualquier\n'
'   valor concreto de dónde colgar el torniquete según escuela: solo lo común a las fuentes. */\n')
s = io.open('/home/user/galon/js/bank7.js', encoding='utf-8').read().rstrip()
assert s.endswith('];')
s = s[:-2] + LOTE11 + ",\n".join(filas) + "\n];\n"
io.open('/home/user/galon/js/bank7.js', 'w', encoding='utf-8').write(s)
from collections import Counter
difs = Counter(r[0] for r in RAW)
print("Lote Tema 11 montado: 50 · reparto correctas:", dict(sorted(Counter(PATRON).items())), "· dificultades:", dict(sorted(difs.items())))
