#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Lote Tema 7 · Organización del Ejército de Tierra (Orden DEF/708/2020 + RD 521/2020) — 50 preguntas, formato: [dif, pregunta, opciones(correcta=0), explicación, ref]
RAW = [
["F","¿Qué norma desarrolla hoy la organización básica del Ejército de Tierra?",["La Orden DEF/708/2020, de 27 de julio, por la que se desarrolla la organización básica del Ejército de Tierra","La Orden DEF/1265/2015, de 29 de junio","El Real Decreto 872/2014, de 10 de octubre","La Orden Ministerial 26/2020, de 11 de junio"],"⚠️ ANTI-OBSOLETO: la DEF/1265/2015 (la de muchos cuadernillos) está DEROGADA expresamente por la DEF/708/2020 (en vigor 29-jul-2020).","Orden DEF/708/2020 · disp. derogatoria única"],
["F","¿Qué Real Decreto establece la organización básica de las Fuerzas Armadas, marco de la DEF/708/2020?",["El Real Decreto 521/2020, de 19 de mayo","El Real Decreto 872/2014, de 10 de octubre","El Real Decreto 309/2021","El Real Decreto 2015/2004, de 11 de octubre"],"La DEF/708/2020 se dicta en virtud de la disposición final segunda del RD 521/2020 (el 872/2014 fue el anterior y quedó sustituido; el RD 2015/2004 es el del CGTAD).","RD 521/2020 · Orden DEF/708/2020 art. único"],
["F","El Cuartel General del Ejército de Tierra está constituido por:",["El Estado Mayor del ET, el Gabinete del JEME, la Jefatura del Ciberespacio y de los Servicios de Asistencia Técnica, el Instituto de Historia y Cultura Militar, la Asesoría Jurídica y las unidades de servicios generales","El Mando de Personal, el Mando de Apoyo y el Mando de la Fuerza Terrestre","El CGTAD, la Fuerza Terrestre y el Mando de Canarias","Las divisiones Castillejos y San Marcial"],"La lista del art. 1. Dentro del Cuartel General se encuentra también la Intervención Delegada en el ET.","Orden DEF/708/2020 art. 1"],
["M","El Estado Mayor del Ejército de Tierra (EME) se articula en:",["La Jefatura, la Secretaría General y las Divisiones de Planes, de Operaciones y de Logística","Las Direcciones de Personal, Sanidad y Acuartelamiento","Las divisiones Castillejos y San Marcial","Los mandos de Artillería, Ingenieros y Transmisiones"],"Tres divisiones (Planes, Operaciones y Logística) más la Jefatura (SEJEME) y la Secretaría General del Estado Mayor.","Orden DEF/708/2020 art. 2.2"],
["D","El Segundo Jefe del Estado Mayor del Ejército de Tierra (SEJEME) encabeza:",["La Jefatura del EME, y su principal órgano de apoyo es la Secretaría General del Estado Mayor, donde se encuadra la Secretaría Permanente del Consejo Superior","La División de Operaciones directamente","El Mando de Apoyo a la Maniobra","La Inspección General del Ejército de Tierra"],"Art. 2.3-2.4: la Jefatura la forma el SEJEME con su apoyo personal; la Secretaría General trabaja para él y alberga la Secretaría Permanente del Consejo Superior del ET.","Orden DEF/708/2020 arts. 2.3-2.4 · caso"],
["F","El principal órgano auxiliar de mando del JEME es:",["El Estado Mayor del Ejército de Tierra (EME)","El Mando de Adiestramiento y Doctrina","El Cuartel General Terrestre de Alta Disponibilidad","El Instituto de Historia y Cultura Militar"],"Definición literal del art. 2.1: el EME asiste al JEME, le proporciona elementos de juicio, traduce sus decisiones en órdenes y vela por su cumplimiento.","Orden DEF/708/2020 art. 2.1"],
["M","El Gabinete del Jefe de Estado Mayor del Ejército de Tierra es:",["El órgano de apoyo inmediato al JEME, responsable del estudio, asesoramiento y trámite de los asuntos que le competen, de sus relaciones institucionales y de comunicación social","La unidad de seguridad del cuartel general","El órgano de contratación del ET","La representación permanente del ET ante la OTAN"],"Art. 3 literal: apoyo inmediato al JEME en cuanto no esté atribuido específicamente a otros órganos del Cuartel General.","Orden DEF/708/2020 art. 3 · caso"],
["M","La Jefatura del Ciberespacio y de los Servicios de Asistencia Técnica (JCISAT) es responsable de:",["Sistemas de información y telecomunicaciones, guerra electrónica, gestión del espectro electromagnético y ciberdefensa, y es la principal asesora ciberespacial del JEME","La instrucción y adiestramiento de las unidades","El abastecimiento y mantenimiento de las unidades","La gestión de los destinos del personal"],"Art. 4: CIS, GE, espectro, ciberdefensa (más estadística, IMO, sociología, publicaciones y cartografía). Asesora al JEME a través del SEJEME.","Orden DEF/708/2020 art. 4"],
["M","El Instituto de Historia y Cultura Militar incluye entre sus órganos:",["El Museo del Ejército, los Archivos Generales Militares y los Centros de Historia y Cultura Militar","El Real Colegio de Artillería en exclusiva","La Biblioteca Nacional de España","El Centro Superior de Estudios de la Defensa Nacional"],"Art. 5: además de las Subdirecciones de Estudios Históricos y de Patrimonio Histórico y Cultural.","Orden DEF/708/2020 art. 5"],
["M","La Intervención Delegada en el Ejército de Tierra depende:",["Orgánica y funcionalmente de la Intervención General de la Defensa","Del Director de Asuntos Económicos del ET en exclusiva","Del Jefe del Mando de Apoyo Logístico","De la Subsecretaría de Defensa"],"Art. 1.2: control interno de la gestión económico-financiera, Notaría Militar y asesoramiento económico-fiscal; dependencia orgánica Y funcional de la Intervención General de la Defensa.","Orden DEF/708/2020 art. 1.2"],
["F","¿De quién dependen directamente el CGTAD, la Fuerza Terrestre y el Mando de Canarias?",["Del Jefe de Estado Mayor del Ejército de Tierra","Del JEMAD operativamente y del Ministro en lo orgánico","Del General Jefe de la Fuerza Terrestre","Del Ministro de Defensa directamente"],"Art. 8.1: los tres órganos de la Fuerza dependen DIRECTAMENTE del JEME.","Orden DEF/708/2020 art. 8.1"],
["D","La Fuerza del Ejército de Tierra está constituida por:",["El Cuartel General Terrestre de Alta Disponibilidad, la Fuerza Terrestre y el Mando de Canarias del ET","El CGTAD, la Fuerza Terrestre, la Fuerza Logística Operativa y el Mando de Canarias","El CGFT, las divisiones Castillejos y San Marcial y el Mando de Apoyo a la Maniobra","El Mando de Personal, el MADOC y el MALOG"],"⚠️ TRAMPA ANTI-OBSOLETO: la Fuerza Logística Operativa ya NO figura (estructura de la derogada 2015). Vigente: tres órganos (art. 8). Y el CGFT/divisiones son la articulación INTERNA de la Fuerza Terrestre.","Orden DEF/708/2020 art. 8 · caso"],
["F","El Cuartel General Terrestre de Alta Disponibilidad es un órgano de nivel:",["Cuerpo de Ejército, con capacidad para liderar operaciones multinacionales terrestres y el componente terrestre de una organización conjunta","Brigada","División","Batallón reforzado"],"Art. 9.1 literal, creado por el RD 2015/2004, de 11 de octubre.","Orden DEF/708/2020 art. 9 · RD 2015/2004"],
["F","La Fuerza Terrestre se articula en:",["El Cuartel General de la Fuerza Terrestre, la División «Castillejos», la División «San Marcial» y el Mando de Apoyo a la Maniobra","Las brigadas I, VI, X y XII","El Mando de Personal y el Mando de Apoyo Logístico","El Mando de Canarias y las Comandancias Generales"],"Los cuatro componentes del art. 10.2. Base para todas las preguntas de división/brigada.","Orden DEF/708/2020 art. 10"],
["D","¿Qué brigadas forman la División «Castillejos»?",["«Aragón» I, «Rey Alfonso XIII» II de La Legión, «Galicia» VII, «Guzmán el Bueno» X, «Extremadura» XI y «Guadarrama» XII","«Almogávares» VI, «Canarias» XVI, «Aragón» I y «Guadarrama» XII","«Galicia» VII, «Almogávares» VI, «Extremadura» XI y «Canarias» XVI","«Aragón» I, «Aragón» II, «Galicia» VII y «Canarias» XVI"],"Las SEIS brigadas del art. 12.2. Ojo: la «Galicia» VII está en Castillejos (no en San Marcial) y la «Almogávares» VI NO (está en San Marcial).","Orden DEF/708/2020 art. 12.2 · caso"],
["D","La División «San Marcial» se articula en:",["La Brigada «Almogávares» VI de Paracaidistas, el Mando de Tropas de Montaña «Roncesvalles», el Mando de Operaciones Especiales «Órdenes Militares» y las FAMET","La Brigada «Galicia» VII y el Mando de Artillería de Campaña","Las brigadas I, II, X, XI y XII","Las Comandancias Generales de Ceuta y Melilla"],"Art. 13.2: más su Cuartel General. Todo lo especial (paracaidistas, montaña, operaciones especiales, aeromóviles) cuelga de San Marcial.","Orden DEF/708/2020 art. 13 · caso"],
["M","La capacidad paracaidista del Ejército de Tierra la proporciona:",["La Brigada «Almogávares» VI de Paracaidistas","La Brigada «Canarias» XVI","El Mando de Tropas de Montaña «Roncesvalles»","Las FAMET"],"Art. 13.4: además, junto con otras unidades, proporciona Fuerzas de Apoyo a unidades de Operaciones Especiales cuando la operación lo exija.","Orden DEF/708/2020 art. 13.4"],
["M","El Mando de Tropas de Montaña «Roncesvalles» está preparado para proporcionar:",["La capacidad de vida, movimiento y combate en zonas de montaña y de clima frío extremo","Capacidad paracaidista","Defensa antiaérea de puntos vitales","Maniobra aeromóvil"],"Art. 13.5 literal. Está en la División «San Marcial».","Orden DEF/708/2020 art. 13.5"],
["M","El Mando de Operaciones Especiales del ET se denomina:",["«Órdenes Militares», y agrupa unidades de operaciones especiales y de apoyo","«Roncesvalles»","«Castillejos»","«San Marcial»"],"Art. 13.6: bajo un mando único, preparado para realizar operaciones especiales. Nombre que pilla despistados.","Orden DEF/708/2020 art. 13.6"],
["M","El Mando de Apoyo a la Maniobra se articula en:",["El Mando de Artillería de Campaña, el Mando de Artillería Antiaérea, el Mando de Ingenieros, el Mando de Transmisiones y la Brigada Logística","El MALOG, la IGET y la DAE","El Mando de Personal y el MADOC","Las Comandancias Generales de Ceuta, Melilla y Baleares"],"Los cinco componentes del art. 14.2 (más su Cuartel General): todo el apoyo al combate centralizado.","Orden DEF/708/2020 art. 14.2"],
["D","La antigua Brigada de Sanidad, tras la reorganización, se transformó en una Agrupación de Sanidad integrada:",["En la Brigada Logística","En la Brigada «Aragón» I","En el Mando de Canarias","En la Inspección General del ET"],"Cambio del preámbulo de la DEF/708/2020: así se integran bajo una misma estructura todas las unidades del apoyo logístico de nivel superior y la sanidad aporta sus capacidades de más alto nivel (art. 14.8).","Orden DEF/708/2020 · preámbulo y art. 14.8 · caso"],
["F","Las brigadas del ET son:",["Grandes unidades elementales de empleo, de composición orgánica fija, que actúan como un sistema de combate integral","Órganos de apoyo al mando sin unidades","Mandos operativos de nivel cuerpo de ejército","Unidades exclusivamente de instrucción"],"Fórmula literal del art. 12.4 (y del 20): combate, apoyo al combate y apoyo logístico al combate.","Orden DEF/708/2020 arts. 12.4 y 20"],
["F","El Mando de Canarias del Ejército de Tierra se articula en:",["Su Cuartel General, las Comandancias Generales de Ceuta, Melilla y Baleares, y la Brigada «Canarias» XVI","Únicamente la Brigada «Canarias» XVI","La Brigada «Galicia» VII y el Mando de Ingenieros","La División «Castillejos»"],"Art. 15.2. Sorpresa para quien estudie de cuadernillos viejos: Baleares también cuelga del Mando de Canarias.","Orden DEF/708/2020 art. 15.2"],
["D","Las Comandancias Generales de Ceuta, Melilla y Baleares dependen de:",["El Mando de Canarias del Ejército de Tierra","La Fuerza Terrestre directamente","El Ministerio de Defensa directamente","El Mando de Apoyo a la Maniobra"],"La estructura vigente las sitúa bajo el Mando de Canarias (art. 15.2), con sus Cuarteles Generales y pequeñas unidades de combate, apoyo al combate y apoyo logístico al combate.","Orden DEF/708/2020 art. 15 · caso"],
["M","El Apoyo a la Fuerza, en el ámbito de los RECURSOS HUMANOS del ET, engloba:",["El Mando de Personal y el Mando de Adiestramiento y Doctrina","El MALOG y la Inspección General","La Dirección de Asuntos Económicos y la IGET","La Fuerza Terrestre y el Mando de Canarias"],"Art. 21.1. El material lo cubren MALOG + IGET (21.2) y lo financiero, la DAE (21.3).","Orden DEF/708/2020 art. 21"],
["M","En el Apoyo a la Fuerza del ET, la Inspección General del Ejército de Tierra y el Mando de Apoyo Logístico corresponden al ámbito de:",["Los recursos materiales","Los recursos humanos","Los recursos financieros","La estructura operativa"],"Art. 21.2: material = MALOG + IGET. La DAE (21.3) es la de los recursos financieros.","Orden DEF/708/2020 art. 21.2"],
["F","El Mando de Personal del ET se articula en:",["La Jefatura, la Dirección de Personal, la Dirección de Asistencia al Personal y la Dirección de Sanidad","La Dirección de Acuartelamiento y la de Infraestructura","El MAPER y la Dirección de Enseñanza","El CGFT y las divisiones"],"Las cuatro piezas del art. 22.2: personal, asistencia al personal y sanidad.","Orden DEF/708/2020 art. 22"],
["M","La Dirección de Personal del ET es responsable de los procesos de:",["Situaciones, ascensos, destinos, recompensas, documentación, evaluación y orientación de carrera, además del reclutamiento y la generación adicional de recursos humanos","Construcciones y obras","Abastecimiento, mantenimiento y transporte","Doctrina y normativa de empleo"],"Art. 24.1-2. Se articula en Subdirecciones de Carrera Militar, de Evaluación y de Gestión de Personal.","Orden DEF/708/2020 art. 24"],
["M","La Dirección de Asistencia al Personal se ocupa de:",["La acción social y el apoyo al personal y a sus familias, las prestaciones sociales y la calidad de vida","Los destinos de los oficiales generales","La ciberdefensa del ET","El mantenimiento de los sistemas de armas"],"Art. 25: con Subdirecciones de Apoyo al Personal y de Gestión de Centros; de ella dependen residencias militares de acción social y centros deportivos y socioculturales.","Orden DEF/708/2020 art. 25"],
["F","El MADOC es:",["El Mando de Adiestramiento y Doctrina, responsable de doctrina, orgánica, materiales, enseñanza y sistemas de instrucción, adiestramiento y evaluación","El Mando de Apoyo Logístico de la División","El Mando de Operaciones Especiales","El órgano de ciberdefensa del ET"],"Art. 27: gestión del conocimiento; también educación físico-militar, deporte y conducción y seguridad vial.","Orden DEF/708/2020 art. 27"],
["M","El Mando de Adiestramiento y Doctrina se articula en:",["La Jefatura, la Dirección de Investigación, Doctrina, Orgánica y Materiales y la Dirección de Enseñanza, Instrucción, Adiestramiento y Evaluación","Las Direcciones de Personal y de Sanidad","Los mandos de Artillería de Campaña y Antiaérea","La Dirección de Adquisiciones"],"Las tres piezas del art. 27.4.","Orden DEF/708/2020 art. 27.4"],
["D","Los centros docentes militares (academias del ET) pertenecen, según la estructura vigente, a:",["La Dirección de Enseñanza, Instrucción, Adiestramiento y Evaluación, del Mando de Adiestramiento y Doctrina","El Mando de Personal, Dirección de Sanidad","La Inspección General del ET","La Fuerza Terrestre"],"⚠️ TRAMPA ANTI-OBSOLETO: art. 30.3.c literal «pertenecen a esta dirección los centros docentes militares», que se rigen por la Ley 39/2007. No van con el Mando de Personal como decían esquemas antiguos.","Orden DEF/708/2020 art. 30.3.c · Ley 39/2007 · caso"],
["M","El Mando de Apoyo Logístico (MALOG) es responsable del material y los procesos de:",["Abastecimiento, mantenimiento y transporte, incluyendo la ingeniería de apoyo","Enseñanza de formación","Recompensas y documentación","Protección medioambiental en exclusiva"],"Art. 31.1, más dirección, gestión, administración y control de dichas funciones e ingeniería de sistemas.","Orden DEF/708/2020 art. 31"],
["F","El Mando de Apoyo Logístico se articula en:",["La Jefatura, la Dirección de Adquisiciones, la Dirección de Integración de Funciones Logísticas y la Dirección de Ingeniería del MALOG","Las subinspecciones generales Sur y Pirenaica","La Dirección de Acuartelamiento y la de Infraestructura","El Museo del Ejército y los Archivos Generales"],"Art. 31.2, incluida la Dirección de Ingeniería, que se detalló como art. 34 bis.","Orden DEF/708/2020 art. 31.2"],
["D","El artículo 34 bis de la DEF/708/2020 (añadido en 2024) regula:",["La Dirección de Ingeniería del Mando de Apoyo Logístico, responsable de la ingeniería de los sistemas de armas, materiales y equipos a lo largo de todo su ciclo de vida","La Brigada Logística","El Mando de Operaciones Especiales","La Dirección de Sanidad"],"El añadido más reciente (Orden DEF/559/2024): con Subdirecciones de Ingeniería de Sistemas y de Ingeniería de Armamento y Material. Si cae, es pregunta de nota.","Orden DEF/708/2020 art. 34 bis · Orden DEF/559/2024 · caso"],
["M","La Dirección de Integración de Funciones Logísticas dirige los procesos de:",["Abastecimiento (excluida la adquisición), mantenimiento y transporte, e incluye la Jefatura de Centros Logísticos","Solo la compra de armamento nuevo","La instrucción de las unidades logísticas","El presupuesto del ET"],"Art. 34: la adquisición va aparte (Dirección de Adquisiciones); esta dirección integra las funciones y encuadra los centros logísticos de apoyo de más alto nivel.","Orden DEF/708/2020 arts. 33-34"],
["F","La Inspección General del Ejército de Tierra es responsable de los procesos relacionados con:",["Infraestructuras, protección medioambiental, prevención de riesgos laborales y la vida y funcionamiento de las unidades","El ascenso por elección","Las operaciones especiales","La gestión del espectro electromagnético"],"Art. 35.1 literal. Ojo: aquí NO viene lo de «inspeccionar generales»: es infraestructura, medio ambiente, PRL y vida y funcionamiento.","Orden DEF/708/2020 art. 35"],
["M","La Inspección General del Ejército de Tierra se articula en:",["La Jefatura, la Dirección de Acuartelamiento y la Dirección de Infraestructura","El MALOG y la DAE","Las brigadas de la División Castillejos","La Dirección de Personal y la de Asistencia al Personal"],"Art. 35.2. La Dirección de Acuartelamiento es la estrella del art. 37 y la de Infraestructura, el órgano técnico de construcciones y obras (art. 38).","Orden DEF/708/2020 arts. 35-38"],
["M","La Dirección de Acuartelamiento es responsable de:",["La vida y funcionamiento de las unidades (sin carácter de preparación ni logístico), la seguridad de bases y acuartelamientos, su inventario, el régimen interior y la prevención de riesgos laborales","El adiestramiento de las brigadas","La fabricación de munición","El reclutamiento de tropa"],"Art. 37.1-2: incluye propiedades y zonas e instalaciones de interés para la Defensa Nacional.","Orden DEF/708/2020 art. 37"],
["D","Las subinspecciones generales del ET son:",["Cuatro: Segunda (Sur), Tercera (Pirenaica), Cuarta (Noroeste) y Quinta (Canarias); la Dirección de Acuartelamiento actúa como Subinspección en Madrid y Castilla-La Mancha","Cinco: Norte, Centro, Sur, Este y Canarias","Tres: Norte, Sur y Levante","Una única central en Madrid"],"Art. 37.3-4. ⚠️ Las cinco regiones (Norte, Centro, Sur, Este y Canarias) eran los MAPER/mandos de apoyo logístico de cuadernillos antiguos; las subinspecciones vigentes son cuatro y SIN Primera.","Orden DEF/708/2020 art. 37.4 · caso"],
["M","La Dirección de Asuntos Económicos del ET se articula en:",["La Subdirección de Contabilidad y Presupuesto y la Subdirección de Gestión Económica y Contratación","Las Direcciones de Adquisiciones y de Ingeniería","La Jefatura de Centros Logísticos y la de Asuntos Económicos","El Gabinete del JEME y la Asesoría Jurídica"],"Arts. 39-41: elaboración técnica del anteproyecto de presupuesto, contabilidad, gestión económica y contratación.","Orden DEF/708/2020 arts. 39-41"],
["D","¿Cuál de estas unidades NO forma parte de la estructura del Ejército de Tierra?",["La Unidad Militar de Emergencias (UME)","El Regimiento de Infantería «Inmemorial» n.º 1 como órgano de servicios generales","La Brigada «Canarias» XVI","El Mando de Operaciones Especiales «Órdenes Militares»"],"La UME es un mando CONJUNTO (su unidad de helicópteros BHEA II, del ET, está operativamente bajo la UME), pero la estructura del ET de la DEF/708/2020 es otra: Cuartel General, Fuerza y Apoyo a la Fuerza.","Orden DEF/708/2020 · DEF/166/2015 · caso"],
["D","Más allá del tercer nivel organizativo (estructuras al mando de oficial general), la organización del ET la desarrolla:",["Una instrucción de organización dictada por el Jefe de Estado Mayor del Ejército de Tierra","Una orden del Ministro de Defensa para cada unidad","El BOE mediante real decreto individual","El JEMAD con la Directiva de Planeamiento Militar"],"Clave de flexibilidad de la orden (preámbulo y disposición transitoria única): el BOE solo baja hasta el tercer nivel; el resto, instrucción del JEME.","Orden DEF/708/2020 · preámbulo y disp. transitoria única · caso"],
["M","En el planeamiento militar de la defensa, el documento que redacta el JEMAD y del que se deducen los planes de cada Ejército (como el Plan del Ejército de Tierra, PMT) es:",["La Directiva de Planeamiento Militar","La Directiva de Defensa Nacional","La Orden de Operaciones permanente","El Plan del Estado Mayor"],"El JEMAD redacta la Directiva de Planeamiento Militar (la DDN la formula el Presidente del Gobierno: no confundir). De ella se deriva el PMT que desarrolla el ET.","Planeamiento militar de la defensa · LODEF art. 6.3.a"],
["M","Quien manda el Ejército de Tierra es:",["El Jefe de Estado Mayor del Ejército de Tierra, bajo la autoridad del Ministro de Defensa","El JEMAD directamente","El Capitán General de la región","El Secretario de Estado de Defensa"],"Enlace con la LODEF (art. 13.2): los JEMEs ejercen el mando de su Ejército bajo la autoridad del Ministro. El JEMAD coordina, no manda los Ejércitos.","LODEF art. 13.2 · Orden DEF/708/2020"],
["D","Las brigadas del ET tienen como principal cometido:",["Prepararse para constituir estructuras operativas que se transfieren a la estructura operativa de las Fuerzas Armadas para realizar operaciones militares","Defender las plazas de Ceuta y Melilla en exclusiva","Administrar los destinos del personal","Ejecutar directamente operaciones sin transferencia alguna"],"Art. 7.2: TODAS las unidades de la Fuerza se preparan para transferirse a la estructura operativa (que manda el JEMAD): preparación orgánica vs empleo operativo.","Orden DEF/708/2020 art. 7.2 · LODEF art. 11 · caso"],
["M","Las Fuerzas Aeromóviles del Ejército de Tierra (FAMET) proporcionan:",["La capacidad de la maniobra aeromóvil, con unidades dotadas de aeronaves que operan en el ámbito aeroterrestre","La defensa antiaérea de puntos vitales","El mando de las Comandancias Generales","El apoyo CIS de las brigadas"],"Art. 13.7: combate, apoyo al combate y apoyo logístico al combate con aeronaves; cuelgan de la División «San Marcial».","Orden DEF/708/2020 art. 13.7"],
["D","Un examen te pregunta por la Brigada «Galicia» VII. Según la estructura vigente, está en:",["La División «Castillejos»","La División «San Marcial»","El Mando de Canarias","El Mando de Apoyo a la Maniobra"],"Art. 12.2: las seis brigadas de Castillejos incluyen la «Galicia» VII y la «Rey Alfonso XIII» II de La Legión; la «Almogávares» VI y las FAMET están en San Marcial.","Orden DEF/708/2020 art. 12.2 · caso"],
["M","La Brigada «Canarias» XVI:",["Es una gran unidad elemental de empleo del Mando de Canarias, de composición orgánica fija, que actúa como un sistema de combate integral","Es el órgano de servicios generales del ET","Depende de la División «San Marcial»","Es una agrupación de sanidad"],"Art. 20, con la misma definición que las brigadas de la Fuerza Terrestre pero bajo el Mando de Canarias.","Orden DEF/708/2020 art. 20"],
["D","¿Cuál de estas funciones NO corresponde a la Dirección de Acuartelamiento?",["El planeamiento y control de la preparación de las unidades para las operaciones","La seguridad de las bases, acuartelamientos y establecimientos","El régimen interior en bases y acuartelamientos","La prevención de riesgos laborales en sus aspectos normativos"],"El art. 37 excluye lo de carácter de preparación o logístico: la preparación de las unidades es de la Fuerza (División de Operaciones del EME y mandos de la Fuerza Terrestre).","Orden DEF/708/2020 arts. 37 y 2.6 · caso"]
]
assert len(RAW) == 50, "RAW tiene %d" % len(RAW)
import io
PATRON = [(p + j) % 4 for j in range(13) for p in range(4)][:50]
filas = []
for i, ((dif, q, ops, x, r), dest) in enumerate(zip(RAW, PATRON), 1):
    correcta = ops[0]; resto = ops[1:]
    nuevas = resto[:dest] + [correcta] + resto[dest:]
    esc = lambda t: t.replace('"', '\\"')
    filas.append('{c:"cabo",b:"C1",t:"Organización del ET",d:"%s",id:"et%02d",q:"%s",o:[%s],a:%d,x:"%s",r:"%s"}' % (dif, i, esc(q), ",".join('"%s"' % esc(o) for o in nuevas), dest, esc(x), esc(r)))
LOTE7 = (',\n/* ===== LOTE EXAMINADOR — Tema 7: Organización del Ejército de Tierra (Orden DEF/708/2020 + RD 521/2020)\n'
'   Elaboración PROPIA (examinador GALÓN), 20-sep-2026, sobre el BOE consolidado VIGENTE: Orden DEF/708/2020,\n'
'   de 27 de julio (BOE 28-jul-2020), ÚLTIMA ACTUALIZACIÓN 11/06/2024 (mod. por Orden DEF/559/2024, art. 34 bis:\n'
'   Dirección de Ingeniería del MALOG). ANTI-OBSOLETO verificado: la Orden DEF/1265/2015 está DEROGADA;\n'
'   la Fuerza del ET NO tiene ya Fuerza Logística Operativa (art. 8: CGTAD + Fuerza Terrestre + Mando de Canarias);\n'
'   las Comandancias Generales de Ceuta, Melilla Y BALEARES dependen del Mando de Canarias (art. 15);\n'
'   División «Castillejos» = Aragón I + Rey Alfonso XIII II Legión + Galicia VII + Guzmán el Bueno X +\n'
'   Extremadura XI + Guadarrama XII; División «San Marcial» = Almogávares VI + Roncesvalles + MOE «Órdenes\n'
'   Militares» + FAMET; Mando de Apoyo a la Maniobra con los 5 mandos y la Brigada Logística (Agrupación de\n'
'   Sanidad integrada); centros docentes bajo la Dirección de Enseñanza, Instrucción, Adiestramiento y\n'
'   Evaluación del MADOC (art. 30.3.c); 4 subinspecciones generales (Sur, Pirenaica, Noroeste, Canarias);\n'
'   estructura por encima del 3.er nivel → Instrucción de organización del JEME. */\n')
s = io.open('/home/user/galon/js/bank7.js', encoding='utf-8').read().rstrip()
assert s.endswith('];')
s = s[:-2] + LOTE7 + ",\n".join(filas) + "\n];\n"
io.open('/home/user/galon/js/bank7.js', 'w', encoding='utf-8').write(s)
from collections import Counter
print("Lote Tema 7 montado: 50 · reparto correctas:", dict(sorted(Counter(PATRON).items())))
