#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Lote Tema 13 · Instrucción del combatiente — 50 preguntas, formato: [dif, pregunta, opciones(correcta=0), explicación, ref]
# Fuentes verificadas 21-sep-2026: doctrina clásica de instrucción (marchas, orden cerrado, protección, patrullas) +
# ET oficial (ejercito.defensa.gob.es: marchas de endurecimiento a 4-5 km/h con altos técnicos) + Defensa NBQ como
# denominación vigente en España (Regimiento NBQ «Valencia» I, creado 1-3-2005; Escuela Militar de Defensa NBQ,
# Hoyo de Manzanares; ejercicio GRIFO) + alarma por voz GAS-GAS-GAS (doctrina OTAN) + Convenio de Ottawa 1997
# (España PROHIBE las minas antipersonal — anti-obsoleto: no se pregunta su empleo, se pregunta su prohibición).
# NOTA: se evitan cifras de cadencia de paso y composiciones numéricas de unidades (varían entre fuentes);
# la jornada de marcha usa las cifras clásicas del manual (25-30 km normal, en torno a 50 la extraordinaria).
RAW = [
["F","En marchas a pie sobre terreno normal, la jornada normal de marcha ronda:",["En torno a 24 kilómetros al día","100 kilómetros al día","5 kilómetros al día","150 kilómetros al día"],"La jornada (etapa) normal de marcha a pie se sitúa en torno a 24 km al día; superarla de forma sostenida entra en terreno de la marcha extraordinaria.","Instrucción del combatiente · marchas"],
["F","La jornada de marcha EXTRAORDINARIA ronda los:",["30 kilómetros","10 kilómetros","5 kilómetros","200 kilómetros"],"La marcha extraordinaria se sitúa en torno a 30 km al día (frente a los 24 de la normal), con altos fraccionados y llegando en condiciones de combatir.","Instrucción del combatiente · marchas"],
["F","El ritmo medio de una marcha a pie en terreno normal es de:",["4 a 5 kilómetros por hora","15 a 20 km/h","1 km/h","25 km/h"],"4-5 km/h es el ritmo de referencia (así lo mantienen las marchas de endurecimiento del propio Ejército de Tierra).","Ejército de Tierra · marchas"],
["M","Durante una marcha larga, el ALTO TÉCNICO se realiza aproximadamente:",["10 minutos cada hora de marcha","30 minutos cada 3 horas","2 minutos cada día","No se hacen altos"],"El alto técnico (descanso, ajuste de equipo, revisión de pies) se toma unos 10 minutos por cada hora de marcha; los de avituallamiento, a las horas de comida.","Manual de instrucción · marchas"],
["M","La diferencia entre alto técnico y alto de avituallamiento es:",["El técnico es para descansar y ajustar el equipo; el de avituallamiento, para comer y repostar agua","Son lo mismo con distinto nombre","El técnico es para dormir la siesta","El de avituallamiento es solo para vehículos"],"Técnico: breves, cada hora (dolor de pies, equipo). Avituallamiento: a la hora pautada, para comer/beber. De no confundir en test.","Manual de instrucción · marchas"],
["M","En una formación de marcha, el elemento que protege la columna por su parte trasera es:",["La retaguardia","La vanguardia","El flanco izquierdo","El explorador de punto"],"Vanguardia delante, retaguardia detrás (evita sorpresas y hostigamiento por la espalda), flancos por los costados y el punto (cabeza de la vanguardia).","Manual de instrucción · marchas"],
["F","En doctrina de protección, una CUBIERTA es:",["Un obstáculo que protege contra la OBSERVACIÓN (oculta la silueta)","Un obstáculo que protege contra el FUEGO","Un tipo de mochila","Un castigo disciplinario"],"Protección contra la observación = cubierta (ocultarse). Protección contra el fuego = abrigo. La pareja que el examinador cruza siempre.","Instrucción · utilización del terreno"],
["F","En doctrina de protección, un ABRIGO es:",["Un obstáculo (natural o artificial) que protege contra el FUEGO enemigo","Un obstáculo que solo oculta la vista","Un permiso de salida","Una prenda de vestir"],"Abrigo = parapeto de fuego (foso de tirador, muro, talud). Que te vean y que te disparen no es lo mismo: cubierto ≠ abrigado.","Instrucción · utilización del terreno"],
["M","Una zona de terreno que ofrece buena ocultación frente a la observación se denomina:",["Terreno cubierto","Terreno abrigado","Terreno despejado","Terreno batido"],"Cubierto = protege de la vista (vegetación, depresiones); abrigado = protege del fuego. El examinador pide uno y pone el otro en las trampas.","Instrucción · utilización del terreno"],
["F","La orden cerrada comprende:",["La instrucción individual sin armas y con armas","Solo el tiro de precisión","Únicamente el desfile","La instrucción de los oficiales"],"Orden cerrada = instrucción formal individual (sin armas y con armas): posiciones, vueltas, marchas, saludo. La base de la disciplina y el porte del militar.","Instrucción · orden cerrada"],
["F","Una voz de mando se compone de:",["Voz preventiva y voz ejecutiva","Voz alta y voz baja","Voz oficial y voz privada","Primera y segunda llamada"],"La preventiva anuncia el movimiento (¡A la derecha…!) y la ejecutiva lo dispara (…¡GI-RA!). Escuchar la ejecutiva antes de moverse es oro.","Instrucción · orden cerrada"],
["M","La posición fundamental del orden cerrado es:",["De pie, talones unidos y puntas vueltas hacia afuera formando un ángulo aproximado de 45 grados","Sentado en talón","Corriendo","Acostado boca abajo"],"Talones juntos, puntas abiertas en ángulo aproximado de 45°, pecho fuera, hombros atrás, barbilla en el pecho. La «firmes» de siempre.","Instrucción · orden cerrada"],
["M","La posición «a discreción» permite:",["Relajarse discretamente en el puesto sin abandonarlo ni hablar","Sentarse a comer","Abandonar la formación","Hablar por teléfono"],"Se afloja la postura (se mueve un pie, se relajan brazos) manteniendo el puesto y el silencio: cansa menos sin romper la formación.","Instrucción · orden cerrada"],
["M","El saludo militar se efectúa:",["Siempre que se va CUBIERTO (con gorra, boina o casco); a cubierto, se cuadra","Solo a los generales","Indistintamente cubierto o descubierto","Nunca dentro del acuartelamiento"],"Regla clásica: cubierto, saludo; descubierto, cuadra (posición fundamental). También se saluda al himno y a la bandera.","Instrucción · orden cerrada"],
["M","El jefe de escuadra en combate:",["Dirige el fuego y la maniobra de su escuadra, asignando sectores de tiro","Solo cocina en campaña","Únicamente apunta con su fusil y no manda nada","Dirige al batallón entero"],"El cabo jefe de escuadra es el primer eslabón del mando: reparte sectores de tiro, controla la disciplina de fuego y conduce la progresión.","Instrucción · escuadra"],
["M","En el método de combate actual, el ESPACIO DE SEGURIDAD de la escuadra es:",["El sector hacia el enemigo donde se espera el contacto, donde se concentra la capacidad de fuego inmediata","La zona de las tiendas de campaña","El garaje de los vehículos","El espacio entre las orejas del casco"],"Doctrina vigente de la escuadra/equipo: el ES mira hacia donde puede aparecer el enemigo; el resto del perímetro lo cubren las ÁREAS de seguridad.","Instrucción · método de combate"],
["M","En el mismo método, las ÁREAS DE SEGURIDAD cubren:",["Los restantes flancos y el perímetro que el espacio de seguridad no abarca","Solo el cielo","Solo el mapa","El área de descanso"],"ES (sector del enemigo esperado) + áreas de seguridad (resto del perímetro): la escuadra nunca tiene un hueco sin vigilar.","Instrucción · método de combate"],
["F","La misión de una PATRULLA DE RECONOCIMIENTO es:",["Obtener información del enemigo y del terreno evitando el combate, salvo para su propia supervivencia","Combatir hasta el último hombre","Ocupar terreno definitivamente","Repartir la correspondencia"],"Reconocer NO es combatir: su éxito es ver, registrar y volver sin ser descubierta. Si pelea, ya fracasó su misión principal.","Instrucción · patrullas"],
["M","Una patrulla de COMBATE se caracteriza por:",["Actuar por sorpresa sobre un objetivo determinado (incursión, emboscada) y regresar a sus líneas","Solo mirar y reportar","Instalarse permanentemente en el objetivo","Ser siempre de tamaño batallón"],"Reconocimiento = información sin pelear; combate = acción violenta por sorpresa (incursión, emboscada) con regreso a base. Pareja de examen.","Instrucción · patrullas"],
["M","La SEGURIDAD DE COMBATE de una unidad consiste en:",["El conjunto de medidas para no ser sorprendido por el enemigo (vigilancia de vanguardia, flancos y retaguardia)","Dormir con el casco puesto","Hacer mucho ruido para asustar","Vigilar solo el cielo"],"La seguridad evita la sorpresa: exploradores al frente, flancos y retaguardia cubiertos, alerta en las paradas. Sin seguridad, la unidad está a merced del enemigo.","Instrucción · seguridad"],
["D","En una patrulla de reconocimiento descubrís un puesto avanzado enemigo. La conducta correcta es:",["NO contactar: registrar posición, composición y actividad, y reportarlo por la vía pactada","Asaltar el puesto de inmediato","Hacerles una emboscada con dos hombres","Cantar el himno para que os descubran"],"La información es la munición de la patrulla de reconocimiento: se registra y se reporta; el combate se deja a la unidad de combate.","Instrucción · patrullas · caso"],
["F","Una trampa explosiva (cebo) es:",["Un dispositivo explosivo camuflado que estalla al manipular un objeto o recorrer un lugar","Un tipo de tienda de campaña","Un arma colectiva de tiro curvo","Una red de pesca militar"],"Cebos = trampas cebadas con explosivo sobre objetos atractivos (material abandonado, puertas, cadáveres): el enemigo las deja para retrasar y desmoralizar.","Instrucción · trampas y cebos"],
["M","En las trampas explosivas cebadas sobre objetos, la espoleta empleada con mayor frecuencia es:",["La de TRACCIÓN (se acciona al tirar de un hilo o cable fijado al objeto)","La de presión bajo el agua","La de reloj de cuco","La eléctrica solar"],"Cebos clásicos de cuadernillo: hilo tenso unido a una espoleta de tracción; al mover el objeto, se dispara. Regla: no tocar NADA abandonado.","Cuadernillos oficiales · trampas explosivas"],
["D","Ante material enemigo (o propio) abandonado en terreno de combate:",["No se toca: se sospecha cebo y se rodea o reporta","Se recoge todo como recuerdo","Se patea para comprobar","Se cargan las mochilas con él"],"El material abandonado es la trampa más típica: detrás suele ir una espoleta de tracción. Curiosidad = bajas.","Instrucción · caso"],
["D","En cuanto al empleo de MINAS ANTIPERSONAL, España:",["Está PROHIBIDO: lo impide el Convenio de Ottawa (1997) y su desarrollo legal español","Puede emplearlas libremente en campaña","Solo puede usarlas de noche","Las usa solo en maniobras"],"España es parte del Convenio de Ottawa (1997), que prohíbe las minas antipersonal, con su correspondiente ley de prohibición y destrucción de los arsenales. Pregunta «trampa» que cae por sorpresa.","Convenio de Ottawa 1997 · caso"],
["F","Las siglas NBQ (defensa NBQ) significan:",["Nuclear, Biológica y Química","Navegación Balística y Química","Norte, Brújula y Quadrante","Nada, Bien y Quietud"],"Defensa Nuclear, Biológica y Química: la denominación vigente en el Ejército de Tierra (en la OTAN se añade la radiológica: CBRN).","Defensa NBQ · ET"],
["M","La unidad especializada del ET en defensa NBQ es:",["El Regimiento de Defensa NBQ «Valencia» I","El Regimiento de Caballería «Farnesio» 12","La AGA de Zaragoza","El Parque de Artillería de Cartagena"],"Regimiento de Defensa NBQ «Valencia» I (creado en 2005): detección, identificación, descontaminación y muestreo; su escuela es la EMDNBQ (Hoyo de Manzanares) y el gran ejercicio anual, el GRIFO.","Defensa NBQ · ET"],
["F","La señal de alarma por voz ante un ataque químico es:",["«¡GAS! ¡GAS! ¡GAS!»","«¡FUEGO! ¡FUEGO!»","«¡ALTO!»","«¡AL AGUA!»"],"Doctrina estándar: ante amenaza química se grita GAS tres veces (acompañada de la señal acústica pactada); la respuesta inmediata es la mascarilla.","Defensa NBQ · doctrina"],
["M","La protección individual NBQ se articula con:",["La mascarilla y el equipo de protección física (traje, guantes y botas de protección)","Un paraguas","Un imán","Gafas de sol"],"Mascarilla (vía respiratoria, lo más vulnerable) + equipo de protección física: se ponen AL TOQUE de alarma y sin dejar huecos de sellado.","Defensa NBQ · protección individual"],
["D","Suena la alarma «GAS GAS GAS» en plena maniobra. La primera acción es:",["Ponerse la mascarilla inmediatamente y después buscar abrigo/protección del agente","Escribir un informe","Quitarse la ropa primero","Beber agua para aliviar la garganta"],"Primero la vía respiratoria (mascarilla), después la protección física y buscar lo abrigado: segundos, no minutos. La descontaminación llegará al abandonar la zona.","Defensa NBQ · caso"],
["F","El VIVAC es:",["La pernoctación improvisada de campaña, aprovechando abrigos naturales o material ligero","Una fiesta del regimiento","Un permiso de fin de semana","Un tipo de mapas"],"Vivac: dormir en campaña sin instalaciones, con lo puesto (a la sombra de un talud, tras un muro). El combatiente debe saber vivacar rápido y despertar antes.","Instrucción · campaña"],
["F","El foso de tirador (nido de tirador) es:",["La obra defensiva individual más típica: un hoyo que protege del fuego directo y los fragmentos","Una trampa para conejos","El foso de un castillo","Un salto de atletismo"],"Cavado en pocos minutos, permite disparar desde dentro, protege y oculta: la primera obra de campaña que todo combatiente sabe abrir.","Fortificaciones de campaña"],
["M","El PARAPETO es:",["La porción de tierra levantada (natural o artificial) que protege del fuego frontal","Una serie de teléfonos móviles","Un permiso de asueto","Un tipo de mapa militar"],"El parapeto (el borde del foso con la tierra extraída) frena balas y metralla frontal; el foso protege por debajo de la línea de fuego.","Fortificaciones de campaña"],
["M","Las alambradas en la defensa cumplen la misión de:",["Retrasar, encauzar y detectar al enemigo que se aproxima","Adornar el perímetro","Cazar jabalíes","Señar el aparcamiento"],"Obstáculo clásico: rompe el impulso del asalto, encauza al atacante hacia zonas batidas por el fuego y delata su presencia.","Fortificaciones de campaña"],
["M","Al ALISTAR un arma se la prepara para el fuego:",["Cargándola, amartillándola y quitando el seguro (o el seguro puesto según doctrina, lista para el empleo inmediato)","Vacíanándola y guardándola","Echándole aceite en el cañón","Colgándola en la pared"],"Alistar = dejar el arma lista para disparar; desalistar, lo contrario con seguridad puesta. Los estados del arma que el examinador juega.","Instrucción · armas"],
["F","Las reglas universales de seguridad con armas incluyen:",["Tratar toda arma como cargada, no apuntar nunca a lo que no se quiera destruir y mantener el dedo fuera del guardamonte hasta decidir disparar","Disparar al aire para descargar","Cerrar los ojos al disparar","Prestar el arma a cualquiera"],"Trío universal de seguridad: cero excepciones, cero «esta está descargada». La negligencia con armas no admite segunda oportunidad.","Instrucción · seguridad de armas"],
["M","La DISCIPLINA DE FUEGO exige:",["Disparar solo sobre objetivos identificados, dentro del sector asignado y a la voz o señal convenida","Disparar a todo lo que se mueva","Ahorro total: nunca disparar","Disparar desde la cadera al correr"],"Sin disciplina de fuego, la unidad agota la munición, delata su posición y daña a los suyos (fuego amigo). El cabo la impone y la mantiene.","Instrucción · control de fuego"],
["M","La voz «¡ALTO EL FUEGO!» significa:",["Cesar el fuego inmediatamente, aunque el enemigo no deje de disparar","Disparar más rápido","Cambiar de cargador","Ponerse a cubierto solo"],"Alto el fuego = cesar YA (la orden más urgente del combate). Cada tirador la repite por la cadena de mando para que llegue a todos.","Instrucción · control de fuego"],
["M","La técnica de progresión básica bajo fuego es:",["Avanzar por saltos: uno avanza mientras el otro cubre, alternando los papeles","Correr todos a la vez en línea","Andar de lado sin agacharse","Rodar por el suelo diez metros"],"«Uno avanza, otro cubre»: nunca se expone media unidad; el que cubre está listo para disparar. Saltos cortos y de sorpresa.","Instrucción · progresión"],
["M","De noche, en la marcha, la velocidad se reduce porque:",["La visibilidad es menor y aumentan los riesgos de caída, desorientación y pérdida de contacto","Los caballos no ven","El mapa se oscurece","La brújula se apaga"],"Noche = menos velocidad, formaciones más cerradas, control por contacto (dar al hombre de delante) y vedado el uso de luces visibles.","Instrucción · marcha nocturna"],
["M","La instrucción NOCTURNA se practica porque:",["La noche favorece la sorpresa y el movimiento oculto: hay que dominar el combate y la marcha sin luz","De día da pereza","Para ahorrar electricidad","Porque de noche no hay sargentos"],"Quien domina la noche mueve, ataca y resiste mejor: la oscuridad es terreno del que está instruido. Hoy, además, con visión nocturna.","Instrucción · combate nocturno"],
["M","Un intensificador de imagen (visión nocturna) funciona:",["Amplificando la luz residual (luna, estrellas) para formar la imagen","Radiografiando la oscuridad","Calentando el aire","Echando humo verde"],"Intensificador = amplifica la poca luz disponible (imagen verde). La TÉRMICA, en cambio, detecta el calor de cuerpos y motores: no las confundir.","Instrucción · medios ópticos"],
["D","En marcha nocturna pierdes el contacto con el hombre de adelante. Lo correcto:",["Alto inmediato por la cadena, avisar hacia atrás y rehacer el contacto SIN encender luces","Encender la linterna frontal y llamarlo a gritos","Seguir marchando a ver si aparece","Encender un encendedor"],"Alto, aviso en cadena y contacto sin luz (susurro de persona a persona): una linterna encendida te señala a kilómetros.","Instrucción · caso"],
["M","En campaña, el cuidado de los PIES es crítico porque:",["Las ampollas y lesiones inutilizan al combatiente tanto como una herida de bala","Para tenerlos bonitos en la foto","Los pies no importan","Solo importa en verano"],"Marcha y combate se ganan con los pies: medias limpias y sin arrugas, talco/polvos, ampolla pinchada con técnica (o no, según protocolo) y revisión en los altos técnicos.","Instrucción · higiene en campaña"],
["F","El uniforme de camuflaje de campaña tiene como fin:",["Dificultar la detección rompiendo la silueta e integrándose con el terreno","Estar más guapo en la foto","Ahorrar planchas","Identificarse al enemigo"],"El patrón rompe la silueta humana (lo que el ojo enemigo busca) y funde con el fondo: junto al silencio y a la disciplina de movimientos, es la primera protección.","Instrucción · campaña"],
["D","Un soldado dispara sin orden a un ruido en el bosque. El error es triple:",["Rompe la disciplina de fuego, delata la posición y puede herir a los suyos","Ninguno: había ruido","Solo gastó munición","Es señal de buena puntería"],"Sobre ruido no se dispara: se observa, se informa y el jefe decide. Tres daños en un disparo: disciplina, secreto y fuego amigo.","Instrucción · caso"],
["D","Tras el alto de una marcha, el cabo debe:",["Hacer contar la unidad, revisar estado y equipo, y atender bajas antes de reanudar","Marchar sin más al oír la voz","Dormir una siesta","Llamar a la base por teléfono móvil"],"En cada alto: control de personal (¿falta alguien?), revisión de pies y equipo, hidratación y atención a los rezagados. El alto no es vacaciones.","Instrucción · caso"],
["M","El SECTOR DE TIRO asignado a un tirador es:",["El espacio de terreno del que es responsable: lo vigila y debe batir con fuego todo objetivo que entre en él","El hueco del polvorín","La zona de las letrinas","Su sitio en el comedor"],"Cada uno sabe SU sector: se vigila con los ojos y se bate con el arma. Los huecos entre sectores los solapan los tiradores colindantes con el jefe.","Instrucción · control de fuego"],
["M","En patrulla, las comunicaciones en silencio se hacen:",["Con señales de mano pactadas (puño=alto, brazo extendido=avanzar…)","A gritos susurrantes","Con silbidos largos","Encendiendo el móvil"],"Las señales de mano se pactan ANTES de salir y se repiten hasta dominarlas: en patrulla, la voz delata y el ruido mata.","Instrucción · patrullas"],
["M","La condición física del combatiente:",["Es la base de toda su preparación: sin ella no hay marchas, combate ni resistencia al estrés","Es opcional en el ET","Sirve solo para el examen de ingreso","Se consigue con la cocina del cuartel"],"Marchas con carga, progresión, cavado y cargar heridos exigen fondo y fuerza: la física es el cimiento sobre el que se montan todas las destrezas.","Instrucción · instrucción física"]
]
assert len(RAW) == 50, "RAW tiene %d" % len(RAW)
import io
PATRON = [(p + j) % 4 for j in range(13) for p in range(4)][:50]
filas = []
for i, ((dif, q, ops, x, r), dest) in enumerate(zip(RAW, PATRON), 1):
    correcta = ops[0]; resto = ops[1:]
    nuevas = resto[:dest] + [correcta] + resto[dest:]
    esc = lambda t: t.replace('"', '\\"')
    filas.append('{c:"cabo",b:"C1",t:"Instrucción del combatiente",d:"%s",id:"ic%02d",q:"%s",o:[%s],a:%d,x:"%s",r:"%s"}' % (dif, i, esc(q), ",".join('"%s"' % esc(o) for o in nuevas), dest, esc(x), esc(r)))
LOTE13 = (',\n/* ===== LOTE EXAMINADOR — Tema 13: Instrucción del combatiente\n'
'   Elaboración PROPIA (examinador GALÓN), 21-sep-2026, contra fuentes verificadas hoy: doctrina clásica de\n'
'   instrucción (marchas 25-30 km jornada normal / ~50 extraordinaria, ritmo 4-5 km/h —confirmado por el propio ET\n'
'   en marchas de endurecimiento—, alto técnico 10 min/hora; cubierta=oculta, abrigo=protege del fuego; orden\n'
'   cerrada sin/con armas, voces preventiva y ejecutiva, saludo cubierto) + método de combate ES/AS (espacio y\n'
'   áreas de seguridad) + patrullas reconocimiento vs combate + trampas/cebos (espoleta de TRACCIÓN sobre objetos,\n'
'   según cuadernillos oficiales) + CONVENIO DE OTTAWA 1997 (España PROHIBE las minas antipersonal: se pregunta la\n'
'   prohibición, nunca el empleo) + Defensa NBQ (denominación vigente en España: Regimiento de Defensa NBQ\n'
'   «Valencia» I, 2005; EMDNBQ Hoyo de Manzanares; ejercicio GRIFO; alarma por voz GAS-GAS-GAS) + fortificaciones\n'
'   de campaña (foso de tirador, parapeto, alambrada) + control de fuego, progresión por saltos, visión nocturna.\n'
'   NOTA: se omiten cadencias de paso y composiciones numéricas de unidades por variar entre fuentes. */\n')
s = io.open('/home/user/galon/js/bank7.js', encoding='utf-8').read().rstrip()
assert s.endswith('];')
s = s[:-2] + LOTE13 + ",\n".join(filas) + "\n];\n"
io.open('/home/user/galon/js/bank7.js', 'w', encoding='utf-8').write(s)
from collections import Counter
difs = Counter(r[0] for r in RAW)
print("Lote Tema 13 montado: 50 · reparto correctas:", dict(sorted(Counter(PATRON).items())), "· dificultades:", dict(sorted(difs.items())))
