#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Lote Tema 6 · Carrera Militar (Ley 39/2007, de 19 de noviembre) — 50 preguntas, formato: [dif, pregunta, opciones(correcta=0), explicación, ref]
RAW = [
["F","Según el artículo 1 de la Ley 39/2007, de 19 de noviembre, esta ley tiene por objeto:",["Regular el régimen del personal militar profesional y, específicamente, la carrera militar, además de la aportación adicional de recursos humanos a las Fuerzas Armadas","Regular únicamente los ascensos y destinos de los militares","Regular el régimen del personal de la Guardia Civil exclusivamente","Regular los derechos y deberes de los militares"],"La 39/2007, de 19 de noviembre, de la CARRERA MILITAR (BOE 20-nov-2007, en vigor 01-01-2008). Los derechos y deberes van en la LO 9/2011 (Tema 4); la GC tiene su Ley 42/1999.","Ley 39/2007 art. 1"],
["F","Según el artículo 2.1 de la Ley de la carrera militar, el Rey tiene el empleo militar de:",["Capitán general del Ejército de Tierra, de la Armada y del Ejército del Aire, máximo rango militar que le corresponde en exclusiva como mando supremo de las Fuerzas Armadas","General de ejército","Teniente general honorífico","Un empleo simbólico sin denominación concreta"],"Art. 2.1 literal: capitán general de los tres Ejércitos, máximo rango en EXCLUSIVA como mando supremo (enlaza con la LODEF, art. 3).","Ley 39/2007 art. 2.1 · LODEF art. 3"],
["F","Según el artículo 3, los españoles pueden vincularse profesionalmente a las Fuerzas Armadas:",["Como militares de carrera, como militares de tropa y marinería y también como militares de complemento","Únicamente como militares de carrera","Como militares de carrera y como reservistas","Como funcionarios o como personal laboral"],"Tres formas de vinculación profesional. Los reservistas aportan recursos (Ley 38/2007) pero no son una tercera relación profesional de este artículo.","Ley 39/2007 art. 3.1"],
["M","Son militares de carrera:",["Quienes mantienen una relación de servicios profesionales de carácter permanente, a quienes corresponde asegurar la continuidad y estabilidad de la estructura, el funcionamiento y los valores esenciales de las FAS","Los que firman compromisos temporales","Los oficiales adscritos temporalmente","Los alumnos de las academias"],"Palabra clave de examen: PERMANENTE. La carrera es la relación estable; la TM y el complemento, temporal.","Ley 39/2007 art. 3.2"],
["M","Según el artículo 3.3, los militares de complemento:",["Son OFICIALES que establecen su relación de servicios profesionales mediante compromisos de carácter temporal","Son suboficiales con contrato de 3 años","Son soldados con compromiso de larga duración","Son reservistas con destino permanente"],"Trampa redonda: el complemento es de OFICIALES (acceden con el empleo de teniente, art. 77).","Ley 39/2007 art. 3.3"],
["M","Los militares de tropa y marinería:",["Constituyen la BASE de las Fuerzas Armadas, establecen su relación mediante compromisos de carácter temporal y pueden acceder a la condición de militar de carrera","Son funcionarios interinos","Solo pueden ser españoles de nacimiento","Tienen relación permanente desde el primer día"],"Base de las FAS + compromisos temporales + posible acceso a carrera. Y los extranjeros con residencia legal también pueden vincularse como TM (art. 3.5).","Ley 39/2007 arts. 3.4-3.5"],
["F","Según el artículo 4 de la Ley de la carrera militar, las reglas esenciales que definen el comportamiento del militar:",["Son las definidas en la Ley Orgánica de derechos y deberes de los miembros de las FAS, y las desarrollan reglamentariamente las Reales Ordenanzas","Se fijan exclusivamente en esta ley","Las determina cada Ejército por su cuenta","Son las del Código Penal común"],"El mapa completo: LODEF art. 20 (mediante ley) → LO 9/2011 (definición) → RROO (desarrollo). Tres temas enlazados.","Ley 39/2007 art. 4 · LO 9/2011 · RROO"],
["D","La fórmula del juramento o promesa ante la Bandera incluye comprometerse a:",["Guardar y hacer guardar la Constitución como norma fundamental del Estado, obedecer y respetar al Rey y a vuestros jefes, no abandonarlos nunca y, si preciso fuera, entregar vuestra vida en defensa de España","Defender la Constitución, obedecer al Gobierno y proteger a los ciudadanos","Servir lealmente a España y a sus instituciones hasta el final de mi compromiso","Obedecer y respetar a la Constitución y a mis jefes durante mi vida militar"],"Fórmula LITERAL del art. 7.2; respuesta de los soldados: «¡Sí, lo hacemos!». Es requisito previo e indispensable para la condición de militar de carrera, de complemento y de TM (art. 7.1).","Ley 39/2007 art. 7"],
["M","El juramento o promesa ante la Bandera se efectúa:",["Durante la enseñanza de formación, como requisito previo e indispensable a la adquisición de la condición de militar de carrera, de complemento y de tropa y marinería","Al obtener el primer ascenso","A los 6 meses de servicio, salvo exención","Solo los militares de carrera"],"Primero se jura, después se adquiere la condición. Sin juramento no hay condición militar profesional.","Ley 39/2007 art. 7.1"],
["M","En materia de personal, el Gobierno y el Ministro de Defensa:",["El Gobierno dirige el planeamiento de la defensa y aprueba la programación plurianual de provisión de plazas; el Ministro dirige la política de personal y de enseñanza en las FAS","Ambos asuntos los decide el JEMAD","El Ministro aprueba las plantillas cuatrienales y el Gobierno dirige la enseñanza","La política de personal la dirige el Subsecretario en exclusiva"],"Gobierno: función ejecutiva y potestad reglamentaria + programación plurianual (art. 8). Ministro: dirige la política de personal y de ENSEÑANZA (art. 9).","Ley 39/2007 arts. 8-9"],
["D","Según el artículo 13.1, el nombramiento del JEMAD y de los JEMEs:",["El JEMAD por real decreto en Consejo de Ministros a propuesta del PRESIDENTE del Gobierno; los JEMEs a propuesta del MINISTRO de Defensa","Ambos a propuesta del Ministro de Defensa","Ambos a propuesta del Presidente del Gobierno","El JEMAD lo nombra el Rey libremente"],"Trampa fina del art. 13.1: el JEMAD se propone desde PRESIDENCIA; los JEMEs desde DEFENSA. Los dos por real decreto en Consejo de Ministros.","Ley 39/2007 art. 13.1"],
["M","El nombramiento de JEMAD o de los JEMEs lleva implícito el ascenso automático a:",["General de ejército, almirante general o general del aire, según el Ejército de procedencia","Teniente general en todo caso","Capitán general","No existe ascenso implícito"],"Art. 13.2: a GE/AG/GA; si el elegido es GD o vicealmirante, antes asciende a TG/almirante. Y durante el cargo, el JEMAD es el más antiguo en su empleo. Además siguen en activo aunque cumplan la edad de retiro (art. 13.3).","Ley 39/2007 arts. 13.2-13.3"],
["F","Los Consejos Superiores del Ejército de Tierra, la Armada y el Ejército del Aire son:",["Órganos colegiados asesores y consultivos del Ministro y del JEME, que actúan como órgano de evaluación en los ascensos al empleo de general de brigada","Órganos de mando operativo de cada Ejército","Órganos disciplinarios de primera instancia","Comisiones sindicales del Ejército"],"Art. 14.1.c: la evaluación de los ascensos a GENERAL DE BRIGADA es de los Consejos Superiores. Detalle que cae.","Ley 39/2007 art. 14.1"],
["M","El número máximo de militares profesionales en servicio activo y de oficiales generales es:",["Entre 130.000 y 140.000 efectivos, con un máximo de 50.000 oficiales generales, oficiales y suboficiales, y un máximo de 200 oficiales generales","200.000 efectivos en total, de ellos 20.000 oficiales","120.000 efectivos, con 300 oficiales generales","Entre 100.000 y 120.000, con 1.000 coroneles"],"Números del art. 16: 130.000-140.000 en activo · máx. 50.000 of+subof · máx. 200 OG · máx. 1.050 coroneles.","Ley 39/2007 art. 16"],
["D","Para amortizar los excedentes en los diferentes empleos y escalas:",["No se da al ascenso la primera vacante de cada DOS en los empleos de oficiales generales y la primera de cada TRES en los restantes empleos","Se congela la primera vacante de cada cinco en todos los empleos","Se suprime directamente el empleo superior","Se congelan todos los ascensos un año"],"Art. 16.5: la regla 2/3. Oficiales generales: se salta una de cada dos vacantes; el resto de empleos: una de cada tres.","Ley 39/2007 art. 16.5"],
["F","El militar profesional ejerce funciones:",["Operativas, técnicas, logísticas y administrativas, desarrolladas por medio de acciones directivas, que incluyen las de mando, y acciones de gestión y ejecutivas","Únicamente operativas","De mando y de descanso programado","Administrativas salvo en operaciones"],"El literal del art. 19.1 que ya cayó en examen oficial. Además ejerce funciones DOCENTES (título IV).","Ley 39/2007 art. 19.1"],
["M","La acción de mando es:",["La acción directiva específica en las Fuerzas Armadas: el ejercicio de la autoridad, con la consiguiente responsabilidad, que corresponde al militar en razón de su cargo, destino o servicio","Cualquier tarea administrativa del día a día","Solo la ejercen los oficiales generales","La colaboración de los subordinados con el jefe"],"Art. 19.3 literal. Y la colaboración de los subordinados (información, planeamiento, asesoramiento, coordinación y control) es el «apoyo al mando», no el mando.","Ley 39/2007 art. 19.3"],
["F","Los militares se agrupan en las categorías siguientes:",["Oficiales generales, oficiales, suboficiales y tropa y marinería","Generales, jefes, oficiales y soldados","Alta dirección, mandos, especialistas y personal de apoyo","Tres: oficiales, suboficiales y tropa"],"CUATRO categorías (art. 20.1). El olvido clásico: separar oficiales GENERALES de oficiales.","Ley 39/2007 art. 20.1"],
["M","Según el artículo 20, constituyen el eslabón fundamental en la estructura orgánica y operativa de las Fuerzas Armadas:",["Los suboficiales","Los oficiales","Los cabos","Los oficiales generales"],"Literal del art. 20.4: los suboficiales, EL ESLABÓN FUNDAMENTAL. La tropa y marinería es la BASE (art. 20.5) y los oficiales generales ejercen la alta dirección (art. 20.2).","Ley 39/2007 arts. 20.2-20.5"],
["M","Los empleos militares de la categoría de oficiales generales son:",["Capitán general; general de ejército, almirante general o general del aire; teniente general o almirante; general de división o vicealmirante; general de brigada o contralmirante","Teniente general, general de división y general de brigada, únicamente","Capitán general, general y coronel general","General de ejército y teniente general, sin más"],"Art. 21.2.a, los CINCO grados de empleo (la primera denominación es la del ET). El capitán general es el empleo del Rey.","Ley 39/2007 art. 21.2.a"],
["M","Los empleos de la categoría de suboficiales, en orden ascendente, son:",["Sargento, sargento primero, brigada, subteniente y suboficial mayor","Sargento, brigada, sargento primero, subteniente y suboficial mayor","Cabo, cabo primero, sargento y brigada","Sargento primero, sargento, brigada, subteniente y suboficial mayor"],"Orden literal del art. 21.2.c: el sargento primero va ANTES que brigada y el suboficial mayor cierra la escala.","Ley 39/2007 art. 21.2.c"],
["M","Los empleos de la categoría de tropa y marinería son:",["Soldado o marinero, cabo, cabo primero y cabo mayor","Soldado, soldado de primera, cabo y cabo primero","Soldado, cabo, cabo primero, cabo mayor y sargento","Soldado y cabo, sin más"],"CUATRO empleos (art. 21.2.d). Anti-obsoleto: el CABO MAYOR sí existe en la ley vigente (lo omiten cuadernillos antiguos).","Ley 39/2007 art. 21.2.d"],
["D","Según las escalas de empleos:",["El empleo inmediato superior a brigada es subteniente, y el inmediato superior a cabo primero es cabo mayor","El inmediato superior a brigada es suboficial mayor, y a cabo primero, sargento","El inmediato superior a brigada es sargento primero, y a cabo primero, brigada","El inmediato superior a brigada es teniente, y a cabo primero, cabo mayor"],"Escalas: …brigada → subteniente → suboficial mayor. T/M: …cabo → cabo primero → cabo mayor (art. 21.2).","Ley 39/2007 art. 21.2"],
["M","Según el artículo 23.2, la antigüedad es:",["El tiempo transcurrido en el primer empleo de una escala desde la fecha de su concesión","El tiempo total de vida militar desde el juramento","El tiempo en el último destino","Los trienios cobrados"],"Definición literal. En sucesivos empleos, desde la firma de la resolución del ascenso (salvo que en ella conste la fecha de la vacante).","Ley 39/2007 art. 23.2"],
["M","El escalafón es:",["La ordenación por empleos y antigüedad de los militares profesionales pertenecientes o adscritos a una escala","La lista de destinos de una unidad","El registro de armas de la unidad","El cuadro de retribuciones"],"Art. 23.3 literal. Su orden solo puede alterarse por la ley y las leyes penales y disciplinarias militares.","Ley 39/2007 art. 23.3"],
["D","La precedencia entre militares se determina:",["Por el cargo o destino que se ocupe si está fijado en normas reglamentarias; si no, por el empleo; a igualdad de empleo, por la antigüedad; y a igualdad de ésta, a favor del de mayor edad","Siempre por la edad, de mayor a menor","Siempre por el cuerpo de procedencia","Por sorteo anual"],"Cadena del art. 23.4: destino → empleo → antigüedad → edad. Última vuelta de tuerca para un examen.","Ley 39/2007 art. 23.4"],
["M","Los empleos con carácter honorífico los concede:",["El Consejo de Ministros, a propuesta del Ministro de Defensa, y consisten en el empleo inmediato superior al que tiene el militar que haya pasado a retiro o resuelva su compromiso","El Rey directamente a petición del interesado","El JEMAD por delegación permanente","El Consejo Superior de cada Ejército en pleno"],"Art. 24.1: CM a propuesta del Ministro. También a título póstumo; y SIEMPRE se inicia expediente para los fallecidos en acto de servicio o que se retiren por incapacidad permanente en acto de servicio (art. 24.2).","Ley 39/2007 art. 24"],
["F","Los empleos concedidos con carácter honorífico:",["No llevan en ningún caso beneficio económico de naturaleza alguna ni serán considerados a efectos de derechos pasivos","Dan derecho a un complemento mensual","Equivalen a un ascenso retribuido","Generan mejora automática de pensión"],"Art. 24.3 literal: honor es honor, no retribución.","Ley 39/2007 art. 24.3"],
["F","La carrera militar queda definida por:",["La ocupación de diferentes destinos, el ascenso a los sucesivos empleos y la progresiva capacitación para puestos de mayor responsabilidad, combinando preparación y experiencia profesional","La suma de cursos realizados durante la vida militar","El cobro de trienios a lo largo de la trayectoria","La antigüedad acumulada en cada destino"],"Definición LITERAL del art. 74.1: destinos + ascensos + capacitación progresiva.","Ley 39/2007 art. 74.1"],
["M","La carrera de los militares de tropa y marinería:",["Comienza con un compromiso inicial renovable hasta un máximo de 6 años; posteriormente pueden suscribir un compromiso de larga duración desde el que se puede acceder a la condición de militar de carrera","Firma relación permanente el primer día","Renueva cada año indefinidamente sin acceso a carrera","Pasa a carrera a los 3 años automáticamente"],"Art. 75.5: inicial (máx. 6 años) → larga duración → posible militar de carrera. Y a partir de los 45 años orientan su trayectoria preferentemente a funciones logísticas y administrativas.","Ley 39/2007 art. 75.5"],
["M","El primer empleo militar de cada escala de oficiales o de suboficiales lo confiere:",["El Rey, refrendado por el Ministro de Defensa","El Ministro de Defensa directamente","El JEME del Ejército correspondiente","El Subsecretario de Defensa"],"Art. 76.2: Rey confiere + Ministro refrenda. Caso aparte: el empleo de teniente de los de complemento lo confiere el MINISTRO (art. 77.1).","Ley 39/2007 art. 76.2"],
["M","Los militares de complemento:",["Adquieren la condición al adscribirse a una escala y cuerpo con el empleo de TENIENTE conferido por el Ministro de Defensa; su compromiso es de 3 u 8 años, renovable hasta un máximo de 8 años de servicio","Entren con empleo de capitán por real decreto","Tienen compromiso único de 12 años","Renuevan sin límite temporal"],"Art. 77: teniente por el Ministro + compromiso de 3 u 8 años + techo de 8 años. Refuerza el carácter TEMPORAL del complemento.","Ley 39/2007 art. 77"],
["F","El historial militar consta de:",["Hoja de servicios, colección de informes personales, expediente académico y expediente de aptitud psicofísica","Curriculum vitae, cartas de recomendación y fotocopia del DNI","Solo la hoja de servicios","Hoja de servicios y sanciones disciplinarias publicadas"],"Los CUATRO documentos del art. 79.1; uso CONFIDENCIAL; sin datos de raza, religión, opinión ni circunstancias que puedan discriminar (art. 79.2).","Ley 39/2007 art. 79"],
["M","Los alumnos de los centros docentes militares de formación:",["Al ingresar firman un documento de incorporación, tienen condición militar SIN relación de servicios profesionales y quedan sujetos al régimen de derechos y deberes y a las leyes penales y disciplinarias militares","No tienen condición militar hasta jurar","Tienen condición de reservistas","Están exentos de la ley disciplinaria"],"Literal del art. 67: explica por qué los alumnos sin condición de militar profesional quedan EXCLUIDOS de las asociaciones profesionales (Tema 4): no están en una relación de servicios profesional.","Ley 39/2007 art. 67 · LO 9/2011"],
["F","Según la ley vigente, los ascensos a los diferentes empleos se producen aplicando los sistemas de:",["Elección, clasificación, concurso o concurso-oposición y antigüedad","Antigüedad, selección y elección","Solo antigüedad y selección","Elección, sorteo y concurso"],"⚠️ ANTI-OBSOLETO: ya NO existe el ascenso por SELECCIÓN (lo que repiten cuadernillos viejos); el texto vigente del art. 88.2 dice CLASIFICACIÓN.","Ley 39/2007 art. 88.2"],
["M","En cuanto a la vacante para ascender:",["Se asciende al empleo inmediato superior con ocasión de vacante en la escala, salvo en los ascensos por antigüedad, en que se asciende cumplido el tiempo de servicios que se determine","Todos los ascensos exigen vacante previa","Ningún ascenso exige vacante","Por elección no se necesita vacante, pero sí por clasificación"],"Regla general del art. 88.3: empleo inmediato superior + vacante. Excepción: ANTIGÜEDAD (capitán, sargento primero): al cumplirse el tiempo de servicios.","Ley 39/2007 art. 88.3"],
["M","Los ascensos en la categoría de oficiales:",["A coronel: elección; a teniente coronel y a comandante: clasificación; a capitán: antigüedad","A coronel: antigüedad; a TC: elección; a comandante: clasificación","A coronel: clasificación; a TC: antigüedad; a capitán: elección","Todos por selección"],"Tabla del art. 89.1. Y a los empleos de oficiales generales: ELECCIÓN. Excepción: en escalas técnicas de ingenieros y oficiales enfermeros, a TC se asciende por elección (art. 89.2).","Ley 39/2007 art. 89"],
["M","Los ascensos de suboficiales y tropa y marinería:",["A suboficial mayor: elección; a subteniente y a brigada: clasificación; a sargento primero: antigüedad; a cabo mayor: elección; a cabo primero y a cabo: concurso o concurso-oposición","Todos por antigüedad","A cabo: elección; a cabo primero: clasificación","A brigada: concurso; a subteniente: antigüedad"],"LA TABLA COMPLETA del art. 89.1. Para vosotros: a CABO se asciende por CONCURSO o CONCURSO-OPOSICIÓN.","Ley 39/2007 art. 89.1"],
["D","Un cabo quiere ascender a cabo primero. Según la ley:",["Se ascenderá por el sistema de concurso o concurso-oposición: entre los que lo soliciten, en el orden obtenido en el correspondiente proceso selectivo","Automáticamente al cumplir 4 años de cabo","Por antigüedad al cumplir 6 años","Por elección del coronel del regimiento"],"Aplicación directa del art. 88.2.c y 89.1.i: el sistema de concurso o concurso-oposición produce ascensos ENTRE LOS QUE LO SOLICITEN, en el orden del proceso selectivo.","Ley 39/2007 arts. 88-89 · caso"],
["M","Para ascender al empleo de cabo mayor se exige:",["La titulación de técnico del sistema educativo general","Solo 8 años de servicio","Titulación universitaria de grado","Ninguna titulación"],"Art. 90.2: para cabo mayor, técnico del sistema educativo general. Para TC: titulaciones específicas del perfeccionamiento (art. 75.2).","Ley 39/2007 art. 90.2"],
["D","Sobre la evaluación para el ascenso:",["Para ascender a un empleo militar hasta el de general de brigada INCLUSIVE es condición indispensable haber sido evaluado","Solo hace falta evaluación para oficial general","La evaluación es voluntaria en todos los empleos","Solo se evalúa a los suboficiales"],"Art. 90.5 literal: la evaluación pesa hasta general de brigada inclusive.","Ley 39/2007 art. 90.5"],
["M","La duración de los ciclos en los ascensos por elección y clasificación es de:",["Un año","Tres años siempre","Cinco años","No existen ciclos"],"Art. 92.1: ciclo de UN AÑO en elección y clasificación (modificable por el Ministro, previo informe del JEME). En concurso y antigüedad, la evaluación vale hasta concederse el ascenso.","Ley 39/2007 art. 92.1"],
["D","Un militar renuncia por segunda vez a ser evaluado para el ascenso. Consecuencia:",["Permanecerá en su empleo hasta su pase a la situación de reserva","Ninguna: puede renunciar tantas veces como quiera","Pasa directamente a retiro","Pierde un empleo"],"Art. 92.3: la doble renuncia a la evaluación congela la carrera. Y quien renuncie dos veces a cursos de actualización no va a esos cursos (y queda limitado en destinos, art. 101.4).","Ley 39/2007 arts. 92.3 y 101.4"],
["F","Los destinos, según su forma de asignación, son:",["De libre designación, de concurso de méritos y de provisión por antigüedad","De sorteo, concurso y antigüedad","De elección, evaluación y sorteo","Únicamente de concurso de méritos"],"Tres formas (art. 100.1). En la libre designación la autoridad aprecia la idoneidad DISCRECIONALMENTE; la provisión por antigüedad es por orden de escalafón.","Ley 39/2007 art. 100"],
["M","Los nombramientos de cargos de oficiales generales:",["Los cargos de teniente general y general de división los nombra el Consejo de Ministros por real decreto a propuesta del Ministro de Defensa; el resto de cargos de oficiales generales, el Ministro de Defensa","Todos los cargos los nombra el Rey en consejo","Todos los nombra el JEMAD","Los nombra el Secretario de Estado de Defensa"],"Art. 102: TG y GD por CM/RD (propuesta del Ministro); los demás cargos de OG, competencia del MINISTRO.","Ley 39/2007 art. 102"],
["F","Las situaciones administrativas de los militares profesionales son:",["Servicio activo, servicios especiales, excedencia, suspensión de funciones, suspensión de empleo, reserva y servicio en la Administración civil","Servicio activo, reserva y retirado, únicamente","Activo, excedencia y retiro","Las mismas que un funcionario común del EBEP sin más"],"SIETE situaciones (art. 107.1). Y a RESERVA y a servicio en la Administración civil SOLO se accede siendo militar de CARRERA (art. 107.2).","Ley 39/2007 art. 107"],
["D","Un militar en situación de servicios especiales:",["Tiene su condición militar en SUSPENSO: deja de estar sujeto al régimen general de derechos y deberes y a las leyes penales y disciplinarias, pero computa para tiempo de servicios, trienios y derechos pasivos y PUEDE ascender","Pierde la condición militar","Se pasa automáticamente a retiro","No computa para nada"],"Art. 109.5: por eso un militar en servicios especiales NO puede afiliarse a una asociación profesional: no está sujeto al régimen general (enlace con el Tema 4).","Ley 39/2007 art. 109 · LO 9/2011 · caso"],
["M","La situación de suspensión de funciones:",["Procede por procesamiento, inculpación o medida cautelar penal, o por la incoación de un procedimiento disciplinario por falta MUY grave; la permanencia máxima es de seis meses","Procede por cualquier falta disciplinaria leve","Es indefinida","Solo procede tras sentencia firme"],"Art. 111: máx. 6 meses (o la duración de la prisión preventiva si es mayor). Enlaza con el Tema 2: falta muy grave → expediente.","Ley 39/2007 art. 111"],
["M","La situación de reserva:",["Pase forzoso al cumplir 4 años en el empleo de general de brigada, 7 entre GB y GD y 10 entre los anteriores y teniente general; y 6 años en el empleo de coronel, de TC de escalas técnicas y de suboficial mayor; además, oficiales y suboficiales de carrera pasan a reserva al cumplir 61 años y los de tropa y marinería de carrera, al cumplir 58","Se produce para todos al cumplir los 65 años","Se produce al cumplir 30 años de servicio siempre","Se produce a los 50 años por regla general"],"Dos claves del art. 113: tiempos en empleo (4/7/10 y 6) y edades (61 of/subof de carrera · 58 TM de carrera). Si al corresponderle la reserva no tiene 20 años de servicios → retiro directo (art. 113.6). En la reserva NO se producen ascensos (113.7).","Ley 39/2007 art. 113"],
["D","Sobre el retiro y los militares retirados:",["El retiro se declara al cumplir los 65 años, por insuficiencia de condiciones psicofísicas o de facultades profesionales, o voluntariamente; el retirado deja de estar sujeto al régimen general y se identifica con su empleo seguido de la palabra «retirado»","El retiro obliga a perder el uniforme para siempre y a no acercarse a unidades","El retiro solo procede por edad","El retirado sigue sujeto a la ley disciplinaria"],"Arts. 114 (65 años; insuficiencias —forzoso en esos supuestos—; voluntario) y 115 (cesa definitivamente; adscripción a unidad si la solicita; uniforme en actos solemnes; empleo + «retirado»). Y la pérdida de la condición de militar de carrera incluye la sanción disciplinaria de SEPARACIÓN firme (art. 116, enlace con el Tema 2).","Ley 39/2007 arts. 114-116"]
]
assert len(RAW) == 50, "RAW tiene %d" % len(RAW)
import io
PATRON = [(p + j) % 4 for j in range(13) for p in range(4)][:50]
filas = []
for i, ((dif, q, ops, x, r), dest) in enumerate(zip(RAW, PATRON), 1):
    correcta = ops[0]; resto = ops[1:]
    nuevas = resto[:dest] + [correcta] + resto[dest:]
    esc = lambda t: t.replace('"', '\\"')
    filas.append('{c:"cabo",b:"C1",t:"Carrera militar",d:"%s",id:"cm%02d",q:"%s",o:[%s],a:%d,x:"%s",r:"%s"}' % (dif, i, esc(q), ",".join('"%s"' % esc(o) for o in nuevas), dest, esc(x), esc(r)))
LOTE6 = (',\n/* ===== LOTE EXAMINADOR — Tema 6: Carrera militar (Ley 39/2007, de 19 de noviembre)\n'
'   Elaboración PROPIA (examinador GALÓN), 20-sep-2026, sobre el texto VIGENTE del BOE consolidado\n'
'   (BOE-A-2007-19880 · ÚLTIMA ACTUALIZACIÓN 09/11/2024). Ley REFORMADA en varias ocasiones: Ley 46/2015\n'
'   (art. 24 empleos honoríficos + art. 24 bis vinculación honorífica + sistemas de ascenso) y Ley 5/2024,\n'
'   de 8 de noviembre (transitorias, suboficiales ascendidos a teniente, pase a reserva); art. 71.4 por la\n'
'   LO 8/2014. ANTI-OBSOLETO verificado en vigente: ya NO existe el ascenso por "selección" (art. 88.2:\n'
'   elección, CLASIFICACIÓN, concurso/concurso-oposición y antigüedad); el CABO MAYOR es empleo vigente;\n'
'   reserva a los 61 (of/subof carrera) y 58 (TM carrera), retiro a los 65 (nada de tablas antiguas por empleos);\n'
'   JEMAD a propuesta del PRESIDENTE vs JEMEs a propuesta del MINISTRO (art. 13.1); primer empleo lo confiere\n'
'   el REY (art. 76.2); fórmula literal del juramento ante la Bandera (art. 7.2); a CABO se asciende por\n'
'   CONCURSO o CONCURSO-OPOSICIÓN (art. 89.1); 7 situaciones administrativas (art. 107). */\n')
s = io.open('/home/user/galon/js/bank7.js', encoding='utf-8').read().rstrip()
assert s.endswith('];')
s = s[:-2] + LOTE6 + ",\n".join(filas) + "\n];\n"
io.open('/home/user/galon/js/bank7.js', 'w', encoding='utf-8').write(s)
from collections import Counter
print("Lote Tema 6 montado: 50 · reparto correctas:", dict(sorted(Counter(PATRON).items())))
