#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Lote Tema 15 · Armamento y tiro — 50 preguntas, formato: [dif, pregunta, opciones(correcta=0), explicación, ref]
# Fuentes verificadas 21-sep-2026: FICHA OFICIAL del ET (ejercito.defensa.gob.es/materiales/armamento_ligero/
# FUSIL-G36E.html: origen Alemania, fabricación Alemania/España, 5,56 mm, cargador, cadencia 750 dpm, toma de
# gases, 3,3 kg, cargador de 30, accesorio lanzagranadas) + INFODEFENSA 11-sep-2026 (el G36E sigue siendo el
# fusil reglamentario de las FAS; compra de 3.580 más: 1.200 G36E + 2.380 G36KVE) + páginas de materiales de
# unidades del ET (USP Standard 9×19 Parabellum; USP-SD en OE; AG36 40×46) + anexo de materiales (G36E desde
# 1999 sustituye al CETME L; cofabricado por Santa Bárbara Sistemas en La Coruña; USP comprada en 2011; LAG-40;
# K=Kurz corto) + teoría clásica del tiro (balística interior/exterior/de efectos, trayectoria, espacio cubierto,
# zona batida, terreno muerto, puesta a cero, cadencia) + familia Instalaza (C-90 90 mm descartable, Alcotán-100).
# OMITIDOS (fuentes disputan o varían): cadencia exacta de la MG3, modelos concretos de mortero y denominaciones
# internas de versiones (regla: no preguntar lo que las fuentes disputan).
RAW = [
["F","El fusil reglamentario del Ejército de Tierra es el:",["G36E (Heckler & Koch), calibre 5,56 mm","AK-47 calibre 7,62 mm","M16A2 calibre 5,56 mm","CETME C calibre 7,62 mm"],"El G36E es el fusil de servicio estándar de las FAS desde 1999: ficha oficial del ET y compras recientes lo confirman (en 2026 se compraron 3.580 más).","Ficha oficial ET · FUSIL-G36E"],
["F","El calibre del fusil G36E es:",["5,56 × 45 mm OTAN","7,62 × 51 mm OTAN","9 × 19 mm","5,45 × 39 mm"],"Ficha oficial: calibre 5,56 mm (5,56 × 45 OTAN), el estándar de fusilería aliado.","Ficha oficial ET · FUSIL-G36E"],
["F","Según la ficha oficial, el cargador del G36E contiene:",["30 cartuchos","20 cartuchos","50 cartuchos","10 cartuchos"],"Ficha oficial literal: cargador de 30 cartuchos.","Ficha oficial ET · FUSIL-G36E"],
["F","La cadencia de fuego del G36E es de:",["750 disparos por minuto","150 disparos por minuto","3.000 disparos por minuto","60 disparos por minuto"],"Ficha oficial: cadencia de 750 disparos por minuto (automático: el límite real lo pone el cargador y la barra del arma).","Ficha oficial ET · FUSIL-G36E"],
["M","El peso del G36E es de:",["3,3 kg","1,2 kg","6,5 kg","10 kg"],"Ficha oficial: 3,3 kg — ligero para la marcha y el combate de infantería.","Ficha oficial ET · FUSIL-G36E"],
["M","El sistema de cierre del G36E (ficha oficial) es:",["Toma de gases","Retroceso de cañón","Cerrojo manual","Palanca de vaciado"],"Toma de gases: parte de los gases del disparo recicla el mecanismo — el sistema clásico de los fusiles de asalto modernos.","Ficha oficial ET · FUSIL-G36E"],
["M","La fabricación del G36E se reparte entre:",["Alemania y España (Santa Bárbara Sistemas, La Coruña)","Estados Unidos y Portugal","Francia e Italia","Solo Alemania"],"Ficha oficial: fabricación Alemania/España; los comprados por España se cofabricaron y montaron en la planta de Santa Bárbara Sistemas de La Coruña.","Ficha oficial ET · materiales"],
["M","El fusil al que sustituyó el G36E en 1999 fue:",["El CETME L","El Mosin-Nagant","El M1 Garand","El FN FAL español"],"El G36E sustituyó al CETME L (5,56), desarrollado en España; el CETME C (7,62) fue su antecesor histórico.","Materiales del ET"],
["M","La versión COMPACTA (cañón corto) del fusil G36 se denomina:",["G36KVE (la K es de Kurz, «corto» en alemán)","G36XXL","G36Largo","MP7"],"G36E estándar, G36KVE de cañón corto (Kurz) y G36CE carabina: la K es de Kurz. En 2026 se compraron 2.380 KVE (más que del estándar).","Infodefensa 2026 · materiales"],
["F","La pistola reglamentaria del Ejército de Tierra es la:",["HK USP, calibre 9 × 19 mm Parabellum","Pistola Llama 7,65 mm","Desert Eagle .50","Beretta 92F 7,65 mm"],"La Heckler & Koch USP en 9 × 19 Parabellum es la pistola estándar del ET (adquirida en 2011 y entregada 2011-2013).","Materiales del ET · fichas de unidad"],
["M","La versión USP-SD de la pistola se caracteriza por:",["Cañón con rosca para montar un supresor (silenciador)","Cargador doble","Calibre 5,56 mm","Ser revólver"],"La USP-SD lleva cañón roscado para el silenciador: la usan las unidades de Operaciones Especiales.","Materiales del ET · MOE"],
["F","El subfusil clásico de 9 × 19 mm del ET (unidades específicas) es la familia:",["MP5 (Heckler & Koch)","Uzi belga","Thompson .45","Sterling inglés"],"El MP5 en 9 × 19 es el subfusil de referencia en unidades específicas (PEO, policía militar, OE).","Materiales del ET"],
["F","El lanzagranadas que se acopla bajo el cañón del G36 es el:",["AG36, de 40 × 46 mm","RPG-7","M203 de 60 mm","MILAN 40"],"AG36: lanzagranadas individual de 40 × 46 mm bajo el fusil (ficha de unidades con el G36).","Fichas de unidad · AG36"],
["M","El LAG-40 es:",["Un lanzagranadas automático de 40 mm sobre trípode","Un fusil de cerrojo","Un mortero de 40 mm","Un lanzallamas"],"Lanzagranadas Automático Santa Bárbara LAG-40 (40 × 53): fuego de área desde posición, sobre trípode o vehículo.","Materiales del ET"],
["F","El C-90 (Instalaza) es:",["Un lanzagranadas contracarros DESCARTABLE de 90 mm","Un camión de combate","Un casco blindado","Un cañón remolcado"],"C-90: arma individual descartable de 90 mm (Instalaza, España): se dispara y se tira. Su sucesor mayor es el Alcotán-100.","Instalaza · materiales"],
["M","El Alcotán-100 (Instalaza) es:",["Un lanzagranadas contracarros de 100 mm recargable con óptica y telémetro","Una granada de mano","Un fusil de precisión","Un misil guiado por cable de 120 mm"],"Alcotán-100: tubo lanzador reutilizable de 100 mm con sistema de puntería: el apoyo contracarros del pelotón español.","Instalaza · materiales"],
["M","La ametralladora MG3 emplea munición:",["7,62 × 51 mm OTAN","5,56 × 45 mm OTAN","9 × 19 mm","12,7 × 99 mm"],"La MG3 (evolución de la mítica MG42 alemana) trabaja el 7,62 × 51 OTAN: el estándar de ametralladora media.","Cuadernillos · MG3"],
["M","La ametralladora LIGERA del pelotón en 5,56 × 45 mm es la:",["Minimi","MG42","Browning .50","Vickers"],"La FN Minimi dispara el mismo cartucho que el fusil G36 (5,56): eso simplifica la logística del pelotón.","Materiales del ET"],
["M","La ametralladora pesada ANTIAÉREA y anticarro ligera clásica es la:",["Browning de 12,70 mm (.50)","MG3 de 7,62","Minimi de 5,56","LAG-40"],"La Browning M2 de 12,70 mm (.50): vehículos y defensa antiaérea corta, un siglo dando guerra.","Materiales del ET"],
["F","La BALÍSTICA INTERIOR estudia:",["Lo que ocurre al proyectil DENTRO del cañón (gases, presiones, aceleración)","El vuelo del proyectil en el aire","El impacto en el blanco","Las balas del enemigo"],"Interior = dentro del cañón; exterior = el vuelo; de efectos = el impacto. Las tres partes de la teoría del tiro.","Teoría del tiro"],
["M","La BALÍSTICA EXTERIOR estudia:",["El vuelo del proyectil desde que sale del cañón hasta el blanco","La combustión de la pólvora","El desgaste del ánima","El relleno del cartucho"],"Exterior: la trayectoria en el aire (gravedad, resistencia, deriva): lo que decide dónde cae el tiro.","Teoría del tiro"],
["F","La TRAYECTORIA es:",["La curva que describe el proyectil en su vuelo","La línea recta del cañón","El camino que recorre el tirador","La línea de carga del arma"],"El proyectil no vuela recto: la gravedad y la resistencia del aire curvan su camino = trayectoria.","Teoría del tiro · balística exterior"],
["M","La línea que une el ojo, los miras y el blanco se llama:",["Línea de puntería","Línea de fuego","Línea de carga","Línea de fuga"],"Línea de puntería: la visual que el tirador alinea; la trayectoria la cruza en el punto de encuentro.","Teoría del tiro"],
["M","La «puesta a cero» de un arma consiste en:",["Ajustar las alzas/miras para que la trayectoria pase por el punto de puntería a una distancia determinada","Vaciar el cargador","Poner el seguro","Limpie el ánima"],"El «cero»: alineas miras y cañón para que donde apuntes, caiga el tiro (a 100, 200 m…). Cada arma y cada tirador.","Cuadernillos · el cero"],
["M","La ZONA BATIDA es:",["La porción de terreno en la que el fuego del arma golpea al blanco en toda su altura","La zona donde nadie dispara","El fondo del foso","La zona de estacionamiento"],"Zona batida = terreno barrido por el fuego a la altura del blanco. Fuera de ella queda «espacio cubierto» sin batir y «terreno muerto».","Cuadernillos · balística exterior"],
["M","El TERRENO MUERTO es:",["La zona que el fuego no alcanza por estar oculta tras el relieve","Donde están enterrados los muertos","El fondo del valle oculto","La zona de descanso"],"Depresiones y revueltas que la trayectoria no tocan: el enemigo las usa para acercarse; el tirador debe cubrirlas con otro arma.","Teoría del tiro · terreno"],
["M","El SECTOR DE TIRO asignado (repaso) es:",["El espacio de terreno que un tirador debe vigilar y batir con su arma","El hueco del polvorín","La zona de las cocinas","El lugar del estacionamiento"],"Todo terreno cubierto por un fuego asignado: solapes entre tiradores y jefatura cierran los huecos.","Instrucción · control de fuego"],
["M","La CADENCIA TEÓRICA de un arma automática es:",["Los disparos por minuto que el mecanismo puede teóricamente disparar (sin recargas ni averías)","Los disparos que aciertan al blanco","El ritmo de marcha del tirador","Los disparos por mes"],"Cadencia teórica = la del mecanismo solo (G36: 750/min). La práctica, con recargas y puntería, es mucho menor.","Ficha oficial ET · G36E"],
["M","El cartucho 9 × 19 mm Parabellum es el de:",["La pistola USP y los subfusiles","El fusil G36","La ametralladora MG3","El mortero de 60"],"9 × 19: pistolas y subfusiles (USP, MP5). No lo confundas con el 5,56 (fusil) ni el 7,62 (MG3).","Materiales del ET"],
["M","La granada de mano FRAGMENTACIÓN sirve para:",["Proyectar metralla contra el personal en el radio de acción","Iluminar de noche","Hacer señal de socorro","Lanzar por arriba al enemigo"],"Fragmentación = contra personal (con radio de seguridad). Las hay también fumígenas (señalizar/pantalla) e iluminadoras.","Materiales · granadas"],
["M","Una granada FUMÍGENA sirve principalmente para:",["Crear pantalla que oculte el movimiento o señalizar","Destruir carros","Iluminar el objetivo","Cortar alambre"],"Humo: pantalla para moverse sin ser visto y marcaje (colores). Jamás juguetear con granadas: live para siempre.","Materiales · granadas"],
["M","El MORTERO es un arma:",["Colectiva de tiro curvo, que bate el terreno detrás de los obstáculos y en depresiones","Individual de tiro directo","Solo antiaérea","Exclusiva de la caballería"],"Tiro curvo: el mortero cae donde el fusil no llega (detrás de lomas, en vaguadas). El apoyo inmediato del jefe de sección.","Armas colectivas"],
["M","Los morteros del ET trabajan en calibres de:",["60, 81 y 120 mm","40 y 90 mm","5,56 y 7,62","155 y 203 mm"],"Familia de morteros 60 (escuadra/sección), 81 (compañía) y 120 (pesado): la escalada clásica del fuego curvo.","Materiales del ET"],
["D","Tu unidad recibe fuego desde el fondo de una vaguada que el fusil no alcanza. El arma adecuada es:",["El mortero (tiro curvo)","La pistola USP","La granada de mano lanzada a mano","La bayoneta"],"Donde el tiro directo no llega, el tiro curvo: el mortero de la sección cae en la vaguada sin exponerse.","Armas colectivas · caso"],
["D","Ante un carro que avanza a 400 m, el arma inmediata del pelotón de infantería es:",["El lanzagranadas contracarros (C-90/Alcotán)","La granada de fragmentación","La pistola","La pala de campaña"],"Carro cerca = contracarros ligero del propio pelotón (C-90 descartable o Alcotán-100): cada soldado sabe dónde está y quién lo usa.","Instalaza · caso"],
["F","La regla PRIMERA de seguridad con armas es:",["Tratar SIEMPRE toda arma como si estuviera cargada","Esperar a que alguien la mire","Soplar el cañón","Cargarla con los ojos cerrados"],"Primera regla universal, sin excepciones: cargada hasta demostrar lo contrario. Las siguientes: no apuntar a nada que no quieras destruir y dedo fuera del guardamonte.","Instrucción · seguridad"],
["M","Antes de abrir fuego, la regla fundamental es:",["Identificar BIEN el objetivo (no disparar a lo que no se ve claro o puede ser propio)","Disparar rápido para no perder el turno","Cerrar un ojo siempre","Cambiar de cargador"],"Identificación antes del disparo: un instante de duda puede costar una vida propia o la de un compañero.","Cuadernillos · reglas de fuego"],
["M","El TRIÁNGULO de puntería se forma con:",["Ojo, mira de alza y masa de mira (apuntado correcto)","Tres soldados en línea","Tres granadas","El mapa, la brújula y el GPS"],"Alza y masa de mira alineadas con el ojo (triángulo de puntería) sobre el punto de puntería: apuntado correcto clásico.","Teoría del tiro"],
["M","La POSICIÓN más estable y precisa para el tiro es:",["Tendido (echado en el suelo)","De pie con un solo pie","Corriendo","Sentado sobre un muro"],"Tendido: cuerpo apoyado en el suelo, arma firme, silueta baja: la posición del tirador para tiro preciso.","Instrucción · tiro"],
["M","La RESPIRACIÓN en el disparo:",["Se retiene brevemente tras una espiración natural, en el momento de accionar","Se mantiene inhalando fuerte","No influye nada","Se grita antes"],"Exhala, retén medio segundo y dispara: respirar a lo grande mueve el arma. Lo primero que enseña cualquier instructor.","Instrucción · tiro"],
["M","La ACCIÓN del disparo correcta es:",["Pulsar el disparador suavemente y en línea, sin «tirar» del dedo","Arrancarlo de un tirón","Golpearlo con la palma","Acompañarlo con un empujón del cuerpo"],"Pulsar (no tirar): presión gradual y recta hacia atrás, sin mover el arma. El «tirón» es el error que suspende tiradores.","Instrucción · tiro"],
["M","La DERIVA del proyectil es:",["El desplazamiento lateral de la trayectoria por el giro del proyectil (sentido del rayado)","La inclinación del arma","El viento que sopla del norte","La desviación del mapa"],"El rayado del ánima gira el proyectil; ese giro lo desvía lateralmente (deriva): corrección fina de tiradores y ametralladoras.","Teoría del tiro · balística exterior"],
["M","El VIENTO afecta al tiro:",["Empujando el proyectil: hay que corregir según su dirección y velocidad","No afecta nunca","Solo de noche","Solo con pistola"],"Viento de cruz = desvío lateral; de frente/cola = acorta o alarga. Cuanto más lejos, más cuenta: por eso el tiro a distancia es un arte.","Teoría del tiro · caso"],
["M","La BOCA DE FUEGO del arma debe mantenerse:",["Siempre hacia el suelo o al blanco, NUNCA hacia personas","Hacia arriba en todo momento, como las vacas","Hacia el propio cuerpo","Donde sea cómoda"],"Regla de oro del porte: la boca al blanco o al suelo en zona segura. Un arma «jugando» en una fila mata.","Instrucción · seguridad"],
["D","Un soldado encuentra un arma cargada en el parque. La secuencia correcta es:",["Boca al suelo/zona segura, extraer cargador, accionar para extraer el cartucho de la recámara y verificar visualmente","Meterla en la caja y salir corriendo","Dispararla al aire","Guardarla tal cual y callarlo"],"Desalistado seguro: cargador fuera, corredera atrás, recámara a la vista. Lo contrario es una negligencia con apellido.","Instrucción · caso"],
["D","Durante una guarda descubres que el arma del puesto está SIN CARGADOR. Lo correcto:",["Reportarlo de inmediato al jefe de guardia por escrito y solicitar arma operativa","Callarlo para no liarla","Esconderla","Cambiarla por la del compañero sin avisar"],"Un arma sin operatividad en guarda es un incidente serio: se reporta YA y por escrito (la cadena de mando decide).","Instrucción · caso"],
["D","El 11 de septiembre de 2026 se compraron 3.580 fusiles G36 más. Esto confirma que:",["El G36 sigue siendo el fusil reglamentario vigente del ET","El G36 se retiró en 2026","El nuevo fusil reglamentario es el AK","El ET ya no usa fusiles"],"Compra reciente (1.200 G36E + 2.380 G36KVE): el reglamentario sigue y seguirá unos años. Anti-obsoleto: los apuntes de «G36 va a salir» fallan.","Infodefensa 11-9-2026 · caso"],
["D","Un tirador dispara y el arma se encasquilla. La primera conducta correcta en combate:",["Mantener la boca al blanco, despejar el arma (recarga táctica) y avisar al jefe si persiste","Tirar el arma al enemigo","Correr hacia atrás gritando","Desmontarla por completo en el suelo"],"Mal funcionamiento: boca al blanco, recarga/despeje inmediato (y de rodillas si hay tiempo). Si vuelve a fallar: arma y aviso al jefe.","Instrucción · caso"],
["M","El PUNTO DE ENCUENTRO es:",["El punto en el que la trayectoria del proyectil corta la línea de puntería (donde cae el tiro apuntado)","El lugar donde se reúne la patrulla","El punto de encuentro del batallón","La esquina del acuartelamiento"],"La trayectoria cruza la línea de puntería en el punto de encuentro: ahí cae el tiro. Con la puesta a cero lo fijas a la distancia que quieras.","Teoría del tiro"],
["M","La familia de munición del equipo básico de un tirador tipo es:",["5,56 × 45 (fusil) y 9 × 19 (pistola)","7,62 y 12,7","40 × 46 y 90","12 de calibre y .22"],"El soldado tipo: G36 (5,56) + USP (9 × 19). Dos familias, una logística simple.","Materiales · munición"]
]
assert len(RAW) == 50, "RAW tiene %d" % len(RAW)
import io
PATRON = [(p + j) % 4 for j in range(13) for p in range(4)][:50]
filas = []
for i, ((dif, q, ops, x, r), dest) in enumerate(zip(RAW, PATRON), 1):
    correcta = ops[0]; resto = ops[1:]
    nuevas = resto[:dest] + [correcta] + resto[dest:]
    esc = lambda t: t.replace('"', '\\"')
    filas.append('{c:"cabo",b:"C1",t:"Armamento y tiro",d:"%s",id:"ar%02d",q:"%s",o:[%s],a:%d,x:"%s",r:"%s"}' % (dif, i, esc(q), ",".join('"%s"' % esc(o) for o in nuevas), dest, esc(x), esc(r)))
LOTE15 = (',\n/* ===== LOTE EXAMINADOR — Tema 15: Armamento y tiro\n'
'   Elaboración PROPIA (examinador GALÓN), 21-sep-2026, contra fuentes verificadas hoy: FICHA OFICIAL del ET\n'
'   (ejercito.defensa.gob.es/materiales/armamento_ligero/FUSIL-G36E.html: 5,56 mm, 750 dpm, 3,3 kg, cargador 30,\n'
'   toma de gases, fabricación Alemania/España, accesorio lanzagranadas) + INFODEFENSA 11-9-2026 (G36 sigue\n'
'   reglamentario: +3.580 fusiles, 1.200 G36E + 2.380 G36KVE) + páginas de materiales de unidades del ET (USP\n'
'   9×19 Parabellum; USP-SD con rosca para supresor en OE; AG36 40×46) + anexo de materiales (G36E desde 1999\n'
'   sustituye al CETME L; Santa Bárbara Sistemas La Coruña; USP comprada 2011; LAG-40 40 mm; K=Kurz) + teoría\n'
'   clásica del tiro (balística interior/exterior/de efectos, trayectoria, línea de puntería, puesta a cero,\n'
'   zona batida, terreno muerto, cadencia teórica, deriva, viento, triángulo de puntería, respiración y pulsado)\n'
'   + familia Instalaza (C-90 90 mm descartable, Alcotán-100 recargable) + morteros 60/81/120 + Minimi 5,56 y\n'
'   MG3 7,62 (cuadernillos). OMITIDOS: cadencia exacta MG3, modelos concretos de mortero y versiones internas\n'
'   (fuentes disputan o varían). Nota de tono: se depuraron dos erratas de borrador ("camarero", "cochecito").\n'  
'   ATENCIÓN ANTI-OBOLETO: el G36 sigue reglamentario en 2026 (compra de septiembre de 2026). */\n')
s = io.open('/home/user/galon/js/bank7.js', encoding='utf-8').read().rstrip()
assert s.endswith('];')
s = s[:-2] + LOTE15 + ",\n".join(filas) + "\n];\n"
io.open('/home/user/galon/js/bank7.js', 'w', encoding='utf-8').write(s)
from collections import Counter
difs = Counter(r[0] for r in RAW)
print("Lote Tema 15 montado: 50 · reparto correctas:", dict(sorted(Counter(PATRON).items())), "· dificultades:", dict(sorted(difs.items())))
