#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Lote Tema 10 · Topografía — 50 preguntas, formato: [dif, pregunta, opciones(correcta=0), explicación, ref]
# Fuentes verificadas 20-sep-2026: RD 1071/2007 (BOE-A-2007-15822: ETRS89 oficial, sustituye ED50, Canarias REGCAN95,
# consistente con GPS/GLONASS/GALILEO, altitudes desde el nivel medio del mar en Alicante) · IGN (MTN25 equidistancia
# 10 m / maestras 50 m; MTN50 20 m / maestras 100 m; curvas auxiliares a mitad; MTN25 = cada hoja MTN50 en 4;
# 1 cm = 250 m a 1:25.000 y 500 m a 1:50.000; cuadrícula kilométrica de 1 km) · UTM (60 husos de 6°, entre 80°N y 80°S,
# coordenadas en metros, falso este 500.000, España peninsular y Baleares en husos 29/30/31) · MGRS (estándar OTAN
# derivado de UTM: zona+cuadrado 100 km+dígitos; 4→1 km, 6→100 m, 8→10 m, 10→1 m).
RAW = [
["F","Un mapa topográfico es:",["La representación convencional, reducida y medida de una parte del terreno sobre un plano","Una fotografía aérea sin tratar","Un dibujo artístico del paisaje","Una lista de coordenadas sin dibujo"],"Definición clásica: representación convencional (signos), reducida (escala) y medida (con equivalencias exactas) del terreno sobre un plano.","IGN educativo · concepto de mapa"],
["F","En un mapa a escala 1:25.000, 1 centímetro del mapa equivale en el terreno a:",["250 metros","2.500 metros","25 metros","1.000 metros"],"1 cm = 25.000 cm = 250 m. Regla de escala numérica: se divide el denominador entre 100 para pasar a metros.","IGN · MTN25"],
["F","En un mapa a escala 1:50.000, 1 centímetro equivale a:",["500 metros","50 metros","5.000 metros","5 metros"],"1 cm = 50.000 cm = 500 m. La base del cálculo rápido de distancias sobre el mapa.","IGN · MTN50"],
["M","¿Cuál de estas escalas da MÁS detalle del terreno?",["1:25.000","1:50.000","1:100.000","1:200.000"],"Cuanto menor es el denominador, mayor el detalle: 1:25.000 representa el terreno más ampliado que 1:50.000.","IGN · escalas"],
["M","Mides 4,7 cm entre dos puntos en un mapa 1:25.000. La distancia real es:",["1.175 metros","117,5 metros","4.700 metros","11.750 metros"],"4,7 cm × 25.000 = 117.500 cm = 1.175 m. El cálculo de distancia reducida que cae siempre.","IGN · MTN25 · caso"],
["M","La escala GRÁFICA de un mapa es:",["La regla dividida dibujada en el margen que permite medir distancias directamente sobre el papel","El número 1:50.000 escrito junto al título","La tabla de signos convencionales","La lista de coordenadas de las esquinas"],"La escala gráfica es la regla dibujada en el margen: sirve para medir directamente (y resiste ampliaciones/reducciones del mapa).","IGN · elementos del mapa"],
["M","Las altitudes (cotas) de la cartografía oficial española se refieren a:",["El nivel medio del mar registrado en Alicante","El fondo del valle más profundo","La cima del Teide","Un punto cero en Madrid"],"El RD 1071/2007 fija como referencia altimétrica el nivel medio del mar en Alicante para la Península (materializado por la Red de Nivelación de Alta Precisión); en islas, referencias mareográficas locales.","RD 1071/2007 · BOE-A-2007-15822"],
["M","Los signos convencionales de un mapa sirven para:",["Representar con símbolos normalizados los elementos del terreno (vías, poblaciones, vegetación…), explicados en la leyenda","Adornar los márgenes","Marcar solo las carreteras","Cifrar la información militar"],"Todo lo dibujado es un convenio: cada símbolo se interpreta con la leyenda del margen. Sin leyenda no hay lectura del mapa.","IGN · elementos del mapa"],
["M","La serie MTN25 (1:25.000) del IGN se obtiene:",["Dividiendo cada hoja del MTN50 en cuatro cuartos","Ampliando fotográficamente el 1:200.000","Uniendo dos hojas del MTN50","Reduciendo el 1:10.000"],"Cada hoja del Mapa Topográfico Nacional 1:50.000 se divide en cuatro cuartos para formar las hojas 1:25.000.","IGN · MTN25"],
["F","Una curva de nivel es:",["La línea que une todos los puntos de igual altitud","La línea de máxima pendiente","El camino más corto entre dos cumbres","La frontera entre dos municipios"],"Concepto base de la altimetría: por una curva de nivel se puede caminar sin subir ni bajar un metro.","IGN educativo · representación del relieve"],
["F","La equidistancia entre curvas de nivel del MTN25 es de:",["10 metros","20 metros","50 metros","100 metros"],"En el Mapa Topográfico Nacional 1:25.000, la diferencia de altitud entre dos curvas consecutivas es de 10 m (maestras cada 50 m).","IGN · MTN25"],
["F","La equidistancia entre curvas de nivel del MTN50 es de:",["20 metros","10 metros","2 metros","250 metros"],"A escala 1:50.000 la equidistancia sube a 20 m (maestras cada 100 m): menos detalle, menos líneas.","IGN · MTN50"],
["M","Las curvas maestras de un mapa topográfico se distinguen porque:",["Se dibujan más gruesas y llevan rotulada su altitud","Son de color rojo","Están a trazos","Siempre forman círculos cerrados"],"Para facilitar la lectura, cada 5 curvas (50 m en MTN25, 100 m en MTN50) se dibuja una maestra más gruesa con la altitud escrita.","IGN · MTN"],
["M","Curvas de nivel muy JUNTAS indican:",["Terreno con fuerte pendiente (escarpado)","Terreno llano","Una meseta","Un valle abierto"],"Cuanto más juntas las curvas, más desnivel en menos distancia: pendiente fuerte. Muy separadas: terreno suave o llano.","IGN educativo · relieve"],
["M","Las curvas auxiliares (a trazos) aparecen en zonas muy llanas y se dibujan:",["A la mitad de la equidistancia normal","Cada kilómetro","Solo en las cimas","Con la misma equidistancia que las normales"],"En llanuras las curvas normales quedarían demasiado lejos: se añaden auxiliares a mitad de equidistancia (5 m en MTN25).","IGN · MTN"],
["F","Un punto acotado (punto cotado) es:",["Un punto del terreno con su altitud escrita junto a él","Un vado de un río","Una cota militar restringida","Un árbol singular"],"En cimas, cruces o lugares sin curvas cercanas se escribe directamente la altitud del punto: es la cota más precisa del mapa.","IGN · MTN"],
["D","Entre dos puntos hay 100 m de desnivel y 1.000 m de distancia horizontal. La pendiente es:",["El 10 %","El 1 %","El 100 %","El 90 %"],"Pendiente (%) = desnivel ÷ distancia horizontal × 100 = 100/1.000 = 10 %. Cálculo que el examinador adorna con datos.","Topografía · cálculo de pendientes · caso"],
["M","El perfil del terreno es:",["El dibujo del corte del relieve sobre una línea elegida, para ver alturas y depresiones de lado","El mapa de vegetación","La vista del terreno desde un satélite","El plano de una ciudad"],"Se construye con las altitudes de las curvas que corta la línea: es la herramienta para estudiar la visibilidad entre puntos.","Topografía · perfiles"],
["F","Un collado es:",["La depresión (sillón) entre dos elevaciones consecutivas","La cima más alta del cordal","El fondo de un desfiladero","Una llanura de cultivo"],"Entre cumbre y cumbre siempre hay un collado: punto bajo del cordal, paso natural entre dos valles.","Terminología topográfica clásica"],
["F","El cordal (divisoria de aguas) es:",["La línea que une las alturas y separa las aguas que van a vertientes distintas","La línea por donde corre el río","La curva de nivel de menor altitud","El borde del mapa"],"Al contrario que la vaguada: el cordal divide; la vaguada recoge. Los dos «esqueletos» del relieve.","Terminología topográfica clásica"],
["F","La vaguada (talweg) es:",["La línea por la que confluyen las aguas en el fondo del valle","La línea de cumbres de una sierra","Una curva de nivel cerrada","La cresta de una loma"],"Vaguada = línea de máxima depresión convergente del agua: por ella discurre el cauce (real o potencial).","Terminología topográfica clásica"],
["D","Las curvas de nivel, al cruzar una vaguada, forman una «V» cuya punta apunta:",["Aguas arriba (hacia la cumbre)","Aguas abajo (hacia el mar)","Siempre al norte","Al punto más bajo del mapa"],"Regla clásica de lectura: en las vaguadas la V apunta remontando el agua; en los espolones (lomas), la V o U apunta hacia abajo. El examinador la da la vuelta para confundir.","Regla clásica de lectura de curvas · caso"],
["M","Un espolón (loma) es:",["La lengua de terreno que baja de un cordal hacia el valle","El punto más hondo de un río","Una curva maestra","Un tipo de camino militar"],"Del cordal descienden espolones separados por vaguadas: el «peine» del relieve. En el espolón, las curvas cierran con la punta hacia cotas bajas.","Terminología topográfica clásica"],
["M","Una depresión (cuenca hundida) se distingue en el mapa porque:",["Sus curvas cerradas llevan pequeños apéndices (raspes) hacia el interior","Sus curvas son de color azul","No tiene curvas de nivel","Se dibuja a trazos gruesos"],"Las curvas cerradas con raspe interior marcan hundimiento; sin raspe sería una cima. Detalle fino de lectura.","IGN · MTN"],
["F","En las coordenadas geográficas, la latitud se mide desde:",["El Ecuador (0° a 90° N o S)","El meridiano de Greenwich","El Polo Norte","El centro del mapa"],"Latitud desde el Ecuador; longitud desde Greenwich (0° a 180° E u O). Pareja de orígenes que hay que tener fina.","Topografía · coordenadas geográficas"],
["F","Las siglas UTM significan:",["Universal Transversa de Mercator","Unión Topográfica Militar","Unidad Táctica de Medición","Universal Total de Medidas"],"Proyección Universal Transversa de Mercator (de Gauss-Krüger): la retícula con la que se imprime la cartografía militar y civil española.","IGN · proyección UTM"],
["F","La proyección UTM divide la Tierra en:",["60 husos de 6 grados de longitud","20 husos de 18 grados","90 husos de 4 grados","360 husos de 1 grado"],"60 husos de 6° numerados de oeste a este desde el antimeridiano de 180°, válidos entre los paralelos 80° N y 80° S.","IGN · proyección UTM"],
["M","La España peninsular y las Baleares se reparten entre los husos UTM:",["29, 30 y 31","27 y 28","1 y 2","30 y 60"],"Huso 29 (oeste: Galicia…), 30 (la mayor parte peninsular) y 31 (este: Cataluña, Comunidad Valenciana y Baleares).","IGN · UTM España"],
["M","Las coordenadas UTM de un punto se expresan en:",["Metros (X hacia el este, Y hacia el norte)","Grados, minutos y segundos","Millas náuticas","Radianes"],"La UTM da coordenadas planas en metros: la X (este) y la Y (norte) crecen desde orígenes convencionales de cada huso.","IGN · proyección UTM"],
["F","El «falso este» de 500.000 metros de la UTM sirve para:",["Que ninguna coordenada X sea negativa al oeste del meridiano central","Que los mapas sean más baratos","Medir la altitud","Corregir el magnetismo terrestre"],"Se traslada el origen 500 km al oeste del meridiano central: todo el huso queda con X positivas y de fácil lectura.","IGN · proyección UTM"],
["F","El sistema geodésico de referencia oficial en España es:",["ETRS89, según el RD 1071/2007","ED50 desde 1975","WGS-84 militar","REGENTE-1900"],"El Real Decreto 1071/2007, de 27 de julio (BOE del 29-8-2007) adopta el ETRS89 para toda la cartografía oficial de Península y Baleares.","RD 1071/2007 · BOE-A-2007-15822"],
["M","El sistema ETRS89 vino a sustituir al antiguo sistema:",["ED50 (y REGCAN95 en Canarias)","Mercator de 1569","UTM-WGS84","Lambert-1875"],"La cartografía española se compilaba en ED50 (Península y Baleares) y REGCAN95 (Canarias); el RD 1071/2007 impone el ETRS89 (obligatorio para las Administraciones desde el 1-1-2015).","RD 1071/2007 · BOE-A-2007-15822"],
["M","Según el propio RD 1071/2007, el ETRS89 es consistente con los sistemas de navegación por satélite:",["GPS, GLONASS y el europeo GALILEO","Solo con el GPS estadounidense","Ninguno: es un sistema aislado","Únicamente con sistemas de cable"],"Literal del real decreto: ETRS89 es consistente con GPS, GLONASS y GALILEO, lo que integra la cartografía española con la navegación por satélite.","RD 1071/2007 · BOE-A-2007-15822"],
["D","El MGRS (Military Grid Reference System) es:",["El estándar de coordenadas de cuadrícula de la OTAN, derivado de la UTM","Un sistema de cifrado de mapas","El nombre del GPS de la OTAN","Una escala cartográfica especial"],"Los militares de la OTAN localizan puntos con MGRS: zona (número+banda), cuadrado de 100 km (dos letras) y dígitos de este y norte: corto y difícil de confundir por radio.","MGRS · estándar OTAN"],
["D","En una referencia MGRS con 6 dígitos (ej. 437695 → 437+695), la precisión del cuadrado resultante es:",["100 metros","1 kilómetro","10 metros","1 metro"],"4 dígitos → 1 km; 6 dígitos → 100 m; 8 dígitos → 10 m; 10 dígitos → 1 m. Cada par de cifras añade un cero de precisión.","MGRS · estándar OTAN"],
["D","En la referencia MGRS «31UDP…», las dos LETRAS (UDP) identifican:",["El cuadrado de 100 km de lado dentro del huso","La banda de altitud","El país al que pertenece el mapa","La versión del mapa"],"Estructura: 31 (huso) + U (banda de latitud) + DP (cuadrado de 100.000 m) + dígitos. Las letras evitan ambigüedades entre husos.","MGRS · estándar OTAN · caso"],
["F","La aguja de la brújula apunta al:",["Norte magnético","Norte geográfico (verdadero)","Norte de cuadrícula","Sur del mapa"],"La aguja sigue el campo magnético terrestre: apunta al norte magnético, que NO coincide con el geográfico: la diferencia es la declinación.","Topografía · orientación"],
["F","La declinación magnética es el ángulo formado entre:",["El norte magnético y el norte geográfico (verdadero)","El este y el oeste","Dos curvas de nivel consecutivas","El rumbo y la distancia"],"Es la corrección clave al pasar de brújula a mapa (o al revés); su valor para la zona se imprime en el margen del mapa y cambia con los años.","Topografía · orientación"],
["M","En el margen de un mapa militar figuran los TRES nortes:",["Geográfico (verdadero), de cuadrícula y magnético","Norte, sur, este y oeste","Solo el norte de cuadrícula","El norte y el sur magnéticos"],"Norte geográfico (eje de rotación), norte de cuadrícula (líneas verticales UTM) y norte magnético (brújula). Sus ángulos (convergencia y declinación) permiten pasar de uno a otro.","Topografía · los tres nortes"],
["M","El acimut es:",["El ángulo medido desde el norte, en sentido horario, de 0 a 360 grados","La distancia entre dos puntos","El ángulo de la pendiente","La altura de un punto sobre el mar"],"Acimut 0° = norte, 90° = este, 180° = sur, 270° = oeste. Con brújula y acimut se marcha de noche o sin referencias visuales.","Topografía · orientación"],
["D","Tu acimut de marcha es 70°. El acimut inverso (de vuelta) es:",["250°","290°","110°","20°"],"Recíproco: si el acimut es menor de 180°, se suman 180° (70+180 = 250°); si es mayor, se restan. El error clásico de noche.","Topografía · caso"],
["F","Orientar el mapa consiste en:",["Colocarlo de forma que sus direcciones coincidan con las del terreno","Ponerlo mirando al sur","Dibujarle el norte","Doblarlo por las cuadrículas"],"Con brújula (norte del mapa = norte magnético, corregida la declinación) o con el terreno (identificando accidentes), el mapa «encaja» con lo que ves.","Topografía · orientación"],
["M","De noche, en el hemisferio norte, el norte se localiza mediante:",["La Estrella Polar","La Luna llena","El orto del sol","La Osa Menor completa rotando"],"La Estrella Polar marca el norte geográfico (se halla prolongando la cola de la Osa Mayor). Técnica clásica de orientación nocturna.","Topografía · orientación nocturna"],
["D","El GPS da tu posición al metro… pero la doctrina exige seguir dominando mapa y brújula porque:",["El GPS puede fallar: pilas, rotura, negación o interferencia del enemigo","El GPS no funciona de día","El mapa y la brújula son más rápidos siempre","El GPS está prohibido en maniobra"],"La navegación por satélite es un apoyo: batería, avería, terreno que oculta o guerra electrónica te devuelven al método clásico. Por eso la instrucción topográfica no se toca.","Topografía militar · caso"],
["M","Dos puntos tienen intervisibilidad cuando:",["Desde uno se ve el otro (línea de vista sin obstáculos)","Están a menos de 1 km","Están en la misma curva de nivel","Comparten huso UTM"],"Se comprueba con el perfil del terreno: una loma intermedia puede ocultar puntos de la misma altitud. Base del estudio de puestos de observación.","Topografía · intervisibilidad"],
["F","Un punto dominante es:",["Una elevación que domina el terreno circundante","El punto más bajo del valle","El centro del mapa","Un vado estrecho"],"Quien ocupa lo dominante observa y bate con fuego el terreno que lo rodea: por eso los puestos de observación buscan cotas dominantes.","Topografía táctica"],
["M","En doctrina militar, «estar OCULTO» y «estar A CUBIERTO» se diferencian en que:",["Oculto = que no te vean; a cubierto = protegido además del fuego (detrás de un obstáculo)","Son exactamente lo mismo","Oculto = protegido del fuego; a cubierto = invisible","Ambos solo valen de noche"],"Un muro te oculta y te cubre; la niebla te oculta pero NO te cubre; un parapeto te cubre aunque te vean desde el aire. Diferencia que se pregunta sola.","Topografía táctica"],
["D","Una sección avanza con enemigo al acecho. La progresión más prudente aprovecha:",["Las vaguadas y laderas inversas (cubiertas), evitando el cordal expuesto a la vista","Las cumbres y crestas, para ver más","Las líneas de cumbres por ser más cortas","Los caminos principales siempre"],"El cordal da observación pero te delata contra el cielo; las vaguadas y las laderas inversas ocultan el movimiento. La regla de oro de la progresión cubierta.","Topografía táctica · caso"],
["M","Contar los pasos en la marcha (podómetro o conteo) sirve para:",["Estimar la distancia recorrida cuando no hay instrumentos","Calibrar la brújula","Medir la pendiente","Corregir la declinación"],"Con el paso medio de cada militar (obtenido calibrándolo en 100 m) se estima la distancia marchada: técnica clásica de navegación terrestre junto al reloj (velocidad × tiempo).","Topografía militar"],
["M","Una ortofotografía (ortofoto) es:",["Una imagen aérea corregida, a escala constante, útil para actualizar lo que el mapa no recoge","Una foto oblicua de avión sin corregir","El dibujo de las curvas de nivel","Un mapa de carreteras"],"La orto se ha corregido para ser medible (como un mapa) y muestra la realidad del momento: el complemento visual para reconocer el terreno antes de la maniobra.","IGN · ortofotografía"]
]
assert len(RAW) == 50, "RAW tiene %d" % len(RAW)
import io
PATRON = [(p + j) % 4 for j in range(13) for p in range(4)][:50]
filas = []
for i, ((dif, q, ops, x, r), dest) in enumerate(zip(RAW, PATRON), 1):
    correcta = ops[0]; resto = ops[1:]
    nuevas = resto[:dest] + [correcta] + resto[dest:]
    esc = lambda t: t.replace('"', '\\"')
    filas.append('{c:"cabo",b:"C1",t:"Topografía",d:"%s",id:"to%02d",q:"%s",o:[%s],a:%d,x:"%s",r:"%s"}' % (dif, i, esc(q), ",".join('"%s"' % esc(o) for o in nuevas), dest, esc(x), esc(r)))
LOTE10 = (',\n/* ===== LOTE EXAMINADOR — Tema 10: Topografía\n'
'   Elaboración PROPIA (examinador GALÓN), 20-sep-2026, 100% contra fuentes verificadas hoy: RD 1071/2007, de 27 de\n'
'   julio (BOE-A-2007-15822: ETRS89 sistema geodésico oficial, sustituye a ED50, REGCAN95 en Canarias, consistente con\n'
'   GPS/GLONASS/GALILEO, altitudes desde el nivel medio del mar en Alicante, obligatorio desde 1-1-2015) · IGN (MTN25:\n'
'   equidistancia 10 m y maestras cada 50 m; MTN50: 20 m y 100 m; curvas auxiliares a mitad; MTN25 = cada hoja del\n'
'   MTN50 en 4; 1 cm = 250 m (1:25.000) y 500 m (1:50.000); cuadrícula kilométrica de 1 km; proyección UTM) · UTM\n'
'   (60 husos de 6° entre 80°N y 80°S, coordenadas en metros, falso este 500.000, España peninsular y Baleares en\n'
'   husos 29/30/31) · MGRS estándar OTAN (zona+banda+cuadrado de 100 km+dígitos: 4→1 km, 6→100 m, 8→10 m, 10→1 m).\n'
'   Conceptos clásicos de orientación y relieve (curvas de nivel, cordal/vaguada, regla de la V, tres nortes,\n'
'   declinación, acimut y recíproco, intervisibilidad, oculto/cubierto) como terminología topográfica universal.\n'
'   NOTA: se evita el huso de Canarias (27/28 según la fuente) y valores concretos de declinación magnética (varían\n'
'   con el tiempo): regla de no preguntar lo que las fuentes disputan. */\n')
s = io.open('/home/user/galon/js/bank7.js', encoding='utf-8').read().rstrip()
assert s.endswith('];')
s = s[:-2] + LOTE10 + ",\n".join(filas) + "\n];\n"
io.open('/home/user/galon/js/bank7.js', 'w', encoding='utf-8').write(s)
from collections import Counter
difs = Counter(r[0] for r in RAW)
print("Lote Tema 10 montado: 50 · reparto correctas:", dict(sorted(Counter(PATRON).items())), "· dificultades:", dict(sorted(difs.items())))
