#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Lote Tema 8 · Enseñanza militar (Ley 39/2007 título IV + RD 1051/2020 + RD 309/2021 + Ordenes DEF/196/2024 y DEF/15/2026) — 50 preguntas, formato: [dif, pregunta, opciones(correcta=0), explicación, ref]
RAW = [
["F","¿Qué real decreto aprueba el Reglamento de ordenación de la enseñanza de formación en las Fuerzas Armadas?",["El Real Decreto 1051/2020, de 1 de diciembre","El Real Decreto 35/2010, de 15 de enero","El Real Decreto 309/2021, de 4 de mayo","El Real Decreto 93/2022, de 1 de febrero"],"El RD 1051/2020 (BOE de 2-dic-2020) desarrolla el título IV de la Ley 39/2007 en materia de enseñanza de FORMACIÓN. El 35/2010 quedó derogado y el 309/2021 es el de ingreso y promoción.","RD 1051/2020"],
["M","Al aprobarse el RD 1051/2020 (enseñanza de formación) y el RD 309/2021 (ingreso y promoción):",["Quedó derogado el Real Decreto 35/2010, de 15 de enero, que aprobaba el Reglamento de ingreso y promoción y de ordenación de la enseñanza de formación","El RD 35/2010 sigue plenamente vigente","Se derogó la Ley 39/2007","Se derogó el título IV de la Ley 39/2007"],"El viejo RD 35/2010 fue sustituido por dos normas: el RD 1051/2020 (enseñanza de formación) y el RD 309/2021 (ingreso y promoción), que lo derogaron íntegramente.","RD 309/2021 · disp. derogatoria"],
["F","Según el art. 3 del RD 1051/2020, la instrucción y el adiestramiento son:",["El conjunto de actividades y ejercicios de carácter eminentemente práctico conducentes a completar la formación militar relacionada con cada cuerpo, escala y especialidad, pudiendo incluir un periodo de orientación y adaptación a la vida militar","Las clases teóricas de los planes de estudios","Las evaluaciones finales de cada curso","Los actos solemnes de los centros docentes"],"Definición LITERAL del reglamento (art. 3.j): lo eminentemente PRACTICO es la clave de la definición.","RD 1051/2020 art. 3.j"],
["M","Según el art. 3 del RD 1051/2020, la destreza o habilidad es:",["La aplicación del conocimiento para transformar una realidad específica","El conocimiento memorístico de la doctrina","La capacidad de mando sobre la unidad","La aptitud física del militar"],"Definición literal (art. 3.i): conocimiento aplicado a transformar una realidad.","RD 1051/2020 art. 3.i"],
["M","Según el art. 3 del RD 1051/2020, un módulo es:",["El conjunto de contenidos temáticos relativos a un ámbito de conocimiento determinado","Un periodo de prácticas en la unidad","Cada asignatura de la universidad","El horario semanal del alumno"],"Definición literal (art. 3.k).","RD 1051/2020 art. 3.k"],
["D","La duración máxima de los cursos académicos de la enseñanza de formación es:",["41 semanas, incluidos los períodos lectivos, los destinados a evaluación y los dedicados a instrucción y adiestramiento, ampliables a 43 en el primer curso si las adicionales son de instrucción y adiestramiento","30 semanas lectivas sin incluir evaluación","52 semanas completas","46 semanas inampliables"],"RD 1051/2020: 41 semanas como regla y 43 en el primer curso con la ampliación dedicada a I&A. No cuenta la preparación y realización de exámenes de 2ª y 4ª convocatoria.","RD 1051/2020 · duración de los cursos"],
["M","En la enseñanza de formación de OFICIALES, el número total de ECTS por curso académico no superará:",["76 créditos, ni 2,2 semanales","60 créditos, ni 1,5 semanales","90 créditos, ni 3 semanales","120 créditos, sin límite semanal"],"Límite literal del RD 1051/2020 para oficiales: 76 ECTS por curso y 2,2 semanales.","RD 1051/2020 · oficiales"],
["M","La duración de la enseñanza de SUBOFICIALES no sobrepasará:",["1.200 horas por curso académico ni 35 horas lectivas semanales","1.000 horas por curso ni 30 semanales","1.500 horas por curso ni 40 semanales","800 horas por curso ni 25 semanales"],"Límites literales para suboficiales: 1.200 horas por curso y 35 lectivas por semana.","RD 1051/2020 · suboficiales"],
["M","El currículo de la enseñanza de formación se distribuye como máximo en:",["Dos cursos académicos","Un único curso","Tres cursos","Cuatro cursos"],"El currículo único se reparte en un máximo de DOS cursos académicos.","RD 1051/2020 · currículo"],
["D","¿Quién elabora los currículos de la enseñanza de formación para el ET y para los Cuerpos Comunes, respectivamente?",["El Jefe del Mando de Adiestramiento y Doctrina (ET) y el Subdirector General de Enseñanza Militar (Cuerpos Comunes)","El JEME (ET) y el Subsecretario (comunes)","El Jefe del Mando de Personal del ET y el DIGEREM","El JEMAD en todos los casos"],"RD 1051/2020: Jefe del MADOC en el ET; Jefe de Personal de la Armada; Jefe del Mando de Personal del EA; y el Subdirector General de Enseñanza Militar para los Cuerpos Comunes.","RD 1051/2020 art. 16 · caso"],
["M","El sistema de enseñanza de formación está sujeto a un proceso continuado de evaluación que incluye:",["La evaluación de los centros docentes militares, la de la actividad docente del profesorado y la específica de los planes de estudios","Solo los exámenes finales de los alumnos","Únicamente las pruebas físicas","La evaluación de las academias cada diez años"],"Triple evaluación del art. 26: centros, profesorado y planes, para detectar áreas de mejora y garantizar calidad.","RD 1051/2020 art. 26"],
["M","Las finalidades de la enseñanza de PERFECCIONAMIENTO (art. 48 Ley 39/2007) son:",["Preparar al militar profesional para la obtención de especialidades y actualizar o ampliar sus conocimientos, incluyendo títulos del sistema educativo general y específicos militares","Únicamente la formación universitaria de grado","Solo las pruebas físicas periódicas","La instrucción básica del soldado"],"Art. 48: especialidades (complementar la inicial o reorientar la carrera) + actualización/ampliación; existe oferta de formación continuada.","Ley 39/2007 art. 48"],
["M","Los ALTOS ESTUDIOS de la defensa nacional (art. 49 Ley 39/2007) son los relacionados con:",["La paz, la seguridad y la defensa y la política militar, orientados a los profesionales de las FAS y a otros ámbitos de las AAPP y de la sociedad","Únicamente la logística militar","Los estudios universitarios ordinarios","La formación básica del soldado"],"Art. 49.1: paz + seguridad y defensa + política militar, con destinatarios que exceden de las FAS. Además existen cursos específicos militares que se determinen (49.2).","Ley 39/2007 art. 49"],
["F","La enseñanza de formación de los OFICIALES se imparte en:",["La Academia General Militar, la Escuela Naval Militar, la Academia General del Aire y las demás academias que determine el Gobierno a propuesta del Ministro de Defensa","Únicamente en la Universidad Complutense","Los centros de formación de tropa","El CESEDEN"],"Trío clásico del art. 50.1: AGM, ENM y AGA.","Ley 39/2007 art. 50.1"],
["F","La enseñanza de formación de los SUBOFICIALES se imparte en:",["La Academia General Básica de Suboficiales, la Escuela de Suboficiales de la Armada y la Academia Básica del Aire","Las academias de oficiales indistintamente","El CESEDEN y la ESFAS","Los centros universitarios de la defensa"],"Trío del art. 50.2; por orden del Ministro se determinan además los centros de formación de los militares de tropa y marinería.","Ley 39/2007 art. 50.2"],
["M","Los centros docentes militares de formación serán responsables de:",["El encuadramiento de los alumnos y de dirigir y gestionar su régimen de vida","Los ascensos de los oficiales generales","La estrategia militar","Las operaciones internacionales"],"Art. 50.4 literal: encuadramiento + régimen de vida.","Ley 39/2007 art. 50.4"],
["M","Los centros universitarios de la defensa se adscriben a:",["Una o varias universidades PÚBLICAS, conforme a la Ley Orgánica 6/2001, de 21 de diciembre, de Universidades","Universidades privadas por convenio","La UNED exclusivamente","Ninguna universidad: son autónomos"],"Art. 51.1-2: adscripción a universidades públicas; se rigen por la LO de Universidades, por la ley y por los convenios de adscripción.","Ley 39/2007 art. 51"],
["D","La titularidad de los centros universitarios de la defensa corresponde al Ministerio de Defensa:",["A través de la Subsecretaría de Defensa, y se ubican en los centros docentes militares de formación de oficiales","A través del JEMAD, en los cuarteles generales","Del CESEDEN, en sus instalaciones","De cada Ejército, en sus brigadas"],"Art. 51.1: titularidad ejercida vía Subsecretaría + ubicación en los CDMF de oficiales.","Ley 39/2007 art. 51.1 · caso"],
["M","En el sistema de centros universitarios de la defensa se pueden impartir además:",["Estudios conducentes a títulos oficiales de POSGRADO (máster y doctor) y líneas de investigación de interés para las FAS","Únicamente ciclos de formación profesional","Solo cursos de idiomas","Exclusivamente estudios de grado, nunca más"],"Art. 51.4: máster y doctor + investigación; y los CUD tienen presupuesto propio (51.5).","Ley 39/2007 art. 51.4"],
["M","El CESEDEN:",["Imparte los altos estudios de la defensa nacional y desarrolla tareas de investigación y de fomento y difusión de la cultura de defensa","Es el centro de instrucción de tropa del ET","Imparte exclusivamente clases de inglés","Depende del Ministerio de Universidades"],"Art. 52: altos estudios + investigación + cultura de defensa. Está vinculado funcionalmente a la SEGENPOL (visto en Tema 5).","Ley 39/2007 art. 52 · LODEF"],
["D","¿Qué centro imparte los cursos de actualización para el desempeño de los cometidos de oficial general y para la obtención del diploma de estado mayor?",["La Escuela Superior de las Fuerzas Armadas (ESFAS)","El CESEDEN","La Academia General Militar","La Escuela de Estudios de Defensa"],"Art. 52 literal: la ESFAS para oficial general y diploma de estado mayor; el CESEDEN imparte los altos estudios (49.1). Trampa clásica entre ambos.","Ley 39/2007 art. 52 · caso"],
["M","Los centros docentes militares de PERFECCIONAMIENTO se determinan:",["Por orden del Ministro de Defensa, y entre ellos pueden estar las academias militares y los demás centros de formación","Por real decreto del JEMAD","Por el Consejo Superior de cada Ejército","Por los propios directores de los centros"],"Art. 53: especialidades + ampliar o actualizar conocimientos; podrán impartir posgrados.","Ley 39/2007 art. 53"],
["M","El mando, dirección y gobierno de los centros docentes militares lo ejerce:",["Su director, que es la máxima autoridad del centro, será militar de carrera y tiene las competencias generales, militares y disciplinarias de los jefes de unidad, centro u organismo","Un funcionario civil designado por oposición","El alumno de mayor antigüedad","Un oficial general en comisión"],"Art. 54.2 literal: el director ostenta la representación del centro e informa o propone la designación de profesores.","Ley 39/2007 art. 54.2"],
["F","El ingreso en los centros docentes militares de formación se efectúa mediante convocatoria pública a través de:",["Los sistemas de concurso, oposición o concurso-oposición libres, garantizando igualdad, mérito y capacidad","Sorteo entre solicitantes","Entrevista personal sin pruebas","Designación directa del jefe de unidad"],"Art. 56.1 literal. Y los órganos de selección no pueden proponer más ingresos que plazas convocadas (56.2).","Ley 39/2007 art. 56.1"],
["M","Requisito de edad para optar al ingreso en los centros docentes militares de formación:",["Tener cumplidos dieciocho años, aunque pueden presentarse los que los cumplan en el año de la convocatoria, supeditándose su acceso a alcanzar esa edad","Tener 21 años cumplidos","Tener entre 18 y 26 años inampliables por ley","Sin límite de edad alguno"],"Art. 56.3: los límites de edad máximos se establecen reglamentariamente; el mínimo (18) está en la ley.","Ley 39/2007 art. 56.3"],
["M","Entre los requisitos generales para el ingreso figuran:",["Poseer la nacionalidad española, carecer de antecedentes penales, no estar procesado o imputado por delito doloso, no haber sido separado de ninguna Administración Pública ni estar inhabilitado firme","Solo tener el título exigido, sin más","Estar empadronado en la provincia de la academia","Acreditar dos años de trabajo previo"],"Art. 56.3, la lista completa: nacionalidad, derechos civiles, antecedentes, procesamiento por delito doloso, separación/inhabilitación.","Ley 39/2007 art. 56.3"],
["M","En los baremos de los sistemas de concurso y concurso-oposición para el ingreso se valorará:",["El tiempo servido en las Fuerzas Armadas","La altura y el peso del aspirante","El número de hermanos","La nota de la ESO exclusivamente"],"Art. 56.7 literal: tiempo servido en las FAS en el baremo.","Ley 39/2007 art. 56.7"],
["M","Para acceder a las escalas de OFICIALES de los cuerpos generales e infantería de marina se exige además de los requisitos generales:",["Los exigidos para la ENSEÑANZA UNIVERSITARIA (o ingreso en cupos con titulaciones de grado determinadas)","Solo el título de la ESO","La titulación de técnico superior","Ninguna titulación"],"Art. 57.1: enseñanza universitaria, en coherencia con el sistema de centros universitarios de la defensa.","Ley 39/2007 art. 57.1"],
["M","Para acceder a las escalas de oficiales de los cuerpos de intendencia, ingenieros y cuerpos comunes se exigen:",["Títulos del sistema educativo general","Únicamente pruebas físicas","El título de técnico superior","Ninguna titulación específica"],"Art. 57.2: títulos del sistema educativo general según los cometidos y facultades del cuerpo y escala.","Ley 39/2007 art. 57.2"],
["M","Superados los planes de estudios de la enseñanza de formación, el acceso a la escala (art. 59):",["Se produce sin que se pueda superar el número de plazas de acceso establecido en la provisión del año de ingreso","Permite exceder las plazas si hay buen rendimiento","Se produce automáticamente al año siguiente","Exige repetir la selectiva completa"],"Art. 59: techo de plazas del año de ingreso; y la clasificación de procedencias se integra en una única clasificación final (art. 70.2).","Ley 39/2007 art. 59"],
["F","Para ingresar en las escalas de SUBOFICIALES de los cuerpos generales e infantería de marina se exigen las condiciones requeridas para acceder a los centros donde se obtiene el título de:",["Técnico superior","Grado universitario","Doctor","Grado medio de ESO"],"Art. 58.1: técnico superior (formación profesional de grado superior). También cupos con titulaciones de FP determinadas.","Ley 39/2007 art. 58.1"],
["M","El acceso a la condición de militar de TROPA Y MARINERÍA (art. 61):",["Se cubre con parámetros objetivos de selección en un proceso continuo; las pruebas selectivas pueden realizarse de forma individualizada o colectiva","Se hace por sorteo anual","Requiere título universitario","Solo puede ser por oposición una vez al año"],"Art. 61 literal: proceso continuo para mantener el objetivo de efectivos.","Ley 39/2007 art. 61"],
["M","En los procesos de promoción para el CAMBIO DE ESCALA (art. 62):",["Se valoran los méritos, incluido el tiempo de servicios, y se reservan plazas para suboficiales y militares de tropa y marinería","No se valora absolutamente nada","Se exige aprobar la selectiva de nuevo desde cero sin ventajas","No existe tal posibilidad en la ley"],"Art. 62: promoción interna con méritos y reservas de plazas; también cupos para militares de complemento adscritos a las escalas.","Ley 39/2007 art. 62"],
["D","Los empleos que se pueden conceder con carácter EVENTUAL a los alumnos de la enseñanza de formación, a efectos académicos, de prácticas y retributivos, son:",["Alférez, sargento y soldado","Teniente, sargento primero y cabo","Capitán, brigada y cabo mayor","Coronel y sargento"],"Art. 68.2, el trío literal (con las denominaciones específicas de cada centro). ⚠️ Los viejos «alférez-alumno» y «sargento-alumno» de los apuntes son ahora empleos eventuales.","Ley 39/2007 art. 68.2 · caso"],
["D","Un alumno que ya tenía empleo militar antes de ingresar en un centro docente militar de formación:",["Conserva los derechos administrativos inherentes a su empleo, queda sometido al mismo régimen que el resto de alumnos y permanece o pasa a la situación de servicio activo","Pierde todos sus derechos anteriores","Pasa automáticamente a la reserva","Deja de estar sujeto a la disciplina"],"Art. 68.3: mismo régimen que los demás + activo; al acceder a la nueva escala causará baja en la de origen, conservando los derechos del tiempo de servicios.","Ley 39/2007 art. 68.3 · caso"],
["F","Las infracciones de carácter académico en la enseñanza de formación:",["NO están incluidas en el régimen disciplinario militar y se sancionan con arreglo al régimen interior de los centros docentes","Se sancionan siempre con arresto disciplinario","Son nulas y sin consecuencia","Se sancionan por el Código Penal Militar"],"⚠️ GOLD del art. 69.2: copiar en un examen no es falta disciplinaria militar, es infracción académica del régimen interior. Muy cañera y muy real.","Ley 39/2007 art. 69.2 · caso"],
["M","Las normas GENERALES de régimen interior de los centros docentes militares las aprueba:",["El Ministro de Defensa","El director de cada centro","El JEME","El Consejo Superior"],"Art. 69.3: Ministro para las generales; el régimen interior concreto de cada centro desarrolla esas normas.","Ley 39/2007 art. 69.3"],
["M","Las calificaciones de los alumnos de la enseñanza de formación sirven, entre otras cosas, para:",["Establecer el orden relativo para la incorporación o adscripción al escalafón correspondiente","Determinar el sueldo de los profesores","Asignar las comisiones de servicio","Fijar las plantillas de la unidad"],"Art. 70.2: el orden relativo al incorporarse a la escala; reglamentariamente se integra en una única clasificación final a las distintas procedencias.","Ley 39/2007 art. 70"],
["D","Un alumno causa baja a PETICIÓN PROPIA cuando lleva tres años de formación. Según el art. 71:",["El Ministro de Defensa determinará los supuestos de resarcimiento económico al Estado por el coste de la formación recibida, siempre que ésta sea superior a dos años","No hay consecuencia alguna","Paga una multa fija de 1.000 euros","Pierde la nacionalidad"],"Art. 71.1: el resarcimiento aplica cuando la formación supera DOS años.","Ley 39/2007 art. 71.1 · caso"],
["M","Entre los motivos de baja de un alumno (art. 71.2) figura:",["La imposición de sanción disciplinaria de baja en el centro docente militar de formación por FALTA GRAVE (o separación/resolución de compromiso por muy grave)","Cualquier falta leve","El suspender un solo examen parcial","El pedir permiso para una boda"],"Art. 71.2.d: la sanción disciplinaria de baja por falta GRAVE causa baja; la muy grave con separación o resolución de compromiso, también.","Ley 39/2007 art. 71.2.d"],
["M","Al causar baja en el centro docente militar de formación, el alumno:",["Pierde su condición militar (salvo que la tuviera antes de ser nombrado alumno) y el empleo eventual que hubiera alcanzado","Conserva todo sin cambios","Pasa a reservista obligatorio","Mantiene su plaza de alumno un año más"],"Art. 71.5 literal; y se resuelve el compromiso inicial de quien lo hubiese firmado.","Ley 39/2007 art. 71.5"],
["M","Los militares profesionales que asisten a cursos de perfeccionamiento o de altos estudios:",["Estarán en situación de servicio activo durante su asistencia","Pasan a la situación de excedencia","Pasan a la reserva automáticamente","Quedan fuera del escalafón"],"Art. 72 literal: servicio ACTIVO; la convocatoria del curso regula si conservan o causan baja en el destino de origen.","Ley 39/2007 art. 72"],
["D","Una alumna no puede asistir al curso de perfeccionamiento convocado por encontrarse de posparto. Según el art. 72:",["Se le facilitarán nuevas oportunidades de asistir a los citados cursos, conforme a lo que se establezca reglamentariamente","Pierde definitivamente la opción al curso","Debe repetir el curso anterior","Pasa a la situación de servicios especiales"],"Art. 72, párrafo segundo: nuevas oportunidades por embarazo, parto o posparto.","Ley 39/2007 art. 72 · caso"],
["M","La formación militar general y específica en los CDMF de OFICIALES se imparte por:",["Profesorado MILITAR, que también desarrollará tareas de tutoría y apoyo en colaboración con los centros universitarios de la defensa","Profesorado exclusivamente civil","Los alumnos de último curso","Personal contratado por lotería"],"Art. 73.1 literal: profesorado militar en la formación militar; en los CUD el grado lo imparte profesorado con la capacitación de la LO de Universidades (73.2).","Ley 39/2007 art. 73.1"],
["M","En los demás centros docentes militares, podrán ser profesores:",["Los militares profesionales de CUALQUIER escala que cumplan requisitos y titulación y, en su caso, el personal civil debidamente titulado y acreditado","Solo coroneles y generales","Solo el personal civil","Únicamente oficiales de la escala de oficiales"],"Art. 73.3: cualquier escala + civil titulado y acreditado. Y para ejercer se exige reconocimiento de competencia: titulación, preparación, experiencia profesional y aptitud pedagógica (73.4).","Ley 39/2007 art. 73.3-4 · caso"],
["F","Para ejercer como profesor en los centros docentes militares es preciso:",["El reconocimiento de su competencia, basada en la titulación, preparación, experiencia profesional y aptitud pedagógica","Solo el permiso del director","Diez años de destino obligatorios","Ser oficial general"],"Los CUATRO elementos del art. 73.4. Cuádruple fórmula que cae tal cual.","Ley 39/2007 art. 73.4"],
["M","El Reglamento de la calidad de la enseñanza militar y de su evaluación está aprobado por:",["El Real Decreto 93/2022, de 1 de febrero","El Real Decreto 1051/2020","La Ley Orgánica 8/2014","El Real Decreto 521/2020"],"RD 93/2022 desarrolla el art. 43.3 de la Ley 39/2007 (evaluación continuada de la enseñanza).","RD 93/2022 · Ley 39/2007 art. 43.3"],
["D","Las normas de la calidad de la enseñanza militar y de su evaluación se aprobaron por:",["La Orden DEF/196/2024, de 26 de febrero (BOE de 5-mar-2024), que desarrolla el RD 93/2022; la evaluación general se sitúa en el ámbito de la Subsecretaría de Defensa","La Orden DEF/464/2017, de 19 de mayo","El Real Decreto 35/2010","La Orden DEF/708/2020"],"Fresquísima (marzo de 2024): develop la calidad; la evaluación del sistema, en dimensión general, en la Subsecretaría, sin perjuicio de JEMAD y JEMEs.","Orden DEF/196/2024 · caso"],
["M","El régimen de PRUEBAS FÍSICAS unificadas de ingreso, formación y egreso de los Centros Docentes Militares de Formación y de evaluación periódica en las Fuerzas Armadas lo establece:",["La Orden DEF/15/2026, de 13 de enero","La Orden DEF/196/2024","El RD 309/2021","La Orden DEF/708/2020"],"Norma de enero de 2026: unifica las marcas físicas para el ingreso en los CDMF, la superación de los planes de estudios y la evaluación periódica del personal militar profesional. Lo más nuevo del nicho.","Orden DEF/15/2026"],
["M","La enseñanza de formación de los EXTRANJEROS tiene, además de la general, la finalidad de:",["Transmitir los conocimientos esenciales sobre la Constitución, historia y cultura de España","Enseñarles exclusivamente español coloquial","Eximirlos de la formación militar general","Enviarlos a estudios fuera del Ministerio"],"Art. 64.3 de la Ley 39/2007, literal. Detalle de ley que cae en los exámenes de cultura general del nicho.","Ley 39/2007 art. 64.3"]
]
assert len(RAW) == 50, "RAW tiene %d" % len(RAW)
import io
PATRON = [(p + j) % 4 for j in range(13) for p in range(4)][:50]
filas = []
for i, ((dif, q, ops, x, r), dest) in enumerate(zip(RAW, PATRON), 1):
    correcta = ops[0]; resto = ops[1:]
    nuevas = resto[:dest] + [correcta] + resto[dest:]
    esc = lambda t: t.replace('"', '\\"')
    filas.append('{c:"cabo",b:"C1",t:"Enseñanza militar",d:"%s",id:"ia%02d",q:"%s",o:[%s],a:%d,x:"%s",r:"%s"}' % (dif, i, esc(q), ",".join('"%s"' % esc(o) for o in nuevas), dest, esc(x), esc(r)))
LOTE8 = (',\n/* ===== LOTE EXAMINADOR — Tema 8: Enseñanza militar (Ley 39/2007, título IV arts. 48-73 + RD 1051/2020 + RD 93/2022 + Ordenes DEF/196/2024 y DEF/15/2026)\n'
'   Elaboración PROPIA (examinador GALÓN), 20-sep-2026, 100% contra BOE consolidado. NOTA DE HONESTIDAD: el\n'
'   proyectado inicialmente "RD 1108/2020 (instrucción, adiestramiento y evaluación operativa)" NO se pudo\n'
'   certificar en el BOE (404 en ELI y 4 búsquedas sin resultado) → se descarta y el lote pivota al bloque de\n'
'   ENSEÑANZA, sí certificado. Literales verificados: RD 1051/2020 art. 3 (definiciones: instrucción y\n'
'   adiestramiento, destreza, módulo), duraciones (41/43 semanas, 76 ECTS oficiales, 1.200 h y 35 lectivas\n'
'   suboficiales, currículo único máx. 2 cursos), art. 16 (currículos: MADOC en ET, Subdir. Gral. Enseñanza\n'
'   Militar en cuerpos comunes), art. 26 (evaluación continua); L39/2007 arts. 48-49 (perfeccionamiento y altos\n'
'   estudios), 50 (AGM/ENM/AGA y AGBS/ESA/ABA), 51-53 (CUD adscritos a universidades públicas vía Subsecretaría,\n'
'   CESEDEN vs ESFAS, perfeccionamiento), 54 (director), 56-58 (requisitos de ingreso: 18 años, baremo tiempo\n'
'   servido, universitario oficiales, técnico superior suboficiales), 61-62, 68.2 (empleos eventuales de alumno:\n'
'   alférez, sargento y soldado), 69.2 (infracciones académicas FUERA del régimen disciplinario), 70-72, 73\n'
'   (profesorado: militar en formación militar, cualquier escala + civil titulado, 4 requisitos de competencia);\n'
'   RD 309/2021 (derogó el RD 35/2010), RD 93/2022 (calidad), Orden DEF/196/2024 (normas de calidad, eval. en la\n'
'   Subsecretaría) y Orden DEF/15/2026 (pruebas físicas unificadas de ingreso, formación y egreso de CDMF). */\n')
s = io.open('/home/user/galon/js/bank7.js', encoding='utf-8').read().rstrip()
assert s.endswith('];')
s = s[:-2] + LOTE8 + ",\n".join(filas) + "\n];\n"
io.open('/home/user/galon/js/bank7.js', 'w', encoding='utf-8').write(s)
from collections import Counter
print("Lote Tema 8 montado: 50 · reparto correctas:", dict(sorted(Counter(PATRON).items())))
