#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Lote Tema 4 · Derechos y deberes (LO 9/2011) — 50 preguntas, formato: [dif, pregunta, opciones(correcta=0), explicación, ref]
RAW = [
["F","¿Qué norma regula los derechos y deberes de los miembros de las Fuerzas Armadas?",["La Ley Orgánica 9/2011, de 27 de julio","La Ley Orgánica 5/2005, de 17 de noviembre","La Ley 39/2007, de 19 de noviembre","El Real Decreto 96/2009, de 6 de febrero"],"La LO 9/2011, de 27 de julio, de derechos y deberes de los miembros de las Fuerzas Armadas (BOE de 28-jul-2011).","LO 9/2011 (27-jul-2011) · título"],
["M","El derecho de asociación profesional de los militares se fundamenta en los artículos 8, 22 y 28 de la Constitución, con la interpretación de la sentencia del Tribunal Constitucional:",["219/2001, de 31 de octubre","14/1983, de 8 de marzo","31/2010, de 28 de junio","119/1995, de 17 de julio"],"La LO 9/2011 apoya el derecho de asociación profesional en los arts. 8, 22 y 28 CE, con la interpretación de la STC 219/2001, de 31 de octubre.","LO 9/2011 · preámbulo · STC 219/2001"],
["F","Según la LO 9/2011, el primer y más fundamental deber del militar tiene su diaria expresión en:",["El más exacto cumplimiento de los preceptos contenidos en la Constitución, en la Ley Orgánica de la Defensa Nacional y en esta ley","El cumplimiento de las Reales Ordenanzas exclusivamente","La ejecución de las órdenes recibidas","El perfeccionamiento de la aptitud combativa"],"Trampa fina: es parecido al art. 3 de las RROO (Tema 1), pero la LO 9/2011 lo remite a la Constitución, a la LODEF y a esta ley — no a las Reales Ordenanzas.","LO 9/2011 · deberes · primer deber"],
["F","El Título I de la LO 9/2011 está dedicado a:",["El ejercicio de los derechos fundamentales y libertades públicas","El régimen de retribuciones","La organización del Ministerio de Defensa","Las operaciones internacionales"],"Título I: «Del ejercicio de los derechos fundamentales y libertades públicas», artículos 8 a 17: la carta de derechos del militar.","LO 9/2011 · estructura"],
["M","Según la LO 9/2011, el derecho a la intimidad y dignidad personal se reconoce en el artículo:",["10","9","11","15"],"Mapa de derechos: art. 8 libertad personal · art. 9 libertad religiosa · art. 10 intimidad y dignidad personal · art. 11 desplazamiento y circulación · art. 12 expresión · art. 13 reunión · art. 14 asociación · art. 15 sufragio.","LO 9/2011 arts. 8-15"],
["M","La libertad religiosa de los militares se reconoce en el artículo:",["9","8","10","14"],"Art. 9 de la LO 9/2011: libertad religiosa, dentro del Título I de derechos fundamentales y libertades públicas.","LO 9/2011 art. 9"],
["M","La libertad de desplazamiento y circulación de los militares se reconoce en el artículo:",["11","8","12","15"],"Art. 11: libertad de desplazamiento y circulación.","LO 9/2011 art. 11"],
["F","La libertad de expresión y de información del militar se reconoce en el artículo:",["12","10","13","22"],"Art. 12: libertad de expresión y de información, con los límites propios de la condición militar.","LO 9/2011 art. 12"],
["M","Según el art. 12 de la LO 9/2011, la libertad de expresión del militar solo tiene como límites:",["Los derivados de la salvaguarda de la seguridad y defensa nacional, el deber de reserva y el respeto a la dignidad de las personas y de las instituciones y poderes públicos","La prohibición absoluta de opinar sobre cualquier asunto público","La autorización previa del jefe de unidad para cualquier opinión","Los que fije cada unidad por costumbre"],"Literal del art. 12: comunicación y recepción libre de información «sin otros límites» que seguridad y defensa nacional, deber de reserva y dignidad de personas, instituciones y poderes públicos.","LO 9/2011 art. 12"],
["D","Un cabo escribe en un blog personal críticas duras pero respetuosas a la gestión de su mando, sin revelar datos del servicio. Según el art. 12 de la LO 9/2011:",["Puede hacerlo: la libertad de expresión solo cede ante la seguridad y defensa nacional, el deber de reserva y la dignidad de personas e instituciones","Comete siempre una falta disciplinaria","Necesita autorización previa de su jefe","Solo puede escribir con seudónimo"],"La expresión del militar no está prohibida: sus límites son los literales del art. 12. La crítica respetuosa sin datos reservados entra dentro.","LO 9/2011 art. 12 · caso"],
["F","En materia de dignidad, la LO 9/2011 exige especial protección frente al acoso:",["Sexual, por razón de sexo y profesional","Solo sexual","Únicamente laboral clásico","Solo por razón de nacionalidad"],"Literal: se respetará la dignidad personal y en el trabajo de TODO militar, especialmente frente al acoso, tanto sexual y por razón de sexo como profesional.","LO 9/2011 · dignidad y acoso"],
["M","Las revistas e inspecciones deberán respetar en todo caso:",["Los derechos a la dignidad e intimidad personal","La uniformidad completa","El horario de la unidad","La cadena de mando"],"Literal: las revistas e inspecciones deberán respetar en todo caso los derechos a la dignidad personal e intimidad.","LO 9/2011 · dignidad · revistas e inspecciones"],
["F","Las reuniones que se celebren EN LAS UNIDADES:",["Deberán estar previa y expresamente autorizadas por su jefe, que las podrá denegar motivadamente ponderando la disciplina y las necesidades del servicio","Están siempre prohibidas","Solo requieren aviso 24 horas antes","Dependen de la autorización del Ministerio"],"Literal del art. 13: dentro de la unidad, autorización previa y expresa del jefe, denegable motivadamente ponderando disciplina y necesidades del servicio.","LO 9/2011 art. 13"],
["F","El derecho de asociación de los militares (crear asociaciones para fines lícitos) se ejerce conforme a:",["La Ley Orgánica 1/2002, de 22 de marzo, reguladora del Derecho de Asociación","La Ley Orgánica 1/2004","La Ley 39/2007","La Ley 40/2015"],"Art. 14: los militares tienen derecho a crear asociaciones y asociarse libremente para fines lícitos conforme a la LO 1/2002.","LO 9/2011 art. 14"],
["M","Cuando el asociacionismo militar tiene como fin la defensa de intereses profesionales, se ajusta a:",["Lo dispuesto en el título III, capítulo I, de la propia LO 9/2011","La ley general de sindicatos","El Código Penal Militar","La LO de libertad sindical"],"Art. 14.2: la defensa de intereses profesionales se rige por el título III, capítulo I, de la LO 9/2011: las asociaciones profesionales militares.","LO 9/2011 art. 14.2 y título III"],
["F","Las asociaciones profesionales de miembros de las FAS tienen como finalidad:",["La promoción y defensa de los intereses profesionales, económicos y sociales de sus asociados","La representación política de sus afiliados","La gestión de los permisos y licencias","La negociación colectiva de los convenios"],"Definición literal: promoción y defensa de los intereses profesionales, económicos y sociales — ni política ni sindical.","LO 9/2011 · asociaciones profesionales"],
["M","Además de su finalidad principal, las asociaciones profesionales podrán realizar actividades sociales, pero NUNCA:",["Interferir en las decisiones de política de seguridad y defensa, en el planeamiento y desarrollo de las operaciones militares y en el empleo de la fuerza","Organizar actos culturales","Difundir la cultura de seguridad y defensa","Favorecer la deontología militar"],"Pueden favorecer la profesión, la deontología militar y la cultura de seguridad y defensa; la línea roja es interferir en política de defensa, operaciones y empleo de la fuerza.","LO 9/2011 · asociaciones profesionales"],
["M","Las asociaciones profesionales de militares deberán respetar el principio de:",["Neutralidad política y sindical","Especialidad tributaria","Buena administración","Planificación presupuestaria"],"Deben respetar la neutralidad política y sindical, sin referencias políticas o ideológicas en su denominación ni en sus estatutos.","LO 9/2011 · asociaciones profesionales"],
["M","En cuanto a su relación con partidos y sindicatos, las asociaciones profesionales de militares:",["No pueden tener vinculación con ellos, ni realizar pronunciamientos públicos conjuntos, ni participar en sus reuniones o manifestaciones","Pueden federarse con sindicatos mayoritarios","Pueden presentarse a elecciones con apoyo sindical","Pueden delegar su representación en un sindicato"],"Triple prohibición literal: vinculación con organizaciones políticas o sindicales, pronunciamientos conjuntos y participación en sus reuniones o manifestaciones.","LO 9/2011 · asociaciones profesionales"],
["M","En cuanto a su ámbito y domicilio, las asociaciones profesionales de militares:",["Deben tener ámbito nacional, constituirse por tiempo indefinido y no pueden establecer su domicilio social en las unidades ni en las dependencias del Ministerio de Defensa","Pueden ser de ámbito provincial con sede en el cuartel","Se constituyen por 4 años renovables","Deben tener sede en el Ministerio de Defensa"],"Literal: ámbito nacional, tiempo indefinido y domicilio prohibido en unidades y dependencias del Ministerio.","LO 9/2011 · asociaciones profesionales"],
["F","El carácter de las asociaciones profesionales de militares es:",["No lucrativo en ningún caso","Lucrativo si lo permiten sus estatutos","Mixto","Lucrativo solo para sus directivas"],"Literal: en ningún caso estas asociaciones profesionales tendrán carácter lucrativo.","LO 9/2011 · asociaciones profesionales"],
["M","¿A qué asociaciones pueden afiliarse los miembros de las Fuerzas Armadas?",["Solo a las asociaciones profesionales reguladas en la propia ley, que únicamente pueden agruparse entre ellas mismas, y a organizaciones internacionales de su mismo carácter","A cualquier sindicato legalmente constituido","A asociaciones y a partidos con autorización ministerial","A cualquier asociación civil sin restricciones"],"Los militares NO se afilian a sindicatos: solo a las asociaciones profesionales de la ley, agrupables entre sí y con organizaciones internacionales del mismo carácter.","LO 9/2011 · afiliación"],
["D","Un alumno de la enseñanza militar de formación que NO tenga la condición de militar profesional:",["No podrá pertenecer a asociaciones profesionales","Puede afiliarse libremente","Puede afiliarse con autorización de su academia","Puede afiliarse si es mayor de edad"],"Literal: los alumnos de la enseñanza militar de formación sin condición de militar profesional quedan fuera de las asociaciones profesionales.","LO 9/2011 · alumnos y asociaciones"],
["M","Los miembros de las asociaciones profesionales, tras su pase a retiro:",["Podrán permanecer afiliados con las limitaciones establecidas en la ley, siempre que lo permitan sus estatutos","Deben darse de baja obligatoriamente","Permanecen con todos los derechos sin condición","Pasan automáticamente a asociaciones de reservistas"],"Literal: el vínculo puede sobrevivir al retiro, si los estatutos lo permiten y con las limitaciones de la ley.","LO 9/2011 · afiliación · retiro"],
["M","¿Dónde deben inscribirse las asociaciones profesionales de militares?",["En el Registro de Asociaciones Profesionales de miembros de las Fuerzas Armadas, habilitado en el Ministerio de Defensa","En el registro civil de su provincia","En el registro de partidos del Ministerio del Interior","En el BOE directamente"],"Registro específico en el Ministerio de Defensa: a solicitud de los promotores, depositando acta fundacional, estatutos y relación de promotores.","LO 9/2011 · registro de asociaciones"],
["M","Las asociaciones profesionales responden:",["Por los actos de sus órganos estatutarios y por los de sus afiliados cuando ejerzan funciones representativas o actúen por cuenta de la asociación","Únicamente por los actos de sus presidentes","De ninguna manera: solo responden los afiliados","Solo ante el Ministerio de Defensa"],"Responsabilidad de la asociación: propia (órganos estatutarios) y por sus afiliados en ejercicio regular de funciones representativas o actuando por su cuenta.","LO 9/2011 · responsabilidad de las asociaciones"],
["M","Entre los derechos de las asociaciones profesionales inscritas figuran:",["Realizar propuestas, emitir informes y dirigir solicitudes; asesorar, apoyar y representar a sus asociados; y recibir información del Ministerio sobre régimen de personal y protección social","Convocar huelga y negociar convenios","Intervenir en el planeamiento de las operaciones","Ejercer acciones disciplinarias sobre sus afiliados"],"Art. 40: propuestas/informes/solicitudes, asesoramiento y representación legítima, y derecho a información del Ministerio — nada de huelga ni negociación colectiva.","LO 9/2011 art. 40"],
["D","¿Qué está EXPRESAMENTE excluido del ámbito de actuación de las asociaciones profesionales?",["El llamamiento al ejercicio del derecho de huelga, las acciones sustitutivas, la negociación colectiva y las medidas de conflicto colectivo","Emitir informes sobre personal","Recibir información del Ministerio de Defensa","Realizar propuestas relacionadas con sus fines"],"Exclusiones literales: llamamiento a huelga, acciones sustitutivas, negociación colectiva, medidas de conflicto colectivo, y acciones que excedan los derechos de los arts. 12 y 13.","LO 9/2011 · exclusiones"],
["M","Las asociaciones profesionales de militares tampoco podrán:",["Realizar actividades paramilitares ni ejercicios de formación e instrucción de ese carácter","Realizar actividades deportivas","Publicar revistas propias","Cobrar cuotas a sus afiliados"],"Literal: prohibidas las actividades paramilitares y los ejercicios de formación e instrucción de ese carácter.","LO 9/2011 · asociaciones profesionales"],
["M","El ejercicio del derecho de asociación profesional debe garantizar:",["El cumplimiento de las misiones, el desarrollo de las operaciones, el código de conducta y los preceptos de la ley","La independencia de la cadena de mando respecto del Ministro","La representación en el Congreso de los Diputados","La participación en el mando operativo"],"Fórmula literal: el derecho se ejerce garantizando las misiones, las operaciones, el código de conducta y la ley.","LO 9/2011 · ejercicio del derecho"],
["M","Los representantes de las asociaciones en el Consejo de Personal tienen, entre otros, el derecho a:",["No ser discriminados en su promoción profesional en razón del desempeño de su representación","Reducir su jornada de guardias a la mitad","Cobrar un plus por representación","Elegir destino libremente"],"Art. 51: garantía clásica del representante: la promoción profesional no puede resentirse por ejercer la representación.","LO 9/2011 art. 51"],
["M","La suspensión o disolución de las asociaciones profesionales de militares queda sometida a:",["El régimen legal establecido para el derecho de asociación","El arbitrio del JEMAD","El procedimiento disciplinario militar","La potestad del jefe de la unidad donde radiquen"],"Art. 39: suspensión y disolución según el régimen general legal del derecho de asociación.","LO 9/2011 art. 39"],
["F","En materia de secretos, el militar está sujeto a:",["La legislación general sobre secretos oficiales y materias clasificadas","Una normativa exclusiva de Defensa sin conexión general","Las normas internas de cada unidad","La ley de protección de datos exclusivamente"],"Literal: sujeción a la legislación general sobre secretos oficiales y materias clasificadas.","LO 9/2011 · deberes · secretos oficiales"],
["D","Un cabo conoce, por su cargo, datos NO CLASIFICADOS pero delicados del servicio. Según la LO 9/2011:",["Debe guardar la debida discreción: no difundirlos por ningún medio ni usarlos para beneficio propio o de terceros o en perjuicio del interés público","Puede comentarlos libremente por no estar clasificados","Solo puede publicarlos si los anonimiza","Debe consultarlos con su asociación profesional"],"Trampa de examen: la discreción NO es solo para lo clasificado — los hechos o datos no clasificados relativos al servicio también exigen discreción.","LO 9/2011 · deberes · discreción · caso"],
["M","Al incorporarse a su destino, los militares serán informados por sus mandos de:",["Los fines, organización y funcionamiento de la unidad, y de las funciones, deberes y responsabilidades que les incumben","Únicamente de su nómina y horario","De los sueldos de sus superiores","De la política de alianzas del Ministerio"],"Deber del mando (y derecho del subordinado): la información de incorporación — fines, organización, funcionamiento, funciones, deberes y responsabilidades.","LO 9/2011 · deberes · incorporación al destino"],
["F","Para el cumplimiento de sus deberes, el militar tiene derecho a:",["El desempeño efectivo de los cometidos o funciones propios de su condición y a participar en la consecución de los objetivos de la unidad","Elegir su destino libremente","Modificar su horario a conveniencia","Oponerse a las órdenes que estime mejorables"],"Correlación deber-derecho: exigir el desempeño efectivo de los cometidos propios y participar en los objetivos de la unidad.","LO 9/2011 · derechos correlativos a deberes"],
["M","Al militar que se le reconozca una incapacidad con limitación para ocupar determinados destinos, se le garantiza:",["El principio de igualdad de trato en los destinos a los que pueda acceder","El pase automático a retiro","La exención definitiva de toda guardia","El ascenso por antigüedad"],"Literal: garantía de igualdad de trato en los destinos accesibles.","LO 9/2011 · incapacidad y destinos"],
["M","El artículo 22 de la LO 9/2011 —el que citaba el examen oficial I/24— se titula:",["Disponibilidad, horarios, permisos y licencias","Libertad de expresión","Derecho de asociación","Prescripción de sanciones"],"El art. 22 regula la disponibilidad, horarios, permisos y licencias. (La libertad de expresión es el art. 12: no confundir.)","LO 9/2011 art. 22 · examen I/24"],
["M","¿En qué situación deben encontrarse los militares para poder afiliarse a una asociación profesional?",["En cualquiera de las situaciones administrativas sujetas al régimen general de derechos y deberes, sin tener su condición militar en suspenso","Solo en servicio activo ordinario","Solo con menos de 10 años de servicio","En cualquier situación, incluso en suspenso"],"Literal: para afiliarse hay que estar sujeto al régimen general de derechos y deberes según la Ley de la carrera militar, SIN condición militar en suspenso.","LO 9/2011 · afiliación · condición en suspenso"],
["M","Según el artículo 30.2 de la Constitución, los militares deben prestar:",["Juramento o promesa de fidelidad al Rey y de obediencia y respeto a la Constitución","Juramento únicamente ante su unidad","Promesa de fidelidad al Ministro de Defensa","Juramento de obediencia absoluta e incondicional"],"Constitución art. 30.2: fidelidad AL REY y obediencia y respeto a la CONSTITUCIÓN.","Constitución art. 30.2"],
["M","Un cabo publica en redes sociales imágenes de una operación clasificada «para presumir». Según la LO 9/2011:",["Viola el deber de reserva y los límites de la libertad de expresión (seguridad y defensa nacional)","Puede hacerlo si no le identifican","Solo comete una incorrección de etiqueta","Es legal si las borra a los pocos días"],"La libertad de expresión (art. 12) cede ante la seguridad y defensa nacional y el deber de reserva; la materia clasificada, además, tiene su legislación general.","LO 9/2011 arts. 12 y deberes · caso"],
["D","Una asociación profesional de militares convoca una manifestación conjunta con un sindicato mayoritario. Según la LO 9/2011:",["No puede: está prohibida la vinculación con organizaciones sindicales y participar en sus reuniones o manifestaciones","Puede, si avisa con 15 días","Puede, si la manifestación es pacífica","Puede con autorización del Consejo de Personal"],"Prohibición expresa: ni pronunciamientos conjuntos con organizaciones sindicales ni participación en sus reuniones o manifestaciones.","LO 9/2011 · asociaciones profesionales · caso"],
["D","Un aspirante en una academia, aún sin condición de militar profesional, quiere afiliarse a una asociación profesional:",["No puede: los alumnos de la enseñanza de formación sin condición de militar profesional quedan excluidos","Puede afiliarse como cualquier soldado","Puede si paga su cuota personalmente","Puede con permiso de su jefe de academia"],"Exclusión literal de los alumnos sin condición de militar profesional.","LO 9/2011 · alumnos y asociaciones · caso"],
["M","Una asociación profesional quiere fijar su sede en un acuartelamiento cedido por la unidad. Según la ley:",["No puede establecer su domicilio social en las unidades ni en las dependencias del Ministerio de Defensa","Puede, si el jefe de la unidad lo autoriza","Puede mientras no interfiera en el servicio","Puede con compromiso de no hacer actos allí"],"Literal: domicilio social prohibido en unidades y dependencias del Ministerio — la asociación vive fuera del cuartel.","LO 9/2011 · asociaciones profesionales · caso"],
["D","Un militar de tropa pasa a retiro y quiere seguir vinculado a su asociación profesional. Según la LO 9/2011:",["Puede permanecer afiliado con las limitaciones de la ley, siempre que lo permitan los estatutos de la asociación","No puede bajo ningún concepto","Puede y además conserva el derecho a representar a afiliados en activo","Debe fundar una asociación nueva de retirados"],"El vínculo post-retiro existe: estatutos que lo permitan + limitaciones legales.","LO 9/2011 · afiliación · caso"],
["M","La inscripción de una asociación profesional en el Registro del Ministerio de Defensa se practica depositando:",["El acta fundacional, los estatutos y una relación de promotores y de sus representantes","Solo el acta fundacional","La lista de todos los afiliados con sus DNI","El presupuesto trienal"],"Kit documental literal: acta fundacional + estatutos + relación de promotores y de quiénes representan a la asociación.","LO 9/2011 · registro de asociaciones"],
["D","¿Cuál de estas conductas de una asociación profesional sería LEGAL?",["Emitir un informe sobre el régimen de retribuciones del personal y remitirlo al Ministerio de Defensa","Convocar una huelga de guardias","Federarse con un sindicato nacional","Montar un campo de instrucción paramilitar"],"Emitir informes y realizar propuestas es derecho núcleo del art. 40. Huelga (excluida), federación sindical (prohibida) y actividades paramilitares (prohibidas), no.","LO 9/2011 art. 40 y exclusiones · caso"],
["M","¿Qué derecho correlativo tiene el militar respecto a su deber de disponibilidad, según la estructura de la LO 9/2011?",["Que le sean informados los fines, organización y funcionamiento de la unidad al incorporarse, y el desempeño efectivo de sus cometidos","Elegir destino cada dos años","Negociar su horario individualmente","Eximirse de las revistas e inspecciones"],"La lógica de la ley: al deber de disponibilidad responde el derecho a saber qué se espera de ti (información de incorporación) y al desempeño efectivo de los cometidos.","LO 9/2011 · deberes y derechos correlativos"],
["M","¿Cuál de estos derechos NO figura en el Título I de la LO 9/2011 (arts. 8-17)?",["El derecho a la negociación colectiva","La libertad religiosa","El derecho de sufragio","La libertad de desplazamiento y circulación"],"La negociación colectiva está EXPRESAMENTE excluida del ámbito de las asociaciones profesionales de militares; los demás sí son derechos del Título I (arts. 9, 15 y 11).","LO 9/2011 arts. 8-17 y exclusiones"],
["M","La fórmula del juramento o promesa que presta el militar compromete, según la Constitución:",["Fidelidad al Rey, obediencia y respeto a la Constitución","Lealtad a su unidad y a su jefe directo","Defensa del ministerio y de sus organismos","Obediencia al JEMAD como jefe supremo"],"CE art. 30.2, literal: «fidelidad al Rey y de obediencia y respeto a la Constitución». Sencilla y cae.","Constitución art. 30.2 · caso"]
]
assert len(RAW) == 50, "RAW tiene %d" % len(RAW)
PATRON = [(p + j) % 4 for j in range(13) for p in range(4)][:50]
filas = []
for i, ((dif, q, ops, x, r), dest) in enumerate(zip(RAW, PATRON), 1):
    correcta = ops[0]; resto = ops[1:]
    nuevas = resto[:dest] + [correcta] + resto[dest:]
    esc = lambda t: t.replace('"', '\\"')
    filas.append('{c:"cabo",b:"C1",t:"Derechos y deberes",d:"%s",id:"dd%02d",q:"%s",o:[%s],a:%d,x:"%s",r:"%s"}' % (dif, i, esc(q), ",".join('"%s"' % esc(o) for o in nuevas), dest, esc(x), esc(r)))
LOTE4 = (',\n/* ===== LOTE EXAMINADOR — Tema 4: Derechos y deberes de los miembros de las FAS (LO 9/2011, de 27 de julio)\n'
'   Elaboración PROPIA (examinador GALÓN), 20-sep-2026, sobre el texto oficial verificado (BOE 28-jul-2011).\n'
'   Literales verificados: Título I arts. 8-15 (mapa de derechos), art. 12 (expresión y límites), art. 13 (reunión en unidades),\n'
'   art. 14 (asociación), art. 22 (disponibilidad, citado en el examen I/24), dignidad/acoso, secreto y discreción (también de lo no clasificado),\n'
'   asociaciones profesionales (finalidad, neutralidad, ámbito, registro, responsabilidades, art. 40, exclusiones, art. 51, STC 219/2001),\n'
'   afiliación (condición no en suspenso, retiro, alumnos) y Constitución art. 30.2 (juramento o promesa). */\n')
import io
s = io.open('/home/user/galon/js/bank7.js', encoding='utf-8').read().rstrip()
assert s.endswith('];')
s = s[:-2] + LOTE4 + ",\n".join(filas) + "\n];\n"
io.open('/home/user/galon/js/bank7.js', 'w', encoding='utf-8').write(s)
from collections import Counter
print("Lote Tema 4 montado: 50 · reparto correctas:", dict(sorted(Counter(PATRON).items())))
