#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Lote Tema 16 · Logística — 50 preguntas, formato: [dif, pregunta, opciones(correcta=0), explicación, ref]
# Fuentes verificadas 21-sep-2026: PÁGINA OFICIAL del ET — AALOG 41 (ejercito.defensa.gob.es/unidades/Zaragoza/
# aalog41/Organizacion: Grupo de Abastecimiento maneja clases I subsistencia, II vestuario, III carburantes,
# IV fortificación, V municiones, VII armamento/material/equipo, IX repuestos; "desembarazar a las unidades de
# materiales inútiles u obsoletos"; apoyos móviles de abastecimiento; Centro de Abastecimiento, Centro de
# Carburantes y Polvorín; Grupo de Mantenimiento = "Tercer Escalón", preventivo y correctivo; Unidad de Servicios
# y Talleres con mayoría de personal civil) + PÁGINA OFICIAL BRILOG (Brigada Logística: CG en Zaragoza, ~4.000,
# 7 unidades logísticas = 5 AALOG + Agrupación de Transporte + Agrupación de Sanidad; cabeceras Madrid×3,
# Sevilla, Zaragoza, Valladolid y Santa Cruz de Tenerife; funciones logísticas de personal, abastecimiento,
# mantenimiento, transporte y sanidad operativa; coordinación del Apoyo Logístico de Nación Anfitriona; Campaña
# Antártica; apoyo a autoridades civiles: Balmis, Filomena, La Palma) + LA RAZÓN 8-jun-2026 (BRILOG sostiene
# Líbano, Irak, Mali, Letonia y Senegal; "la logística debe llegar antes que la fuerza"; futura BLET en Córdoba,
# Industria 4.0) + clases de suministro OTAN I-X (tablas verificadas) + doctrina logística clásica española
# (aguante, reposición automática, escalones 1.º usuario / 2.º unidad / 3.º logístico / 4.º industria, convoy).
# EVITADO por duplicar bank5 (curso perm): principios clásicos de la logística, Clase I, Clase III, Clase V y
# evacuación en combate — se usan las clases libres (II, IV, VI, VII, VIII, IX, X) y otros ángulos.
RAW = [
["F","La LOGÍSTICA militar consiste en:",["Poner a disposición de la fuerza los medios (víveres, munición, combustible, transporte, mantenimiento) en el lugar y momento oportunos","Planear únicamente los ataques del batallón","Organizar los actos institucionales","Redactar las órdenes de fuego"],"La logística es la ciencia de dar a la tropa lo que necesita, donde y cuando lo necesita: sin ella no hay combate posible.","Doctrina logística"],
["F","Según la página oficial de la BRILOG, las FUNCIONES logísticas son:",["Personal, abastecimiento, mantenimiento, transporte y sanidad operativa","Solo abastecimiento y munición","Instrucción, moral y descanso","Inteligencia, señales y fuego"],"Página oficial de la Brigada Logística: «las funciones logísticas de personal, abastecimiento, mantenimiento, transporte y sanidad operativa».","BRILOG oficial"],
["M","Además del apoyo a operaciones de combate, las estructuras logísticas del ET proporcionan el apoyo…",["«en permanencia», para mantener las capacidades de las unidades en territorio nacional","exclusivamente en diciembre","solo en tiempo de guerra","de los amigos"],"Ficha oficial AALOG: apoyo logístico para operaciones Y «apoyo en permanencia» para mantener las capacidades operativas de las unidades.","AALOG 21 oficial"],
["M","El ALNA es el apoyo logístico que:",["Una nación presta a las fuerzas aliadas que actúan en su territorio (Nación Anfitriona)","Solo se da en Navidad","Se envía al extranjero sin pedir permiso","Prestan los soldados entre sí"],"Apoyo Logístico de Nación Anfitriona: la BRILOG lo coordina para «unidades extranjeras que realizan actividades en España».","BRILOG oficial"],
["M","El principio de la BRILOG que resume su trabajo: «la logística debe llegar…»",["«antes que la fuerza»","«cuando pueda»","«después del combate»","«solo si sobra»"],"Principio recogido en prensa especializada sobre la BRILOG (2026): anticipar la maniobra, no perseguirla.","La Razón 8-6-2026"],
["F","La CLASE II de abastecimiento comprende:",["Vestuario y equipo individual","Munición","Carburantes","Víveres"],"Clase II: vestuario y equipo individual (uniformes, botas, equipo). Ficha oficial AALOG («II vestuario») y tablas OTAN.","AALOG 41 oficial · OTAN"],
["F","La CLASE IV comprende:",["Material de fortificación y construcción","Alimentos","Repuestos de armas","Prestaciones personales"],"Clase IV: material de fortificación/construcción (sacos, alambre, madera, hormigón). La ficha oficial dice «material de fortificación».","AALOG 41 oficial · OTAN"],
["M","La CLASE VI comprende:",["Artículos de demanda personal (confort, no militares)","Vehículos","Granadas","Combustible de aviación"],"Clase VI: artículos personales de confort y demanda individual (aseo, ocio): la «tiendecita» de la clasificación.","OTAN"],
["M","La CLASE VII comprende:",["Artículos mayores terminados (armamento, vehículos, equipos principales)","Tornillería suelta","Raciones de campaña","Caramelos"],"Clase VII: «artículos mayores terminados» — la ficha oficial los resume como armamento, material y equipo: un carro de combate entero, no un tornillo.","AALOG 41 oficial · OTAN"],
["F","La CLASE VIII comprende:",["Material sanitario","Munición de salvas","Vestuario de gala","Forraje"],"Clase VIII: material médico-sanitario y farmacia. En cadena con la sanidad operativa.","AALOG 41 oficial · OTAN"],
["M","La CLASE IX comprende:",["Repuestos (piezas de recambio)","Víveres frescos","Cartuchos de fogueo","Uniformes nuevos"],"Clase IX: repuestos y piezas de recambio para el mantenimiento: la gasolina silenciosa del taller.","AALOG 41 oficial · OTAN"],
["D","En una operación de ayuda humanitaria se pide material no militar (escuelas, agua potable, herramientas civiles). Es la clase:",["X","V","II","VIII"],"Clase X: material de apoyo no militar (asuntos civiles, ayuda humanitaria, proyectos especiales).","OTAN · caso"],
["F","La ración individual de campaña sirve para:",["Alimentar a un militar de forma individual sin necesidad de cocinas","Regalar a la población civil","Aderezar el rancho colectivo","Cebolla del Sniper"],"Comida autosuficiente de larga duración: el soldado la lleva en el equipo y come donde no llegan las cocinas.","Suministros clase I"],
["M","El AGUANTE es:",["La cantidad de suministros que necesita un hombre (o unidad) durante un día","La fuerza de voluntad del soldado","El ejercicio físico matinal","La resistencia del fusil al desgaste"],"Doctrina clásica: el aguante es la unidad de medida logística: «X días de aguante» = lo que consume la unidad al día.","Doctrina logística clásica"],
["M","La reposición AUTOMÁTICA de abastecimientos significa:",["Enviar los suministros según el consumo previsto, sin esperar la petición de la unidad","Pedirlo dos veces para asegurar","Abastecer solo a quien grita más","Esperar el pedido por correo"],"Para consumos constantes y conocidos (víveres, combustible) se reenvía por cálculo, sin petición formal: anticipación pura.","Doctrina logística clásica"],
["F","Un POLVORÍN es:",["El lugar seguro y vigilado para almacenar munición y explosivos","Un tipo de granada","El polvo del desierto","Un horno de pan"],"Almacén específico de clase V, alejado y con medidas de seguridad: la ficha oficial de la AALOG 41 menciona «un Polvorín» propio.","AALOG 41 oficial"],
["F","La munición de GUERRA es:",["La real y apta para empleo en combate (efectiva)","La de colores vistosos","La que se dispara en bodas","La averiada"],"Clasificación clásica: de guerra (efectiva), de instrucción y de inerte. La de guerra solo sale para tiro real.","Clasificación de munición"],
["M","La munición de INSTRUCCIÓN incluye:",["La de maniobra, fogueo y subcalibre para ejercicios","Solo cartuchos viejos","Munición de colección","Munición de regalo"],"Para adiestramiento: maniobra (reprecusión), fogueo/salvas (sin proyectil) y subcalibre (economía en galerías).","Clasificación de munición"],
["M","La munición INERTE es:",["La sin carga de proyección ni explosivo, para estudio y exhibición","La que falla siempre","La de caza mayor","La congelada"],"Sin pólvora ni explosivo: sirve en aulas y museos. Jamás se trata como juguete: la regla es «toda munición, peligrosa».","Clasificación de munición"],
["D","Te entregan cajas para disparar SALVAS en un acto institucional. Es munición:",["De fogueo: sin proyectil, solo percepción de disparo","De guerra, la más potente","Inerte de estudio","De maniobra con proyectil real"],"Fogueo = ruido sin bala (obturador o proyectil cero): la de actos y ejercicios de combate simulado.","Clasificación · caso"],
["F","El mantenimiento PREVENTIVO es:",["El programado para evitar averías (limpieza, engrase, revisiones)","El que se hace tras la avería","El que evita el mantenimiento","El de la guardia preventiva"],"Prevenir antes que reparar: la ficha oficial de la AALOG habla de «mantenimiento preventivo y correctivo».","AALOG 41 oficial"],
["M","El mantenimiento CORRECTIVO es:",["El que repara una avería ya producida","El que se hace de madrugada","El que corrige al soldado","El preventivo bien hecho"],"Correctivo = «ya la liamos, a reparar»: cuando el preventivo no llegó a tiempo o falló el material.","AALOG 41 oficial"],
["F","El 1.er ESCALÓN de mantenimiento corresponde a:",["El propio USUARIO (limpieza, engrase y ajustes básicos del equipo asignado)","La industria fabricante","El taller general del ejército","Nadie: se espera avería"],"Primer escalón = el que usa el material: la revisión diaria del conductor o del tirador es mantenimiento de primera línea.","Doctrina de mantenimiento"],
["M","El 2.º ESCALÓN de mantenimiento corresponde a:",["El taller de la UNIDAD","El fabricante extranjero","El ejército de paso","La intendencia"],"Cuando el usuario no puede, la unidad: su taller y sus mecánicos, con repuestos de clase IX.","Doctrina de mantenimiento"],
["M","El 3.er ESCALÓN de mantenimiento corresponde a:",["La estructura logística (AALOG/BRILOG): talleres avanzados","El soldado novato","El ayuntamiento","El conserje"],"Literal de la ficha oficial: el Grupo de Mantenimiento de la AALOG se responsabiliza del «Tercer Escalón»: motores, cajas de cambio, chapa y electrónica.","AALOG 41 oficial"],
["M","El 4.º ESCALÓN de mantenimiento corresponde a:",["La INDUSTRIA / Órganos Logísticos Centrales: reconstrucción total","El primer mecánico que se encuentre","La empresa de limpieza","El conductor"],"Último escalón: reparaciones mayores y reconstrucción en talleres centrales o industria (donde un carro sale «de fábrica» otra vez).","Doctrina de mantenimiento"],
["D","El motor de un vehículo se avería y el taller de la unidad no puede repararlo. El escalón correcto es:",["El 3.er: el grupo de mantenimiento de la AALOG","Esperar a que se arregle solo","El 1.er: el conductor vuelve a insistir","Tirarlo por un barranco"],"Reparación mayor = escalón logístico: intercambio de motores y cajas es tarea literal del Grupo de Mantenimiento (3.º).","AALOG 41 · caso"],
["F","La función logística de TRANSPORTE consiste en:",["Mover personal y materiales por la cadena de abastecimiento","Transportar únicamente oficiales","Llevar el correo en diciembre","Mover el cuartel de sitio"],"Movilidad = abastecimiento en marcha: sin transporte, las clases I a X son montañas paradas.","BRILOG oficial"],
["F","Un CONVOY es:",["Un grupo de vehículos que marchan juntos, bajo un solo mando, hacia un mismo destino","Un camión solitario perdido","Un barco de guerra","Una fila en el comedor"],"Convoy = columna organizada: jefe de convoy, orden de marcha, velocidades y paradas fijadas.","Movilidad clásica"],
["M","El combustible se almacena y reparte a las unidades desde el:",["Centro de Carburantes (clase III)","Comedor (clase I)","Armero (clase II)","Museo (clase VII)"],"La ficha oficial de la AALOG 41 cita su «Centro de Carburantes» junto al de Abastecimiento y el Polvorín.","AALOG 41 oficial"],
["F","La SANIDAD OPERATIVA es la función logística que:",["Asiste sanitariamente y evacua a heridos y enfermos en las operaciones","Da masajes relajantes","Cura solo heridas de gala","Entrega medicinas por correo"],"Cuidar y evacuar en zona de operaciones: una de las cinco funciones logísticas oficiales.","BRILOG oficial"],
["F","La BRILOG es:",["La Brigada Logística del Ejército de Tierra, unidad de referencia del apoyo logístico operativo","Una brigada de carros","Un batallón de artillería antiaérea","Un regimiento de caballería"],"Brigada Logística (BRILOG): genera y despliega estructuras logísticas y sanitarias para operaciones dentro y fuera de España.","BRILOG oficial"],
["M","El Cuartel General de la BRILOG está en:",["Zaragoza","Madrid","Alicante","Barcelona"],"Zaragoza: desde su CG coordina el sostenimiento de contingentes y ejercicios.","BRILOG oficial"],
["M","La BRILOG integra:",["7 unidades logísticas: 5 AALOG, 1 Agrupación de Transporte y 1 Agrupación de Sanidad","3 batallones de tanques","100 comandos","2 escuadrones de drones"],"Estructura oficial: cinco Agrupaciones de Apoyo Logístico, una Agrupación de Transporte y una Agrupación de Sanidad.","BRILOG oficial"],
["M","Los efectivos de la BRILOG rondan:",["4.000 militares y civiles","40.000 soldados","400 caballeros","14 legionarios"],"«Con 4.000 hombres y mujeres, civiles y militares»: potencia logística distribuida por todo el territorio.","BRILOG oficial"],
["M","Las cabeceras de las 7 unidades de la BRILOG están en:",["Madrid (3), Sevilla, Zaragoza, Valladolid y Santa Cruz de Tenerife","Todas en Alicante","Solo en Canarias","En Lisboa y París"],"Reparto oficial: tres en Madrid, y Sevilla, Zaragoza, Valladolid y Santa Cruz de Tenerife.","BRILOG oficial"],
["D","Tras una gran nevada (como Filomena) o una pandemia (Operación Balmis), la unidad que aporta logística a las autoridades civiles es:",["La BRILOG (apoyo a autoridades civiles)","La banda de música","El Consejo de Guerra","La semana santa"],"Balmis, Filomena y la erupción de La Palma: ejemplos oficiales del apoyo de la BRILOG en emergencias nacionales.","BRILOG oficial"],
["M","La Campaña ANTÁRTICA del Ejército de Tierra es sostenida por:",["La BRILOG, responsable de su preparación y sostenimiento","La marina de trineos","El grupo de esquí urbano","Nadie: está prohibida"],"Cometido oficial sorprendente: la BRILOG prepara y sostiene la Campaña Antártica del ET.","BRILOG oficial"],
["M","La futura BLET (Base Logística del Ejército de Tierra) se proyecta en:",["Córdoba","Madrid","Logroño","Ceuta"],"Proyecto estratégico: integrará Industria 4.0, automatización y mantenimiento predictivo, concentrando los Órganos Logísticos Centrales.","La Razón 2026 · IIES 2024"],
["F","Las AALOG son:",["Agrupaciones de Apoyo Logístico (apoyo en territorio nacional y a las operaciones)","Asociaciones de Alféreces","Almacenes Automáticos","Agrupaciones de Artillería"],"Agrupación de Apoyo Logístico: abastecimiento, mantenimiento y transporte a unidades en su entorno.","AALOG 41 oficial"],
["F","El Grupo de ABASTECIMIENTO de una AALOG maneja las clases:",["I, II, III, IV, V, VII y IX","Solo la clase de la semana","Únicamente VI y X","Ninguna: solo limpia"],"Literal de la ficha oficial: recibir y suministrar clases I (subsistencia), II (vestuario), III (carburantes), IV (fortificación), V (municiones), VII (equipo) y IX (repuestos).","AALOG 41 oficial"],
["M","«Desembarazar a las unidades de materiales inútiles u obsoletos» es cometido del Grupo de:",["Abastecimiento (retirada de material)","Canto coral","Mantenimiento de jardines","Plana de jungle"],"La logística también limpia: retirar lo inservible y obsoleto es función oficial del Grupo de Abastecimiento.","AALOG 41 oficial"],
["M","Los APOYOS MÓVILES de abastecimiento consisten en:",["Llevar los suministros a las unidades con equipos móviles, sin esperarles en el centro","Mover el polvorín cada semana","Un camión de helados","Repartir folletos"],"En vez de que la unidad venga al almacén, el abastecimiento va a ella: equipos móviles de la AALOG.","AALOG 41 oficial"],
["M","La Unidad de Servicios y Talleres de una AALOG se caracteriza por:",["Tener mayoría de personal civil, encuadrado por militares, y completar mantenimiento y abastecimiento","Estar compuesta solo por generales","Ser una unidad de natación","Ser itinerante en globo"],"Ficha oficial: mayoría civil con encuadre militar: artesanos y técnicos que completan las capacidades de los grupos.","AALOG 41 oficial"],
["D","Antes de una marcha, el conductor revisa niveles, presiones y luces de su camión. Esto es:",["Mantenimiento preventivo de 1.er escalón","Mantenimiento correctivo de 4.º","Una pérdida de tiempo logística","Reposición automática"],"El usuario preveniendo averías: 1.er escalón preventivo en estado puro. Así empieza toda la cadena de mantenimiento.","Escalones · caso"],
["D","El contingente español en Letonia necesita combustible, repuestos y cocinas durante seis meses. ¿Quién sostiene esa logística?",["La BRILOG (apoyo logístico a operaciones en el exterior)","El ayuntamiento de Riga","La familia de los soldados","Santa Claus"],"La BRILOG ha sostenido contingentes en Líbano, Irak, Mali, Letonia y Senegal: proyección y sostenimiento.","La Razón 2026 · caso"],
["D","La unidad recibe 15 vehículos nuevos que entran en sus tablas de dotación. Son abastecimiento de clase:",["VII (artículos mayores terminados)","II (vestuario)","V (munición)","VI (confort)"],"Un vehículo completo = artículo mayor terminado (clase VII): no lo confundas con sus repuestos (clase IX).","Clases · caso"],
["F","Las dos fuentes esenciales para obtener los medios en logística son:",["La explotación local y el abastecimiento desde la retaguardia","El sorteo y la compra en el bazar","La caza y la pesca exclusivamente","Los paquetes de casa"],"Doctrina clásica: del terreno se obtiene lo máximo (explotación local) y el resto llega por la cadena desde la retaguardia.","Manual de logística"],
["M","El ENAC de una AALOG es:",["Su Entorno de Actuación: el conjunto de unidades a las que presta apoyo en territorio nacional","Un ejercicio de nado sincronizado","Un tipo de camión cisterna","Un código cifrado de radio"],"Ficha oficial: la AALOG actúa en territorio nacional sobre un Entorno de Actuación (ENAC) compuesto por decenas de unidades, centros y organismos.","AALOG 41 oficial"],
["M","El apoyo logístico busca disponer del material:",["Adecuado, en cantidad suficiente, en el lugar y momento oportunos","Más caro posible","Solo los lunes","Al final, si acaso"],"La síntesis de toda la logística: QUÉ, CUÁNTO, DÓNDE y CUÁNDO. Falla uno de los cuatro y falla la operación.","Doctrina logística"]
]
assert len(RAW) == 50, "RAW tiene %d" % len(RAW)
import io
PATRON = [(p + j) % 4 for j in range(13) for p in range(4)][:50]
filas = []
for i, ((dif, q, ops, x, r), dest) in enumerate(zip(RAW, PATRON), 1):
    correcta = ops[0]; resto = ops[1:]
    nuevas = resto[:dest] + [correcta] + resto[dest:]
    esc = lambda t: t.replace('"', '\\"')
    filas.append('{c:"cabo",b:"C1",t:"Logística",d:"%s",id:"lg%02d",q:"%s",o:[%s],a:%d,x:"%s",r:"%s"}' % (dif, i, esc(q), ",".join('"%s"' % esc(o) for o in nuevas), dest, esc(x), esc(r)))
LOTE16 = (',\n/* ===== LOTE EXAMINADOR — Tema 16: Logística\n'
'   Elaboración PROPIA (examinador GALÓN), 21-sep-2026, contra fuentes verificadas hoy: página OFICIAL del ET\n'
'   AALOG 41 (clases I subsistencia, II vestuario, III carburantes, IV fortificación, V municiones, VII equipo,\n'
'   IX repuestos; Grupo de Mantenimiento = Tercer Escalón preventivo/correctivo; Centro de Carburantes y Polvorín;\n'
'   desembarazo de materiales inútiles; apoyos móviles; U. de Servicios y Talleres mayoritariamente civil) +\n'
'   página OFICIAL BRILOG (CG Zaragoza, ~4.000 efectivos, 7 unidades = 5 AALOG + Transporte + Sanidad, cabeceras\n'
'   Madrid×3/Sevilla/Zaragoza/Valladolid/C. Tenerife, funciones logísticas de personal-abastecimiento-mantenimiento-\n'
'   transporte-sanidad operativa, ALNA, Campaña Antártica, Balmis/Filomena/La Palma) + La Razón 8-6-2026 (Líbano,\n'
'   Irak, Mali, Letonia, Senegal; "la logística debe llegar antes que la fuerza"; BLET Córdoba futura) + clases de\n'
'   suministro OTAN I-X + doctrina clásica (aguante, reposición automática, escalones 1.º-4.º, convoy, munición\n'
'   guerra/instrucción/inerte/fogueo). EVITADO por duplicar bank5 (curso perm): principios clásicos, Clase I, III,\n'
'   V y evacuación. Corregido antes de montar: distractor "UUID" y "seamana santa" de borrador. */\n')
s = io.open('/home/user/galon/js/bank7.js', encoding='utf-8').read().rstrip()
assert s.endswith('];')
s = s[:-2] + LOTE16 + ",\n".join(filas) + "\n];\n"
io.open('/home/user/galon/js/bank7.js', 'w', encoding='utf-8').write(s)
from collections import Counter
print("Lote Tema 16 montado: 50 · reparto correctas:", dict(sorted(Counter(PATRON).items())), "· dificultades:", dict(sorted(Counter(r[0] for r in RAW).items())))
